### ISSUE TITLE
Ignition: CoreOS hanging on first boot in AWS EC2 with custom user data

### ISSUE THREAD

**Issue by sethp-jive** [coreos/bugs#1047] opened 2015-12-18 02:38 UTC
Edited to add summary: any userdata that does not begin with "#!", "#cloud-config\n", or is valid ignition json leads to an ignition failure that prevents booting the CoreOS image in EC2. Issuing an EC2 "reboot" seems to skip the ignition step, and works around the problem.

Original issue follows.

The short version is that all of the times I've tried the following:

```
aws ec2 run-instances --image-id ami-13607c72 --count 1 --instance-type t2.micro --key-name id_aws --user-data fileb://<(echo "#cloud-config" | gzip -c)
```

I've gotten an instance which gets stuck in the boot process (NB: if you see `Error parsing parameter '--user-data': file does not exist: /dev/fd/XX` you'll need a more recent version of `awscli`; `pip install --upgrade "awscli>=1.7.24"` should do the trick). Removing the `gzip -c` similarly reliably produces an instance that boots with no problems. The instance hangs very early – the last message in the AWS system console is typically around the 3-4 second mark:

```
[    3.483402] EXT4-fs (xvda9): mounted filesystem with ordered data mode. Opts: (null)
[    3.522758] EXT4-fs (xvda3): mounted filesystem without journal. Opts: (null)
```

and that's all, folks! In one case, I left a machine apparently stuck in this state over the weekend and it didn't come back. Rebooting the VM appears to nearly immediately unstick whatever was happening in the boot process, as does creating an instance with non-gzipped userdata.

So far the issue has proved challenging to debug, primarily because it seems to be happening before or during systemd startup – no journal output to the console, no cloud configs to send data out of the instance over the network, and no ssh (though the network stack is healthy enough to refuse any attempts to establish a TCP connection to port 22). Post-reboot `journalctl --list-boot` reliably reports just one entry, and my primitive attempts so far at establishing `Storage=persistent` only records multiple boots once the system stops having the problem.

**Comment by sethp-jive** [comment] 2015-12-18 15:45
I had discovered that I was unable to reproduce this on a very old version (766.5.0) – I did a binary search of the HVM AMIs for us-west-2 and it looks like the first (in version number order) that presents with this problem is: `ami-c9869bf9` ([801.0.0](https://coreos.com/releases/#801.0.0)).

**Comment by crawford** [comment] 2015-12-18 21:30
coreos-cloudinit only gained support for gzipped configs starting in [870.2.0](https://github.com/coreos/manifest/releases/tag/v870.2.0).

**Comment by sethp-jive** [comment] 2015-12-18 23:21
Indeed – that's why this behavior is so strange. Once the system is able to successfully boot, every time I run coreos-cloudinit pre-870.2.0, I get the expected failure, and every time post-870.2.0 the same config (in this case, nothing) is applied. So the system appears to be getting stuck on something pre-cloudinit (or very early in the cloudinit run, but only on first boot) when given a gzipped userdata. But only the first time!

Is there some other system that might be reading the userdata? Does running the above command produce a system that's able to boot for you? I've tried quite a few times, and only pre-801.0.0 does the system boot (print a login prompt to the console that's getting reported as the "system log" in AWS, accepts connections on port 22, etc). Post-801.0.0, that example userdata yields a nonbooting system.

To be honest, I suspect the gzip part is a red herring – that's what's driving the problem for me, but I suspect gzip is just part of a broader equivalence class of user-datas that would reproduce the problem.

**Comment by sethp-jive** [comment] 2015-12-19 00:28
Also of note is that I've been unable to reproduce the error on GCE – user data binary blobs are apparently mangled (as per https://bugs.launchpad.net/cloud-init/+bug/1404311 ) and cloudinit doesn't try a base64 decoding pass (perhaps it should, but that would be a different issue).

It gets even weirder for me, though – I tried base64 encoding my userdata, which I expected to "work" (up to the part where cloudinit runs) and actually saw the same symptom. On a whim, I tried the following:

```
aws ec2 run-instances --image-id ami-13607c72 --count 1 --instance-type t2.micro --key-name id_aws --user-data "hi"
```

and saw the same "stuck" result. I'll leave the instance running over the weekend in case it eventually gets to the point where it'll accept my ssh connections, but at the moment it's looking to me like any user data string that does not begin with precisely "#cloud-config" as userdata is rendering my instances unbootable.

**Comment by sethp-jive** [comment] 2015-12-21 19:47
~65 hours later, the instance whose userdata is "hi" is still in the middle of what seems to be systemd startup (at least, according the limited data I'm able to gather via the system log). Rebooting the machine gets the expected state (running system, failed oem-cloudinit because "hi" is not a valid cloud config).

I've found another working case which has given a clue to the underlying issue: creating an ec2 instance with user-data "#!/not/a/thing" led me to the following log:

```
Dec 21 17:26:59 localhost ignition[244]: Ignition v0.2.4
Dec 21 17:26:59 localhost ignition[244]: op(1): [started]  GET "http://169.254.169.254/2009-04-04/user-data"
Dec 21 17:26:59 localhost ignition[244]: op(1): [failed]   GET "http://169.254.169.254/2009-04-04/user-data": Get http://169.254.169.254/2009-04-04/user-data: dial tcp 169.254.169.254:80: network is unreachable
Dec 21 17:26:59 localhost ignition[244]: op(2): [started]  GET "http://169.254.169.254/2009-04-04/user-data"
Dec 21 17:26:59 localhost ignition[244]: op(2): [failed]   GET "http://169.254.169.254/2009-04-04/user-data": Get http://169.254.169.254/2009-04-04/user-data: dial tcp 169.254.169.254:80: network is unreachable
Dec 21 17:26:59 localhost ignition[244]: op(3): [started]  GET "http://169.254.169.254/2009-04-04/user-data"
Dec 21 17:26:59 localhost ignition[244]: op(3): got data "#!/not/a/thing/"
Dec 21 17:26:59 localhost ignition[244]: op(3): [finished] GET "http://169.254.169.254/2009-04-04/user-data"
Dec 21 17:26:59 localhost ignition[244]: config successfully fetched
Dec 21 17:26:59 localhost ignition[244]: failed to fetch config: not a config (found coreos-cloudinit script)
Dec 21 17:26:59 localhost ignition[244]: not a config (found coreos-cloudinit script): ignoring and exiting...
Dec 21 17:27:01 localhost ignition[415]: Ignition v0.2.4
Dec 21 17:27:01 localhost ignition[415]: op(1): [started]  GET "http://169.254.169.254/2009-04-04/user-data"
Dec 21 17:27:01 localhost ignition[415]: op(1): got data "#!/not/a/thing/"
Dec 21 17:27:01 localhost ignition[415]: op(1): [finished] GET "http://169.254.169.254/2009-04-04/user-data"
Dec 21 17:27:01 localhost ignition[415]: config successfully fetched
Dec 21 17:27:01 localhost ignition[415]: failed to fetch config: not a config (found coreos-cloudinit script)
Dec 21 17:27:01 localhost ignition[415]: not a config (found coreos-cloudinit script): ignoring and exiting...
```

Which led to what I believe is the source of my trouble, the EC2 ignition provider. Specifically:

0. [config.Parse](https://github.com/coreos/ignition/blob/d8292ba3ce80b55549c88bd1d3df41a2ff2bb65b/src/config/config.go#L41-L54) can return one of five possible classes of error:
  1. ` json.Unmarshal` errors – when the input is not valid json (almost always in ec2)
  2. `ErrVersion` – when the json version mismatches
  3. `ErrCloudConfig` – if the user-data begins with exactly '#cloud-config'
  4. `ErrScript` – if the user-data begins with exactly '#!'
  5. `ErrEmpty` – if the user-data is exactly 0 bytes
1. The EC2 ignition provider has the following [`provideConfig`](https://github.com/coreos/ignition/blob/d8292ba3ce80b55549c88bd1d3df41a2ff2bb65b/src/providers/ec2/ec2.go#L75-L82) implementation:
```go
func (p provider) FetchConfig() (config.Config, error) {
	cfg, err := config.Parse(p.rawConfig)
	if err == nil || err == config.ErrEmpty {
		err = p.fetchSSHKeys(&cfg)
	}

	return cfg, err
}
```
Meaning, for our purposes, that `ErrEmpty` errors are handled by fetching ssh keys and replacing the `ErrEmpty` with the success or failure of that operation.
2. Otherwise, the error is bubbled up to [`Engine.Run`](https://github.com/coreos/ignition/blob/d8292ba3ce80b55549c88bd1d3df41a2ff2bb65b/src/exec/engine.go#L76) by way of `Engine.acquireConfig` (which is kind enough to generate the `failed to fetch config` log message first):
```go
func (e Engine) Run(stageName string) bool {
	cfg, err := e.acquireConfig()
	switch err {
	case nil:
		e.Logger.PushPrefix(stageName)
		defer e.Logger.PopPrefix()
		return stages.Get(stageName).Create(&e.Logger, e.Root).Run(cfg)
	case config.ErrCloudConfig, config.ErrScript, config.ErrEmpty:
		e.Logger.Info("%v: ignoring and exiting...", err)
		return true
	default:
		e.Logger.Crit("failed to acquire config: %v", err)
		return false
	}
}
```
The `ignoring and exiting` branch here is taken if the error is `ErrCloudConfig`, `ErrScript`, or `ErrEmpty`, which is what happened with my `#!/not/a/thing` user-data. So, again, for our purposes we find those classes of error to be well-handled (in that ignition does nothing but exit successfully).
3. However, in the case of my `hi` user-data (or gzipped user data), we fall down into the `default` case, log a critical message that has not in my testing appeared anywhere I can see it, and return `false` up to [`main`](https://github.com/coreos/ignition/blob/d8292ba3ce80b55549c88bd1d3df41a2ff2bb65b/src/main.go#L104-L106) causing ignition to exit with an error.
4. Now, both the ignition-files and ignition-disks service(s) are in error. My knowledge of systemd is fairly limited, but it would seem then that [`ignition.target`](https://github.com/coreos/coreos-overlay/blob/master/sys-apps/ignition/files/ignition.target) never fires because its two `Requires` dependencies failed. Or perhaps the system successfully enters `emergency.target`, which appears to be a root shell for someone with direct tty access to the box?

So, that appears to be the causal chain that I'm experiencing, and it looks like anyone who sets a user-data that isn't explicitly a `#cloud-config`, `#!`, valid ignition JSON payload, or empty will run into the same behavior.

I can work around the issue by using a `#!` script for now, but it seems to me that there would be two good things to discuss here:

1. As a relative EC2 and systemd novice, the error messaging was fairly hard to track down – something to the effect of "ignition failed for reason X, aborting boot" in the EC2 system log would've made debugging a bit easier. Some form of dumping `journalctl -xb` to whatever device is read for the [instance console](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-console.html#instance-console-console-output)?
2. Is there a more straightforward ignition default than throwing up its hands and halting boot when it runs across user-data it doesn't understand? In EC2, the only I/O access I found to the box is the read-only console and ssh – it would have helped me understand the problem much faster if ignition's failure had still produced a ssh-able (if otherwise degraded) instance. Instead of `emergency.target`, which needs physical access to the box, could there be an `ssh-only.target` that is functional enough for me to get in and run `journalctl -xb` myself?

**Comment by crawford** [comment] 2015-12-21 20:03
@sethp-jive thank you for tracking this down! What you've found is exactly right. If Ignition does not find a valid config, it halts the boot (which is the only safe response). Ignition should be able to recognize a gzipped config though, which I think is the root cause here.

**Comment by sethp-jive** [comment] 2015-12-21 20:16
While I'll of course have to defer to your expertise on what ignition should do, as a user of CoreOS I've made a lot of seemingly small mistakes in my configs (such as using the header `#cloud-init` instead of `#cloud-config`). In that case, the system refusing to boot or otherwise communicate the error until I get the config right seems a bit stringent – is there some other kind of signal we might add in addition to teaching ignition to recognize gzipped configs?

**Comment by crawford** [comment] 2015-12-21 21:49
The reasoning behind the hard failure is that we do not want a system to come up and appear to be online if anything from the Ignition config failed to be applied. Provisioning should be an atomic operation. The trick is that we currently accept either an Ignition config or a cloud-config and it's tough to determine if the user _intended_ to write an Ignition config. If it's valid JSON, it's probably safe to assume an Ignition config was intended, but what about malformed JSON? Where do you draw the line between an attempt at an Ignition config vs a cloud-config? We ended up doing the easiest approach and requiring a valid config (Ignition or cloud-config).

As for communicating this error, there are several approaches. We could spin up an SSH server in the event that the boot failed. This of course has the security disadvantage if you don't control the network. At the other end of the spectrum, we can encourage users to use tools like https://coreos.com/validate/ to check their config, but this requires them to be proactive. In my eyes, the ideal case would be the platform providing a read/write console so that the user can poke around in the emergency shell, but I'm not holding my breath for that feature.

**Comment by crawford** [comment] 2016-01-07 05:25
Fixed via https://github.com/coreos/coreos-overlay/pull/1712.

**Closed by crawford** 2016-01-07 05:25 UTC
Labels: area/usability, component/cloud-init, component/ignition, kind/bug, priority/P1, team/os
