### ISSUE TITLE
CoreOS 899.13.0 ksoftirqd consumes 100% CPU for all cores with more than 20 TCP connections

### ISSUE THREAD

**Issue by rfliam** [coreos/bugs#1275] opened 2016-05-10 19:09 UTC
Problem Description:
CoreOS 899.13.0 has ksoftirqd consume 100% of 40 cores when more than 20 TCP connections are moving traffic. Response times become terrible and throughput drops through the floor. This problem does _not_ occur with Centos 7 (3.10.0-327.el7.x86_64). 

Example with 20 TCP connections:
![image](https://cloud.githubusercontent.com/assets/718129/15157744/27ecd9b4-16aa-11e6-8151-beb219395713.png)

With 10 TCP connections:
![image](https://cloud.githubusercontent.com/assets/718129/15158602/ef495ebc-16ad-11e6-9951-8778bb6e1e1d.png)

Flamegraph from perf:
![image](https://cloud.githubusercontent.com/assets/718129/15159186/a52c46fc-16b0-11e6-9d9b-be7cff4219a5.png)

It looks like something is holding the spinlocks in the iommu code for excessive amounts of time. Whats strange is low numbers of concurrent tcp connections don't seem to have this and the kernel moves packets very quickly. We are able to hit a 20GB/s line rate on LACP bonds for low concurrency in TCP connections. Breaking or creating the LACP bond does not help. We attempted disabling the gro, lro, and changing the tcp hash algorithms, and the number of TX and Rx Buckets. None of this helped. On Centos 7 this issue does not manifest.

Testing with Java, C, and Go servers all manifest this behavior. Coupled with the perf reports it seems unlikely to be caused by userspace.

Machine Configuration

```
Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
ethtool -i eno1
driver: ixgbe
version: 4.0.1-k
firmware-version: 0x800004e0
bus-info: 0000:06:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no

CPU
Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
```

Release Info:

```
cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=899.13.0
VERSION_ID=899.13.0
BUILD_ID=2016-03-23-0120
PRETTY_NAME="CoreOS 899.13.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by philips** [comment] 2016-05-10 23:38
Could you test beta on this machines so we have a bit of data on if this is fixed in a later kernel version?

**Comment by rfliam** [comment] 2016-05-11 01:44
We tested it on beta to the same effect. We are currently investigating redhat's default kernel tunings to see if they are the cause in the (rather drastic) performance difference.

**Comment by philips** [comment] 2016-05-11 16:09
@rfliam was there a version of CoreOS that has worked? Can you test alpha? Or is this the first version of CoreOS that you have tried and then you hit this issue?

**Comment by rfliam** [comment] 2016-05-11 18:07
Testing with Alpha showed the same problem. We haven't tested this specific machine configuration with older CoreOS versions. Load testing with older versions (815.0.0) on different hardware (Cisco NIC's) did not manifest this problem.

I will try and test the old versions on the new hardware, is there a specific version you would like us to try?

**Comment by philips** [comment] 2016-05-11 18:50
@rfliam Do you know what version of alpha you used? I am just trying to bisect this down by understanding what used to work. 

Let me dig through the ixgbe/netdev commits and see if something should be backported. Perhaps @gregkh has seen a patch in his stable Linux tree related to this?

**Comment by philips** [comment] 2016-05-11 19:04
Can you explain a bit more about the workload as well? Are the 20 TCP connections ingress or egress? Are there firewalls or other network configurations? Can you dump the route tables, iptables, etc?

**Comment by 4a4c** [comment] 2016-05-11 23:20
Hi @philips , 
We've found a pretty easy way replicate replicate the issue we're seeing using iperf.  This is not our actual workload, but the behavior we're seeing with this method matches what we're seeing.

On the 'server' CoreOS box, I start up iperf (just have an alpine container with iperf installed) `iperf -s`, on multiple 'client' CoreOS boxes I initiate connections to the server via something like `iperf -c xx.xx.xx.xx -P 100 -t 20`

if the sum of all `-P` is <50, the server is able to produce near line rate throughput with minimal CPU or ksoftirqd util.  

If the sum of `-P` starts to get up into the 50-100+ range, we start seeing ksoftirqd ramp way up across all CPU cores and throughput starts to suffer drastically.

the only iptables we have are those created by the kube-proxy running in iptables mode.

**Comment by rfliam** [comment] 2016-05-11 23:20
@philips The work is as described above. This actually replicates with all iptables flushed. Info below.

Alpha was tested on 1032.1.0. 

Config info:
```
iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination        

 iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         

iptables -t filter -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

iptables -t mangle -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination     

netstat -ar 
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
default         10.43.151.1     0.0.0.0         UG        0 0          0 eno1
10.43.151.0     *               255.255.255.0   U         0 0          0 eno1
10.43.151.1     *               255.255.255.255 UH        0 0          0 eno1
192.168.198.0   *               255.255.254.0   U         0 0          0 docker0

ethtool -k eno1
Features for eno1:
rx-checksumming: on
tx-checksumming: on
	tx-checksum-ipv4: on
	tx-checksum-ip-generic: off [fixed]
	tx-checksum-ipv6: on
	tx-checksum-fcoe-crc: off [fixed]
	tx-checksum-sctp: on
scatter-gather: on
	tx-scatter-gather: on
	tx-scatter-gather-fraglist: off [fixed]
tcp-segmentation-offload: on
	tx-tcp-segmentation: on
	tx-tcp-ecn-segmentation: off [fixed]
	tx-tcp6-segmentation: on
udp-fragmentation-offload: off [fixed]
generic-segmentation-offload: on
generic-receive-offload: off
large-receive-offload: off
rx-vlan-offload: on
tx-vlan-offload: on
ntuple-filters: off
receive-hashing: on
highdma: on [fixed]
rx-vlan-filter: on [fixed]
vlan-challenged: off [fixed]
tx-lockless: off [fixed]
netns-local: off [fixed]
tx-gso-robust: off [fixed]
tx-fcoe-segmentation: off [fixed]
tx-gre-segmentation: off [fixed]
tx-ipip-segmentation: off [fixed]
tx-sit-segmentation: off [fixed]
tx-udp_tnl-segmentation: off [fixed]
fcoe-mtu: off [fixed]
tx-nocache-copy: off
loopback: off [fixed]
rx-fcs: off [fixed]
rx-all: off
tx-vlan-stag-hw-insert: off [fixed]
rx-vlan-stag-hw-parse: off [fixed]
rx-vlan-stag-filter: off [fixed]
l2-fwd-offload: off
busy-poll: on [fixed]
```

**Comment by philips** [comment] 2016-05-12 14:37
@rfliam great, I am going to dig through netdev a bit for 4.6 fixes related to this to see if we are seeing a known issue.

**Comment by rfliam** [comment] 2016-05-13 20:59
Testing with CoreOS 653.0.0 with the 3.19 kernel shows good throughput. This makes it unlikely that it is simply a kernel setting Centos 7 has, but CoreOS does not (unless something changed in that regard). 

Worth noting is that 653.0.0 isn't doing "as good" a job of balancing IRQ's across cores, even though the settings are the same from what we can tell (rx-flow-hash is the same, RPS, RSS, and RFS are the same). 

Increasing the TCP window to 2.5MB helped the 4.5 kernel in alpha significantly. I suspect  this is due to the significantly lower ACK traffic on the TCP connection (and corresponding PPS).

**Comment by mjg59** [comment] 2016-05-17 16:34
@rfliam Let's see if we can narrow this down a bit more. Does booting with intel_iommu=off on the kernel command line help? We wouldn't recommend this for long-term use for security reasons, but it may help us figure out what layer in the stack is causing problems.

**Comment by 4a4c** [comment] 2016-05-17 19:02
@mjg59 We did the test disabling IOMMU and were able to push 20G @1000 streams which is our target.  A few interesting notes:
1 - Prior to disabling IOMMU, interrupts were being processed across all threads on both sockets by default.
2 - After disabling IOMMU, interrupts were being processed mostly by the physical cores on CPU0 with some interrupts being processed by the 'hyper-threaded' cores on CPU0.  Negligible interrupts were being processed by CPU1.
3 - Via some investigation and trial/error we were able to achieve similar results to #2 without disabling IOMMU by limiting the number of tx/rx queues that the NICs were allocated from the default of 48 down to 6 per nic.  This accomplished essentially the same behavior as #2, keeping interrupt processing on the physical cores of CPU0.  We were able to push 20G @1000 streams with this configuration as well.

Of #2,3 do you have input on which is a more viable solution and/or do these findings lend us to investigating further?

**Comment by mjg59** [comment] 2016-05-17 19:46
Ok, let's try one more thing. Can you identify the IRQ that each card is attached to, and then set the IRQ affinity by doing:

echo 01 >/proc/irq/number/smp_affinity

Changing 01 to match the mask of the CPUs associated with the first socket - ie, if CPUs 0, 1, 2, 3 are on the first socket, use 0f, if CPUs 0, 1, 2, 3, 4, 5, 6 and 7 are then use ff, if CPUs 0, 1, 3 and 4 are then use 33. This will attach the interrupts to the first socket without changing any other aspects of the system configuration, and will help us understand whether the issue is actually the IOMMU or whether IOMMU usage is just altering IRQ balancing somehow.

**Comment by rfliam** [comment] 2016-05-17 21:53
Thanks for looking into this, the interrupts theory seems to have paid off to some degree:
  1) Tying interrupts to 333333 (one per real core, all cores enabled) as you suggested produced almost exactly the same behavior as disabling IOMMU. That is almost all work done on one CPU. With IOMMU disabled we get this behavior _despite_ the IRQ masks being of the form:
```
0000,00000001
0000,00000002
0000,00000004
0000,00000008
0000,00000010
0000,00000020
0000,00000040
0000,00000080
0000,00000100
0000,00000200
0000,00000400
0000,00000800
```
  2) Once the IRQ assignment has been done the kernel _will not_ process interrupts on the second socket, even with the IRQ masks re-assigned to the default state (until reboot).
  3) Setting the number of queues to 12 is closely equivalent to setting the IRQ masks for 48 queues to not be processed on the second core. We can not force the "12" rx queues (if set after boot) to process on the second socket.

**Comment by mjg59** [comment] 2016-05-17 21:56
Does performing the IRQ assignment give you the expected levels of throughput? If so, I'd suggest that as the workaround for now - we'll need to figure out why having the iommu enabled results in IRQ affinity being broken.

**Comment by rfliam** [comment] 2016-05-17 21:59
It does, we will be working to droping to 12 rx queues and just tying irq's to one rx queue per physical core.

Again thanks for the help!

**Comment by ntquyen** [comment] 2016-09-29 06:13
Dump question: How to identify which IRQ number associated with the ethernet device? In my case, the ethernet device is eth0, but I found nothing related to `eth0` in `/proc/interrupts`

**Comment by crawford** [comment] 2016-12-19 02:13
Closing due to inactivity.

**Closed by crawford** 2016-12-19 02:13 UTC
Labels: area/performance, component/kernel, kind/bug, priority/P1, team/os
