### ISSUE TITLE
acpi_pad cpu high

### ISSUE THREAD

**Issue by yangjun** [coreos/bugs#2044] opened 2017-07-05 00:34 UTC
# Issue Report #

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.5.0
VERSION_ID=1409.5.0
BUILD_ID=2017-06-22-2222
PRETTY_NAME="Container Linux by CoreOS 1409.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

ThinkServer RD450 CPU 2*E5-2609v4 Double Power 32G MEM 2*1T DISK

### Actual Behavior ###

```
11530 root      -2   0       0      0      0 R  95.6  0.0 971:55.24 acpi_pad/3
 8152 root      -2   0       0      0      0 R  77.7  0.0 972:38.65 acpi_pad/0
 8153 root      -2   0       0      0      0 R  71.7  0.0 972:16.36 acpi_pad/1
11529 root      -2   0       0      0      0 D  65.7  0.0 972:14.50 acpi_pad/2
```

**Comment by bgilbert** [comment] 2017-07-05 01:16
The only purpose of `acpi_pad` threads is to consume CPU time, so they're working as intended.  Those threads are started when the system's firmware asks the OS to reduce power consumption by idling some CPU cores.

You may be able to reduce or eliminate this behavior by configuring the ThinkServer firmware to prefer performance over energy conservation, using the firmware menus.  If that doesn't work, you could also try updating your system firmware, in case a firmware bug is idling CPUs too often.

**Comment by vcaputo** [comment] 2017-07-05 21:36
Judging from the commit message for https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=8e0af5141ab950b78b3ebbfaded5439dcf8b3a8d I would not expect this to be happening without the user explicitly requesting it via IPMI or similar.  Specifically:
```
    The intent is to lower power consumption to ride-out
    transient electrical and thermal emergencies,
    rather than powering off the server.
```
It sounds like a probable firmware bug, or perhaps your system has a thermal emergency you're otherwise unaware of and firmware is attempting to automagically mitigate.

It's unfortunate these kernel threads are indistinguishable from any other CPU hog, UX fail.

**Comment by bgilbert** [comment] 2017-07-19 23:57
Upstream kernel is working as intended; closing.

**Closed by bgilbert** 2017-07-19 23:57 UTC
Labels: area/performance, component/kernel, kind/question, team/os
