### ISSUE TITLE
tectonic: k8s scheduling regression results in failed tectonic-torcx OS updates

### ISSUE THREAD

**Issue by vinhthang** [coreos/bugs#2403] opened 2018-04-12 09:30 UTC
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.5.3
VERSION_ID=1688.5.3
BUILD_ID=2018-04-03-0547
PRETTY_NAME="Container Linux by CoreOS 1688.5.3 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```
### Environment ###

Virtual Box Baremetal

### Expected Behavior ###

Startup normally after reboot

### Actual Behavior ###
After a week or more, I can't access to https://tectonic1 (one of my workers), I reboot all machine.
I see that my coreos is auto updated to 1688.5.3, before I installed 1632.3.0
### Reproduction Steps ###

  1. reboot
  2. wait
  3. ssh core@master

> Apr 12 09:10:12 master kubelet-wrapper[16104]: Error: failed to run Kubelet: failed to create kubelet: failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

> core@master ~ $ docker version
The program docker is managed by torcx, which did not run.

**Comment by lucab** [comment] 2018-04-13 08:44
Just for the sake of clarity, the root cause of this is a mix of the k8s regression referenced above (which broke the upgrade process) and a manual reboot while in the middle of the ongoing node OS upgrade.

@aaronlevy @robszumski I'm assigning this for you just for tracking. There are however at least a few other tickets in tectonic-forum, so feel free to just keep the one you prefer for ongoing updates and close the redundant ones.

**Comment by robszumski** [comment] 2018-05-24 16:19
Hi folks, apologies for the delay but [Tectonic 1.9.6](https://coreos.com/tectonic/releases/#1.9.6-tectonic.1) has been released to the pre-production channel and should fix this issue. Please report back if you do or don't see a change in behavior.

1.9.6 will be pushed to the production channel after baking in pre-prod.

**Closed by robszumski** 2018-05-24 16:19 UTC
Labels: area/stability, component/kubernetes, dependency/external, kind/regression, team/k8s
