### ISSUE TITLE
Kublet-wrapper won't start after upgrade to 1409.2.0 with duplicate /var/log mount

### ISSUE THREAD

**Issue by dadux** [coreos/bugs#2016] opened 2017-06-22 02:06 UTC
## Bug ##

Similar to https://github.com/coreos/bugs/issues/1892 - thought the issue was resolved before re-introducing /var/log in the wrapper ??

### Container Linux Version ###

```
1409.2.0
```

### Reproduction Steps ###

This the rkt run command executed by the kubelet-wrapper :
```
exec /usr/bin/rkt run --volume dns,kind=host,source=/etc/resolv.conf --mount volume=dns,target=/etc/resolv.conf --volume logs,kind=host,source=/var/log --mount volume=logs,target=/var/log --volume certs,kind=host,source=/etc/ssl/kubernetes --mount volume=certs,target=/etc/ssl/kubernetes --uuid-file-save=/var/run/kubelet-pod.uuid --trust-keys-from-https --volume etc-kubernetes,kind=host,source=/etc/kubernetes,readOnly=false --volume etc-ssl-certs,kind=host,source=/etc/ssl/certs,readOnly=true --volume usr-share-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume var-lib-docker,kind=host,source=/var/lib/docker,readOnly=false --volume var-lib-kubelet,kind=host,source=/var/lib/kubelet,readOnly=false,recursive=true --volume var-log,kind=host,source=/var/log,readOnly=false --volume os-release,kind=host,source=/usr/lib/os-release,readOnly=true --volume run,kind=host,source=/run,readOnly=false --mount volume=etc-kubernetes,target=/etc/kubernetes --mount volume=etc-ssl-certs,target=/etc/ssl/certs --mount volume=usr-share-certs,target=/usr/share/ca-certificates --mount volume=var-lib-docker,target=/var/lib/docker --mount volume=var-lib-kubelet,target=/var/lib/kubelet --mount volume=var-log,target=/var/log --mount volume=os-release,target=/etc/os-release --mount volume=run,target=/run --stage1-from-dir=stage1-fly.aci quay.io/coreos/hyperkube:v1.6.6_coreos.0 --exec=/kubelet -- --client-ca-file=/etc/ssl/kubernetes/ca.pem --read-only-port=0 --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --network-plugin=cni --container-runtime=docker --rkt-path=/usr/bin/rkt --require-kubeconfig --kubeconfig=/etc/kubernetes/kubeconfig/kubelet-kubeconfig.yaml --rkt-stage1-image=coreos.com/rkt/stage1-coreos --register-schedulable=false --allow-privileged=true --pod-manifest-path=/etc/kubernetes/manifests --cluster_dns=10.150.55.10
```

Fails with : 
```
kubelet-wrapper[2568]: run: can't evaluate mounts: missing mount for volume "var-log"
```

As you can see there's 2 `/var/log` mount. 

### Other Information ###
```
$ rkt version
rkt Version: 1.25.0
appc Version: 0.8.10
Go Version: go1.7.5
Go OS/Arch: linux/amd64
Features: -TPM +SDJOURNAL
```

**Comment by lucab** [comment] 2017-06-22 09:37
Confirmed. While we fixed this for alpha, it looks like things on stable didn't go as planned and the kubelet-wrapper in `build-1409` slipped by mistake a bit too far in history. Sorry for the breakage.

/cc @euank @dm0-

**Comment by euank** [comment] 2017-06-22 19:25
Thanks for catching this (again) @dadux.

We slipped-up on keeping track of the reversions and fixes for this.

We're rolling a quick stable bump to revert the `/var/log` mount one last time.
The next major stable release should have the proper resolution along with rkt 1.26.0.

This time we'll also make sure to add a regression test to our test suite; we were negligent not to last time.

**Comment by bgilbert** [comment] 2017-06-22 21:52
Fixed by https://github.com/coreos/coreos-overlay/pull/2624, which should be released shortly in 1409.5.0.

**Closed by bgilbert** 2017-06-22 21:52 UTC
Labels: area/usability, component/kubelet, kind/regression, team/os

**Comment by coreyjohnston** [comment] 2017-06-23 00:43
Thanks for the update; this bug caused a world of hurt for our prod customers last time so glad to see it fixed now.

**Comment by micahhausler** [comment] 2017-07-06 17:54
Just wanted to comment on this. I know this was the incorrect and breaking behavior: but we were relying on this and now we have had to re-add the `/var/log/{containers,pods}` mounts.

**Comment by euank** [comment] 2017-07-06 18:27
@micahhausler  per above, the bindmount will be added by default in a backwards compatible way with the next major stable version (and is already present in alpha & beta); adding the mount yourself should be a safe thing to do and shouldn't break in the future either.

Apologies for the churn around this specific change. Per the discussion in #1892 it ended up being a more complicated fix than expected, and so it's taking a little time to get to stable.
