### ISSUE TITLE
AWS: Low timeout for NVMe devices

### ISSUE THREAD

**Issue by johanneswuerbach** [coreos/bugs#2484] opened 2018-07-30 22:09 UTC
# Issue Report #

### Container Linux Version ###

```
1800.5.0
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

`AWS us-east-1 c5.2xlarge`

### Expected Behavior ###

Having an NVMe I/O Operation Timeout configured according to the recommendations from AWS. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html#timeout-nvme-ebs-volumes

### Actual Behavior ###

The NVMe timeout defaults to the kernel default of 30 seconds.

```
$ cat /sys/module/nvme_core/parameters/io_timeout
30
```

### Other Information ###

Might be related to https://github.com/coreos/bugs/issues/2371

**Comment by mariusgrigoriu** [comment] 2018-08-03 16:44
Where in the CoreOS code-base would this value be updated?

**Comment by Alalk** [comment] 2018-08-08 21:37
@johanneswuerbach i'm trying to test this to see if the aws docs will fix this. 

I was able to get the nvme_core params in the boot. I had to edit the grub in
` /usr/share/oem/grub.cfg` in a running ec2, then create an ami and try on a new ec2. 

`[    0.000000] Linux version 4.17.12-coreos-r1 (jenkins@ip-10-7-32-103) (gcc version 7.3.0 (Gentoo Hardened 7.3.0 p1.0)) #1 SMP Sat Aug 4 01:54:41 UTC 2018
[    0.000000] Command line: BOOT_IMAGE=/coreos/vmlinuz-a mount.usr=/dev/mapper/usr verity.usr=PARTUUID=7130c94a-213a-4e5a-8e26-6cce9662f132 rootflags=rw mount.usrflags=ro consoleblank=0 root=LABEL=ROOT console=ttyS0,115200n8 nvme_core.io_timeout=4294967295 nvme_core.max_retries=10 coreos.oem.id=ec2 modprobe.blacklist=xen_fbfront net.ifnames=0 verity.usrhash=398d83dd5252c42312d7ff4b49d0b854072cfcc03657d72e7c792ae24d60077e`

i'm still not see the drives get picked up. Although i'm trying on the i3 bare.metal.

**Comment by Alalk** [comment] 2018-08-09 16:19
@johanneswuerbach 
So i got this working. The grub file needs to be changed to have this nvme_core defaults set. Also it only works on the kernel version above 4.15. I will see if i can get a pull request into coreos for the fix.

**Comment by r7vme** [comment] 2018-09-24 12:44
We are also hitting this issue, setting timeouts (255 sec) and retries (10) seems helps.

Would love to have this "out-of-the-box" in AWS images.

**Comment by bgilbert** [comment] 2018-11-15 21:16
Closing as duplicate of #2464.

**Comment by bgilbert** [comment] 2019-03-14 23:28
Reopening per https://github.com/coreos/bugs/issues/2464#issuecomment-472917319.

**Comment by dm0-** [comment] 2019-05-07 20:06
The NVMe timeout has been changed for EC2 in the current alpha.  It will promote to stable in mid-June.

**Closed** 2019-05-16 15:47 UTC
Labels: area/stability, component/distro, jira, kind/friction, platform/aws, team/os

**Comment by pms1969** [comment] 2019-07-08 15:18
I'm running a mix of 2079.6 and 2135.4 and neither has the correct setting...  What version is meant to have this fix?

**Comment by bgilbert** [comment] 2019-07-08 17:06
It's in 2135.0.0 and above, but only for new installs.  Machines that are upgraded from older releases retain their previous settings.
