### ISSUE TITLE
Update systemd to v227

### ISSUE THREAD

**Issue by iaguis** [coreos/bugs#979] opened 2015-11-13 12:28 UTC
We would like to use v227 in rkt's stage1 to get some fixes (mainly https://github.com/systemd/systemd/pull/1318).

**Comment by vcaputo** [comment] 2015-11-17 15:07
@mischief You had experimented with v226 trying to reproduce the journal compression bug, were there any barriers to shipping v226 that we need to verify as fixed in v227 before it can potentially land?

Bumping util-linux to 2.27 seems to be sufficient for v227 to build successfully.

**Comment by alban** [comment] 2015-12-07 14:54
rkt would actually need to have future systemd-v229 for systemd/systemd#1318, systemd/systemd#1619, systemd/systemd#2097.

**Comment by crawford** [comment] 2016-01-20 21:27
Closing in favor of https://github.com/coreos/bugs/issues/1058.

**Closed by crawford** 2016-01-20 21:27 UTC
Labels: area/distribution, component/systemd, kind/enhancement, priority/P1, team/os
