### ISSUE TITLE
SELinux doesn't contain Docker containers

### ISSUE THREAD

**Issue by tjdett** [coreos/bugs#972] opened 2015-11-11 04:16 UTC
On a clean 845.0,  following:
```
rm /etc/audit/rules.d/80-selinux.rules
rm /etc/audit/rules.d/99-default.rules
rm /var/lib/selinux; cp -a /usr/lib/selinux/policy /var/lib/selinux
rm /etc/selinux/mcs; cp -a /usr/lib/selinux/mcs /etc/selinux/
semodule -DB
systemctl restart audit-rules
setenforce 1
systemctl restart docker
```

Docker runs as `kernel_t`:
```
$ ps -efZ | grep docker
system_u:system_r:kernel_t:s0   root      1792     1  0 04:04 ?        00:00:00 docker daemon --host=fd://
```

and as a result Docker containers are unrestricted in their access to the filesystem:
```
$ getenforce && docker run -ti --rm -v /etc:/mnt/etc alpine:3.2 sh -c "echo foo > /mnt/etc/test" && cat /etc/test
Enforcing
foo
```

**Comment by crawford** [comment] 2015-11-11 05:39
Looks like a duplicate of https://github.com/coreos/bugs/issues/961.

**Closed by crawford** 2015-11-11 05:39 UTC
