### ISSUE TITLE
solarflare adapter link is down after alpha installation 

### ISSUE THREAD

**Issue by mazad01** [coreos/bugs#412] opened 2015-07-14 16:06 UTC
Originally, SFC drivers weren't enabled in CoreOS builds. `ip a` didn't show the solarflare adapters. This issue https://github.com/coreos/bugs/issues/400 enabled that in the alpha version. The adapter came up after the upgrade but the link is down.

```
~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=738.1.0
VERSION_ID=738.1.0
BUILD_ID=
PRETTY_NAME="CoreOS 738.1.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
~ $ lsmod | grep -i sfc
sfc                   262144  0
mtd                    49152  9 sfc
i2c_algo_bit           16384  1 sfc
hwmon                  16384  2 sfc,coretemp
ptp                    20480  2 sfc,bnx2x
mdio                   16384  2 sfc,bnx2x
i2c_core               49152  3 sfc,ipmi_ssif,i2c_algo_bit
 ~ $ ip a
2: ens1f0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 00:0f:53:12:00:88 brd ff:ff:ff:ff:ff:ff
    inet 10.187.10.11/24 brd 10.187.10.255 scope global ens1f0
       valid_lft forever preferred_lft forever
3: ens1f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 00:0f:53:12:00:89 brd ff:ff:ff:ff:ff:ff
~ $
```

The light on the physical switch is also down. (the light was up before the switch from stable to alpha, but obviously  the stable version didn't have the driver enabled). Any ideas?

**Comment by marineam** [comment] 2015-07-14 16:38
Anything logged in dmesg that seems related?

**Comment by mazad01** [comment] 2015-07-14 16:44
on journalctl

```
Jul 10 18:38:16 localhost kernel: Solarflare NET driver v4.0
Jul 10 18:38:16 localhost kernel: sfc 0000:06:00.0 (unnamed net_device) (uninitialized): Solarflare NIC detected
Jul 10 18:38:16 localhost kernel: sfc 0000:06:00.0 (unnamed net_device) (uninitialized): Part Number : SFN5802K
Jul 10 18:38:16 localhost kernel: hub 2-0:1.0: USB hub found
Jul 10 18:38:16 localhost kernel: hub 2-0:1.0: 2 ports detected
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:00:1d.1: UHCI Host Controller
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:00:1d.1: new USB bus registered, assigned bus number 3
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:00:1d.1: detected 2 ports
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:00:1d.1: irq 23, io base 0x00001020
Jul 10 18:38:16 localhost kernel: hub 3-0:1.0: USB hub found
Jul 10 18:38:16 localhost kernel: hub 3-0:1.0: 2 ports detected
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:00:1d.2: UHCI Host Controller
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:00:1d.2: new USB bus registered, assigned bus number 4
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:00:1d.2: detected 2 ports
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:00:1d.2: irq 22, io base 0x00001040
Jul 10 18:38:16 localhost kernel: hub 4-0:1.0: USB hub found
Jul 10 18:38:16 localhost kernel: hub 4-0:1.0: 2 ports detected
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:00:1d.3: UHCI Host Controller
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:00:1d.3: new USB bus registered, assigned bus number 5
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:00:1d.3: detected 2 ports
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:00:1d.3: irq 23, io base 0x00001060
Jul 10 18:38:16 localhost kernel: hub 5-0:1.0: USB hub found
Jul 10 18:38:16 localhost kernel: hub 5-0:1.0: 2 ports detected
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:01:04.4: UHCI Host Controller
Jul 10 18:38:16 localhost kernel: ACPI Warning: SystemIO range 0x0000000000000928-0x000000000000092F conflicts with OpRegion 0x0000000000000920-0x000000000000092F (\SGPE) (20150204/utaddress-254)
Jul 10 18:38:16 localhost kernel: ACPI: If an ACPI driver is available for this device, you should use it instead of the native driver
Jul 10 18:38:16 localhost kernel: lpc_ich: Resource conflict(s) found affecting gpio_ich
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:01:04.4: new USB bus registered, assigned bus number 6
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:01:04.4: detected 8 ports
Jul 10 18:38:16 localhost kernel: uhci_hcd 0000:01:04.4: port count misdetected? forcing to 2 ports
Jul 10 18:38:17 localhost kernel: uhci_hcd 0000:01:04.4: irq 22, io base 0x00003800
Jul 10 18:38:17 localhost kernel: sfc 0000:06:00.0 (unnamed net_device) (uninitialized): MC command 0x30 inlen 12 failed rc=-13 (raw=13) arg=0
Jul 10 18:38:17 localhost kernel: sfc 0000:06:00.0 (unnamed net_device) (uninitialized): MC command 0xb inlen 8 failed rc=-38 (raw=38) arg=0
Jul 10 18:38:17 localhost kernel: hub 6-0:1.0: USB hub found
Jul 10 18:38:17 localhost kernel: hub 6-0:1.0: 2 ports detected
Jul 10 18:38:17 localhost kernel: microcode: CPU0 sig=0x106a5, pf=0x1, revision=0x15
Jul 10 18:38:17 localhost kernel: microcode: CPU1 sig=0x106a5, pf=0x1, revision=0x15
Jul 10 18:38:17 localhost kernel: microcode: CPU2 sig=0x106a5, pf=0x1, revision=0x15
Jul 10 18:38:17 localhost kernel: microcode: CPU3 sig=0x106a5, pf=0x1, revision=0x15
Jul 10 18:38:17 localhost kernel: microcode: CPU4 sig=0x106a5, pf=0x1, revision=0x15
Jul 10 18:38:17 localhost kernel: microcode: CPU5 sig=0x106a5, pf=0x1, revision=0x15
Jul 10 18:38:17 localhost kernel: microcode: CPU6 sig=0x106a5, pf=0x1, revision=0x15
Jul 10 18:38:17 localhost kernel: microcode: CPU7 sig=0x106a5, pf=0x1, revision=0x15
Jul 10 18:38:17 localhost kernel: microcode: Microcode Update Driver: v2.00 <tigran@aivazian.fsnet.co.uk>, Peter Oruba
Jul 10 18:38:17 localhost kernel: sfc 0000:06:00.1 (unnamed net_device) (uninitialized): Solarflare NIC detected
Jul 10 18:38:17 localhost kernel: sfc 0000:06:00.1 (unnamed net_device) (uninitialized): Part Number : SFN5802K
Jul 10 18:38:17 localhost kernel: iTCO_vendor_support: vendor-support=0
Jul 10 18:38:17 localhost kernel: iTCO_wdt: Intel TCO WatchDog Timer Driver v1.11
Jul 10 18:38:17 localhost kernel: iTCO_wdt: unable to reset NO_REBOOT flag, device disabled by hardware/BIOS
Jul 10 18:38:17 localhost kernel: kvm: VM_EXIT_LOAD_IA32_PERF_GLOBAL_CTRL does not work properly. Using workaround
Jul 10 18:38:17 localhost kernel: ipmi_si 0000:01:04.6: Using irq 21
Jul 10 18:38:17 localhost kernel: sfc 0000:06:00.1 (unnamed net_device) (uninitialized): MC command 0x30 inlen 12 failed rc=-13 (raw=13) arg=0
Jul 10 18:38:17 localhost kernel: sfc 0000:06:00.1 (unnamed net_device) (uninitialized): MC command 0xb inlen 8 failed rc=-38 (raw=38) arg=0
Jul 10 18:38:17 localhost kernel: sd 0:0:0:0: [sda] 585871964 512-byte logical blocks: (299 GB/279 GiB)
Jul 10 18:38:17 localhost kernel: sd 0:0:0:0: [sda] Write Protect is off
Jul 10 18:38:17 localhost kernel: sd 0:0:0:0: [sda] Mode Sense: 6b 00 00 08
Jul 10 18:38:17 localhost kernel: sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
Jul 10 18:38:17 localhost kernel:  sda: sda1 sda2 sda3 sda4 sda6 sda7 sda9
Jul 10 18:38:17 localhost kernel: sd 0:0:0:0: [sda] Attached SCSI disk
Jul 10 18:38:17 localhost kernel: tsc: Refined TSC clocksource calibration: 2933.437 MHz
Jul 10 18:38:17 localhost kernel: ipmi_si 0000:01:04.6: Found new BMC (man_id: 0x00000b, prod_id: 0x2020, dev_id: 0x11)

**Comment by jumanjiman** [comment] 2015-07-15 18:12
@mazad01 try `sudo dmesg`

**Comment by mazad01** [comment] 2015-07-15 18:18
> @mazad01 try sudo dmesg

```
~ $ sudo dmesg | grep sfc
[    4.315691] sfc 0000:06:00.0 (unnamed net_device) (uninitialized): Solarflare NIC detected
[    4.332836] sfc 0000:06:00.0 (unnamed net_device) (uninitialized): Part Number : SFN5802K
[    4.417851] sfc 0000:06:00.0 (unnamed net_device) (uninitialized): MC command 0x30 inlen 12 failed rc=-13 (raw=13) arg=0
[    4.417860] sfc 0000:06:00.0 (unnamed net_device) (uninitialized): MC command 0xb inlen 8 failed rc=-38 (raw=38) arg=0
[    4.558558] sfc 0000:06:00.1 (unnamed net_device) (uninitialized): Solarflare NIC detected
[    4.562230] sfc 0000:06:00.1 (unnamed net_device) (uninitialized): Part Number : SFN5802K
[    4.647890] sfc 0000:06:00.1 (unnamed net_device) (uninitialized): MC command 0x30 inlen 12 failed rc=-13 (raw=13) arg=0
[    4.647900] sfc 0000:06:00.1 (unnamed net_device) (uninitialized): MC command 0xb inlen 8 failed rc=-38 (raw=38) arg=0
[    8.309649] sfc 0000:06:00.1 ens1f1: renamed from eth1
[    8.365695] sfc 0000:06:00.0 ens1f0: renamed from eth0
[   16.604496] sfc 0000:06:00.1 ens1f1: link down
[   16.623868] sfc 0000:06:00.0 ens1f0: link down


```

**Comment by mazad01** [comment] 2015-07-16 17:01
just tested on a standalone server running latest version of alpha and link is up. 

```
~ $ sudo dmesg | grep sfc
[    5.888011] sfc 0000:04:00.0 (unnamed net_device) (uninitialized): Solarflare NIC detected
[    5.892472] sfc 0000:04:00.0 (unnamed net_device) (uninitialized): Part Number : 728531-001
[    5.922609] sfc 0000:04:00.0 (unnamed net_device) (uninitialized): MC command 0x30 inlen 12 failed rc=-13 (raw=13) arg=0
[    5.922618] sfc 0000:04:00.0 (unnamed net_device) (uninitialized): MC command 0xb inlen 8 failed rc=-38 (raw=38) arg=0
[    6.573249] sfc 0000:04:00.1 (unnamed net_device) (uninitialized): Solarflare NIC detected
[    6.626094] sfc 0000:04:00.1 (unnamed net_device) (uninitialized): Part Number : 728531-001
[    6.656072] sfc 0000:04:00.1 (unnamed net_device) (uninitialized): MC command 0x30 inlen 12 failed rc=-13 (raw=13) arg=0
[    6.668370] sfc 0000:04:00.1 (unnamed net_device) (uninitialized): MC command 0xb inlen 8 failed rc=-38 (raw=38) arg=0
[    8.613370] sfc 0000:04:00.1 eno50: renamed from eth5
[    8.623701] sfc 0000:04:00.0 eno49: renamed from eth3
[   10.065057] sfc 0000:04:00.1 eno50: link down
[   10.072817] sfc 0000:04:00.1 eno50: link down
[   10.213834] sfc 0000:04:00.0 eno49: link up at 10000Mbps full-duplex (MTU 1500)
 ~ $ lspci | grep -i solar
04:00.0 Ethernet controller: Solarflare Communications SFC9020 [Solarstorm]
04:00.1 Ethernet controller: Solarflare Communications SFC9020 [Solarstorm]
~ $
```

And the controller is the same as the host tested above.

**Comment by mazad01** [comment] 2015-07-22 15:08
bump

**Comment by marineam** [comment] 2015-07-24 00:55
Is the working host and the broken host using the same alpha version?

**Comment by vcaputo** [comment] 2015-07-24 01:00
I'm curious what happens when you run `ethtool --negotiate` on the sfc interfaces, does it cause a link to be established?

**Comment by marineam** [comment] 2015-07-24 01:00
Oh different models, it looks like `SFN5802K` does not work but `728531-001` does.

**Comment by mazad01** [comment] 2015-07-24 01:32
> Is the working host and the broken host using the same alpha version?

yes same version

> Oh different models, it looks like SFN5802K does not work but 728531-001 does.

correct, and the other notable difference is the one that does not work is a blade server whereas the one that works is a stand-alone server

**Comment by mazad01** [comment] 2015-07-24 01:33
> I'm curious what happens when you run ethtool --negotiate on the sfc interfaces, does it cause a link to be established?

```
 ~ # ethtool ens1f0
Settings for ens1f0:
        Supported ports: [ FIBRE ]
        Supported link modes:   Not reported
        Supported pause frame use: Symmetric Receive-only
        Supports auto-negotiation: Yes
        Advertised link modes:  Not reported
        Advertised pause frame use: Symmetric
        Advertised auto-negotiation: Yes
        Link partner advertised link modes:  Not reported
        Link partner advertised pause frame use: Symmetric
        Link partner advertised auto-negotiation: No
        Speed: 10000Mb/s
        Duplex: Full
        Port: FIBRE
        PHYAD: 2
        Transceiver: internal
        Auto-negotiation: on
        Supports Wake-on: g
        Wake-on: d
        Current message level: 0x000020f7 (8439)
                               drv probe link ifdown ifup rx_err tx_err hw
        Link detected: no
~ # ethtool --negotiate ens1f0
Cannot restart autonegotiation: Operation not supported
~ #
```

**Comment by mazad01** [comment] 2015-07-24 01:36
ethtool on the interface from the server that the link is up
```
 ~ $ ethtool eno49
Settings for eno49:
        Supported ports: [ FIBRE ]
        Supported link modes:   Not reported
        Supported pause frame use: Symmetric Receive-only
        Supports auto-negotiation: No
        Advertised link modes:  Not reported
        Advertised pause frame use: No
        Advertised auto-negotiation: No
        Link partner advertised link modes:  Not reported
        Link partner advertised pause frame use: No
        Link partner advertised auto-negotiation: No
        Speed: 10000Mb/s
        Duplex: Full
        Port: FIBRE
        PHYAD: 255
        Transceiver: internal
        Auto-negotiation: off
Cannot get wake-on-lan settings: Operation not permitted
        Current message level: 0x000020f7 (8439)
                               drv probe link ifdown ifup rx_err tx_err hw
        Link detected: yes
~ $
```

**Comment by marineam** [comment] 2015-07-24 03:43
Two more things I can think of:
 - Try turning auto negotiation off, matching the setup of the stand-alone card: `ethtool -s ens1f0 autoneg off`
 - Enable all logging for the driver, maybe something insightful will come up: `modprobe -r sfc; modprobe sfc debug=0xffff`

**Comment by mazad01** [comment] 2015-07-24 12:28
> Try turning auto negotiation off, matching the setup of the stand-alone card: ethtool -s ens1f0 autoneg off

```
~ $ sudo ethtool -s ens1f0 autoneg off
Cannot set new settings: Invalid argument
  not setting autoneg
~ $
```



> Enable all logging for the driver, maybe something insightful will come up: modprobe -r sfc; modprobe sfc debug=0xffff

nothing came up

**Comment by vcaputo** [comment] 2015-07-24 20:30
Since these are theoretically the same controllers just in different physical form factors, maybe firmware versions are responsible for the disparity.

`ethtool -i <iface>` should report the firmware version, perhaps a firmware update will fix things up?

**Comment by vcaputo** [comment] 2015-07-24 20:50
Also curious to know if the phy_type differs in `/sys/class/net/<iface>/device/phy_type` between the two cards.

**Comment by philips** [comment] 2015-07-24 23:05
@mazad01 Also, are there any distros that you have tried with this hardware that does work? That would help us diagnose the issue and file an issue upstream. It is possible that the pure mainline kernel.org Linux that we ship might have a bug in it preventing this from working and information on a different or older Kernel would help track down the right patch or the regression.

**Comment by mazad01** [comment] 2015-07-27 13:42
> ethtool -i <iface> should report the firmware version,

on the host that sfc is working
```
 ~ $ ethtool -i eno49
driver: sfc
version: 4.0
firmware-version: 3.3.0.6275
bus-info: 0000:04:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
```

on the host that sfc is not working
```
~ $ ethtool -i ens1f0
driver: sfc
version: 4.0
firmware-version: 3.2.0.6006
bus-info: 0000:06:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
```

I'll try updating the firmware



> Also curious to know if the phy_type differs in /sys/class/net/<iface>/device/phy_type between the two cards.

Working SFC host:
```
~ $ cat /sys/class/net/eno49/device/phy_type
12
```

Not-Working SFC host:
```
~ $ cat /sys/class/net/ens1f0/device/phy_type
17
```



> Also, are there any distros that you have tried with this hardware that does work?

Unfortunately no, we have worked with only CoreOS on these servers. A diff distro would be a good step troubleshooting going forward if the firmware upgrade doesn't do the trick

**Comment by mazad01** [comment] 2015-07-27 14:18
searching the web, i came across http://h20564.www2.hp.com/hpsc/swd/public/detail?swItemId=MTX_25c596cf9e4e4354928d14d288#tab1. Any tips on how to install this rpm?

**Comment by mazad01** [comment] 2015-07-27 16:04
Edit: the last link is not the firmware utility. i found the correct one here https://support.solarflare.com/index.php?view=categories&id=2384&option=com_cognidox&Itemid=15, and installed the rpm via toolbox. 

```
 ~# sfupdate
Solarstorm firmware update utility [v3.4.0]
Copyright Solarflare Communications 2006-2013, Level 5 Networks 2002-2005

ens1f0 - MAC: 00-0F-53-12-00-88

ens1f1 - MAC: 00-0F-53-12-00-89
    Firmware version:   v3.2.0
    PHY type:           QT2025_KR
    PHY version:        v3.3.0.0
    Controller type:    Solarflare SFC9000 family
    Controller version: v3.2.0.6006
    Boot ROM version:   v3.1.0.4018

The PHY firmware is up to date
This utility contains more recent Boot ROM firmware [v3.3.1.6312]
   - run "sfupdate --write" to perform an update
This utility contains more recent controller firmware [v3.3.0.6275]
   - run "sfupdate --write" to perform an update
~# sfupdate --write
Solarstorm firmware update utility [v3.4.0]
Copyright Solarflare Communications 2006-2013, Level 5 Networks 2002-2005
ens1f1: not changing PHY firmware from 3.3.0.0 to 3.3.0.0
ens1f1: updating controller firmware from 3.2.0.6006 to 3.3.0.6275
ens1f1: will be disabled during controller firmware update
To continue, press Y then Enter
To skip this update, press Enter
Y
ens1f1: writing controller firmware
[100%] Complete
[100%] Completeg adapter
ens1f1: updating Boot ROM from 3.1.0.4018 to 3.3.1.6312
ens1f1: writing Boot ROM
[100%] Complete
ens1f1: writing version information
[100%] Complete
ens1f0: writing version information
[100%] Complete

```
after a reboot, still no link, and has latest firmware
```
[~]# sfupdate
Solarstorm firmware update utility [v3.4.0]
Copyright Solarflare Communications 2006-2013, Level 5 Networks 2002-2005

ens1f0 - MAC: 00-0F-53-12-00-88

ens1f1 - MAC: 00-0F-53-12-00-89
    Firmware version:   v3.4.0
    PHY type:           QT2025_KR
    PHY version:        v3.3.0.0
    Controller type:    Solarflare SFC9000 family
    Controller version: v3.3.0.6275
    Boot ROM version:   v3.3.1.6312

The PHY firmware is up to date
The Boot ROM firmware is up to date
The controller firmware is up to date
[~]#
~ $ ethtool -i ens1f0
driver: sfc
version: 4.0
firmware-version: 3.3.0.6275
bus-info: 0000:06:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no

```

**Comment by mazad01** [comment] 2015-07-27 16:16
@philips also just found out, we do in fact use these sfc cards with rhel

**Comment by marineam** [comment] 2015-07-27 23:48
One thing I hadn't thought of before is there was a compiler issue with the kernel build in 738.1.0, although it seems unlikely maybe there is a tiny memory corruption confusing things. If you haven't tested a newer CoreOS than the one this issue was started with it is worth a shot. Also the latest alpha  752.1.0 has a small kernel update, 4.0.9. The changes there seem unlikely to have an impact on this driver but who knows.

If that doesn't help I'd try the latest Fedora or other distro with a close-to-mainline kernel to get a final answer on if this is a common issue or if there is something wrong with how we are configuring/building kernels.

**Comment by mazad01** [comment] 2015-07-28 01:00
@marineam I'm currently on 752.1.0, i was hoping the later releases would help fix the problem as well :(

**Comment by jumanjiman** [comment] 2015-07-29 00:59
here is a comparison.

in the table, the right-most 2 columns use the same blade. (coreos 752.1.0 is hard drive install, coreos 522.2.0 is pxe-boot).

|                 | works                | not works             | not works                |
| --------------- | -------------------- | --------------------- | ------------------------ |
| hostname        | td-np01              | td-np11               | td-np11                  |
| CoreOS          | 752.1.0              | 752.1.0               | 522.2.0                  |
| NIC (lspci)     | SFC 9020 (00:04.0x)  | SFC 9020 (00:06.0x)   | SFC 9020 (00:06.0x)      |
| firmware        | 3.3.0.6275           | 3.3.0.6275            | 3.3.0.6275               |
| system hw       | DL 360 g9 rackmount  | BL 460c g6 blade      | BL 460c g6 blade         |
| hp passthrough? | no                   | yes                   | yes                      |
| phy type        | 12                   | 17                    | missing                  |
| interface name  | eno49                | ens1f0                | missing                  |
| sfc driver      | 4.0                  | 4.0                   | missing                  |
| ip link         | yes                  | no                    | missing                  |
| passthru link   | n/a                  | no                    | on, solid green          |
| switch link     | yes                  | no                    | on, solid green          |

@mazad01 can you grab a g8v2 blade wednesday and install coreos with an sfc 9020?
i'm pretty sure we have a g9 blade handy, too.

@planet didn't we deprecate the g6 blades due to hardware issues? (feel free to respond in-house)

**Comment by mazad01** [comment] 2015-07-29 02:32
will do @jumanjiman

**Comment by jumanjiman** [comment] 2015-07-29 15:31
update https://github.com/coreos/bugs/issues/412#issuecomment-125793893 with column for rhel 6.5 + bl460cg6 (not works)

**Comment by mazad01** [comment] 2015-07-29 21:19
just an update, we tried putting a gen9 blade in that slot with an SFC 9120 and the link is up. So the issue maybe somewhere in the gen6 + sfc 9020 mix. Quick question, is this the driver you guys are loading into the kernel for SFC? https://support.solarflare.com/index.php?option=com_cognidox&file=SF-103848-LS-34_Solarflare_NET_driver_source_RPM.rl.txt&task=download&format=raw&id=1945

**Comment by mischief** [comment] 2015-07-29 21:37
we're loading the upstream linux kernel driver. i enabled it in coreos/coreos-overlay@7705fab8ab028a89716e14d867ac8d972fb0a603

**Comment by mischief** [comment] 2015-07-29 21:39
did i forget anything?

**Comment by mazad01** [comment] 2015-07-29 22:07
is it possible we can go from sfc driver version 4.0 to 4.5.1.1010 in the coreos kernel? I just upgraded the sfc driver on a spare g6 blade on rhel-6.3 from 4.0 to 4.5 and I got link. So i think this is a driver issue most definitely. The g6 blade + sfc 9020 combo works on rhel-6.3 with the 4.5.1.1010 driver.

**Comment by marineam** [comment] 2015-07-29 23:17
4.0 is just the dummy version the mainline driver reports, it is developed in parallel to the out-of-tree driver so the one in coreos should be relatively close to recent 4.5 releases, minus some extra stuff that is only in the out of tree driver has. I did some digging through recent changes and some of the differences between the two drivers but haven't spotted anything interesting so far. Do you have a support account with either HP or Solarflare? I would expect the mainline driver being broken would be a known issue to someone and what the fix in the out-of-tree driver is.

**Comment by marineam** [comment] 2015-07-29 23:25
One thing that may be of interest is there is a lot of new code/refactoring in both the latest out-of-tree driver and the latest (linux 4.2-rc) upstream driver for virtual function SR-IOV devices, I wonder if some of that churn also impacts multi-function PCI devices like the one that isn't working for you. To test that theory I can spin you an image with the latest 4.2-rc kernel and see if that helps. Alternatively you can try building the latest git kernel yourself on a development friendly distro.

**Comment by jumanjiman** [comment] 2015-07-29 23:44
i was also looking at the code comparisons.

@mazad01 perhaps change SRIOV bios setting in the g6 on np11 (is there a setting for that on g6?). We've seen that SRIOV bios setting impacts NICs (internal, private issues) on recent hardware.

* coreos 752.1.0 + in-tree driver on g6 == no work
* coreos 752.1.0 + in-tree driver on g9 == success
* rhel6.5 + in-tree driver on g6 == no work
* rhel6.3 + out-of-tree driver on g6 == success

@marineam @mischief 

fyi We pulled td-np11 and set it aside today. We put a g9 blade (albeit with an SFC9120 as opposed to SFC9020 due to form factor) in the np11 physical slot today and it worked. We could pass traffic. That proves the pass-through, gbics, switch, etc., are all good. 

Consequently we're focusing our efforts on the g6 and SFC9020.

**Comment by jumanjiman** [comment] 2015-07-29 23:50
> Do you have a support account with either HP or Solarflare?

yes.

@mazad01 can you engage both hp & solarflare support in the morning?
You have proven that an out-of-tree driver works on the g6, which shifts support to some combo of hp & solarflare. Where possible, let's cherry-pick snippets from internal issues to this public issue in case it informs others (incl the vendors), assuming it's ok by coreos peeps.

**Comment by jumanjiman** [comment] 2015-07-30 00:02
@mazad01 

btw if you want to compare the code within your own devenv (others: we have devenvs with strict memory constraints), start with this:

```console
$ git clone --depth=1 https://github.com/torvalds/linux.git
$ cd linux
$ git fetch --unshallow
```

then download the srpm zip from solarflare support portal:

```console
$ wget "$url"
$ cd /tmp/
$ unzip ~/<path-to-zip>
$ rpm2cpio <path-to-srpm> | cpio -idv
```

**Comment by mazad01** [comment] 2015-07-30 00:22
> 4.0 is just the dummy version the mainline driver reports, it is developed in parallel to the out-of-tree driver so the one in coreos should be relatively close to recent 4.5 releases,

got it

> perhaps change SRIOV bios setting in the g6 on np11

Will try this first tomorrow

> engage both hp & solarflare support in the morning

:sweat_smile: sure

> btw if you want to compare the code within your own devenv

ok, will check it out.

**Comment by philips** [comment] 2015-08-05 22:05
@mazad01 How did the SRIOV bios setting swap work out?

**Comment by mazad01** [comment] 2015-08-06 16:48
Thanks for following up, the Gen8 server + SFC combo worked with rhel and coreos. The gen6 failed with both. So we have decided to retire the gen6 + sfc combo.

**Comment by philips** [comment] 2015-08-07 17:56
@mazad01 OK, can I close this issue then?

**Closed** 2015-08-07 17:56 UTC
Labels: os

**Comment by mazad01** [comment] 2015-08-07 18:08
> @mazad01 OK, can I close this issue then?

sure.

**Comment by mazad01** [comment] 2015-08-07 18:08
thanks for the help guys, much appreciated.
