### ISSUE TITLE
cpuacct.usage_percpu has extra 0 values for every cgroup (in aws)

### ISSUE THREAD

**Issue by nicklan** [coreos/bugs#2088] opened 2017-08-03 21:22 UTC
# Issue Report #

## Bug ##
The number of entries in all `cpuacct.usage_percpu` files in the cgroup hierarchy is incorrect, there are a number of spurious zeros.

This was not an issue in 899.  

This causes problems down the line when kublet wants to export `container_cpu_usage_seconds_total`.  It creates a large number of "spurious" 0 metrics for non-existent cpus as cAdvisor iterates over the number of entries in this file for each container.

### Container Linux Version ###
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.7.0
VERSION_ID=1409.7.0
BUILD_ID=2017-07-19-0005
PRETTY_NAME="Container Linux by CoreOS 1409.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

AWS t2.micro instance, ami-19c0de60

Have also seen on M4.4xlarge and M4.10xlarge

### Expected Behavior ###
File should only contain one entry per cpu.
### Actual Behavior ###
Number of entries gets padded up to 2^x-1.  With a one core machine there will be 15 entries, with a 16 core machine, 127.  I don't know the exact pattern, but it does seem to follow powers of 2.  
### Reproduction Steps ###
1. launch an aws instance (i used a t2.micro instance on ami-19c0de60 for the data below.
2. ssh into the instance
3. `cat  /sys/fs/cgroup/cpu,cpuacct/cpuacct.usage_percpu` =>
```
6131142892 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
```

### Other Information ###
/proc/cpuinfo:
```processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
stepping	: 2
microcode	: 0x36
cpu MHz		: 2400.098
cache size	: 30720 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt
bugs		:
bogomips	: 4800.17
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

Regarding how many entries should be there.  From [here](https://kernel.googlesource.com/pub/scm/linux/kernel/git/glommer/memcg/+/cpu_stat/Documentation/cgroups/cpu.txt)

"cpuacct.usage_percpu: The CPU time, in nanoseconds, consumed by all tasks in
this group, separated by CPU. The format is an space-separated array of time
values, one for each present CPU."

**Comment by euank** [comment] 2017-08-03 22:00
I think this is working as intended. See the linux kernel mailing list discussion here: https://patchwork.kernel.org/patch/8607101/

That patch changed it from each *present* cpu to each *possible* cpu. The documentation you link is now outdated.

Presumably AWS is presenting the possibility of hotplug cpus up to that amount based on your machine's configuration.

This change was originally included in the v4.7 kernel is why that older version worked correctly.

I think this bug is best addressed by Kubernetes updating their parsing code to work correctly on modern kernels.

**Closed by euank** 2017-08-03 22:00 UTC

**Comment by euank** [comment] 2017-08-03 22:38
I threw up a patch that might fix this for Kubernetes. If you want to include that change in the kubelet and see if it fixes for you, and then comment on that PR, that would be helpful.

https://github.com/google/cadvisor/pull/1711

**Comment by nicklan** [comment] 2017-08-03 22:42
Awesome, thanks so much!  I'll try and test and comment asap
