### ISSUE TITLE
Dockers unable to resolve hostmachine's hostname even with networking host enabled

### ISSUE THREAD

**Issue by hassaanp** [coreos/bugs#2182] opened 2017-10-06 11:15 UTC
# Issue Report #

## Bug ##
Any docker containers spawned on coreOS instances are unable to resolve the hostmachine's hostname.

Dockers are spawned with `--networking host`
An explicit entry in /etc/hosts for the hostname resolution is necessary 
### Container Linux Version ###

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1465.8.0
VERSION_ID=1465.8.0
BUILD_ID=2017-09-20-2237
PRETTY_NAME="Container Linux by CoreOS 1465.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
COREOS_BOARD="amd64-usr"

BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
Digital Ocean

### Expected Behavior ###
ping hostname should work

### Actual Behavior ###
hostname could not be resolved

### Reproduction Steps ###

  1. spawn a docker (any image) with --networking host as the flags
  2. enter the container and try to run `ping hostname`

### Other Information ###

## Feature Request ##

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

### Desired Feature ###

### Other Information ###

**Comment by squeed** [comment] 2017-10-06 13:20
Is the hostname in the host's `/etc/hosts`?

**Comment by euank** [comment] 2017-10-06 18:17
Hostnames are handled by the UTS namespace, not the network namespace (yes, it's confusing!).

Whether it resolves also depends on the software running in the container.

```sh
$ hostname
multivac.euank.com
$ docker run -it --uts=host fedora sh -c 'dnf install -y iputils && ping -c 1 multivac.euank.com'
....
PING multivac.euank.com (172.17.0.2) 56(84) bytes of data.
64 bytes from 2ac75d96ce32 (172.17.0.2): icmp_seq=1 ttl=64 time=0.076 ms
```

Note, this is because fedora has a `/etc/nsswitch.conf` file in the container containing:
```
hosts:      files dns myhostname
```

On busybox, and various other containers, that wouldn't work.

Basically, everything here is working as intended I think. 
To summarize:
1. The UTS namespace controls the hostname.
2. Hostname resolution depends on how the container does it. Some use UTS hostname, some don't. For some container userspaces you'll have to write an /etc/hosts file.

Since I don't think there's actually a bug here on our end, I'm closing this. It's possible docker could provide better documentation for this if you want to contact them.

Cheers

**Closed by euank** 2017-10-06 18:17 UTC
