### ISSUE TITLE
Cant install on Windows 7 via Vagrant Virtualbox

### ISSUE THREAD

**Issue by NameTheJew** [coreos/bugs#2479] opened 2018-07-26 12:25 UTC
# Issue Report #
After running Vagrant up get the following error
## Bug ##
```
C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `[]=': Invalid argument - ruby_setenv(VAGRANT_NO_PLUGINS) (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `block in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `each_index'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vag
```
### Container Linux Version ###
Trying to install stable following this guide
https://coreos.com/os/docs/latest/booting-on-vagrant.html
### Environment ###
Windows 7
Vagrant 2.1.2
Virtualbox Version 5.2.12 r122591 (Qt5.6.2)

### Expected Behavior ###
To complete installing
### Actual Behavior ###
stops due to plugin error
### Reproduction Steps ###
  1. . Download and extract https://github.com/coreos/coreos-vagrant
  2  . rename config.rb & user-data
  3 . open cmd
  4  . cd /coreos-vagrant-master dir
  5  . vagrant up
  6  . get error above

**Comment by lucab** [comment] 2018-07-26 12:45
Your log entries seems to be cut and missing the final bits. However from what I can see this is not specific to coreos-vagrant, but something broken on vagrant side.
Specifically, this looks a like a duplicate of https://github.com/hashicorp/vagrant/issues/9577.

I'm closing this ticket here, feel free to move further followups to vagrant bug tracker.

**Closed by lucab** 2018-07-26 12:45 UTC

**Comment by NameTheJew** [comment] 2018-07-26 13:54
@lucab 
You closed my issue linking to a closed issue?

**Comment by lucab** [comment] 2018-07-26 14:09
Yes. https://github.com/hashicorp/vagrant/issues/9577#issuecomment-373554445 contains an explanation of what's probably going on and how to workaround it.
