### ISSUE TITLE
Can't install package in toolbox

### ISSUE THREAD

**Issue by mieciu** [coreos/bugs#1698] opened 2016-12-06 15:15 UTC
# Issue Report #

## Bug ##

When installing a package in `toolbox`, you are suddenly escaped from the container. 

I've noticed that when switching toolbox script to use `fedora:24` image instead of `fedora:latest` ( ~`:25` release ) image problem does not exist any longer.  This might be problem of `systemd-nspawn`-way of running toolbox container.  When installing package in `fedora:25` user is warned about missing repository GPG key and prompted to add it. When this situation occurs in container ran via `systemd-nspawn`, container gets KILLed. 

```
...
Installed size: 1.2 M
Is this ok [y/N]: y
Downloading Packages:
[SKIPPED] tcpdump-4.7.4-4.fc24.x86_64.rpm: Already downloaded
warning: /var/cache/dnf/fedora-310f9d37d74ceec1/packages/tcpdump-4.7.4-4.fc24.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID fdb19c98: NOKEY
Container core-fedora-latest terminated by signal KILL.
```

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1068.8.0
VERSION_ID=1068.8.0
BUILD_ID=2016-07-18-0616
PRETTY_NAME="CoreOS 1068.8.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

AWS EC2.

### Expected Behavior ###

```
[root@69a35700f7e7 /]# dnf install tcpdump
Fedora 25 - x86_64 - Updates                                                                          30 MB/s | 9.9 MB     00:00
Fedora 25 - x86_64                                                                                    20 MB/s |  50 MB     00:02
Last metadata expiration check: 0:00:20 ago on Tue Dec  6 14:24:30 2016.
Dependencies resolved.
=====================================================================================================================================
 Package                       Arch                         Version                               Repository                    Size
=====================================================================================================================================
Installing:
 tcpdump                       x86_64                       14:4.7.4-4.fc24                       fedora                       442 k

Transaction Summary
=====================================================================================================================================
Install  1 Package

Total download size: 442 k
Installed size: 1.2 M
Is this ok [y/N]: y
Downloading Packages:
tcpdump-4.7.4-4.fc24.x86_64.rpm                                                                      1.2 MB/s | 442 kB     00:00
-------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                366 kB/s | 442 kB     00:01
warning: /var/cache/dnf/fedora-310f9d37d74ceec1/packages/tcpdump-4.7.4-4.fc24.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID fdb19c98: NOKEY
Importing GPG key 0xFDB19C98:
 Userid     : "Fedora 25 Primary (25) <fedora-25-primary@fedoraproject.org>"
 Fingerprint: C437 DCCD 558A 66A3 7D6F 4372 4089 D8F2 FDB1 9C98
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-25-x86_64
Is this ok [y/N]: y
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : tcpdump-14:4.7.4-4.fc24.x86_64                                                                                   1/1
  Verifying   : tcpdump-14:4.7.4-4.fc24.x86_64                                                                                   1/1

Installed:
  tcpdump.x86_64 14:4.7.4-4.fc24

Complete!
```

### Actual Behavior ###

```
core@ip-10-40-20-221 ~ $ toolbox
Spawning container core-fedora-latest on /var/lib/toolbox/core-fedora-latest.
Press ^] three times within 1s to kill container.
[root@ip-10-40-20-221 ~]#
[root@ip-10-40-20-221 ~]# dnf install tcpdump
Last metadata expiration check: 0:22:35 ago on Tue Dec  6 14:03:48 2016.
Dependencies resolved.
=====================================================================================================================================
 Package                       Arch                         Version                               Repository                    Size
=====================================================================================================================================
Installing:
 tcpdump                       x86_64                       14:4.7.4-4.fc24                       fedora                       442 k

Transaction Summary
=====================================================================================================================================
Install  1 Package

Total size: 442 k
Installed size: 1.2 M
Is this ok [y/N]: y
Downloading Packages:
[SKIPPED] tcpdump-4.7.4-4.fc24.x86_64.rpm: Already downloaded
warning: /var/cache/dnf/fedora-310f9d37d74ceec1/packages/tcpdump-4.7.4-4.fc24.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID fdb19c98: NOKEY
Container core-fedora-latest terminated by signal KILL.
```

### Reproduction Steps ###

  1. Run `toolbox`
  2. When in toolbox install tcpdump -> `dnf install tcpdump`

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

### Other Information ###

**Comment by oherrala** [comment] 2016-12-07 11:13
I found the same problem. For temporary fix I went back to Fedora 24:

```console
$ echo "TOOLBOX_DOCKER_TAG=24" >>$HOME/.toolboxrc
```

**Comment by lucab** [comment] 2016-12-07 11:17
This is a duplicate of https://github.com/coreos/bugs/issues/1676, which in turn points to https://github.com/coreos/bugs/issues/1216.

**Comment by mieciu** [comment] 2016-12-07 12:44
@oherrala that's my temporary patch as well 😄 

After all, I think that using `latest` image in such a vital CoreOS component is unacceptable -> `toolbox` should be frozen and bound to particular CoreOS release IMO.

**Comment by crawford** [comment] 2016-12-07 17:41
Duplicate of https://github.com/coreos/bugs/issues/1676.

**Closed by crawford** 2016-12-07 17:41 UTC
Labels: area/usability, component/toolbox, kind/bug, team/os
