### ISSUE TITLE
polkit.service fails to start with systemd 225

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#462] opened 2015-09-05 16:14 UTC
I see this failure occasionally on boot (I've booted this machine a couple hundred times). 
```
-- Logs begin at Sat 2015-09-05 00:34:19 UTC, end at Sat 2015-09-05 16:12:55 UTC. --
Sep 05 16:07:08 localhost systemd[1]: Starting Authorization Manager...
Sep 05 16:07:08 localhost polkitd[660]: Started polkitd version 0.112
Sep 05 16:07:08 localhost polkitd[660]: Loading rules from directory /etc/polkit-1/rules.d
Sep 05 16:07:08 localhost polkitd[660]: Loading rules from directory /usr/share/polkit-1/rules.d
Sep 05 16:07:08 localhost polkitd[660]: Finished loading, compiling and executing 2 rules
Sep 05 16:07:08 ip-172-31-29-31 polkitd[660]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Sep 05 16:08:38 ip-172-31-29-31 systemd[1]: polkit.service: Start operation timed out. Terminating.
Sep 05 16:08:39 ip-172-31-29-31 systemd[1]: Failed to start Authorization Manager.
Sep 05 16:08:39 ip-172-31-29-31 systemd[1]: polkit.service: Unit entered failed state.
Sep 05 16:08:39 ip-172-31-29-31 systemd[1]: polkit.service: Failed with result 'timeout'.
```

**Comment by crawford** [comment] 2015-09-22 06:23
I have not been able to reproduce this issue. I can only assume that my trees where out of sync or it was fixed with the latest set of security patches.

**Comment by h0tbird** [comment] 2015-10-01 10:06
+1 I see this problem quite often:

```
Last login: Thu Oct  1 10:04:02 2015 from 172.20.59.106
CoreOS alpha (815.0.0)
Failed Units: 1
  polkit.service
core@core-2 ~ $ systemctl status polkit.service
● polkit.service - Authorization Manager
   Loaded: loaded (/usr/lib64/systemd/system/polkit.service; static; vendor preset: disabled)
   Active: failed (Result: timeout) since Thu 2015-10-01 09:18:11 UTC; 46min ago
     Docs: man:polkit(8)
 Main PID: 809 (code=killed, signal=TERM)

Oct 01 09:16:48 core-2.cell-1.ofi.xnood.com systemd[1]: Starting Authorization Manager...
Oct 01 09:16:48 core-2.cell-1.ofi.xnood.com polkitd[809]: Started polkitd version 0.112
Oct 01 09:16:48 core-2.cell-1.ofi.xnood.com polkitd[809]: Loading rules from directory /etc/polkit-1/rules.d
Oct 01 09:16:48 core-2.cell-1.ofi.xnood.com polkitd[809]: Loading rules from directory /usr/share/polkit-1/rules.d
Oct 01 09:16:48 core-2.cell-1.ofi.xnood.com polkitd[809]: Finished loading, compiling and executing 2 rules
Oct 01 09:16:48 core-2.cell-1.ofi.xnood.com polkitd[809]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Oct 01 09:18:11 core-2.cell-1.ofi.xnood.com systemd[1]: polkit.service: Start operation timed out. Terminating.
Oct 01 09:18:11 core-2.cell-1.ofi.xnood.com systemd[1]: Failed to start Authorization Manager.
Oct 01 09:18:11 core-2.cell-1.ofi.xnood.com systemd[1]: polkit.service: Unit entered failed state.
Oct 01 09:18:11 core-2.cell-1.ofi.xnood.com systemd[1]: polkit.service: Failed with result 'timeout'.
```

**Comment by Zapadlo** [comment] 2015-10-20 15:09
+1

```
Last login: Tue Oct 20 15:03:53 2015 from 52.16.117.250
CoreOS alpha (835.1.0)
Failed Units: 1
  polkit.service
core@ip-172-24-70-78 ~ $ systemctl status polkit.service
● polkit.service - Authorization Manager
   Loaded: loaded (/usr/lib64/systemd/system/polkit.service; static; vendor preset: disabled)
   Active: failed (Result: timeout) since Tue 2015-10-20 14:50:16 UTC; 18min ago
     Docs: man:polkit(8)
 Main PID: 707 (code=killed, signal=TERM)

Oct 20 14:48:42 localhost systemd[1]: Starting Authorization Manager...
Oct 20 14:48:43 localhost polkitd[707]: Started polkitd version 0.113
Oct 20 14:48:45 localhost polkitd[707]: Loading rules from directory /etc/polkit-1/rules.d
Oct 20 14:48:45 localhost polkitd[707]: Loading rules from directory /usr/share/polkit-1/rules.d
Oct 20 14:48:45 localhost polkitd[707]: Finished loading, compiling and executing 2 rules
Oct 20 14:48:45 ip-172-24-70-78 polkitd[707]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Oct 20 14:50:16 ip-172-24-70-78.eu-west-1.compute.internal systemd[1]: polkit.service: Start operation timed out. Terminating.
Oct 20 14:50:16 ip-172-24-70-78.eu-west-1.compute.internal systemd[1]: Failed to start Authorization Manager.
Oct 20 14:50:16 ip-172-24-70-78.eu-west-1.compute.internal systemd[1]: polkit.service: Unit entered failed state.
Oct 20 14:50:16 ip-172-24-70-78.eu-west-1.compute.internal systemd[1]: polkit.service: Failed with result 'timeout'.
```

**Comment by marineam** [comment] 2015-10-20 19:23
Bah, was hopeful that the 0.113 update would improve things. :(

**Comment by crawford** [comment] 2015-11-20 07:21
I just saw this again after letting Ignition reformat my root filesystem to btrfs.

**Comment by pquerna** [comment] 2015-12-02 23:28
+1, seeing this with CoreOS stable (835.8.0):

```
systemctl status polkit
● polkit.service - Authorization Manager
   Loaded: loaded (/usr/lib64/systemd/system/polkit.service; static; vendor preset: disabled)
   Active: failed (Result: timeout) since Wed 2015-12-02 18:49:16 UTC; 4h 38min ago
     Docs: man:polkit(8)
 Main PID: 735 (code=killed, signal=TERM)

Dec 02 18:47:44 localhost systemd[1]: Starting Authorization Manager...
Dec 02 18:47:45 localhost polkitd[735]: Started polkitd version 0.113
Dec 02 18:47:45 ip-10-0-225-157 polkitd[735]: Loading rules from directory /etc/polkit-1/rules.d
Dec 02 18:47:46 ip-10-0-225-157 polkitd[735]: Loading rules from directory /usr/share/polkit-1/rules.d
Dec 02 18:47:46 ip-10-0-225-157 polkitd[735]: Finished loading, compiling and executing 2 rules
Dec 02 18:47:46 ip-10-0-225-157 polkitd[735]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Dec 02 18:49:16 ip-10-0-225-157.us-west-2.compute.internal systemd[1]: polkit.service: Start operation timed out. Terminating.
Dec 02 18:49:16 ip-10-0-225-157.us-west-2.compute.internal systemd[1]: Failed to start Authorization Manager.
Dec 02 18:49:16 ip-10-0-225-157.us-west-2.compute.internal systemd[1]: polkit.service: Unit entered failed state.
Dec 02 18:49:16 ip-10-0-225-157.us-west-2.compute.internal systemd[1]: polkit.service: Failed with result 'timeout'.
```

**Comment by mischief** [comment] 2015-12-03 01:36
@pquerna presumably, you only see this very rarely?

**Comment by tjanczuk** [comment] 2015-12-03 22:31
Seeing this quite consistently when deploying CoreOS "stable" (835.8.0) 3 VM clusters to AWS us-east-1, eu-central-1, and eu-west-1. Interestingly I don't see it when deploying same bits to us-west-1.

**Comment by mischief** [comment] 2015-12-03 23:20
@tjanczuk can you share a coreos-cloudinit/ignition config that causes this for you? not having a lot of luck reproducing this consistently.

**Comment by tjanczuk** [comment] 2015-12-03 23:25
@mischief This is part of cloud formation template, the relevant piece is here I believe: https://gist.github.com/tjanczuk/932ba0747e051a6b6cd4

**Comment by pquerna** [comment] 2015-12-04 19:02
I just booted 8 instances of 835.8.0 (stable) in AWS EC2 us-west-2, 3 of them had polkit failed.  cloud-init config was very simple:

```yaml
#cloud-config

coreos:
  update:
    reboot-strategy: reboot
```

**Comment by crawford** [comment] 2015-12-04 19:28
```
CoreOS stable (835.8.0)
Failed Units: 1
  polkit.service
core@ip-172-31-44-240 ~ $ systemctl is-active polkit.service
failed
core@ip-172-31-44-240 ~ $ echo $?
3
```

**Comment by crawford** [comment] 2015-12-04 19:29
```
$ busctl 
NAME                              PID PROCESS         USER             CONNECTION    UNIT                      SESSION    DESCRIPTION        
:1.0                                1 systemd         root             :1.0          -                         -          -                  
:1.1                              634 systemd-logind  root             :1.1          systemd-logind.service    -          -                  
:1.13                             752 locksmithd      root             :1.13         locksmithd.service        -          -                  
:1.14                             752 locksmithd      root             :1.14         locksmithd.service        -          -                  
:1.16                             926 busctl          core             :1.16         sshd@2-172.31.44.240:2... -          -                  
:1.2                              639 update_engine   root             :1.2          update-engine.service     -          -                  
:1.3                              670 systemd-network systemd-network  :1.3          systemd-networkd.service  -          -                  
:1.5                              691 systemd-resolve systemd-resolve  :1.5          systemd-resolved.service  -          -                  
com.coreos.update1                639 update_engine   root             :1.2          update-engine.service     -          -                  
org.freedesktop.DBus                - -               -                -             -                         -          -                  
org.freedesktop.PolicyKit1          - -               -                (activatable) -                         -         
org.freedesktop.hostname1           - -               -                (activatable) -                         -         
org.freedesktop.import1             - -               -                (activatable) -                         -         
org.freedesktop.locale1             - -               -                (activatable) -                         -         
org.freedesktop.login1            634 systemd-logind  root             :1.1          systemd-logind.service    -          -                  
org.freedesktop.machine1            - -               -                (activatable) -                         -         
org.freedesktop.network1          670 systemd-network systemd-network  :1.3          systemd-networkd.service  -          -                  
org.freedesktop.resolve1          691 systemd-resolve systemd-resolve  :1.5          systemd-resolved.service  -          -                  
org.freedesktop.systemd1            1 systemd         root             :1.0          -                         -          -                  
org.freedesktop.timedate1           - -               -                (activatable) -                         -
```

**Comment by crawford** [comment] 2015-12-04 20:12
Here is a log of a failure: https://gist.githubusercontent.com/crawford/74f69907914cece20031/raw/fab0f80bd7d4bd7efcc52bdb4798c48c4376332a/journal.txt

**Comment by FirefighterBlu3** [comment] 2015-12-04 21:56
this is a common problem with gentoo, arch, and more -- with what i've
noted as appears to be a delay in resolving users or groups. i've spent
months trying to track down this issue. my nss setup does AD lookups to
resolve user info. do you by chance have anything similar?

i can boot successfully about 90% of the time and polkit and login
services start properly but once in a while login service fails and i've
found out that polkit is failing. flushing nscd caches and rebooting
solves it and it appears to be a very close race condition with the lookups.

**Comment by mischief** [comment] 2015-12-04 22:01
@FirefighterBlu3 we use nss-altfiles to merge /etc/ and /usr databases. no AD.

**Comment by crawford** [comment] 2015-12-04 23:45
In our case, it appears to be a race between a daemon-reload and bus messages. It looks like there is a brief period during the reload that the bus matchers are uninstalled and that's when a message could sneak in and get dropped on the floor. We still have to verify this theory though.

**Comment by crawford** [comment] 2015-12-05 01:18
I am pretty confident the above theory is the root cause. There is an 800ms gap between the RemoveMatch and AddMatch on my system. You could drive a truck through that.

**Comment by vcaputo** [comment] 2015-12-05 01:28
Good work digging into this, is it just a matter of reordering how things occur in the reload or is this more tricky to fix than that?

**Comment by crawford** [comment] 2015-12-05 01:31
I haven't looked yet, but I suspect systemd isn't querying the state after setting up the matches. The result is that any state changes that occur during that 800ms are lost. I _think_ it is just a matter of querying the state during the reload.

**Comment by mischief** [comment] 2015-12-10 01:49
this problem was introduced in systemd/systemd@bbc2908635ca3ded9162504683fa126809f0ec14 systemd/systemd@cf9fd50884bcd2fd3a54e0e0c0c83a7b3326ca9b. with these two reverted i can't reproduce with my test:

```sh
while sudo systemctl daemon-reload; do sleep 0.01; done &
while sudo systemctl is-active polkit.service; do sudo systemctl restart polkit.service; sleep 1; done &
```

and in another terminal:

```sh
watch systemctl status -l polkit
```

with the daemon-reload and restarting of polkit going, the chance of the race condition goes way up, and almost immediately systemctl status reports polkit is stuck in activating. the process is actually running, systemd simply missed the notification of the bus owner changing.

systemd probably needs to call `org.freedesktop.DBus.NameHasOwner` after registering the matcher for the `org.freedesktop.DBus.NameOwnerChanged` signal.

**Comment by vcaputo** [comment] 2015-12-10 01:57
Good news!  Tractable.

**Comment by danielwhatmuff** [comment] 2015-12-14 09:35
Also seeing this every now and again - three vms running 835.8.0 with the same cloud-config and one will just randomly spit out:

Dec 09 09:28:30 ip-10-244-72-62.eu-west-1.compute.internal systemd[1]: Starting Authorization Manager...
Dec 09 09:28:31 ip-10-244-72-62.eu-west-1.compute.internal polkitd[704]: Started polkitd version 0.113
Dec 09 09:28:31 ip-10-244-72-62.eu-west-1.compute.internal polkitd[704]: Loading rules from directory /etc/polkit-1/rules.d
Dec 09 09:28:31 ip-10-244-72-62.eu-west-1.compute.internal polkitd[704]: Loading rules from directory /usr/share/polkit-1/rules.d
Dec 09 09:28:31 ip-10-244-72-62.eu-west-1.compute.internal polkitd[704]: Finished loading, compiling and executing 2 rules
Dec 09 09:28:31 ip-10-244-72-62.eu-west-1.compute.internal polkitd[704]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Dec 09 09:30:01 ip-10-244-72-62.eu-west-1.compute.internal systemd[1]: polkit.service: Start operation timed out. Terminating.
Dec 09 09:30:01 ip-10-244-72-62.eu-west-1.compute.internal systemd[1]: Failed to start Authorization Manager.
Dec 09 09:30:01 ip-10-244-72-62.eu-west-1.compute.internal systemd[1]: polkit.service: Unit entered failed state.
Dec 09 09:30:01 ip-10-244-72-62.eu-west-1.compute.internal systemd[1]: polkit.service: Failed with result 'timeout'.

**Comment by mischief** [comment] 2015-12-17 22:59
@zonque is working on this upstream in systemd/systemd#2136.

**Comment by jgehrcke** [comment] 2015-12-23 12:20
Thanks to @zonque and @mischief this is fixed by https://github.com/systemd/systemd/pull/2216 (not yet merged).

@mischief from your experience, how long do you think this will take to land in a 835.x release?

**Comment by mischief** [comment] 2015-12-23 20:57
@jgehrcke are you using Type=dbus..? if not, this should not be very problematic.

**Comment by jgehrcke** [comment] 2015-12-26 15:33
@mischief: None of our custom services explicitly set Type=dbus. We are also using 835.8.0 on AWS, and daemon-reload usually fails referring to PolicyKit error state.
```
# systemctl daemon-reload
Error getting authority: Error initializing authority: Error calling StartServiceByName for org.freedesktop.PolicyKit1: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Activation of org.freedesktop.PolicyKit1 timed out (g-dbus-error-quark, 20)
Failed to execute operation: Connection timed out
```

**Comment by vnadgir-ef** [comment] 2016-02-10 14:36
Had the same issue on 835.11.0.

However, an update to 835.12.0 has solved the issue for now.

**Comment by pwaller** [comment] 2016-02-10 15:36
I still see the failure on 835.12.0.

**Comment by zonque** [comment] 2016-02-10 15:44
Which systemd version is 835.12.0 based on, and does it contain https://github.com/zonque/systemd/commit/8936a5e34dbfa9274348f3fef99f7c9f9327ddf9 ?

**Comment by vnadgir-ef** [comment] 2016-02-10 20:57
@zonque Looks like the version of systemd didnt change between 835.11.0 and 835.12.0.
`https://github.com/coreos/manifest/blob/v835.11.0/build-835.xml#L47`
`https://github.com/coreos/manifest/blob/v835.12.0/build-835.xml#L47`

**Comment by rlister** [comment] 2016-02-13 05:04
Seeing this on at least 50% new installs of 835.12.0, so problem still exists.

**Comment by mischief** [comment] 2016-02-13 05:13
@vnadgir-ef unfortunately manifest is not always the exact hash of the installed copy.

right now 835.12.0, 899.6.0, and 955.0.0 all contain systemd-225 with some patches. we'll be looking at systemd-229 soon.

**Comment by mkocikowski** [comment] 2016-02-23 18:34
As of today, seeing the same issue with `835.13.0` running on aws `us-west-2` using `ami-4f00e32f`

**Comment by codeshrew** [comment] 2016-03-08 21:22
Seeing this same issue with `835.13.0` on AWS `us-west-2` using `ami-7c01e21c`

**Comment by nickmoorman** [comment] 2016-03-10 20:33
FWIW, I've been seeing this pretty frequently as well on `899.9.0` (and one machine that mysteriously updated to `899.10.0` when none of the others in the cluster did...).  Running `ami-c1fac5ab` for the Beta release channel in `us-east-1`.

    $ for i in {35..37} {100..103}; do ssh core@10.24.195.$i "cat /etc/os-release | grep PRETTY_NAME; systemctl is-active polkit.service"; done
    PRETTY_NAME="CoreOS 899.10.0"
    failed
    PRETTY_NAME="CoreOS 899.9.0"
    active
    PRETTY_NAME="CoreOS 899.9.0"
    failed
    PRETTY_NAME="CoreOS 899.9.0"
    failed
    PRETTY_NAME="CoreOS 899.9.0"
    active
    PRETTY_NAME="CoreOS 899.9.0"
    active
    PRETTY_NAME="CoreOS 899.9.0"
    active

**Comment by mischief** [comment] 2016-03-23 23:40
fixed by coreos/coreos-overlay#1833

**Closed by mischief** 2016-03-23 23:40 UTC
Labels: component/other, component/systemd, kind/bug, priority/P0, team/os

**Comment by LudicrousSpeed** [comment] 2016-04-07 20:43
CoreOS stable (835.13.0)
Failed Units: 1
  polkit.service

Seeing this on AWS also.

**Comment by githubuseracct** [comment] 2016-04-11 15:48
@mischief Is the fix going to be backported into 225 or will we have to wait for 229 to hit stable?

**Comment by crawford** [comment] 2016-04-11 18:00
This will not be backported. The error message can be safely ignored. `polkit.service` will restart when it is needed.

**Comment by jalaziz** [comment] 2016-04-11 20:34
@crawford, in our experience it can't be safely ignored. When conducting maintenance on servers, various services fail to restart due to the polkit timeout, while others restart fine. The error also means that automated tooling breaks, since a `systemctl` operation can fail, but the underlying operation may or may not have completed.

**Comment by opsline-ryan** [comment] 2016-05-09 21:05
Greetings,
We are seeing this in 1010.3.0.
ami: ami-b1af4cdc

```
May 09 20:13:20 localhost dbus[710]: [system] Activating via systemd: service name='org.freedesktop.PolicyKit1' unit='polkit.service'
May 09 20:13:22 localhost polkitd[762]: Started polkitd version 0.113
May 09 20:13:23 localhost polkitd[762]: Loading rules from directory /etc/polkit-1/rules.d
May 09 20:13:23 localhost polkitd[762]: Loading rules from directory /usr/share/polkit-1/rules.d
May 09 20:13:23 localhost polkitd[762]: Finished loading, compiling and executing 3 rules
May 09 20:13:23 localhost polkitd[762]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
May 09 20:14:54 ip-172-31-14-48.ec2.internal systemd[1]: polkit.service: Start operation timed out. Terminating.
May 09 20:14:54 ip-172-31-14-48.ec2.internal systemd[1]: polkit.service: Unit entered failed state.
May 09 20:14:54 ip-172-31-14-48.ec2.internal systemd[1]: polkit.service: Failed with result 'timeout'.
```

**Comment by timrsmith** [comment] 2016-05-12 18:05
Seeing this in CoreOS stable (899.17.0) - ami-8d6485e0

```
systemctl --failed
  UNIT           LOAD   ACTIVE SUB    DESCRIPTION
● polkit.service loaded failed failed Authorization Manager
```

```
systemctl status polkit
● polkit.service - Authorization Manager
   Loaded: loaded (/usr/lib64/systemd/system/polkit.service; static; vendor preset: disabled)
   Active: failed (Result: timeout) since Thu 2016-05-12 16:13:56 UTC; 1h 43min ago
     Docs: man:polkit(8)
 Main PID: 677 (code=killed, signal=TERM)

May 12 16:12:25 localhost systemd[1]: Starting Authorization Manager...
May 12 16:12:25 localhost polkitd[677]: Started polkitd version 0.113
May 12 16:12:25 ip-10-233-137-250 polkitd[677]: Loading rules from directory /etc/polkit-1/rules.d
May 12 16:12:25 ip-10-233-137-250.ec2.internal polkitd[677]: Loading rules from directory /usr/share/polkit-1/rules.d
May 12 16:12:25 ip-10-233-137-250.ec2.internal polkitd[677]: Finished loading, compiling and executing 2 rules
May 12 16:12:25 ip-10-233-137-250.ec2.internal polkitd[677]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
May 12 16:13:56 ip-10-233-137-250.ec2.internal systemd[1]: polkit.service: Start operation timed out. Terminating.
May 12 16:13:56 ip-10-233-137-250.ec2.internal systemd[1]: Failed to start Authorization Manager.
May 12 16:13:56 ip-10-233-137-250.ec2.internal systemd[1]: polkit.service: Unit entered failed state.
May 12 16:13:56 ip-10-233-137-250.ec2.internal systemd[1]: polkit.service: Failed with result 'timeout'.
```

**Comment by tilgovi** [comment] 2016-05-12 18:12
The cause of this was diagnosed and the fix committed. According to the comments here and on the related issues, it should be fixed with systemd 229. Stable and Beta are still using 225. Therefore, reports that it's happening on these are not helpful. That is to be expected.

**Comment by iamthemuffinman** [comment] 2016-06-02 21:08
Why isn't CoreOS stable on systemd 229? All of the outstanding issues blocking it seem to have been closed.

**Comment by crawford** [comment] 2016-06-02 21:15
@iamthemuffinman our issue tracker isn't necessarily an exhaustive list of issues. We need to give it time in the Alpha and Beta channels to find any undiscovered issues.

**Comment by iamthemuffinman** [comment] 2016-06-02 21:34
@crawford Okay. I was just curious. systemd 229 has only been out for a few months, but I think everyone was hoping for a little faster turn around considering the issues with 225. Thanks!

**Comment by ohjames** [comment] 2016-06-07 12:09
I just deployed three brand new CoreOS clusters to AWS from the stable channel. In my third cluster, two of three machines have manifested this bug immediately.

Not sure if they are useable.

**Comment by obeattie** [comment] 2016-06-07 12:44
My experience running about 100 AWS instances is that this happens very frequently, but it does not impact the machines' functionality.

**Comment by chynphh** [comment] 2019-06-18 18:02
> [root@localhost polkit-1]# systemctl status polkit
● polkit.service - Authorization Manager
   Loaded: loaded (/usr/lib/systemd/system/polkit.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since 三 2019-06-19 01:55:00 CST; 2min 59s ago
     Docs: man:polkit(8)
 Main PID: 8796 (code=exited, status=127)
6月 19 01:55:00 localhost.localdomain systemd[1]: Starting Authorization Manager...
6月 19 01:55:00 localhost.localdomain polkitd[8796]: /usr/lib/polkit-1/polkitd: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
6月 19 01:55:00 localhost.localdomain systemd[1]: polkit.service: main process exited, code=exited, status=127/n/a
6月 19 01:55:00 localhost.localdomain systemd[1]: Failed to start Authorization Manager.
6月 19 01:55:00 localhost.localdomain systemd[1]: Unit polkit.service entered failed state.
6月 19 01:55:00 localhost.localdomain systemd[1]: polkit.service failed.

But I have libstdc++.so.6 in lib. What can I do?

**Comment by bgilbert** [comment] 2019-06-19 14:31
@chynphh Are you seeing this on CoreOS Container Linux?

**Comment by chynphh** [comment] 2019-06-19 17:18
@bgilbert sorry, CentOS.
