### ISSUE TITLE
"Failed to unescape command line" After updating to SystemD 220

### ISSUE THREAD

**Issue by munkyboy** [coreos/bugs#387] opened 2015-06-12 20:47 UTC
regression in SystemD which has been fixed. not sure if it's been released yet.
https://github.com/systemd/systemd/pull/51

**Comment by tj-corrigan** [comment] 2015-06-30 22:01
+1 would be nice to see this make it into a release as the current builds break our entire environment

**Comment by grahamjenson** [comment] 2015-07-08 07:21
+1 same here, is there a work around?

**Comment by grahamjenson** [comment] 2015-07-08 07:56
This broke in the stable coreos release for my system. The problem I found was that in the `ExecStart` script I had the code `sed "s/^\/key\///g"`` which escaped the the forward slashes in the sed regex. The work around I found was to change the script to do the same thing just without escaping anything.

**Comment by crawford** [comment] 2015-07-08 16:12
@grahamjenson this patch only fixes the parsing of octal numbers, so it seems as though your issue is unrelated. Can you open a separate bug detailing your issue?

**Comment by crawford** [comment] 2015-07-08 23:02
Fixed by https://github.com/coreos/systemd/pull/14.

**Closed by crawford** 2015-07-08 23:02 UTC
Labels: regression, systemd

**Comment by grahamjenson** [comment] 2015-07-09 16:29
@crawford Cheers :)

**Comment by scole-scea** [comment] 2015-07-09 17:55
I dug into the cause for this a bit more. The underlying issue is that improperly escaped command lines were passed through unchanged prior to 717.1.0, and now generate errors.

Example of something that causes a problem:
```
ExecStart=/bin/bash -c "echo \"I see dollars: \$\""
```
Prior to 717, systemd transforms `\"` to `"`, and leaves `\$` alone, so that bash sees its last argument as `echo "I see dollars: \$"` (I.e.: that's the buffer content of `argv`.)
In 717.1.0, that `\$` is invalid, and so we throw the error.

Fixing this is not so much a workaround, but rather fixing our systemd files so that they're properly escaped. In other words, that example becomes:
```
ExecStart=/bin/bash -c "echo \"I see dollars:\\$\""
```
So that systemd transforms the `\\` to simply `\`, and then bash gets its `\$` like we want.

Making that change to all of our affected unit files has fixed the issue for us.
