### ISSUE TITLE
CoreOS 835.9.0: possible race between resolv.conf and Docker

### ISSUE THREAD

**Issue by jumanjiman** [coreos/bugs#1033] opened 2015-12-12 18:12 UTC
This may be related to, or a dupe of, https://github.com/coreos/bugs/issues/1029

We have not noticed this before. There appears to be a race at boot-time.
The docker version is now 1.8.3 on this update.

### Scenario

1. reboot the host (in this case by coreupdate)

1. `docker.service` starts

1. a container starts. The app in this container depends on `/etc/resolv.conf` having name servers.

   The app in the container periodically forks a child process, and the child throws tracebacks related to failure in `getaddrinfo`. However, the main pid stays up, so docker and systemd think everything is good.

1. `systemd-resolved` starts and populates `/run/systemd/resolve/resolv.conf`. (`/etc/resolv.conf` is symlink to the systemd `resolv.conf`)

1. we observe the failures in the logs from the troublesome container, restart it, and everything is good.

### more info

If we delay the start of the troublesome container until sometime _after_ systemd-resolved runs, then we do not observe the TBs in the app.

According to https://github.com/docker/docker/blob/master/docs/userguide/networking/default_network/configure-dns.md 
docker is supposed to maintain `/etc/resolv.conf` "up to date across all containers when the host machine receives new configuration over DHCP later". 

:point_right:  Is it possible that this doesn't work when `/etc/resolv.conf` is a symlink to a file on a different filesystem (`/run` is a tmpfs)?

:warning: This host is bare-metal. We have not observed this (yet) in AWS, even on coreos alpha.

:warning: This host uses btrfs as root fs.

```
core@ic-dock01 ~ $ egrep '(/run|/dev/sda9)' /proc/mounts 
tmpfs /run tmpfs rw,seclabel,nosuid,nodev,mode=755 0 0
/dev/sda9 / btrfs rw,seclabel,relatime,space_cache,subvolid=257,subvol=/root 0 0
```

### possible workaround

We have ~~two~~ numerous containers so far that exhibit this behavior across multiple bare-metal hosts. 
Conveniently for this issue, ~~they are both~~ two of them are open-source: 

* https://github.com/jumanjihouse/puppet-on-coreos 
* https://github.com/jumanjihouse/docker-duoauthproxy

I'm considering to add a drop-in at either `/etc/systemd/system/puppet.service.d/dns.conf` or possibly `/etc/systemd/system/docker.service.d/dns.conf`:

```
[Unit]
Wants=systemd-resolved.service
After=systemd-resolved.service
```

**Comment by jumanjiman** [comment] 2015-12-12 20:36
this seems to be pretty easy to reproduce on bare metal.

1. configure systemd unit file to start *any* container with a shell.

1. reboot host.

1. run `docker exec -it <container_name> cat /etc/resolv.conf` and observe that it has search path but not name servers.

1. create `/etc/systemd/system/docker.service.d/dns.conf` as shown in OP above, then
reboot the host again.

1. after reboot, run `docker exec -it <container_name> cat /etc/resolv.conf` and observe that it has the name servers this time.

**Comment by jumanjiman** [comment] 2016-01-25 20:58
informational update. 

this trick...

```
# /etc/systemd/system/docker.service.d/dns.conf
[Unit]
# Delay startup until after systemd-resolved.
# "Wants" is a weaker form of "Requires" to
# avoid bouncing this service if systemd-resolved bounces.
Wants=systemd-resolved.service
After=systemd-resolved.service
```

...has helped significantly but is not a cure.
we still occasionally (circa 10%) see hosts that don't populate `/etc/resolv.conf` until after docker starts.

**Comment by jumanjiman** [comment] 2016-02-04 04:12
still an issue on 835.12.0

**Comment by mischief** [comment] 2016-03-15 21:19
ok, i can reproduce this here on coreos stable 835.13.0. i suspect this will be fixed by docker 1.9.1.

**Comment by mischief** [comment] 2016-03-15 21:26
looks like in 1.9.1, docker inserts:

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

if there's no ips from host /etc/resolv.conf.

**Comment by mischief** [comment] 2016-03-15 21:30
the docker daemon says:

```
Mar 15 21:24:12 localhost dockerd[1206]: time="2016-03-15T21:24:12.728357535Z" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers : [nameserver 8.8.8.8 nameserver 8.8.4.4]"
```

so, this is still a problem in coreos 899.10.0/docker 1.9.1

@jumanjiman, could you just set the docker daemon flag `--dns=...` for now?

**Comment by jumanjiman** [comment] 2016-03-15 21:49
> could you just set the docker daemon flag --dns=... for now?

yes i believe that'll work.
i should be able to export `DOCKER_OPTS` via a drop-in.

thanks for looking into this!

____

```
core@ic-kix03 ~ $ systemctl cat docker
# /usr/lib64/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=docker.socket early-docker.target network.target
Requires=docker.socket early-docker.target

[Service]
EnvironmentFile=-/run/flannel_docker_opts.env
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
ExecStart=/usr/lib/coreos/dockerd daemon --host=fd:// $DOCKER_OPTS $DOCKER_OPT_BIP $DOCKER_OPT_MTU $DOCKER_OPT_IPMASQ

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/docker.service.d/dns.conf
[Unit]
# Delay startup until after systemd-resolved.
# "Wants" is a weaker form of "Requires" to
# avoid bouncing this service if systemd-resolved bounces.
Wants=systemd-resolved.service
After=systemd-resolved.service
# /etc/systemd/system/docker.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://proxy2.<snip>.com:3128"
```

**Comment by mischief** [comment] 2016-03-15 21:55
the alternative solution would be to delay docker.service until dns actually works. here's an example -

`wait-for-dns.service`:
```
[Service]
Type=oneshot
RemainAfterExit=true
ExecStart=/bin/sh -c 'while ! getent ahosts index.docker.io >dev/null; do sleep 1; done'
[Install]
WantedBy=network-online.target
```

docker.service drop-in, `10-wait-for-dns.conf`:
```
[Unit]
After=network-online.target
Wants=network-online.target
```

if this solution works for you, i'll close the issue.

**Comment by mischief** [comment] 2016-03-15 21:56
also fyi - delaying docker until systemd-resolved is running won't guarantee that dns works, because simply running systemd-resolved is not enough. resolv.conf is only populated when systemd-networkd sends a dbus message to systemd-resolved after getting dns nameserver info via dhcp.

**Comment by jumanjiman** [comment] 2016-03-15 22:00
> delaying docker until systemd-resolved is running won't guarantee that dns works

yeah, it's racy depending on dhcp.
docker *used* to update container dns when `resolv.conf` changes, but this appears to not work any more.

**Closed** 2016-03-15 23:18 UTC
Labels: area/usability, component/docker, kind/regression, priority/P0, team/os

**Comment by mischief** [comment] 2016-03-26 18:21
note that `wait-for-dns.service` needs to be 'enabled' to be part of `network-online.target`, but i'm not sure how nicely that's going to play with coreos-cloudinit, and enabling won't work on first boot with coreos-cloudinit.

should be fine with ignition.

**Comment by jumanjiman** [comment] 2016-03-26 18:34
> note that wait-for-dns.service needs to be 'enabled' to be part of network-online.target

yup



> i'm not sure how nicely that's going to play with coreos-cloudinit, and enabling won't work on first boot with coreos-cloudinit.

ack.

we only use cloud-config to bootstrap our hosts to config mgmt.



> should be fine with ignition

cool. we haven't started using ignition yet, but i've been watching the repo and all the progress happening there. :+1:

**Comment by brmakana** [comment] 2016-06-28 22:00
Hello,

I'm running into this issue a lot still, with coreOS stable 1010.5.0. It can be reproduced by just doing docker run -it --rm ubuntu cat /etc/resolv.conf over and over. There doesn't seem to be any pattern either (i.e. it only happens on the first time, etc).
