### ISSUE TITLE
Cannot join cluster when behind discovery-proxy

### ISSUE THREAD

**Issue by mthibaut** [coreos/bugs#442] opened 2015-08-19 21:43 UTC
It's possible to start a cluster behind a discovery-proxy, but it's not possible to join one. To reproduce:

1) Create the following config-drive

user_data:

#cloud-config

coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    discovery: https://discovery.etcd.io/0000000000000000000000000000000
    discovery-proxy: http://proxy.example.com:8080/
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://$public_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start

ssh_authorized_keys:
  - ssh-dss .......

2) Boot node 1:

Aug 19 20:45:28 localhost systemd[1]: Started etcd2.
Aug 19 20:45:28 localhost systemd[1]: Starting etcd2...
Aug 19 20:45:30 localhost etcd2[641]: 2015/08/19 20:45:30 etcd: listening for peers on http://:2380
Aug 19 20:45:30 localhost etcd2[641]: 2015/08/19 20:45:30 etcd: listening for peers on http://:7001
Aug 19 20:45:30 localhost etcd2[641]: 2015/08/19 20:45:30 etcd: listening for client requests on http://0.0.0.0:2379
Aug 19 20:45:30 localhost etcd2[641]: 2015/08/19 20:45:30 etcd: listening for client requests on http://0.0.0.0:4001
Aug 19 20:45:30 localhost etcd2[641]: 2015/08/19 20:45:30 etcdserver: datadir is valid for the 2.0.1 format
Aug 19 20:45:30 localhost etcd2[641]: 2015/08/19 20:45:30 discovery: using proxy "http://proxy.example.com:8080/"
Aug 19 20:45:31 localhost etcd2[641]: 2015/08/19 20:45:31 discovery: found self 3fc172cbb861331b in the cluster
Aug 19 20:45:31 localhost etcd2[641]: 2015/08/19 20:45:31 discovery: found 1 peer(s), waiting for 2 more

3) Boot Node 2:

-- Logs begin at Wed 2015-08-19 20:48:19 UTC, end at Wed 2015-08-19 20:49:07 UTC. --
Aug 19 20:48:34 localhost systemd[1]: Started etcd2.
Aug 19 20:48:34 localhost systemd[1]: Starting etcd2...
Aug 19 20:48:35 localhost etcd2[623]: 2015/08/19 20:48:35 etcd: listening for peers on http://:2380
Aug 19 20:48:35 localhost etcd2[623]: 2015/08/19 20:48:35 etcd: listening for peers on http://:7001
Aug 19 20:48:35 localhost etcd2[623]: 2015/08/19 20:48:35 etcd: listening for client requests on http://0.0.0.0:2379
Aug 19 20:48:35 localhost etcd2[623]: 2015/08/19 20:48:35 etcd: listening for client requests on http://0.0.0.0:4001
Aug 19 20:48:35 localhost etcd2[623]: 2015/08/19 20:48:35 etcdserver: datadir is valid for the 2.0.1 format
Aug 19 20:48:35 localhost etcd2[623]: 2015/08/19 20:48:35 discovery: using proxy "http://irc-mgmt.cisco.com:8080/"
Aug 19 20:48:36 localhost etcd2[623]: 2015/08/19 20:48:36 etcd: stopping listening for client requests on http://0.0.0.0:4001
Aug 19 20:48:36 localhost etcd2[623]: 2015/08/19 20:48:36 etcd: stopping listening for client requests on http://0.0.0.0:2379
Aug 19 20:48:36 localhost etcd2[623]: 2015/08/19 20:48:36 etcd: stopping listening for peers on http://:7001
Aug 19 20:48:36 localhost etcd2[623]: 2015/08/19 20:48:36 etcd: stopping listening for peers on http://:2380
Aug 19 20:48:36 localhost etcd2[623]: 2015/08/19 20:48:36 member "a1a43f9d821f4c65be5b95d28fed007e" has previously registered with discovery service token (https://discovery.etcd.io/0000000000000000000000000000000).
Aug 19 20:48:36 localhost etcd2[623]: 2015/08/19 20:48:36 But etcd could not find vaild cluster configuration in the given data dir (/var/lib/etcd2).
Aug 19 20:48:36 localhost etcd2[623]: 2015/08/19 20:48:36 Please check the given data dir path if the previous bootstrap succeeded
Aug 19 20:48:36 localhost etcd2[623]: 2015/08/19 20:48:36 or use a new discovery token if the previous bootstrap failed.
~

**Comment by yichengq** [comment] 2015-09-17 02:05
1. There is no join concept in static bootstrap. See https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#static for more details.

2. I think proxy is not the root cause considering node1 could wait on discovery service. In most probability, it is caused by this issue: https://github.com/coreos/etcd/issues/3012 and it has been fixed in 2.1.3 and 2.2

Could you check it again?

**Comment by yichengq** [comment] 2015-09-21 22:07
Have you given it a try?

**Comment by yichengq** [comment] 2015-10-09 00:26
Friendly ping.

**Comment by mthibaut** [comment] 2015-10-10 11:06
Sorry haven't seen this till now. I'll give it a try.

**Comment by mischief** [comment] 2015-12-14 22:55
@mthibaut please reopen the issue if you continue to have this problem.

**Closed by mischief** 2015-12-14 22:55 UTC
Labels: component/etcd, kind/bug
