### ISSUE TITLE
Docker daemon becomes unusable 

### ISSUE THREAD

**Issue by someword** [coreos/bugs#1836] opened 2017-02-28 23:01 UTC
# Issue Report #

## Bug ##

The docker daemon get's wedged and the only recourse is to terminate the node.    A kill -9 on the docker daemon doesn't do anything.

### Container Linux Version ###

We have seen the same problem with 1235.9.0 as well

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.12.0
VERSION_ID=1235.12.0
BUILD_ID=2017-02-23-0222
PRETTY_NAME="Container Linux by CoreOS 1235.12.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

```

### Environment ###

We are running in AWS using upstream AMI's.  For example in us-east-1 the ami is ami-1ad0000c
We use the CoreOS provided docker binary.
We run CoreOS as the foundation for our Kubernetes infrastructure which is currently 1.4.7

### Expected Behavior ###

When i run 'docker info' or 'docker ps' or 'docker images' I expect the command to return in typically a second.

### Actual Behavior ###

Running any docker commands just hangs and never returns.   This makes the node unusable as kubernetes cannot get or update the container state.

### Reproduction Steps ###

 Unclear on how to reproduce.     We get this problem between 1 - 3 times a day across a kubernetes cluster node population of about 50.    We have not made any correlation between why 1 node experiences this and not another.

### Other Information ###
I cannot get the docker info from a 'hung' node but this is the docker info output from a node which is the same as the hung one.

```
Containers: 63
 Running: 58
 Paused: 0
 Stopped: 5
Images: 31
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.7.3-coreos-r3
Operating System: Container Linux by CoreOS 1235.12.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 36
Total Memory: 58.97 GiB
Name: ip-10-20-3-222.ec2.internal
ID: NE6X:OPDV:I5XR:MKJL:KPMK:ROIL:KBSZ:OWZL:WGBM:UR7Y:4BWW:XNQM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

Here are the command line flags of the running dockerd daemon

```
root      53086      1  0 20:25 ?        00:00:02 dockerd --host=fd:// --containerd=/var/run/docker/libcontainerd/docker-containerd.sock --iptables=false --ip-masq=false --storage-driver=overlay --log-driver=journald --live-restore --bip=172.20.30.1/24 --mtu=8951 --ip-masq=false --selinux-enabled

```

Filesystem info

```
core@ip-10-20-4-11 ~ $ df -hT
Filesystem      Type      Size  Used Avail Use% Mounted on
devtmpfs        devtmpfs   30G     0   30G   0% /dev
tmpfs           tmpfs      30G     0   30G   0% /dev/shm
tmpfs           tmpfs      30G  4.8M   30G   1% /run
tmpfs           tmpfs      30G     0   30G   0% /sys/fs/cgroup
/dev/xvda9      ext4       95G   32G   60G  35% /
/dev/mapper/usr ext4      985M  625M  309M  67% /usr
tmpfs           tmpfs      30G     0   30G   0% /media
/dev/xvda1      vfat      128M   39M   90M  31% /boot
tmpfs           tmpfs      30G   14M   30G   1% /tmp
/dev/xvda6      ext4      108M   64K   99M   1% /usr/share/oem
overlay         overlay    95G   32G   60G  35% /var/lib/rkt/pods/run/c4337999-d00e-4bdd-9713-0f7415ede39c/stage1/rootfs
overlay         overlay    95G   32G   60G  35% /var/lib/rkt/pods/exited-garbage/16ce0cd4-4fd2-40b9-b66e-0a1cc7fe8a76/stage1/rootfs
tmpfs           tmpfs     5.9G     0  5.9G   0% /run/user/500
```

Docker version output

```
core@ip-10-20-3-222 ~ $ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Thu Feb 23 02:17:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Thu Feb 23 02:17:18 2017
 OS/Arch:      linux/amd64
```

Here is the stacktrace from containerd https://gist.github.com/jswoods/d69ce3e329381e26f76a334c4e29296a

Here is the stacktrace from dockerd
https://gist.github.com/jswoods/ec918ea44663e86189db60e0557ec7b7

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

**Comment by crawford** [comment] 2017-03-01 01:10
This sounds like a duplicate of https://github.com/coreos/bugs/issues/1681 or https://github.com/coreos/bugs/issues/1726.

**Closed by crawford** 2017-03-01 01:10 UTC

**Comment by someword** [comment] 2017-03-01 02:45
@crawford 
Assuming this issue is the same as reported in #1681 or #1726.   Can we in the community provide any further details or do any leg work to help determine the cause of the issue?

Also it's not clear to me if the issue is specific to the docker binary provided with CoreOS or if the the issue is believed to be upstream in the docker 1.12.X code base.    

Thanks!

**Comment by crawford** [comment] 2017-03-07 03:06
@someword any help you can provide would be greatly appreciated. Unfortunately, I can't name specific things to test since we haven't had a chance to dig into this issue yet.

I believe the issue to not be specific to the binary we ship, though it might be a combination of the kernel we use and docker.
