### ISSUE TITLE
Encrypted HVM AMI from 1235.1.0 not booting

### ISSUE THREAD

**Issue by seanknox** [coreos/bugs#1692] opened 2016-12-05 02:38 UTC
# Issue Report #

### CoreOS Version ###
1235.1.0

### Environment ###

Encrypted HVM instance on AWS in us-east-1

### Expected Behavior ###
Boot

### Actual Behavior ###
Instance is not reachable via SSH (but is pingable) 

### Reproduction Steps ###

  1. Create an encrypted copy of official CoreOS 1235.1.0 HVM AMI from us-east-1 (`ami-f49aa4e3`): `aws ec2 copy-image --source-region=us-east-1 --source-image-id=ami-f49aa4e3 --name=Encrypted-CoreOS-beta-1235.1.0-hvm --description "Encrypted CoreOS beta 1235.1.0 (HVM)" --encrypted`
  2. Boot HVM instance

### Other Information ###

Might be related to https://github.com/coreos/bugs/issues/1690

**Comment by crawford** [comment] 2016-12-07 17:43
Can you provide the console logs?

**Comment by seanknox** [comment] 2016-12-10 01:35
hey @crawford, here you go and sorry I took a few days to get back to you:

<img width="361" alt="ec2_management_console" src="https://cloud.githubusercontent.com/assets/1231630/21070123/a23362fa-be35-11e6-9082-67d10261553f.png">

That's as far as the instance gets. Tried with a variety of EC2 instance types: `t2.small`, `m4.large`, and `m3.medium`.

**Comment by seanknox** [comment] 2016-12-13 02:31
FWIW, same issue occurs on 1248 Alpha (`device-mapper: verity` block errors).

**Comment by crawford** [comment] 2016-12-13 02:35
Out of curiosity, can you try 1185.5.0? That image doesn't have dm-verity enabled by default.

**Comment by seanknox** [comment] 2016-12-13 15:57
Encrypted AMIs with 1185.5.0 work--that's what we're currently using.

**Comment by iameli** [comment] 2017-01-12 22:01
Exact same issue over here. Is there a workaround for this? We need encrypted root partitions for compliance reasons, so we're sort of stuck not upgrading CoreOS for now.

**Comment by crawford** [comment] 2017-01-12 23:42
We looked into this briefly and couldn't find a reasonable explanation for why verity is failing. Our guess at this point is that Amazon is modifying the image when it does the encrypted copy which means verity is working as intended.

We'll need to dig into this more closely with Amazon to figure out what is going on.

**Comment by iameli** [comment] 2017-01-13 03:25
Worked around it by baking my own AMI: 

* Spun up an unencrypted CoreOS 1235.6.0
* Created and attached an encrypted EBS volume
* Ran [coreos-install](https://github.com/coreos/init/blob/master/bin/coreos-install) on the encrypted volume
* Made a snapshot of that volume
* Made an AMI of that snapshot with these settings:

<img width="1352" alt="screen shot 2017-01-12 at 7 15 47 pm" src="https://cloud.githubusercontent.com/assets/257909/21917469/c5474ba8-d8fc-11e6-8d59-5390d1c123d9.png">

Appears to be working just fine so far.

**Comment by icereval** [comment] 2017-01-29 21:53
Seems to be introduced in a change made to verify `/usr` from [1214.0.0](https://coreos.com/releases/#1214.0.0):

>Changes:
>
>New installations will have dm-verity enabled by default for the /usr mount.

#### Error:
```
[    4.015108] sh[372]: Verity device detected corruption after activation.
[    4.022502] systemd[1]: Started Verity Setup for /dev/mapper/usr.
[    4.050704] device-mapper: verity: 202:3: data block 512 is corrupted
[    4.054296] device-mapper: verity: 202:3: data block 512 is corrupted
```

#### A quick test of a couple encrypted AMIs (x = boots):
- [x] CoreOS-stable-1185.5.0-hvm
- [x] CoreOS-beta-1192.2.0-hvm
- [ ] CoreOS-alpha-1214.0.0-hvm
- [ ] CoreOS-stable-1235.4.0-hvm
- [ ] CoreOS-stable-1235.5.0-hvm
- [ ] CoreOS-stable-1235.6.0-hvm

**Comment by crawford** [comment] 2017-01-31 01:25
@icereval this is expected (though undesirable). dm-verity verifies the contents of the disk before allowing it to be read. In this case, it looks like Amazon is changing the filesystem during the encryption process, so dm-verity's failure is completely expected. We are working with them to figure out why and how they are changing the filesystem.

**Comment by bgilbert** [comment] 2017-08-22 02:00
Amazon has informed us that their encrypt-on-copy functionality apparently only encrypts blocks that contain data, and not blocks that are excluded from the snapshot because they only contain zeroes.  When the latter blocks are then accessed, they apparently read as non-zero, causing dm-verity to fail.  Amazon is looking into fixing this.

https://github.com/coreos/bugs/issues/1692#issuecomment-272351698 is a valid workaround.  Another option might be to create an unencrypted volume from the snapshot specified by the AMI, then `dd` it to an encrypted volume and take a snapshot of that.

We may be able to work around this in Container Linux by enabling the verity `ignore_zero_blocks` option (https://github.com/torvalds/linux/commit/0cc37c2df4fa0aa702f9662edce4b7ce12c86b7a).

**Comment by bgilbert** [comment] 2017-09-15 00:34
It appears Amazon has fixed this for new AMIs.  Could someone who has encountered this problem verify that the latest alpha release (1535.0.0) is no longer affected?

**Comment by bgilbert** [comment] 2017-10-05 17:55
This appeared to be working when I tested it, so I'm going to close this issue.  Please leave a comment if encrypted AMI copies still aren't working for you.

**Closed by bgilbert** 2017-10-05 17:55 UTC
Labels: area/usability, component/distro, dependency/external, kind/bug, team/os

**Comment by kabbedijk** [comment] 2018-08-08 12:44
We have this same issue now again using CoreOS Container Linux stable 1800.6.0 (HVM)

**Comment by kabbedijk** [comment] 2018-09-12 09:15
Since this morning the issue is fixed again. It was fixed by AWS and the image released in (it appears) all regions.
