### ISSUE TITLE
Job for system-cloudinit@-var-tmp-hostname.yml.service failed because a configured resource limit was exceeded

### ISSUE THREAD

**Issue by piclez** [coreos/bugs#386] opened 2015-06-12 17:13 UTC
Hi,

I'm using Vagrant and CoreOS and after sometime the instance got unstable and getting this error:

sudo systemctl start system-cloudinit@-var-tmp-hostname.yml.service
Job for system-cloudinit@-var-tmp-hostname.yml.service failed because a configured resource limit was exceeded. See "systemctl status system-cloudinit@-var-tmp-hostname.yml.service" and "journalctl -xe" for details.

system-cloudinit@-var-tmp-hostname.yml.service                          loaded failed failed    system-cloudinit@-var-tmp-hostname.yml.service

systemctl status system-cloudinit@-var-tmp-hostname.yml.service
● system-cloudinit@-var-tmp-hostname.yml.service
   Loaded: loaded (/usr/lib64/systemd/system/system-cloudinit@.service; static; vendor preset: disabled)
   Active: failed (Result: resources)

Jun 12 17:04:26 core-br-01 systemd[1]: system-cloudinit@-var-tmp-hostname.yml.service: Failed to run 'start' task: Invalid argument
Jun 12 17:04:26 core-br-01 systemd[1]: Failed to start system-cloudinit@-var-tmp-hostname.yml.service.
Jun 12 17:04:26 core-br-01 systemd[1]: system-cloudinit@-var-tmp-hostname.yml.service: Unit entered failed state.
Jun 12 17:04:26 core-br-01 systemd[1]: system-cloudinit@-var-tmp-hostname.yml.service: Failed with result 'resources'.
Jun 12 17:04:26 core-br-01 systemd[1]: Starting system-cloudinit@-var-tmp-hostname.yml.service...
Jun 12 17:11:10 core-br-01 systemd[1]: Stopped system-cloudinit@-var-tmp-hostname.yml.service.
Jun 12 17:11:15 core-br-01 systemd[1]: system-cloudinit@-var-tmp-hostname.yml.service: Failed to run 'start' task: Invalid argument
Jun 12 17:11:15 core-br-01 systemd[1]: Failed to start system-cloudinit@-var-tmp-hostname.yml.service.
Jun 12 17:11:15 core-br-01 systemd[1]: system-cloudinit@-var-tmp-hostname.yml.service: Failed with result 'resources'.
Jun 12 17:11:15 core-br-01 systemd[1]: Starting system-cloudinit@-var-tmp-hostname.yml.service...

Any ideas?

Thanks,

Peter

**Comment by crawford** [comment] 2015-06-12 19:22
Duplicate of https://github.com/coreos/bugs/issues/382.

**Closed by crawford** 2015-06-12 19:22 UTC
