### ISSUE TITLE
systemd v229 usr.mount fails on first boot

### ISSUE THREAD

**Issue by mischief** [coreos/bugs#1187] opened 2016-03-28 21:29 UTC
boot log attached.
[usr.mount.txt](https://github.com/coreos/bugs/files/192510/usr.mount.txt)

**Comment by mischief** [comment] 2016-03-28 22:43
got a log with `debug quiet` on kernel commandline.
[usr.mount.debug.txt](https://github.com/coreos/bugs/files/192592/usr.mount.debug.txt)

**Comment by mischief** [comment] 2016-04-04 21:35
filed upstream bug at https://github.com/systemd/systemd/issues/2960

**Comment by mischief** [comment] 2016-04-06 17:35
this issue appears to be unreproducible if systemd v225 is in the initrd and v229 is in /usr.

**Comment by marineam** [comment] 2016-04-06 17:40
didn't @crawford reproduce it with v225 in /usr and v229 in the initrd?

**Comment by crawford** [comment] 2016-04-06 17:45
I _think_ I saw the failure with v229 in the initrd, but not v225. If I remember correctly, it didn't matter which version was in /usr. @mischief this is why we need to record all of the tests and their results.

**Comment by mischief** [comment] 2016-04-06 19:18
here's a full log containing the state transitions of the usr.mount unit, including the transition to `dead`. before while using the default systemd.log_target=journal, some messages were lost during a critical period. now i use `systemd.log_level=debug systemd.log_target=kmsg log_buf_len=128M` and `dmesg` to recover the logs.

some interesting bits:

```
$ grep -E 'dev-vda3\.device|usr\.mount|Switching' journal-debug-kmsg.txt 
[    2.092724] systemd[1]: dev-vda3.device: Installed new job dev-vda3.device/start as 49
[    2.092752] systemd[1]: sysroot-usr.mount: Installed new job sysroot-usr.mount/start as 46
[    2.544866] systemd[1]: dev-vda3.device: Changed dead -> plugged
[    2.544868] systemd[1]: dev-vda3.device: Job dev-vda3.device/start finished, result=done
[    2.805628] systemd[1]: sysroot-usr.mount: About to execute: /bin/mount /dev/vda3 /sysroot/usr -o ro,ro
[    2.805794] systemd[1]: sysroot-usr.mount: Forked /bin/mount as 669
[    2.805841] systemd[1]: sysroot-usr.mount: Changed dead -> mounting
[    2.806300] systemd[669]: sysroot-usr.mount: Executing: /bin/mount /dev/vda3 /sysroot/usr -o ro,ro
[    2.811933] systemd[1]: sysroot-usr.mount: Child 669 belongs to sysroot-usr.mount
[    2.811936] systemd[1]: sysroot-usr.mount: Mount process exited, code=exited status=0
[    2.811940] systemd[1]: sysroot-usr.mount: Changed mounting -> mounted
[    2.811942] systemd[1]: sysroot-usr.mount: Job sysroot-usr.mount/start finished, result=done
[    2.853875] systemd[1]: dev-vda3.device: Changed dead -> plugged
[    2.853890] systemd[1]: sysroot-usr.mount: Changed dead -> mounted
[    2.990566] systemctl[754]: Switching root - root: /sysroot; init: n/a
[    2.993244] systemd[1]: Switching root.
[    2.994985] systemd[1]: dev-vda3.device: Failed to send unit remove signal for dev-vda3.device: Transport endpoint is not connected
[    2.995043] systemd[1]: sysroot-usr.mount: Failed to send unit remove signal for sysroot-usr.mount: Transport endpoint is not connected
[    3.099733] systemd[1]: usr.mount: Failed to load configuration: No such file or directory
[    3.103497] systemd[1]: sysroot-usr.mount: Failed to load configuration: No such file or directory
[    3.104491] systemd[1]: sysroot-usr.mount: Changed dead -> mounted
[    3.104523] systemd[1]: usr.mount: Changed dead -> mounted
[    3.223302] systemd[1]: sysroot-usr.mount: Changed mounted -> dead
[    3.223335] systemd[1]: usr.mount: Changed mounted -> dead
[    3.241887] systemd[1]: sysroot-usr.mount: Collecting.
[    3.455302] systemd[1]: dev-vda3.device: Changed dead -> plugged
[    3.455305] systemd[1]: usr.mount: Trying to enqueue job usr.mount/start/fail
[    3.455429] systemd[1]: usr.mount: Installed new job usr.mount/start as 355
[    3.455433] systemd[1]: usr.mount: Enqueued job usr.mount/start as 355
[    3.455539] systemd[1]: usr.mount: Directory /usr to mount over is not empty, mounting anyway.
[    3.457567] systemd[1]: usr.mount: Failed to run 'mount' task: No such file or directory
[    3.457570] systemd[1]: usr.mount: Changed dead -> failed
[    3.457575] systemd[1]: usr.mount: Job usr.mount/start finished, result=failed
[    3.462311] systemd[1]: usr.mount: Unit entered failed state.
```
[journal-debug-kmsg.txt](https://github.com/coreos/bugs/files/207173/journal-debug-kmsg.txt)

**Comment by marineam** [comment] 2016-04-07 05:12
This bug was an exact duplicate of https://github.com/coreos/bugs/issues/463

Between https://github.com/coreos/bootengine/pull/86 and https://github.com/systemd/systemd/pull/2978 we should be good :)

**Comment by marineam** [comment] 2016-04-07 05:16
and https://github.com/coreos/systemd/pull/48

**Comment by marineam** [comment] 2016-04-07 05:34
Just for reference if ever needed some day, this is the dumb patch I wrote to capture libmount's debug output which made this bug blatantly obvious: https://gist.github.com/marineam/d3111d4f105fcac7516abde3ae9c3558

**Closed** 2016-04-21 17:32 UTC
Labels: area/usability, component/systemd, kind/bug, priority/P0, team/os
