### ISSUE TITLE
 GCP metadata script does not run. 

### ISSUE THREAD

**Issue by sampcoug** [coreos/bugs#2558] opened 2019-02-27 20:05 UTC
# Issue Report #

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1911.4.0
VERSION_ID=1911.4.0
BUILD_ID=2018-11-26-1924
PRETTY_NAME="Container Linux by CoreOS 1911.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
...
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###
GCE
What hardware/cloud provider/hypervisor is being used to run Container Linux?
Google Cloud Platform (GCP)
### Expected Behavior ###
I am using Terraform to launch the GCE VM instance and have added the metadata piece as startup script automation to my terraform code.
The metadata script should run when the VM instance gets created. I do see the script was added to the - Custom metadata section of the VM instance.

### Actual Behavior ###
The script does not run.
### Reproduction Steps ###

  1. Start a CoreOS instance in GCE in Terraform.
  2. Setup Metadata piece as below in Terraform. 

` metadata {
    startup-script = <<SCRIPT
    #!/bin/bash
    sudo su
    echo "this is a test" > /var/log/test.txt
    SCRIPT
    }`
### Other Information ###
Having Metadata piece working is critical to the CoreOs machine configuration.

**Comment by ajeddeloh** [comment] 2019-02-27 20:16
Container Linux only supports using Ignition or coreos-cloudint (which in turn supports scripts). coreos-cloudinit is deprecated though, if you're looking to do a new installation use [Container Linux Configs]( https://coreos.com/os/docs/latest/provisioning.html) and [Ignition](https://github.com/coreos/ignition).

Both of these use the `user-data` field. using `statup-script` is intentionally not supported.

**Comment by sampcoug** [comment] 2019-02-27 22:06
Thanks ajeddeloh! So to understand, using metadata for post deployment automation is not possible at   all in CoreOS?

**Comment by ajeddeloh** [comment] 2019-02-27 23:07
It is with cloudinit, but again, that's deprecated in favor of Ignition. Container Linux was designed as an immutable OS; once you've deployed a configuration you don't change it. The flip side of that is since all of the the configuration is declaratively defined in the Ignition spec, redeploying should be easy.

I'm closing this issue, but feel free to ask more questions if you have them.

**Closed by ajeddeloh** 2019-02-27 23:07 UTC

**Comment by sampcoug** [comment] 2019-02-28 00:14
Thanks for the clarification!
