### ISSUE TITLE
set docker default logger to journald

### ISSUE THREAD

**Issue by camerondavison** [coreos/bugs#472] opened 2015-09-14 15:29 UTC
I think that it would be nice to have the default logger for docker in coreos be journald, since basically everything else logs to it. https://docs.docker.com/reference/logging/journald/

**Comment by marineam** [comment] 2015-09-21 16:41
Fyi, this is being rolled back in https://github.com/coreos/coreos-overlay/pull/1553 due to https://github.com/coreos/bugs/issues/483

**Comment by a86c6f7964** [comment] 2015-09-21 19:35
Is this going to have to be an opt in thing instead? That seems kinda too bad to me.

**Comment by marineam** [comment] 2015-09-21 19:40
@a86c6f7964 sure, just add the command line arg similar to how insecure registry is done here: https://coreos.com/blog/docker-1-3-2-stable-channel/

**Comment by a86c6f7964** [comment] 2015-09-22 01:25
ya I realize that I could do that. I was just thinking that it would be a really nice default so that disk space is less likely to fill up from app logs.

**Comment by a86c6f7964** [comment] 2016-03-24 21:15
just for anyone in the future better to follow the instructions at https://coreos.com/os/docs/latest/registry-authentication.html rather than the blog post. The blog post has some of the quotes in the wrong places.

**Comment by crawford** [comment] 2016-03-24 21:17
Oops. We should fix that blog post.

**Comment by JacobHayes** [comment] 2016-05-23 20:24
Looks like `--log-driver=journald` can be the default again now that `docker logs` supports reading from journald.

**Comment by mischief** [comment] 2016-05-23 20:35
@JacobHayes do you have a reference for that? what version is that introduced in?

**Comment by JacobHayes** [comment] 2016-05-23 22:43
It looks at least since docker 1.6/remote API 1.18. I can't find release notes before that, but the remote api 1.18 doc [log section](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.18/#get-container-logs) mentions that the endpoint works for the `json-file` and `journald` logging drivers.

Testing on docker 1.9.1/coreos 899.17.0 worked fine.

```
docker run -d --log-driver=journald --name=logging-test debian:jessie /bin/sh -c "while true; do echo 'check docker logs and journalctl'; sleep 1; done;"
```

**Comment by crawford** [comment] 2016-05-23 23:04
@JacobHayes the concern is more around `docker logs` and any other tools which interact with the log. We had briefly set the log driver to journald, but it ended up breaking all of these support tools.

**Comment by JacobHayes** [comment] 2016-05-23 23:07
As stated in the linked log section and hinted at in the command (`check docker logs and journalctl`), `docker logs` does work. Is that what you mean? As far as I can tell, it's completely transparent, so any other support tools will work out of the box, with the command line or API.

**Comment by crawford** [comment] 2016-05-23 23:11
@JacobHayes whoops, yeah that's exactly what I meant. :smile: We can probably make this change now.

**Comment by mischief** [comment] 2016-05-24 21:00
unfortunately, i can't read any logs, new or old, after switching to the journald driver. need to investigate more.

```
core@coreos_production_qemu-1053-1-0- ~ $ docker run --name busybox busybox echo hello
hello
core@coreos_production_qemu-1053-1-0- ~ $ docker logs busybox
Error running logs job: configured logging reader does not support reading
core@coreos_production_qemu-1053-1-0- ~ $ ps -auxww | grep "docker daemon"
root      1217  0.1  3.7 574160 38296 ?        Ssl  20:57   0:00 docker daemon --host=fd:// --log-driver=journald --exec-opt native.cgroupdriver=systemd --selinux-enabled
```

**Comment by JacobHayes** [comment] 2016-05-24 21:58
@mischief It worked for me on coreos 899.17.0 (current stable). My docker process doesn't have the `--exec-opt native.cgroupdriver=systemd` option, but that (naively) seems unrelated.

Default daemon logging w/ container `--log-driver`:
```
# docker run --name busybox --log-driver=journald busybox echo hello
hello
# docker logs busybox
hello
# journalctl | grep hello
May 24 21:35:09 <hostname> docker[1055]: hello
# ps -auxww | grep "docker daemon"
root      1055  0.2  0.2 1299100 57352 ?       Ssl  13:56   1:00 docker daemon --host=fd:// --selinux-enabled
```

Daemon `--log-driver`:
```
# docker run --name busybox2 busybox echo hello
hello
# docker logs busybox2
hello
# journalctl | grep hello
May 24 21:35:09 <hostname> docker[1055]: hello
May 24 21:43:56 <hostname> docker[10586]: hello
# ps -auxww | grep "docker daemon"
root     10586  0.5  0.1 960272 45196 ?        Ssl  21:42   0:00 docker daemon --host=fd:// --log-driver=journald --selinux-enabled
```

`/etc/os-release`
```
NAME=CoreOS
ID=coreos
VERSION=899.17.0
VERSION_ID=899.17.0
BUILD_ID=2016-05-03-2151
PRETTY_NAME="CoreOS 899.17.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by mischief** [comment] 2016-05-24 22:34
@JacobHayes it's easy enough to enable this, but the thing i'm not sure about is behavior of old logs after switching.

afaik, it's impossible to recover logs of prior container executions after switching the driver.

**Comment by marineam** [comment] 2016-05-25 04:01
Perhaps the best way forward is to just document how to enable it easily
and call it good, loosing access to previous logs isn't something wise to
do automatically in an upgrade. One of the previously cited reasons for
using journal was to avoid running out of disk space due to logs but
assuming logrotate is still working since Sara added it last year that
should be ok.

**Comment by simonvanderveldt** [comment] 2016-05-27 10:36
> One of the previously cited reasons for
> using journal was to avoid running out of disk space due to logs but
> assuming logrotate is still working since Sara added it last year that
> should be ok.

Which logrotate do you mean?
Because the docker daemon keeps it's own logs of the containers, which can take up a serious amount of space.

**Comment by crawford** [comment] 2016-05-27 17:52
I think the ideal case would be to use journald going forward and remain on Docker for existing installs. Maybe we can inspect Docker in post_inst and conditionally create a drop-in to revert the logging behavior.

**Comment by marineam** [comment] 2016-05-27 18:44
@simonvanderveldt bah, my mistake. I thought we had added rotation of those logs to the image by default and documented configuring logrotate but it was only ever an email :(

https://groups.google.com/forum/#!topic/coreos-user/83Ln2j4t6uU

**Comment by marineam** [comment] 2016-05-27 18:46
@crawford hm, maybe our dockerd script checks for the existence of the docker logs directory and sets the default mechanism accordingly?

**Comment by simonvanderveldt** [comment] 2016-05-27 20:55
> @simonvanderveldt bah, my mistake. I thought we had added rotation of those logs to the image by default and documented configuring logrotate but it was only ever an email :(

Well, we're only human so that can always happen :)
I wasn't sure either that's why I asked ;)

Regarding switching Docker to the SystemD log driver, it definitely makes sense to do so, at the very least it prevents issues with full disks because of massive log pile-up caused by Docker and the double logging is pretty much redundant anyway.

Do keep in mind that there are some requirements/issues on the Docker side. The ones I'm aware of:
- Docker 1.9.0 or higher is required for `docker logs` to work https://github.com/docker/docker/pull/13707
- Containers with a tty won't actually show their output in the logs, but only show `#B blob data`, see https://github.com/docker/docker/issues/15722

Also if this change is made it pretty much adds a "hard" dependency on systemd-journald to the Docker daemon, because I expect containers won't be able to start if journald isn't running. I haven't been able to verify this behaviour though.
To be honest there is already a hard coupling with systemd-journald, because when I killed systemd-journald the Docker daemon restarted, obviously stopping/killing all running containers.
Just something to be aware of :)

**Comment by chancez** [comment] 2016-06-01 22:09
FYI, switching this will break anyone using the upstream kubernetes aggregating logging addon. 

Details here: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/td-agent.conf#L1-L6

So at the minimum, we should coordinate this change with https://github.com/coreos/coreos-kubernetes such that either CoreOS Kubernetes has an alternative logging choice which slurps directly from journald (similar to https://github.com/kubernetes/kubernetes/issues/21702), or more likely, that CoreOS Kubernetes hardcodes the logging driver in our setup scripts until we have time to tackle getting logs from journald.

**Comment by llarsson** [comment] 2016-06-15 06:11
What is the correct way of handling logs in CoreOS, anyway? When I started using CoreOS, I filled my logs with a lot of stuff because I did not reflect on how expensive that could get in terms of disk space. Then, I could fix it with journalctl and some vacuuming.

Does Docker's own log rotation ensure that logs are kept at a reasonable size, or will they still be put in systemd's journal as well?

I would love some documentation and/or best practices regarding this on the website.

With etcd growing practically infinitely with its snapshotting, and the systemd journal as well, my long-running clusters need more care than I had hoped for.

**Comment by Zapadlo** [comment] 2016-06-15 09:39
I can only speak from experience but we turn off docker logging:

```
units:
  - name: docker.service
    drop-ins:
      - name: 10-turn-off-logging.conf
        content: |
          [Service]
          Environment="DOCKER_OPTS=--log-driver=none"
```

Converted all apps to be more "12 factor" and only log to stdout.

**Comment by jimmycuadra** [comment] 2016-07-20 08:46
Can someone summarize what the current state of this is? I have a systemd drop-in for Docker that sets `DOCKER_OPTS='--log-driver=journald'`, and `docker logs` (as well as `kubectl logs` for a container running on such a node) works in the latest CoreOS beta but not CoreOS stable. That is, on CoreOS stable, those commands just output the dreaded "configured logging reader does not support reading" error message. Logs are written to journald in both versions, but the `docker`/`kubectl` client behavior is different. What is the difference between the two release channels of CoreOS that would cause this? Specifically, my beta cluster is on version 1081.5.0 and my stable cluster is on 1068.8.0.

**Comment by basvdlei** [comment] 2016-07-20 09:59
@jimmycuadra `docker logs` failing to read from journald was reported in issue https://github.com/coreos/bugs/issues/1422

**Comment by crawford** [comment] 2016-07-26 02:15
@jimmycuadra [1081.1.0](https://coreos.com/releases/#1081.1.0) added support for the journald logging driver.

**Comment by philk** [comment] 2016-07-29 18:06
Is there a plan to hotfix this on the stable channel or since it's a docker version do we have to wait till beta rolls through?

**Comment by crawford** [comment] 2016-08-05 02:47
We are going to wait until the next Beta rolls through. That should happen in about a month.

**Comment by simonvanderveldt** [comment] 2016-08-05 16:18
@crawford a bit offtopic, but related to your comment: Where can the current open issues and PRs for a specific release be found? The [milestones](https://github.com/coreos/bugs/milestones) don't show anything of significance.

**Comment by crawford** [comment] 2016-08-06 00:24
@simonvanderveldt unfortunately, we don't have a good way of tracking that. GitHub's issue tracker is a bit limited in that regard. We'll probably end up switching to a more feature-rich bug system so we can represent that sort of stuff in the future.

**Comment by jimmycuadra** [comment] 2016-08-29 22:42
Perhaps veering off topic from the original issue here, but it's worrisome that it wasn't considered worthy of an immediate hotfix. Waiting a month for a fix to broken logging won't be acceptable for my team once we start using CoreOS in production. :\

**Comment by llarsson** [comment] 2016-08-30 04:22
I will stay away from it as well until "stable" means getting important updates and fixes, not just "did not seem to break catastrophically during alpha or beta", and will be stuck in a broken state for who knows how long. 

It seems that the best way to use CoreOS is to be on the alpha channel, because that is where bugs get fixed in a reasonably timely fashion. I just can't recommend that for production. 

Jimmy Cuadra <notifications@github.com> skrev: (30 augusti 2016 00:42:30 CEST)
>Perhaps veering off topic from the original issue here, but it's
>worrisome that it wasn't considered worthy of an immediate hotfix.
>Waiting a month for a fix to broken logging won't be acceptable for my
>team once we start using CoreOS in production. :\
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/coreos/bugs/issues/472#issuecomment-243279875

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bgilbert** [comment] 2018-05-21 23:49
Thank you for reporting this issue. Unfortunately, we don't think we'll end up addressing it in Container Linux.

As we recently announced, we're working on a [successor to Container Linux](https://groups.google.com/d/topic/coreos-user/PFHJQMJSRbE/discussion), and we expect most major development to occur there instead. Meanwhile, Container Linux won't see many new features, but will still be fully maintained into 2020. Stay tuned for more details about that.

**Closed by bgilbert** 2018-05-21 23:49 UTC
Labels: closed/rejected, component/docker, kind/enhancement, priority/P1, team/os
