### ISSUE TITLE
CoreOS 899.15.0 (openstack) problem with discovery token

### ISSUE THREAD

**Issue by Norna** [coreos/bugs#1254] opened 2016-04-28 16:42 UTC
Hi, I setup my cluster in Openstack with CoreOS 899.15.0 but the etcd2 failed to start because of discovery token was used. The token was newly generated. How can this be?

This is from the log

Apr 28 16:25:31 rhino-cls-1.novalocal etcd2[1614]: discovery token https://discovery.etcd.io/02fb831ce240ee521f6bf3e197ca4446 was used, but failed to bootstrap the cluster.
Apr 28 16:25:31 rhino-cls-1.novalocal etcd2[1614]: please generate a new discovery token and try to bootstrap again.

**Comment by mischief** [comment] 2016-04-28 21:58
@Norna do you have more logs..?

you can only use a discovery token once, and if the bootstrap fails, you need to generate a new one and reconfigure all of the cluster members.

**Comment by Norna** [comment] 2016-04-28 22:02
@mischief I destroyed the instance already but the log was kinda repeat as the service was restarted. The token generated by  https://discovery.etcd.io. They were new. I tried to create the cluster several times and they were all failed. I switch to older version of CoreOS then it was okay. I am not sure what is going on with that.

**Comment by mischief** [comment] 2016-04-28 22:54
@Norna without logs it's hard to say what happened. if you can reproduce it, post logs of the failure.

**Comment by Norna** [comment] 2016-05-03 15:40
@mischief : this is the logs:

-- Subject: Unit etcd2.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit etcd2.service has failed.
--
-- The result is failed.
May 03 15:37:54 rhino-nd-1.novalocal systemd[1]: etcd2.service: Unit entered failed state.
May 03 15:37:54 rhino-nd-1.novalocal systemd[1]: etcd2.service: Failed with result 'exit-code'.
May 03 15:38:04 rhino-nd-1.novalocal systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.
May 03 15:38:04 rhino-nd-1.novalocal systemd[1]: Stopped etcd2.
-- Subject: Unit etcd2.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit etcd2.service has finished shutting down.
May 03 15:38:04 rhino-nd-1.novalocal systemd[1]: Starting etcd2...
-- Subject: Unit etcd2.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit etcd2.service has begun starting up.
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.0.10.190:2379,http://10.0.10.190:4001
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/68e5f075b11a0e6cabd2726ded6be9d9
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: recognized and used environment variable ETCD_ELECTION_TIMEOUT=1200
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.0.10.190:2380
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://10.0.10.190:2380
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: recognized and used environment variable ETCD_NAME=281650fb4d36435495d670af4f940bfb
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: etcd Version: 2.2.3
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: Git SHA: 05b564a
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: Go Version: go1.4.3
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: Go OS/Arch: linux/amd64
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: setting maximum number of CPUs to 1, total number of available CPUs is 2
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: listening for peers on http://10.0.10.190:2380
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: listening for client requests on http://0.0.0.0:2379
May 03 15:38:04 rhino-nd-1.novalocal etcd2[870]: listening for client requests on http://0.0.0.0:4001
May 03 15:38:09 rhino-nd-1.novalocal etcd2[870]: stopping listening for client requests on http://0.0.0.0:4001
May 03 15:38:09 rhino-nd-1.novalocal etcd2[870]: stopping listening for client requests on http://0.0.0.0:2379
May 03 15:38:09 rhino-nd-1.novalocal etcd2[870]: stopping listening for peers on http://10.0.10.190:2380
May 03 15:38:09 rhino-nd-1.novalocal etcd2[870]: failed to join discovery cluster (context deadline exceeded)
May 03 15:38:09 rhino-nd-1.novalocal etcd2[870]: discovery token https://discovery.etcd.io/68e5f075b11a0e6cabd2726ded6be9d9 was used, but failed to bootstrap the cluster.
May 03 15:38:09 rhino-nd-1.novalocal etcd2[870]: please generate a new discovery token and try to bootstrap again.
May 03 15:38:09 rhino-nd-1.novalocal systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
May 03 15:38:09 rhino-nd-1.novalocal systemd[1]: Failed to start etcd2.
-- Subject: Unit etcd2.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit etcd2.service has failed.
--
-- The result is failed.
May 03 15:38:09 rhino-nd-1.novalocal systemd[1]: etcd2.service: Unit entered failed state.
May 03 15:38:09 rhino-nd-1.novalocal systemd[1]: etcd2.service: Failed with result 'exit-code'.

**Comment by Norna** [comment] 2016-05-03 15:52
@mischief : this is the logs:

May 03 15:34:46 rhino-nd-3.novalocal fleetd[714]: INFO fleetd.go:64: Starting fleetd version 0.11.7
May 03 15:34:46 rhino-nd-3.novalocal fleetd[714]: INFO fleetd.go:168: No provided or default config file found - proceeding without
May 03 15:34:46 rhino-nd-3.novalocal fleetd[714]: INFO server.go:157: Establishing etcd connectivity
May 03 15:34:56 rhino-nd-3.novalocal systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.
May 03 15:34:56 rhino-nd-3.novalocal systemd[1]: Stopped etcd2.
-- Subject: Unit etcd2.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit etcd2.service has finished shutting down.
May 03 15:34:56 rhino-nd-3.novalocal locksmithd[597]: etcd2.service is active
May 03 15:34:56 rhino-nd-3.novalocal systemd[1]: Starting etcd2...
-- Subject: Unit etcd2.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit etcd2.service has begun starting up.
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.0.10.191:2379,http://10.0.10.191:4001
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/68e5f075b11a0e6cabd2726ded6be9d9
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: recognized and used environment variable ETCD_ELECTION_TIMEOUT=1200
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.0.10.191:2380
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://10.0.10.191:2380
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: recognized and used environment variable ETCD_NAME=12f64ff31ced419d805af9f07768b3c8
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: etcd Version: 2.2.3
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: Git SHA: 05b564a
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: Go Version: go1.4.3
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: Go OS/Arch: linux/amd64
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: setting maximum number of CPUs to 1, total number of available CPUs is 2
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: listening for peers on http://10.0.10.191:2380
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: listening for client requests on http://0.0.0.0:2379
May 03 15:34:56 rhino-nd-3.novalocal etcd2[722]: listening for client requests on http://0.0.0.0:4001
May 03 15:35:01 rhino-nd-3.novalocal etcd2[722]: stopping listening for client requests on http://0.0.0.0:4001
May 03 15:35:01 rhino-nd-3.novalocal etcd2[722]: stopping listening for client requests on http://0.0.0.0:2379
May 03 15:35:01 rhino-nd-3.novalocal etcd2[722]: stopping listening for peers on http://10.0.10.191:2380
May 03 15:35:01 rhino-nd-3.novalocal locksmithd[597]: Unlocking old locks failed: error setting up lock: Error initializing etcd client: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]. Ret
May 03 15:35:01 rhino-nd-3.novalocal etcd2[722]: failed to join discovery cluster (context deadline exceeded)
May 03 15:35:01 rhino-nd-3.novalocal etcd2[722]: discovery token https://discovery.etcd.io/68e5f075b11a0e6cabd2726ded6be9d9 was used, but failed to bootstrap the cluster.
May 03 15:35:01 rhino-nd-3.novalocal etcd2[722]: please generate a new discovery token and try to bootstrap again.
May 03 15:35:01 rhino-nd-3.novalocal systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
May 03 15:35:01 rhino-nd-3.novalocal systemd[1]: Failed to start etcd2.

**Comment by Norna** [comment] 2016-05-04 14:24
@mischief : Have you got time to review this?

**Comment by mischief** [comment] 2016-05-04 19:13
@Norna as the log suggests,

```
May 03 15:35:16 rhino-nd-3.novalocal etcd2[732]: failed to join discovery cluster (context deadline exceeded)
```

it looks like etcd can't reach the discovery server. perhaps you need a proxy, or your network latency is too high.

in any case, you will need to get a *new* discovery token, reconfigure each member with that new url, *and* erase the data dir of each member to try bootstrapping again.

**Comment by Norna** [comment] 2016-05-04 19:55
@mischief : I tried to get a new token and replaced the old one but still got the same error. why this doesn't happen with older version of CoreOS on the same OpenStack platform? if the cluster has not formed yet why can't it be reused? can we extend the context deadline?

**Comment by xiang90** [comment] 2016-05-12 21:30
>  if the cluster has not formed yet why can't it be reused? 

It cannot be reused since some of your machine already wrote something into that token and polluted it.


> can we extend the context deadline?

It is a 5 seconds timeout, can I know why it is not enough? What is your network situation?

**Comment by Norna** [comment] 2016-05-13 09:49
@xiang90 : I am not quite sure about the network situation since I am just a user in that system. By the way I have already moved my cluster to a new openstack setup by my school and it works. 

Still there must be something, why the old CoreOS forms a cluster perfectly while the new version cannot. That could be something that the team should investigate but for now I am fine with my new cluster. Thank so much for your time :)

**Comment by xiang90** [comment] 2016-06-20 21:35
@Norna OK. I am closing this since it is not a problem for you anymore. If this happens again and you can reproduce, please reopen. Thanks a lot!

**Closed by xiang90** 2016-06-20 21:35 UTC
Labels: component/etcd, kind/question

**Comment by tyrael007** [comment] 2016-07-28 09:40
@xiang90 5 seconds timeout is not enough.It may takes 10 seconds in China.
