### ISSUE TITLE
Docker is not creating DOCKER-chain always

### ISSUE THREAD

**Issue by theikkila** [coreos/bugs#338] opened 2015-04-25 08:43 UTC
## Introduction
This issue happens a least in current beta 647.0.0 and alpha 660.0.0 and causes all containers which uses port mapping (at least public ports) unable to start.
This has caused often but not in all nodes same time and not always.
This issue origin is really hard to reproduce, but consequences can be simulated by removing DOCKER-chain from iptables.

## Signs in logs
Logs show no sign for original problem but the missing chain looks like this:
```
Apr 25 07:35:16 localhost dockerd[733]: iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 80 -j ACCEPT: iptables: No chain/target/match by that name.
```

## work-around fix
Just add `iptables -N DOCKER` in iptables configuration and that should affect immediately.

**Comment by croemmich** [comment] 2015-04-28 02:28
I'm seeing this issue as well. My hunch in my case is that I have enabled iptables-restore.service, which seems to be getting applied after Docker is started, thus removing all of Docker's rules. I haven't been able to figure out why it is being run after Docker however.

**Comment by porjo** [comment] 2015-05-01 06:00
I'm using `iptables-restore.service` also but I've never had this issue with missing `DOCKER` chain. I am, however, seeing an issue where certain rules are missing from the `FORWARD` chain after a Docker restart - see #344. That may be related.

**Comment by croemmich** [comment] 2015-06-05 14:09
I just had this happen again last night. I'm wondering if it might be related to iptables-restore.service.

**Comment by crawford** [comment] 2015-10-19 22:38
Is this still a problem with the latest version of Docker?

**Comment by crawford** [comment] 2015-11-18 00:02
Bump. Have you seen these failures in the Alpha or Beta channels? We are shipping a newer version of Docker there (soon to make its way to Stable).

**Comment by kristofferhagen** [comment] 2015-11-19 23:58
I had a similar problem today trying to set up CoreOS stable (tried beta as well) in Vagrant. My issue was that the DOCKER-chain did not exist in the NAT-table. I was about to test in alpha as well, but ended up solving the issue by not adding the flannel service. I should mention that this happened 5/5 times when I was just doing `vagrant up` and resetting with `vagrant destroy`. `iptables-restore.service` and `iptables-save` is not enabled.

**Comment by mischief** [comment] 2015-11-20 00:07
@eyakubovich any ideas on this one?

**Comment by eyakubovich** [comment] 2015-11-20 21:58
If you run flannel, Docker ends up getting run with `--ip-masq=false` which should prevent it installing NAT table rules. This is because under CoreOS, flanneld is started with `--ip-masq=true` which causes it to take over installing (slightly different) masquerade rules. However, this should not affect filter table or DNAT rules under NAT table.

**Comment by crawford** [comment] 2015-12-01 23:33
Closing due to inactivity. Please re-open if this is still a problem.

**Comment by PatrickHeneise** [comment] 2015-12-28 08:50
Having the same issue with beta 877.1.0. `-N DOCKER` in the iptables config does the trick for now.

**Comment by crawford** [comment] 2016-07-27 06:13
Is this still an issue with the latest releases of Docker?

**Comment by mwbrown** [comment] 2016-08-03 01:45
I am noticing that with CoreOS Stable 1068.8.0 this still appears to be an issue. It seems like iptables-restore.service is running after Docker is creating its chain, despite docker.service being listed after network.target, and iptables is listed before network.target.

**Comment by mwbrown** [comment] 2016-08-03 01:58
Actually, after some experimentation on a VULTR host, I noticed that overriding iptables-restore.service via /etc/systemd/system/ and changing it to "Before=docker.service", it is working properly.

It seems that VULTR uses their /usr/share/oem/cloud-config.yml as an odd late-init where the unit files listed in there can potentially get started too late, i.e. wiping out the existing chains.

**Comment by crawford** [comment] 2016-08-05 02:45
Oof, that is a nasty side effect. Yet another reason we need to migrate to Ignition ASAP.

**Comment by crawford** [comment] 2016-09-20 18:11
I have not been able to reproduce this failure with the latest releases of CoreOS Linux. I'm going to close this out. We can revisit it if there continues to be a problem.

**Closed by crawford** 2016-09-20 18:11 UTC
Labels: area/usability, component/docker, component/other, kind/bug, priority/P0, team/os

**Comment by christidis** [comment] 2018-06-29 08:03
Had the same issue
```
No chain/target/match by that name.\n (exit status 1)
```

on debian not CoreOS with
```
# docker --version
Docker version 17.03.1-ce, build c6d412e
```

In my case this systemd workaround did the trick 
```
[Service]
...
ExecStartPre=/bin/bash -c "/sbin/iptables -N DOCKER && echo 'created docker chain' || /bin/true"
Restart=on-failure
RestartSec=10s
```

On server reboot I can see the chain creation.
```
Jun 27 12:49:20 dhost01 systemd[1]: Starting Docker Application Container Engine...
Jun 27 12:49:23 dhost01 bash[11878]: created docker chain
...
```

Hope that helps.
