### ISSUE TITLE
Toolbox quits when any program sends a sigkill not the top level command

### ISSUE THREAD

**Issue by achew22** [coreos/bugs#1216] opened 2016-04-11 00:40 UTC
Is there any way to make it only care about sigkill from the bash command that is the root of the process tree?

**Comment by crawford** [comment] 2016-04-21 15:38
I can't reproduce this failure. Can you give me a simple test case?

**Comment by achew22** [comment] 2016-05-08 22:08
This seems to make it happen on my box with ~100% reliability

```
achew22@springs:~$ sh -c 'sleep 1000s' &
[1] 21888
achew22@springs:~$ kill -9 %1
achew22@springs:~$
Container my-container terminated by signal KILL.
```

If I run that on other boxes it doesn't seem to have a problem with it killing the parent.

**Comment by crawford** [comment] 2016-05-10 17:23
I cannot reproduce this in my toolbox (`PRETTY_NAME="Fedora 23 (Twenty Three)"`). Which version of Fedora is in your toolbox? Can you try recreating the toolbox with the latest?

**Comment by daper** [comment] 2016-06-11 09:55
@achew22 The same for me. I've tried with an image of ubuntu, debian and fedora (latest versions). Any workarround to avoid this weird bug? Thank you all.

**Comment by spacepluk** [comment] 2016-07-23 15:43
I'm getting the same error with `pritunl/archlinux` any time I try to install a package (e.g. `pacman -S tmux`).  But I tried @achew22's test and that doesn't kill it.

**Comment by a86c6f7964** [comment] 2017-01-10 15:28
There is a workaround linked several issues over. just copying it over to this issue since it took me a while to track it down again and the other issues are closed as dupes of this one.

Use the previous fedora tag
```
echo "TOOLBOX_DOCKER_TAG=24" >>$HOME/.toolboxrc
```

**Comment by ankon** [comment] 2017-01-10 16:58
When one actually needs Fedora 25 for whatever reasons, this workaround from https://github.com/coreos/bugs/issues/1676#issuecomment-263123937 worked for me:
```sh
rpm --import /etc/pki/rpm-gpg/RPM*
```

**Comment by vmarkovtsev** [comment] 2017-01-16 14:50
There is another workaround: remove `--share-system` from systemd-nspawn command line. Somehow it propagates SIGKILL. I reference https://github.com/coreos/bugs/issues/1610 here

**Comment by urzds** [comment] 2017-01-27 16:38
I can also reproduce this on `Container Linux by CoreOS stable (1235.6.0)` running a Fedora 25 toolbox:
```
$ toolbox
[...]
# dnf -y install 'dnf-command(config-manager)'
[...]
Downloading Packages:
[SKIPPED] dnf-plugins-core-0.1.21-4.fc25.noarch.rpm: Already downloaded
[SKIPPED] python3-dnf-plugins-core-0.1.21-4.fc25.noarch.rpm: Already downloaded
warning: /var/cache/dnf/fedora-310f9d37d74ceec1/packages/dnf-plugins-core-0.1.21-4.fc25.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID fdb19c98: NOKEY
Container core-fedora-latest terminated by signal KILL.
```

`rpm --import /etc/pki/rpm-gpg/RPM*` as mentioned above https://github.com/coreos/bugs/issues/1216#issuecomment-271631939 works around this issue.

**Comment by dm0-** [comment] 2017-03-08 00:33
I believe this is fixed in systemd v233.  It should be in the alpha next week.

**Closed** 2017-03-14 02:19 UTC
Labels: area/usability, component/toolbox, kind/regression, priority/P0, team/os
