### ISSUE TITLE
CoreOS alpha - install failed to start

### ISSUE THREAD

**Issue by bchanan03** [coreos/bugs#914] opened 2015-10-11 20:56 UTC
Hi All,

When start my virtualbox in order to install the new version 829.0 I get
"Failed to start Switch Root"

Attached is an image showing the error and the status
![failed](https://cloud.githubusercontent.com/assets/7847610/10419035/7f4337e0-7073-11e5-9a33-03d758667965.png)

the issue found within initrd-switch-root.service - I tried downloading the ISO file twice
same issue found on both.

Thanks
Chanan

**Comment by bchanan03** [comment] 2015-10-12 06:28
Update: 
1) I found that also stable version failed - and I am sure it worked in the past :(
2) I re-installed the virtualbox with the latest version 5.0.6 - and tried the Stable version
all works.

**Comment by bchanan03** [comment] 2015-10-12 06:33
I tried again:
1) Stable version works as should
2) Alpha version failed the initrd-switch-root.service service

**Comment by crawford** [comment] 2015-10-13 18:30
Which version of CoreOS are you attempting to boot? 829.0.0?

**Comment by marineam** [comment] 2015-10-13 18:53
How much ram did you give the VM?

**Comment by kayrus** [comment] 2015-10-13 19:33
@bchanan03 can you post full logs? `systemctl status -l initrd-switch-root.service`

**Comment by vcaputo** [comment] 2015-10-26 07:59
@crawford I wonder if this is a manifestation of the races fixed by https://github.com/coreos/bootengine/pull/75

**Comment by mischief** [comment] 2015-11-23 23:27
@bchanan03 any chance you can try this against the latest alpha?

**Comment by mischief** [comment] 2015-12-01 23:23
@bchanan03 closing due to inactivity. please try a newer alpha, and if you continue to have trouble, reopen this issue.

**Closed by mischief** 2015-12-01 23:23 UTC
Labels: component/other, kind/regression, priority/P0, team/os

**Comment by mheese** [comment] 2015-12-30 23:33
I'm seeing the same issue here ... fails with all latest (as of this writing) alpha, beta and stable releases. I'm doing an iPXE boot on physical hardware. The machine has 32GB RAM.

**Comment by crawford** [comment] 2016-01-04 20:43
@mheese what hardware are you using? Which version of CoreOS? Can you provide the boot logs?

**Comment by mheese** [comment] 2016-01-07 17:05
@crawford: I think I am finally able to reproduce it in a standard VirtualBox VM. I will create a new ticket for this. It seems to be related to booting iPXE as EFI image. The exact same images and kernel command line settings boot fine if I use iPXE in "legacy" mode. This might even be expected behaviour or maybe a bug in iPXE is involved as well.

**Comment by changx** [comment] 2016-01-17 14:30
I'm in the same issue here.

The versions I've tested, the problem begins from 877 ~ the latest alpha.

**Comment by nathankunicki** [comment] 2016-05-25 16:24
An additional note, I've also tried the following, with the same result:

```
#!/bin/bash
set -ex

cat<<-EOF > /etc/systemd/system/docker-tcp.socket
[Unit]
Description=Docker Socket for the API

[Socket]
ListenStream=2375
BindIPv6Only=both
Service=docker.service

[Install]
WantedBy=sockets.target
EOF

systemctl enable /etc/systemd/system/docker-tcp.socket
systemctl start docker-tcp.socket
```

**Comment by muthu81** [comment] 2016-08-16 20:13
@mcheese, Was there a fix for this? This seems to be a problem with only the EFI boot image and "legacy" mode booting is perfectly fine.

**Comment by matti** [comment] 2017-12-05 13:27
Check RAM, accidentally I had reset my settings to 1024mb

**Comment by marcusrafael** [comment] 2018-01-31 17:44
Worked to me after set RAM as 2048 MB

**Comment by redice** [comment] 2018-09-11 10:31
It worked  to me after set RAM to 2048MB in 1855.3.0

**Comment by aweris** [comment] 2018-11-27 08:49
Same here worked to me after set RAM to 2048MB.
