### ISSUE TITLE
709.0.0 is broken under vagrant...

### ISSUE THREAD

**Issue by AntonioMeireles** [coreos/bugs#385] opened 2015-06-12 13:03 UTC
it just seems that coreos/coreos-overlay#1280 wasn't merged yet at the time when 709.0.0 was cut out. 

cf. pires/kubernetes-vagrant-coreos-cluster#123

**Comment by crawford** [comment] 2015-06-12 14:49
Duplicate of https://github.com/coreos/bugs/issues/382.

**Closed by crawford** 2015-06-12 14:49 UTC
