### ISSUE TITLE
CoreOS Azure VMs sometimes provision timeout

### ISSUE THREAD

**Issue by lizzha** [coreos/bugs#1178] opened 2016-03-23 01:41 UTC
The repro rate is around 5%. We found the waagent service is not started, and there're repeated logs in the output of journalctl

```
Mar 23 00:02:59 localhost.localdomain locksmithd[742]: [etcd.service etcd2.service] are inactive
Mar 23 00:02:59 localhost.localdomain locksmithd[742]: Unlocking old locks failed: [etcd.service etcd2.service] are inactive. Retrying in 5m0s.
Mar 23 00:03:09 localhost.localdomain systemd[1]: Started OpenSSH per-connection server daemon (23.102.211.134:1816).
Mar 23 00:03:09 localhost.localdomain sshd[15722]: Did not receive identification string from 23.102.211.134
Mar 23 00:04:00 localhost.localdomain systemd[1]: Starting Generate /run/coreos/motd...
Mar 23 00:04:00 localhost.localdomain systemd[1]: Started OpenSSH per-connection server daemon (23.102.211.134:1816).
Mar 23 00:04:00 localhost.localdomain systemd[1]: Started Generate /run/coreos/motd.
Mar 23 00:04:01 localhost.localdomain sshd[15727]: Did not receive identification string from 23.102.211.134
```

Please see the attached full console serial logs and journalctl logs.

[coreos-seriallog.txt](https://github.com/coreos/bugs/files/185272/coreos-seriallog.txt)
[coreos-journal.txt](https://github.com/coreos/bugs/files/185273/coreos-journal.txt)

**Comment by crawford** [comment] 2016-03-23 17:26
Jeez, that is a rough start:

```
Mar 22 10:07:23 localhost.localdomain systemd[1]: systemd-journald.service: Watchdog timeout (limit 1min)!
Mar 22 10:07:23 localhost.localdomain systemd[1]: Time has been changed
Mar 22 10:07:23 localhost.localdomain systemd[1]: update-engine.service: Start operation timed out. Terminating.
Mar 22 10:07:23 localhost.localdomain systemd[1]: Failed to start Update Engine.
Mar 22 10:07:23 localhost.localdomain systemd[1]: update-engine.service: Unit entered failed state.
Mar 22 10:07:23 localhost.localdomain systemd[1]: update-engine.service: Failed with result 'timeout'.
Mar 22 10:07:23 localhost.localdomain systemd[1]: Time has been changed
Mar 22 10:07:23 localhost.localdomain systemd[1]: Time has been changed
Mar 22 10:07:23 localhost.localdomain systemd[1]: Time has been changed
Mar 22 10:07:23 localhost.localdomain systemd[1]: locksmithd.service: Main process exited, code=exited, status=1/FAILURE
Mar 22 10:07:23 localhost.localdomain systemd[1]: locksmithd.service: Unit entered failed state.
Mar 22 10:07:23 localhost.localdomain systemd[1]: locksmithd.service: Failed with result 'exit-code'.
Mar 22 10:07:23 localhost.localdomain systemd[1]: Started Generate /run/coreos/motd.
Mar 22 10:07:23 localhost.localdomain systemd[1]: Starting Generate /run/coreos/motd...
Mar 22 10:07:23 localhost.localdomain systemd[1]: Started Generate /run/coreos/motd.
Mar 22 10:07:23 localhost.localdomain systemd[1]: systemd-journald.service: Main process exited, code=dumped, status=6/ABRT
Mar 22 10:07:23 localhost.localdomain systemd[1]: systemd-journald.service: Unit entered failed state.
Mar 22 10:07:23 localhost.localdomain systemd[1]: systemd-journald.service: Failed with result 'core-dump'.
Mar 22 10:07:23 localhost.localdomain systemd[1]: systemd-journald.service: Service has no hold-off time, scheduling restart.
Mar 22 10:07:23 localhost.localdomain systemd[1]: Stopped Flush Journal to Persistent Storage.
Mar 22 10:07:23 localhost.localdomain systemd[1]: Stopping Flush Journal to Persistent Storage...
Mar 22 10:07:23 localhost.localdomain systemd[1]: Stopped Journal Service.
Mar 22 10:07:23 localhost.localdomain systemd[1]: Starting Journal Service...
Mar 22 10:07:23 localhost.localdomain systemd[1]: Started Load cloud-config from /usr/share/oem/cloud-config.yml.
Mar 22 10:07:23 localhost.localdomain systemd[1]: Reached target Load system-provided cloud configs.
Mar 22 10:07:23 localhost.localdomain systemd[1]: Reached target Load user-provided cloud configs.
Mar 22 10:07:23 localhost.localdomain systemd[1]: Started Extend Filesystems.
Mar 22 10:07:23 localhost.localdomain systemd[1]: Started Generate sshd host keys.
Mar 22 10:07:23 localhost.localdomain systemd[1]: sshd@1-100.79.158.37:22-23.102.211.134:1664.service: Failed to run 'start' task: Transport endpoint is not connected
Mar 22 10:07:23 localhost.localdomain systemd[1]: Failed to start OpenSSH per-connection server daemon (23.102.211.134:1664).
Mar 22 10:07:23 localhost.localdomain systemd[1]: sshd@1-100.79.158.37:22-23.102.211.134:1664.service: Unit entered failed state.
Mar 22 10:07:23 localhost.localdomain systemd[1]: sshd@1-100.79.158.37:22-23.102.211.134:1664.service: Failed with result 'resources'.
```

There is something seriously wrong going on with the VM below the OS.

**Comment by crawford** [comment] 2016-03-24 23:21
It doesn't look like this was a first boot since I don't see `ignition`in the logs. I also see some disk failures in the log:

```
Mar 22 10:03:49 localhost systemd-fsck[370]: ROOT: Clearing orphaned inode 156 (uid=1002, gid=1002, mode=040755, size=4096)
Mar 22 10:03:49 localhost systemd-fsck[370]: ROOT: Clearing orphaned inode 171 (uid=0, gid=0, mode=040775, size=4096)
```

**Comment by lizzha** [comment] 2016-03-28 09:29
@crawford The previous logs are from a VM created from captured image, as we pre-added a user in the image for debugging purpose.
Here attaches the console log from a VM created from Gallery image, could you please have a look?

[90fd1c2a-1f5d-4ed2-93ba-ce744be67351.txt](https://github.com/coreos/bugs/files/191588/90fd1c2a-1f5d-4ed2-93ba-ce744be67351.txt)

**Comment by lizzha** [comment] 2016-03-30 06:34
Here's the console log from a normal VM, for comparison.

[e66b4924-6f53-42d1-ae99-320a43d365d1.txt](https://github.com/coreos/bugs/files/194937/e66b4924-6f53-42d1-ae99-320a43d365d1.txt)

There're following logs in the VM with issues, which is different with a normal VM
[   42.000072] systemd[1]: Starting Activation of LVM2 logical volumes...
[   42.087458] lvm[686]: No volume groups found
......
Starting Update Engine...
[   47.249415]          systemdStarting Generate sshd host keys...
[1]: Starting Generate sshd host keys...
         [   47.260819] Starting Login Service...systemd
[1]: Starting Login Service...
         Starting Generate /run/coreos/motd...[   47.658729] 
systemd[1]: Starting Generate /run/coreos/motd...
[   47.668585] systemd[1]: Started D-Bus System Message Bus.
[[32m  OK  [0m] Started D-Bus System Message Bus.
[   72.751091] systemd[1]: Failed to subscribe to NameOwnerChanged signal: Connection timed out
         Starting Load cloud-config from /usr/share/oem/cloud-config.yml...
         Starting Network Service...
         Starting Garbage Collection for rkt...
         Starting Install an ssh key from /proc/cmdline...
         Starting Extend Filesystems...
[[32m  OK  [0m] Started Serial Getty on ttyS0.
[[32m  OK  [0m] Started Getty on tty1.
[[32m  OK  [0m] Reached target Login Prompts.
[   73.256049] systemd[1]: Looping too fast. Throttling execution a little.
[   74.666035] systemd[1]: Looping too fast. Throttling execution a little.
[   76.161040] systemd[1]: Looping too fast. Throttling execution a little.
[   77.589042] systemd[1]: Looping too fast. Throttling execution a little.
[   79.192032] systemd[1]: Looping too fast. Throttling execution a little.
[   79.387598] systemd[1]: Failed to subscribe to NameOwnerChanged signal: Connection timed out
[   79.398429] systemd[1]: Failed to subscribe to NameOwnerChanged signal: Connection timed out
[   79.414493] systemd[1]: Failed to subscribe to NameOwnerChanged signal: Connection timed out
[   79.424278] systemd[1]: Failed to subscribe to NameOwnerChanged signal: Connection timed out
[   79.434411] systemd[1]: Failed to subscribe to NameOwnerChanged signal: Connection timed out
[   79.443667] systemd[1]: Failed to subscribe to NameOwnerChanged signal: Connection timed out
[   79.451586] systemd[1]: Failed to subscribe to activation signal: Connection timed out
[   79.462327] systemd[1]: Failed to register name: Connection timed out
[   79.470187] systemd[1]: Failed to set up API bus: Connection timed out

**Comment by crawford** [comment] 2016-04-27 20:33
This issue has been fixed in the latest Alpha (1029.0.0).

**Comment by LiliDeng** [comment] 2016-05-06 03:34
@crawford 
Validate against lateast Core OS (1032.1.0) in Microsoft Azure, hit one provision time out issue, seems also caused by systemd service? full log attached
system hung after systemd[1]: initrd-cleanup.service: Failed with result 'exit-code'. 

[andycored20503065311.txt](https://github.com/coreos/bugs/files/251506/andycored20503065311.txt)

**Comment by crawford** [comment] 2016-05-10 23:16
```
[  105.816166] systemd[1]: Timed out waiting for device dev-disk-by\x2dpartuuid-7130c94a\x2d213a\x2d4e5a\x2d8e26\x2d6cce9662f132.device.
```

It timed out waiting for the USR partition... I have never seen that.

**Comment by crawford** [comment] 2016-12-19 01:42
Closing due to inactivity.

**Closed by crawford** 2016-12-19 01:42 UTC
Labels: area/usability, component/other, kind/bug, priority/P1, team/os
