### ISSUE TITLE
df command hanging indefinitely

### ISSUE THREAD

**Issue by tylux** [coreos/bugs#2028] opened 2017-06-29 20:02 UTC
# Issue Report #

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.2.0
VERSION_ID=1409.2.0
BUILD_ID=2017-06-19-2321
PRETTY_NAME="Container Linux by CoreOS 1409.2.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

```
and
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.5.0
VERSION_ID=1409.5.0
BUILD_ID=2017-06-22-2222
PRETTY_NAME="Container Linux by CoreOS 1409.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

AWS EC2 running Kubernetes

### Expected Behavior ###
```
df -h
```
should return information

### Actual Behavior ###
df command hangs indefinitely, dmesg shows 

```SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)```

### Reproduction Steps ###

  1. Using locksmith cluster upgraded to latest stable 1409.2.0 and then 1409.5.0 
  2. Noticed df was hanging and saw the errors in dmesg

### Other Information ###

The same problem is happening on all 4 of my instances. They seem to be functioning other than df not working.

**Comment by euank** [comment] 2017-06-30 06:58
Can you check your systemd's logs (`journalctl -t systemd`) for messages related to automounts? I want to narrow down whether this is a duplicate of #1630

If you have messages like the following, then we can treat this as a dupe.

```
systemd[1]: proc-sys-fs-binfmt_misc.automount: Got automount request for /proc/sys/fs/binfmt_misc
systemd[1]: Mounting Arbitrary Executable File Formats File System...
systemd[1]: Mounted Arbitrary Executable File Formats File System.
systemd[1]: proc-sys-fs-binfmt_misc.automount: Got automount request for /proc/sys/fs/binfmt_misc
systemd[1]: proc-sys-fs-binfmt_misc.automount: Automount point already active?
```

(note: the order of `Mounted ...` then `Got automount request` afterwards).

**Comment by tylux** [comment] 2017-07-05 22:23
You are correct, this seems to be a duplicate of the latest comments on https://github.com/coreos/bugs/issues/1630. 

Feel free to close

**Closed** 2017-07-05 22:25 UTC
