### ISSUE TITLE
Race condition in sshd.socket / sshd.service

### ISSUE THREAD

**Issue by felixsanz** [coreos/bugs#1591] opened 2016-09-29 10:12 UTC
# Issue Report #1591

### CoreOS Version ###

1122.2.0

### Environment ###

vultr cloud provider

### Expected Behavior ###

Starting sshd.service

### Actual Behavior ###

By default, coreOS uses sshd.socket to start the daemon. I tried to switch to sshd.socket, but it doesn't work because of a race condition:

```
core@mercury ~ $ journalctl -u sshd.socket 
Sep 29 09:05:54 localhost systemd[1]: Listening on OpenSSH Server Socket.
Sep 29 09:05:58 mercury systemd[1]: Closed OpenSSH Server Socket.
```

```
core@mercury ~ $ journalctl -u sshd.service
Sep 29 09:05:58 mercury systemd[1]: Starting OpenSSH server daemon...
Sep 29 09:05:58 mercury systemd[1]: Started OpenSSH server daemon.
Sep 29 09:05:58 mercury sshd[915]: Bind to port 22 on 0.0.0.0 failed: Address already in use.
Sep 29 09:05:58 mercury sshd[915]: Bind to port 22 on :: failed: Address already in use.
Sep 29 09:05:58 mercury sshd[915]: Cannot bind any address.
Sep 29 09:05:58 mercury systemd[1]: sshd.service: Main process exited, code=exited, status=255/n/a
Sep 29 09:05:58 mercury systemd[1]: sshd.service: Unit entered failed state.
Sep 29 09:05:58 mercury systemd[1]: sshd.service: Failed with result 'exit-code'.
```

This happens on the same second so it doesn't work. If I start manually sshd.service later on, it works.

My cloud-config contains as follows:

```
  - name: sshd.socket
    command: stop

  - name: sshd.service
    command: start
```

**I also tried `mask: true` but the same thing happens.** Shouldn't this remove the option to start/stop the unit? Why is starting and stopping even when masked to /dev/null?

This could be fixed if coreOS serves sshd.service unit file with `Restart=always` or `Restart=on-failure`. My desktop machine (Arch Linux) contains `Restart=always`, so I don't know if we should have it here too. Or there is any reason to not have a restart directive here?

sshd is something that should be restarted! :dizzy_face: 

(Sure, i can add it myself by replacing the unit contents, but what if the default unit file contains changes in the future?)

**Comment by felixsanz** [comment] 2016-09-29 10:42
Also i noticed that here:

```
Sep 29 09:05:54 localhost systemd[1]: Listening on OpenSSH Server Socket.
Sep 29 09:05:58 mercury systemd[1]: Closed OpenSSH Server Socket.
```

The first is "localhost", so looks like sshd.socket is activated in initramfs and ignoring cloud-config masking option (what is the point of the mask option then?). And 4 seconds later, using rootfs, cloud-config masks the unit file and stop it.

But the masking happens too late!

**Comment by felixsanz** [comment] 2016-09-29 11:01
I fixed it with:

```
  - name: sshd.service
    drop-ins:
      - name: 10-conclicts_with_sshd_socket.conf
        content: |
          [Unit]
          Conflicts=sshd.socket
    command: start
```

But i'll leave this open in case someone wants to discuss about the restarting directive, masking not happening because of sshd.socket started before cloud-config acts, etc.

**Comment by crawford** [comment] 2016-09-30 16:01
> I also tried mask: true but the same thing happens. Shouldn't this remove the option to start/stop the unit? Why is starting and stopping even when masked to /dev/null?

This is because coreos-cloudinit is executing this config and doesn't pay attention to systemd semantics. It's basically its own init system.

> This could be fixed if coreOS serves sshd.service unit file with Restart=always or Restart=on-failure. My desktop machine (Arch Linux) contains Restart=always, so I don't know if we should have it here too. Or there is any reason to not have a restart directive here?

Since sshd is socket activated, restarting wouldn't do any good since it will have lost the connection for which it was spawned. Reconnecting to the server will cause an instance of sshd to exec and handle the new connection.

> The first is "localhost", so looks like sshd.socket is activated in initramfs and ignoring cloud-config masking option (what is the point of the mask option then?).

It's not being activated in the initramfs; very little actually runs there. What you are seeing is a race between DHCP (I assume that is where the hostname is coming from) and coreos-cloudinit. These operations are run before your machine knows its hostname, which is why you are seeing "localhost".

You're solution is perfectly valid. It's just converting it from a socket-activated service to a standard service. Another solution to your issue is to use [Ignition](https://coreos.com/ignition) to configure the system. Ignition runs long before sshd (in fact, it runs before systemd), so it is able to reconfigure everything properly. Ignition isn't currently supported on Vultr, but it should be trivial (famous last words) to add support. If you (or anyone else) is interested in working on this, the [EC2 provider](https://github.com/coreos/ignition/blob/c96715d99339669b646f35237428a44187341061/internal/providers/ec2/ec2.go) for Ignition is a good example.

**Comment by crawford** [comment] 2016-09-30 16:04
This is a duplicate of https://github.com/coreos/bugs/issues/426. Closing.

**Closed by crawford** 2016-09-30 16:04 UTC
Labels: area/usability, component/distro, kind/friction, team/os
