### ISSUE TITLE
Ignition: fails to retry fetching config

### ISSUE THREAD

**Issue by colhom** [coreos/bugs#1455] opened 2016-07-12 01:53 UTC
```sh
Jul 12 01:48:25 ignition ignition[603]: Ignition v0.7.0
Jul 12 01:48:25 ignition ignition[603]: parsed url from cmdline: "oem:///shim.json"
Jul 12 01:48:25 ignition ignition[603]: oem config not found in "/usr/share/oem", trying "/mnt/oem"
Jul 12 01:48:29 ignition ignition[603]: op(1): [started]  mounting "/dev/disk/by-label/OEM" at "/mnt/oem"
Jul 12 01:48:29 ignition ignition[603]: op(1): [finished] mounting "/dev/disk/by-label/OEM" at "/mnt/oem"
Jul 12 01:48:29 ignition ignition[603]: op(2): [started]  unmounting "/mnt/oem"
Jul 12 01:48:33 ignition ignition[603]: op(2): [finished] unmounting "/mnt/oem"
Jul 12 01:48:33 ignition ignition[603]: op(3): [started]  GET "http://147.7xx:8080/ignition?foo=bar"
Jul 12 01:48:33 ignition ignition[603]: op(3): [failed]   GET "http://147.7xx:8080/ignition?foo=bar": Get http://147.75.xx:8080/ignition?foo=bar: dial tcp 147.75.xxxx:8080: connect: network is unreachable
Jul 12 01:48:33 ignition ignition[603]: failed to fetch config: Get http://147.75.xxxx:8080/ignition?foo=bar: dial tcp 147.75.xx:8080: connect: network is unreachable
Jul 12 01:48:33 ignition ignition[603]: failed to acquire config: Get http://147.75.xxxxxx:8080/ignition?foo=bar: dial tcp 147.75.xx:8080: connect: network
```

\cc @crawford

**Comment by crawford** [comment] 2016-07-12 04:53
It's failing at [this line](https://github.com/coreos/ignition/blob/v0.7.0/internal/util/url.go#L51). This system is using the cmdline provider with an oem:// URL, so it succeeds immediately. Then when the config attempts to reference a remote config, it fails because the network isn't up yet. The logic around this doesn't retry because only the providers retry.

**Comment by vcaputo** [comment] 2016-07-18 20:15
Should the retry logic of providers and arbitrary remote fetches be unified then?

It looks like the configuration has been made recursive but the implementation isn't, otherwise the embedded remote configuration would naturally be handled uniformly.  Even if the configuration were fetched via providers recursively, there would still be the question of non-configuration remote assets and their retries.

@crawford mentioned when discussing this briefly irl that perhaps the provider retry logic should just be discarded altogether.  I'm unsure if that implied simply moving the retry logic to a wrapper around all remote asset retrievals, configuration or otherwise.

**Comment by colhom** [comment] 2016-07-18 21:29
@vcaputo IIRC the craw was referring to unifying the provider retry w/ the remote config logic. I believe the reason for the divergence was that the remote config stuff was written at a later date and has additional facilities in place for hash-based verification and maybe HTTPS?

@crawford: What is the motivation for allowing a remote config to be specified in the `coreos.config.url` kernel parameter, and not just locking it in to only refer to non-remote configs? 

It seems that the same end result as a remote `coreos.config.url` config could be achieved just as easily by placing a `shim.json` ignition config on the oem filesystem, pointing the kernel parameter at `oem://shim.json`, which will in turn point to the "actual" remote config? Then fetching the "root" config and fetching remote configs can remain separate processes and we don't have to knock down walls and mutilate the present architecture (which is quite nice).

This would have the immediate advantage of solving this network dependency problem.

In the more general sense, I see cryptographic verification of remote configs (hash, gpg, whatever) to be an integral part of the whole "remote config" functionality. We're (hopefully) not going to add more kernel parameters to allow verification of the config url passed via `coreos.config.url`, so I would say that the "root" config needs to be non-remote, special and implicitly trusted after the bios hands off to the bootloader.

**Comment by crawford** [comment] 2016-07-19 05:38
I think we should get rid of the provider retry logic and let each provider handle that on their own. If we make the network operations retry implicitly, that should cover most of the providers as well as this bug. The remaining providers (only Azure?) can retry on their own.

The reason the kernel parameter can be an HTTP URL is because all URLs are handled in one location. I don't see a good reason to limit the use here (and make them remember rules about when they can and can't use certain URL schemes). What your saying is valid and we should probably suggest it, but I don't think it makes the scenario you are concerned about invalid.

**Comment by colhom** [comment] 2016-07-19 22:00
Why would the Azure provider specifically not be covered by the blanket network retry logic?

**Comment by crawford** [comment] 2016-07-20 15:27
Because it doesn't use the network to read metadata. It comes from an attached DVD.

**Comment by MichaelAtPractiv** [comment] 2016-08-03 06:55
I got something very similar (failed to get user-data) when bootstrapping with kube-aws using stable on ec2 us-west-1 and us-west-2.

**Comment by crawford** [comment] 2016-08-03 15:17
That sounds like another issue. Can you provide the logs?

**Comment by colhom** [comment] 2016-08-03 18:02
@MichaelAtPractiv kube-aws still uses coreos-cloudinit to enact the user-data, though switching over to ignition is on the roadmap.

**Comment by MichaelAtPractiv** [comment] 2016-08-03 23:45
So I could not reproduce the scenario when the instance just never finished coming up and I did not keep the original logs or vms. However spinning up a new cluster which took while did log these errors.

To throw my [currently] ignorant 2c in, these error would be best avoided, if that is the normal behaviour that the network won't be up for a while to get the config has to be after several errors and retries.

Hope this is useful. I have the whole boot log but only this really seemed relevant to this ticket.

`journlctl -b | grep ignition`

> Aug 03 17:47:54 localhost ignition[242]: Ignition v0.6.0
> Aug 03 17:47:54 localhost ignition[242]: op(1): [started]  fetching config from "http://169.254.169.254/2009-04-04/user-data"
> Aug 03 17:47:54 localhost ignition[242]: op(1): op(2): [started]  GET "http://169.254.169.254/2009-04-04/user-data"
> Aug 03 17:47:54 localhost ignition[242]: op(1): op(2): [failed]   GET "http://169.254.169.254/2009-04-04/user-data": Get http://169.254.169.254/2009-04-04/user-data: dial tcp 169.254.169.254:80: connect: network is unreachable
> Aug 03 17:47:54 localhost ignition[242]: op(1): [failed]   fetching config from "http://169.254.169.254/2009-04-04/user-data": Get http://169.254.169.254/2009-04-04/user-data: dial tcp 169.254.169.254:80: connect: network is unreachable
> Aug 03 17:47:54 localhost ignition[242]: op(3): [started]  fetching config from "http://169.254.169.254/2009-04-04/user-data"
> Aug 03 17:47:54 localhost ignition[242]: op(3): op(4): [started]  GET "http://169.254.169.254/2009-04-04/user-data"
> Aug 03 17:47:54 localhost ignition[242]: op(3): op(4): [failed]   GET "http://169.254.169.254/2009-04-04/user-data": Get http://169.254.169.254/2009-04-04/user-data: dial tcp 169.254.169.254:80: connect: network is unreachable
> Aug 03 17:47:54 localhost ignition[242]: op(3): [failed]   fetching config from "http://169.254.169.254/2009-04-04/user-data": Get http://169.254.169.254/2009-04-04/user-data: dial tcp 169.254.169.254:80: connect: network is unreachable
> Aug 03 17:47:55 localhost ignition[242]: op(5): [started]  fetching config from "http://169.254.169.254/2009-04-04/user-data"
> Aug 03 17:47:55 localhost ignition[242]: op(5): op(6): [started]  GET "http://169.254.169.254/2009-04-04/user-data"
> Aug 03 17:47:55 localhost ignition[242]: op(5): op(6): [failed]   GET "http://169.254.169.254/2009-04-04/user-data": Get http://169.254.169.254/2009-04-04/user-data: dial tcp 169.254.169.254:80: connect: network is unreachable
> Aug 03 17:47:55 localhost ignition[242]: op(5): [failed]   fetching config from "http://169.254.169.254/2009-04-04/user-data": Get http://169.254.169.254/2009-04-04/user-data: dial tcp 169.254.169.254:80: connect: network is unreachable
> Aug 03 17:47:55 localhost ignition[242]: op(7): [started]  fetching config from "http://169.254.169.254/2009-04-04/user-data"
> Aug 03 17:47:55 localhost ignition[242]: op(7): op(8): [started]  GET "http://169.254.169.254/2009-04-04/user-data"
> Aug 03 17:47:55 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=ignition-disks comm="systemd" exe="/usr/lib64/systemd/systemd" hostname=? addr=? terminal=? res=success'
> Aug 03 17:47:55 localhost audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=ignition-disks comm="systemd" exe="/usr/lib64/systemd/systemd" hostname=? addr=? terminal=? res=success'
> Aug 03 17:47:55 localhost ignition[242]: op(7): op(8): GET result: OK
> Aug 03 17:47:55 localhost ignition[242]: op(7): op(8): [finished] GET "http://169.254.169.254/2009-04-04/user-data"
> Aug 03 17:47:55 localhost ignition[242]: op(7): [finished] fetching config from "http://169.254.169.254/2009-04-04/user-data"
> Aug 03 17:47:55 localhost ignition[242]: failed to fetch config: not a config (found coreos-cloudconfig)
> Aug 03 17:47:55 localhost ignition[242]: not a config (found coreos-cloudconfig): ignoring user-provided config
> Aug 03 17:47:58 localhost ignition[408]: Ignition v0.6.0
> Aug 03 17:47:58 localhost ignition[408]: op(1): [started]  fetching config from "http://169.254.169.254/2009-04-04/user-data"
> Aug 03 17:47:58 localhost ignition[408]: op(1): op(2): [started]  GET "http://169.254.169.254/2009-04-04/user-data"
> Aug 03 17:47:58 localhost kernel: audit: type=1130 audit(1470246478.918:23): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=ignition-files comm="systemd" exe="/usr/lib64/systemd/systemd" hostname=? addr=? terminal=? res=success'
> Aug 03 17:47:58 localhost kernel: audit: type=1131 audit(1470246478.918:24): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=ignition-files comm="systemd" exe="/usr/lib64/systemd/systemd" hostname=? addr=? terminal=? res=success'
> Aug 03 17:47:58 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=ignition-files comm="systemd" exe="/usr/lib64/systemd/systemd" hostname=? addr=? terminal=? res=success'
> Aug 03 17:47:58 localhost audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=ignition-files comm="systemd" exe="/usr/lib64/systemd/systemd" hostname=? addr=? terminal=? res=success'
> Aug 03 17:47:58 localhost ignition[408]: op(1): op(2): GET result: OK
> Aug 03 17:47:58 localhost ignition[408]: op(1): op(2): [finished] GET "http://169.254.169.254/2009-04-04/user-data"
> Aug 03 17:47:58 localhost ignition[408]: op(1): [finished] fetching config from "http://169.254.169.254/2009-04-04/user-data"
> Aug 03 17:47:58 localhost ignition[408]: failed to fetch config: not a config (found coreos-cloudconfig)
> Aug 03 17:47:58 localhost ignition[408]: not a config (found coreos-cloudconfig): ignoring user-provided config
> Aug 03 17:47:58 localhost ignition[408]: files: op(3): [started]  writing unit "coreos-metadata-sshkeys@.service"
> Aug 03 17:47:58 localhost systemd[1]: Reached target ignition.target.
> Aug 03 17:47:58 localhost ignition[408]: files: op(3): [finished] writing unit "coreos-metadata-sshkeys@.service"
> Aug 03 17:47:58 localhost ignition[408]: files: op(4): [started]  enabling unit "coreos-metadata-sshkeys@.service"
> Aug 03 17:47:58 localhost ignition[408]: files: op(4): [finished] enabling unit "coreos-metadata-sshkeys@.service"
> Aug 03 17:47:59 localhost systemd[1]: Stopped target ignition.target.`

**Comment by crawford** [comment] 2016-08-05 02:31
There actually aren't any real errors in that log. It takes a few tries before Ignition is able to fetch the config (expected - DHCP takes some time) and once it does, it correctly identifies the config as a cloud-config, so it ignores it.

**Comment by crawford** [comment] 2016-08-05 18:29
Fixed via https://github.com/coreos/ignition/pull/264.

**Closed by crawford** 2016-08-05 18:29 UTC
Labels: area/usability, component/ignition, kind/bug, priority/P1, team/os
