### ISSUE TITLE
Ignition fails to create more than one RAID device

### ISSUE THREAD

**Issue by dlaube** [coreos/bugs#1780] opened 2017-01-26 21:24 UTC
# Issue Report #

Upon executing ignition from the command line using the file OEM, it fails to create raid devices when more than one are specified.  Errors and example config provided below.

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS

./ignition -version
Ignition v0.12.1-40-gdab3efc-dirty
...
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

Packet.net baremetal

### Expected Behavior ###

The successful creation of two RAID1 arrays across 2 physical disks.

### Actual Behavior ###
Partitions are created successfully, but when more than one raid devices are specified in config.ign, no raid devices are created. 

```
root@dlaube-raidchk2:~/GIT/ignition/bin/amd64# fdisk -l /dev/sdc
Disk /dev/sdc: 447.1 GiB, 480103981056 bytes, 937703088 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 8E5C4EC6-F69C-483F-91E4-EB447D689A9B

Device     Start   End Sectors Size Type
/dev/sdc1   2048 22527   20480  10M Linux filesystem
/dev/sdc2  22528 43007   20480  10M Linux filesystem
root@dlaube-raidchk2:~/GIT/ignition/bin/amd64# fdisk -l /dev/sdd
Disk /dev/sdd: 447.1 GiB, 480103981056 bytes, 937703088 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: C421DE04-C526-44A4-B7FF-3754424F006D

Device     Start   End Sectors Size Type
/dev/sdd1   2048 22527   20480  10M Linux filesystem
/dev/sdd2  22528 43007   20480  10M Linux filesystem
```

### Reproduction Steps ###

  1. `vi config.ign`
  2. `./ignition -oem=file -root=/ -stage=disks ; journalctl -xea --no-pager -t ignition`

### Other Information ###

Errors reported by ignition -> http://pastebin.com/y1Bgdy3K
Example config.ign being used has been attached.
[config.ign.txt](https://github.com/coreos/bugs/files/733639/config.ign.txt)

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?

**Comment by vcaputo** [comment] 2017-01-31 23:46
Strange, maybe ignition should log a dump of `ls -lR /dev` in the case of device wait timeouts to aid in troubleshooting.  Nothing in particular stands out as obviously incorrect to me after a casual glance.

**Comment by crawford** [comment] 2017-02-03 00:40
The failure was due to a device timing out. That's odd because it looks like the rest of the devices showed up. My gut reaction is that it's a race with udev that causes us to miss the hotplug event.

**Comment by vcaputo** [comment] 2017-02-03 00:53
Except ignition leans on systemd device units rather than udev directly, and shouldn't be sensitive to such races.  The device units should exist if the partitions were created with those labels, and that should make the wait finish - regardless of the wait starting before or after the udev events fired for them.

I would be more suspicious of the relatively complicated golang machinery (go-systemd, godbus...) between Ignition and Systemd than anything else.  There was already a deadlock in waiting for multiple devices I fixed by making the notification channels buffered.

**Comment by dgonyeo** [comment] 2017-06-06 22:56
@dlaube I'm having issues reproducing this locally so I'm attempting to duplicate your setup on packet.net. Based on [this](https://help.packet.net/technical/storage/packet-block-storage-linux) it looks like after attaching storage via the website I need to run a magic script to attach the iscsi devices, but it's not clear to me how this is being done before Ignition runs. How are you getting the storage devices to appear so that Ignition can manipulate them?

**Comment by dgonyeo** [comment] 2017-06-08 19:32
@bgilbert informed me that what I need is a type 2 instance, as that comes with the necessary disks for this.

I tweaked the config slightly (the raid arrays were appearing under `/dev/md126` and `/dev/md127`, not `/dev/md125`): https://gist.github.com/dgonyeo/bff5aa9e55053672f81c5a5320517200

I've been unable to reproduce this after bringing up 16 CL alpha machines (1430.0.0) successfully with that config, so I'm going to assume that since February something in either Ignition or the OS changed that fixed the problem. If anyone sees this issue again, please reopen this!

**Closed by dgonyeo** 2017-06-08 19:32 UTC
Labels: area/usability, component/ignition, kind/bug, priority/P2, team/os
