### ISSUE TITLE
hostnamectl fails in coreos-1520.6.0

### ISSUE THREAD

**Issue by jeevarathinam-dhanapal** [coreos/bugs#2193] opened 2017-10-13 06:33 UTC
# Issue Report #

### Bug ###
Bug

### Container Linux Version ###
1520.6.0

### Environment ###

AWS

### Expected Behavior ###

Hostname is properly set

### Actual Behavior ###

"ip-10-1-1-154 jeeva # hostnamectl set-hostname k8s-worker-1507708889.ops1.srcclr.com
Could not set property: Failed to activate service 'org.freedesktop.hostname1': timed out"

systemd-hostname.service also failed.

logs --
"ct 13 04:24:14 ip-10-1-1-154.us-west-2.compute.internal systemd[1]: systemd-hostnamed.service: Main process exited, code=exited, status=226/NAMESPACE
Oct 13 04:24:14 ip-10-1-1-154.us-west-2.compute.internal systemd[1]: Failed to start Hostname Service.
Oct 13 04:24:14 ip-10-1-1-154.us-west-2.compute.internal systemd[1]: systemd-hostnamed.service: Unit entered failed state."

All the systemd files are updated on Oct12th

### Reproduction Steps ###

  1.  hostnamectl set-hostname <xyz>
  

### Other Information ###

 We are facing this only after recent update on systemd files.

**Comment by bgilbert** [comment] 2017-10-13 07:34
I'm unable to reproduce this.  Do you have any custom configuration (e.g. systemd drop-ins) for `systemd-hostnamed.service` or any other `systemd-*` services?

Possibly related: https://github.com/coreos/bugs/issues/2190 reports `systemd-resolved.service` failing with `status=226/NAMESPACE`.

**Comment by jeevarathinam-dhanapal** [comment] 2017-10-13 08:41
we have flanneld an docker wrapper in /etc/systemd/system. Im not sure if you are looking for this.
I also see **"status=226/NAMESPACE"**

"oem-cloudinit.service -> /etc/systemd/system/oem-cloudinit.service
lrwxrwxrwx. 1 root root 38 Oct 12 04:33 ansible-pull.timer -> /etc/systemd/system/ansible-pull.timer
lrwxrwxrwx. 1 root root 40 Oct 12 04:33 flanneld.service -> /usr/lib/systemd/system/flanneld.service
lrwxrwxrwx. 1 root root 34 Oct 12 04:33 docker.service -> /run/systemd/system/docker.service
lrwxrwxrwx. 1 root root 35 Oct 12 04:35 kubelet.service -> /etc/systemd/system/kubelet.service
**k8s-worker-1507782522 multi-user.target.wants** # pwd
/etc/systemd/system/multi-user.target.wants"

I have file "/var/lib/coreos-install/user_data" and its content 
"#cloud-config
hostname: k8s-worker-1507782522.ops1.srcclr.com
coreos:
  flannel:
    etcd_endpoints: htt"

**Comment by jeevarathinam-dhanapal** [comment] 2017-10-15 04:11
I tried creating drop-in(systemctl edit systemd-hostnamed.service --full) but the result is same. 

"Oct 15 04:00:27 ip-10-1-1-154.us-west-2.compute.internal systemd[1]: systemd-hostnamed.service: Unit entered failed state.
Oct 15 04:00:27 ip-10-1-1-154.us-west-2.compute.internal systemd[1]: systemd-hostnamed.service: Failed with result 'exit-code'.
Oct 15 04:00:27 ip-10-1-1-154.us-west-2.compute.internal systemd[1]: systemd-hostnamed.service: cgroup is empty"

**Comment by ajeddeloh** [comment] 2017-10-18 23:24
> I tried creating drop-in(systemctl edit systemd-hostnamed.service --full) but the result is same.

I assume you're talking about the drop mentioned in https://github.com/coreos/bugs/issues/2190. Can you give the output of `systemctl cat systemd-hostnamed.service` with the drop in applied?

Are you running on HVM or PV?

**Comment by jeevarathinam-dhanapal** [comment] 2017-10-19 00:27
systemd-hostname.service
`[Unit]
Description=Hostname Service
Documentation=man:systemd-hostnamed.service(8) man:hostname(5) man:machine-info(5)
Documentation=https://www.freedesktop.org/wiki/Software/systemd/hostnamed

[Service]
ExecStart=/usr/lib/systemd/systemd-hostnamed
BusName=org.freedesktop.hostname1
WatchdogSec=3min
CapabilityBoundingSet=CAP_SYS_ADMIN
PrivateTmp=yes
PrivateDevices=yes
PrivateNetwork=yes
ProtectSystem=strict
ProtectHome=yes
ProtectControlGroups=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
MemoryDenyWriteExecute=yes
RestrictRealtime=yes
RestrictNamespaces=yes
RestrictAddressFamilies=AF_UNIX
SystemCallFilter=~@clock @cpu-emulation @debug @keyring @module @mount @obsolete @raw-io @reboot @swap
SystemCallArchitectures=native
ReadWritePaths=/etc`

Cloud-config content
`#cloud-config
hostname: k8s-worker-1507708889.ops1.srcclr.com
coreos:
  flannel:
    etcd_endpoints: http://etcd-1.xxx.io:2379,http://etcd-2.xxx:2379,http://etcd-3.xxx.io:2379`

Our instances are HVM

**Comment by ajeddeloh** [comment] 2017-10-19 00:46
Can you try this drop in for `systemd-hostnamed.service` (or change it with `systemctl edit systemd-hostnamed.service --full`)
```
[Service]
ProtectSystem=full
```
Then run `systemctl daemon-reload` and verify the "ProtectSystem" line changed when you view it with `systemctl cat systemd-hostnamed.service` and see if that changes anything.

Also, I should have mentioned, for multi-line monospace blocks you need triple backticks on their own line before and after the block.

**Comment by jeevarathinam-dhanapal** [comment] 2017-10-19 00:55
That did the trick. Systemd-hostnamed.service works now. But only few nodes were affected and not all. There is no difference in the way nodes been brought up. Is there a way I can track what could have caused this

**Comment by ajeddeloh** [comment] 2017-10-19 17:36
Glad to hear that worked. The fact that only some fail to come up despite them all makes me think there might be a race somewhere. I wasn't able to reproduce it before, but it could be I just wasn't hitting it by chance, so I'll try reproducing it again. Have you experienced this on new nodes or just ones that were upgraded?

The error is almost certainly coming from [when systemd sets up the mount namespace](https://github.com/coreos/systemd/blob/v234-coreos/src/core/execute.c#L2626) for a new process, however it's not obvious why that is failing.

**Comment by parabolic** [comment] 2017-10-23 15:21
Same here I am getting this error:
```

**Comment by ajeddeloh** [comment] 2017-10-23 20:35
@parabolic are you seeing this across all nodes or just some?
What does `df -iT` show?

**Comment by parabolic** [comment] 2017-10-24 07:46
Hi @ajeddeloh,
I am seeing this only in newly created instances with the latest stable coreos. The rest are not updated and now I am afraid to update them :). I saw it every time I started the instance. Neither startup has passed without one of these services failing ( or both at the same time ):
 - systemd-resolved.service
 - systemd-hostnamed.service

Which led to subsequent failure of other service ( DNS doesn't work etc. etc. ).

Here's the output after setting the `LogLevel=Debug`
https://gist.github.com/parabolic/69f3fae95a4cd26a9cc56ad5071d8a8d

Output from `df -iT`
```sh
Filesystem                                Type       Inodes IUsed    IFree IUse% Mounted on
devtmpfs                                  devtmpfs   122848   300   122548    1% /dev
tmpfs                                     tmpfs      127281     1   127280    1% /dev/shm
tmpfs                                     tmpfs      127281   496   126785    1% /run
tmpfs                                     tmpfs      127281    16   127265    1% /sys/fs/cgroup
/dev/xvda9                                ext4     25474432 48283 25426149    1% /
/dev/mapper/usr                           ext4       260096 19603   240493    8% /usr
none                                      tmpfs      127281    26   127255    1% /run/torcx/unpack
/dev/xvda1                                vfat            0     0        0     - /boot
tmpfs                                     tmpfs      127281     1   127280    1% /media
tmpfs                                     tmpfs      127281    11   127270    1% /tmp
/dev/xvda6                                ext4        32768    13    32755    1% /usr/share/oem
<efs_endpoint>:/                          nfs4            0     0        0     - /mnt/efs
tmpfs                                     tmpfs      127281     5   127276    1% /run/user/500
```

Hope this helps!
Cheers.

**Comment by ajeddeloh** [comment] 2017-10-24 18:28
@parabolic Thanks for the logs. Can you run `strace -f -p 1 -s500` and trigger the issue?

**Comment by parabolic** [comment] 2017-10-30 16:20
Hi @ajeddeloh and sorry for not replying earlier but I got sick and couldn't. I am not sure I'll be able to provide the output from the command because of a tight schedule that I am running on at the moment. I'll try to simulate the problem with spinning a coreos stable instance and passing basic user data.
Cheers!

**Comment by ajeddeloh** [comment] 2017-11-15 23:20
@parabolic have you had a chance to look at this again?

**Comment by parabolic** [comment] 2017-11-16 08:05
Hi @ajeddeloh, unfortunatelly no I haven't. I got dragged into something else. 
Today or tomorrow I'll  build a new cluster with CoreOS and I'll try it without the dropins and will provide you with an `strace`.
Thank you for your patience

**Comment by parabolic** [comment] 2017-11-16 15:13
Hi @ajeddeloh, 
unfortunately the issue still persists in the latest stable CoreOS version:
```

here's the gist with the output you've requested
https://gist.github.com/parabolic/e864d38fe963cc5e58e566075187d3b3

**Comment by parabolic** [comment] 2017-11-16 15:39
Just FYI, the dropins work just fine with 
```
CoreOS stable (1520.8.0)
```
Cheers.

**Comment by parabolic** [comment] 2017-11-16 15:59
Hi, we've been testing this issue with a friend and we found out that if you run an instance c5 instance everything works as expected and no droping are required.
 In my case the dropins are required for a t2.small instance.

**Comment by ajeddeloh** [comment] 2017-11-16 20:44
Thanks again for the logs. I'm looking into to it and will relay the info upstream as well.

**Comment by euank** [comment] 2017-11-16 22:09
@ajeddeloh even if we aren't sure exactly what's happening, it seems like we have enough evidence to switch over to `ProtectSystem=full` for now, right?

It seems like a low-risk enough change to backport that to the beta+stable branches to be picked up the next time they release.

**Comment by ajeddeloh** [comment] 2017-11-16 22:12
SGTM, then we'll switch back once it's resolved upstream?

**Comment by ajeddeloh** [comment] 2017-11-21 18:51
Relaying from the upstream bug: it turns out its a kernel bug with the `name_to_handle_at` syscall and probably nfs. They're fixing it upstream to work around the bug and we're reverting the `ProtectSystem=strict` change until then.

@parabolic sorry to keep bothering you for more details. Can you share anything about how your nfs is configured?

@jeevarathinam-dhanapal are you also running nfs?

**Comment by parabolic** [comment] 2017-11-21 19:18
Hi @ajeddeloh,
I am glad that a bug has been found.
To answer your question yes we use nfs. Here's the configuration:
```
write-files:
  - path: /etc/conf.d/nfs
    permissions: '0644'
    content: |
      OPTS_RPC_MOUNTD=""
    - name: rpc-statd.service
      command: start
      enable: true
....
....
.....
    - name: mnt-efs.mount
      command: start
      enable: true
      content: |
        [Unit]
        Description=Mount the efs.
        [Mount]
        What=efs_on.amazonaws.com:
        Where=/mnt/efs
        Type=nfs
        DirectoryMode=775
 
```
Hope this helps.
Cheers.

**Comment by bgilbert** [comment] 2017-11-30 05:20
We're reverting to `ProtectSystem=full` pending a complete fix in upstream systemd. This should avoid the problem starting in alpha 1590.1.0, beta 1576.3.0, and stable 1520.9.0, which are due shortly.  I'll leave this open until we can replace this workaround with a long-term fix.

**Comment by parabolic** [comment] 2017-11-30 08:29
@bgilbert thanks for the update!
Cheers.

**Comment by ajeddeloh** [comment] 2017-12-06 20:19
There's a [kernel patch](https://patchwork.kernel.org/patch/10085647/) to fix the underlying issue as well as a bunch of systemd commits that work around the kernel bug. We will continue the `ProtectSystem=strict` reversion until the kernel patch is accepted by an upstream maintainer at which point we will backport it. We will then switch `ProtectSystem` back to `strict`. Once systemd 236 is released and makes its way into our branches, we will stop backporting the patch. We'll keep this bug open until the kernel patch is backported.

**Comment by ajeddeloh** [comment] 2018-01-23 22:51
Closed via https://github.com/coreos/coreos-overlay/pull/2967 which is in Alpha 1662.0.0.

**Closed by ajeddeloh** 2018-01-23 22:51 UTC
Labels: area/usability, component/systemd, kind/regression, platform/aws, team/os
