### ISSUE TITLE
Feature request: Enable CONFIG_CEPH_LIB_USE_DNS_RESOLVER and CONFIG_CEPH_FS_POSIX_ACL

### ISSUE THREAD

**Issue by kayrus** [coreos/bugs#1519] opened 2016-08-15 09:30 UTC
## Feature Request ##

Enable CONFIG_CEPH_LIB_USE_DNS_RESOLVER and CONFIG_CEPH_FS_POSIX_ACL

"CONFIG_CEPH_LIB_USE_DNS_RESOLVER" option is useful for CEPH deployments which use DNS names for monitors.

### Other Information ###

As an example here are the options which current Ubuntu uses (but they are not in CoreOS):

```sh
cat config-4.4.0-34-generic | 
CONFIG_CEPH_LIB=m
# CONFIG_CEPH_LIB_PRETTYDEBUG is not set
CONFIG_CEPH_LIB_USE_DNS_RESOLVER=y #<<<<<<<
CONFIG_CEPH_FS=m
CONFIG_CEPH_FSCACHE=y
CONFIG_CEPH_FS_POSIX_ACL=y #<<<<<<<
```

**Comment by mjg59** [comment] 2016-08-15 17:14
Partial duplicate of https://github.com/coreos/bugs/issues/1500

**Closed by mjg59** 2016-08-15 17:14 UTC
