### ISSUE TITLE
CT should use new passwd.users semantics

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1967] opened 2017-05-16 18:03 UTC
# Issue Report #

### Desired Feature ###

Ignition recently deprecated the "create" object from `passwd.users`. CT should use these semantics as well.

**Comment by dgonyeo** [comment] 2017-05-18 17:33
Do we want to wait for ignition to rubber stamp the v2.1.0 spec, or is it ok for ct to be generating 2.1.0-experimental configs?

**Comment by crawford** [comment] 2017-05-18 18:04
We have to wait for the v2.1.0 spec. Official tooling should not be relying on experimental behavior which is subject to change.

**Comment by ajeddeloh** [comment] 2017-09-26 00:03
Closed via https://github.com/coreos/container-linux-config-transpiler/pull/106

**Comment by crawford** [comment] 2017-09-26 00:10
Is this reflected in the CT config? I forget if the fields changed.

**Comment by ajeddeloh** [comment] 2017-09-26 00:13
Yes, see https://github.com/coreos/container-linux-config-transpiler/blob/master/doc/configuration.md
The fields are the same as the Ignition 2.1.0 ones

**Comment by crawford** [comment] 2017-09-26 00:16
The wording still says "added".

**Comment by ajeddeloh** [comment] 2017-09-26 00:24
Are you referring to the "add in all the new fields available in the 2.1.0 spec"? It's using the 2.1.0 types under the hood, and since the Ignition and CT config trees are the same for `passwd` it picks up the deprecation notices from Ignition automatically (just tested and confirmed this too)

**Comment by crawford** [comment] 2017-09-26 18:00
> users (list of objects): the list of accounts to be added.

**Comment by ajeddeloh** [comment] 2017-09-26 18:10
Oh, womp. Looks like that got missed in https://github.com/coreos/container-linux-config-transpiler/commit/a9055b8c10c48da08747be7abe5e5441cd6987d1. It's just in the docs. I'll reopen this and open a PR to fix it.

**Closed** 2017-10-04 21:16 UTC
Labels: area/usability, component/ct, kind/cleanup, priority/P1, team/tools
