### ISSUE TITLE
dev/mapper/usr is at 85% space used

### ISSUE THREAD

**Issue by scottdhowell3** [coreos/bugs#2573] opened 2019-03-28 21:46 UTC
# Issue Report #

## Bug ##
Not able increase partition size of /dev/mapper/usr. Our current nodes are reporting in at 85% being used. We would like to be able to modify the size of this partition.
### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2093.0.0
VERSION_ID=2093.0.0
BUILD_ID=2019-03-25-1621
PRETTY_NAME="Container Linux by CoreOS 2093.0.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

AWS t3.medium

### Expected Behavior ###

Able to modify partition to increase the size of the dev/mapper/usr when increasing the size of block device associated with the node

### Actual Behavior ###

Only ROOT partition is increased

**Comment by ajeddeloh** [comment] 2019-03-28 21:51
USR is read only and changing that is not supported. It is only controlled by updates, which we validate first. You don't need to worry about running out of space there

Closing this as "working as intended" but feel free to ask any questions about that if you have any.

**Closed by ajeddeloh** 2019-03-28 21:51 UTC

**Comment by scottdhowell3** [comment] 2019-03-29 14:21
A little more information about what we are seeing. When we updated coreos (alpha-channel) this week, an alert fired from the [prometheus-operator](https://github.com/coreos/prometheus-operator). This alert fired because the coreos update sent the size of the the /dev/mapper/usr directory above 85% along with the alert expression believing it would be a linear increase in size of this directory.

While this alert was noise in our slack channel with our staging and production environments this alert could fire for up to 72 hours. For others using the coreos/prometheus-operator this timeline could go well past 72 hours of this alert firing causing noise around legitimate alerts. We are just trying to understand what could be done to alleviate noise with alerts with fixing the expansion of this directory.

**Comment by ajeddeloh** [comment] 2019-03-29 17:18
Sounds like this is something we might be able to fix in the Prometheus operator. I'll follow up with them and see if we can exclude /usr. Not sure how much Prometheus knows about what OS it's running on, but that's definitely the place to fix it. There's not much we can do OS side about it.
