### ISSUE TITLE
Ignition 0.2.4 reads config from first disk with a partition labeled "OEM", not the boot disk

### ISSUE THREAD

**Issue by SpencerBrown** [coreos/bugs#1043] opened 2015-12-17 16:58 UTC
and that may not actually be the disk we booted from.

this is not hypothetical, this actually happened to me. I had written CoreOS to `/dev/sda` using `coreos-install` and my updates to install an Ignition JSON config file, with stuff in the config to wipe and repartition `/dev/sdb`. 

Then I decided to switch it up and install CoreOS on `/dev/sdb`, and use Ignition to wipe/repartition `/dev/sda`. Ignition picked up the old JSON config from `/dev/sda` and used that, nuking my newly created `/dev/sdb` boot drive.

**Comment by crawford** [comment] 2015-12-17 18:49
There is not much we can do in this case. In order to mount the correct partition, we need to know the label, which means we will always look for the same label. If there are two CoreOS installations on the same box, we will end up with two of each partition, sharing the labels. It's very difficult to try to guess what the user has intended (and it's arguably incorrect to guess in the first place).

**Comment by crawford** [comment] 2016-01-12 16:45
I'm going to close this since there really isn't anything that can be done.

**Closed by crawford** 2016-01-12 16:45 UTC
Labels: component/distro, kind/design, kind/question, team/os
