### ISSUE TITLE
AWS c5 instance fails to connect to metadata service

### ISSUE THREAD

**Issue by jtwile2** [coreos/bugs#2331] opened 2018-01-26 16:40 UTC
### Container Linux Version ###

```ini
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1576.5.0
VERSION_ID=1576.5.0
BUILD_ID=2018-01-05-1121
PRETTY_NAME="Container Linux by CoreOS 1576.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###
AWS c5.xlarge

These instances are started as an Atlassian Bamboo Elastic Agent

### Expected Behavior ###
EC2 instance starts with expected SSH keys and is accessible.

### Actual Behavior ###
SSH keys are not installed and the instance is not accessible.

### Reproduction Steps ###
This is an intermittent failure, only around 1 in 20 of created instances experience this failure.

### Other Information ###
This started when we upgraded to 1576.5.0.  I noticed there is a bugfix for this release on this systemd unit: #2283

Relavent logs from the journal:
```
Jan 26 14:51:00 ip-10-201-15-67 coreos-metadata[641]: Error: fetching metadata from provider
Jan 26 14:51:00 ip-10-201-15-67 coreos-metadata[641]: Caused by: timed out
Jan 26 14:51:00 ip-10-201-15-67 coreos-metadata[641]: Caused by: failed to fetch
Jan 26 14:51:00 ip-10-201-15-67 coreos-metadata[641]: Caused by: http://169.254.169.254/2009-04-04/meta-data/instance-id: Connection timed out (os error 110)
Jan 26 14:51:00 ip-10-201-15-67 systemd[1]: coreos-metadata-sshkeys@core.service: Main process exited, code=exited, status=1/FAILURE
Jan 26 14:51:00 ip-10-201-15-67 systemd[1]: coreos-metadata-sshkeys@core.service: Unit entered failed state.
Jan 26 14:51:00 ip-10-201-15-67 systemd[1]: coreos-metadata-sshkeys@core.service: Failed with result 'exit-code'.
```

**Comment by crawford** [comment] 2018-01-26 18:38
Can you attach the full logs for that service? (`journalctl -b -u coreos-metadata --no-pager`)

**Comment by jtwile2** [comment] 2018-01-26 20:36
The coreos-metadata unit didn't report anything in journal so I'm attaching the full boot log from that boot.
[journal.log](https://github.com/coreos/bugs/files/1669107/journal.log)

**Comment by sdemos** [comment] 2018-01-26 22:28
That's interesting, there is acutally an earlier failure in there. `coreos-cloudinit` fails first - 

```Jan 26 14:33:04 ip-10-201-15-67.redacted.devops coreos-cloudinit[643]: 2018/01/26 14:33:04 Checking availability of "ec2-metadata-service"                                                                                                                                                                                     
Jan 26 14:33:04 ip-10-201-15-67.redacted.devops coreos-cloudinit[643]: 2018/01/26 14:33:04 Checking availability of "cloud-drive"                                                                                                                                                                                              
Jan 26 14:33:34 ip-10-201-15-67.redacted.devops coreos-cloudinit[643]: 2018/01/26 14:33:34 Checking availability of "cloud-drive"                                                                                                                                                                                              
Jan 26 14:33:43 ip-10-201-15-67.redacted.devops coreos-cloudinit[643]: 2018/01/26 14:33:43 No datasources available in time                                                                                                                                                                                                    
Jan 26 14:33:43 ip-10-201-15-67.redacted.devops systemd[1]: oem-cloudinit.service: Main process exited, code=exited, status=1/FAILURE                                                                                                                                                                                          
Jan 26 14:33:43 ip-10-201-15-67.redacted.devops systemd[1]: Failed to start Cloudinit from EC2 metadata.                                                                                                                                                                                                                       
Jan 26 14:33:43 ip-10-201-15-67.redacted.devops systemd[1]: oem-cloudinit.service: Unit entered failed state.                                                                                                                                                                                                                  
Jan 26 14:33:43 ip-10-201-15-67.redacted.devops systemd[1]: oem-cloudinit.service: Failed with result 'exit-code'.
```

then the reported `coreos-metadata` failure - 

```
Jan 26 14:51:00 ip-10-201-15-67.redacted.devops coreos-metadata[641]: Error: fetching metadata from provider
Jan 26 14:51:00 ip-10-201-15-67.redacted.devops coreos-metadata[641]: Caused by: timed out
Jan 26 14:51:00 ip-10-201-15-67.redacted.devops coreos-metadata[641]: Caused by: failed to fetch
Jan 26 14:51:00 ip-10-201-15-67.redacted.devops coreos-metadata[641]: Caused by: http://169.254.169.254/2009-04-04/meta-data/instance-id: Connection timed out (os error 110)
Jan 26 14:51:00 ip-10-201-15-67.redacted.devops systemd[1]: coreos-metadata-sshkeys@core.service: Main process exited, code=exited, status=1/FAILURE
```

it seems like they are both having issues connecting to the metadata service.

**Comment by crawford** [comment] 2018-01-26 22:40
On first boot, Container Linux will DHCP _twice_. I wonder if that is tripping up their new C5 instances. At this point, my gut tells me this is just another one of the many problems with the new C5 instances.

@jtwile2 it might be worth moving to a different instance type for now (if possible).

**Comment by jtwile2** [comment] 2018-01-26 22:48
Thank you for the quick response, I'll look into moving instance types, in the meantime is there anything else I can do to get more data for you?

**Comment by crawford** [comment] 2018-01-26 22:49
@jtwile2 I don't think so. This is the same sort of failure our CI systems have been seeing (and only seeing with C5).

**Comment by jtwile2** [comment] 2018-01-26 22:57
Thanks @crawford  I'll close, and reopen if we see a similar issue on C4.

**Comment by arithx** [comment] 2018-01-26 23:33
Going to re-open this issue so we can continue monitoring

**Comment by arithx** [comment] 2018-01-29 22:37
@jtwile2 can you provide the userdata you're using to configure the machines where you were seeing this issue?

So far I haven't been able to repro this issue.

**Comment by euank** [comment] 2018-01-29 22:40
It's also possible that this was an issue on AWS's side which has since been fixed on their end. If you can still reliably reproduce it, any more information would be appreciated, but if you can't, I'd be happy to chalk it up to being on AWS's end.

**Comment by jtwile2** [comment] 2018-01-30 20:57
[user-data.txt](https://github.com/coreos/bugs/files/1679317/user-data.txt)

These are Atlassian Bamboo Elastic Instances so the user data is used by Bamboo.  I'm not able to get the user data from an instance that failed, but the attached file is typical of what a coreos instance would have.  Note that this is a binary file, not a text file.

I've seen it a few more times, but not often enough to be a blocker so I'm ignoring this and letting the agents that don't come up be destroyed automatically.  I also presume it is an issue with AWS and the new C5 types.

**Comment by bclodius** [comment] 2018-02-07 14:47
@jtwile2 unrelated to coreos...our organization has noticed inconsistencies in general with c5 instance type as well regarding connectivity.  We find about 60% of the time no connectivity issues with other objects in the same VPC.  When we revert to c4 type we don't face any issues.

**Comment by samlin86** [comment] 2018-02-07 17:24
I've been following this issue for a few days now for an unrelated issue with our c5 instance as well - related to DNS queries failing. We've reached out to AWS support and after 2 months they got back to us after some investigation noting that the new c5 instances have eliminated DNS query retries that are done internally within the network for c5 instances. I do not believe they are going to fix this as they recommended us to go back to c4 instances. This is adding to what @bclodius has noted above too. Hopefully that helps.

**Comment by euank** [comment] 2018-02-07 19:37
`coreos-metadata` retries [10 times](https://github.com/coreos/coreos-metadata/blob/e28473eb9def6a9b3862a4d28549fc92be45fe59/src/retry/mod.rs#L34-L38) for fetching the instance-id (over the course of around 40 seconds of sleeping + fetch time, in this case timeout-time).

In the journal posted, there's a large delay before coreos-metadata fails, which makes it seem like coreos-metadata timed out 10 times in a row for that request.

Note as well that this can't be a dns query issue since it's directly requesting `169.254.169.254`, for which no dns resolution needs to be done.

It's also not that the network is entirely down because docker + update_engine, in that log, do succeed at making http requests.

Based on that log, it really looks like the instance-metadata service is just hosed for those instances. We're already retrying more than enough, so I don't see anything on our end we can do.
Contacting AWS support may be the best course of action to get this fixed or get more information on it.

Since I don't think there's anything for us to do on our end, I'm closing this issue.
Please re-open or file a new one if there's any evidence this issue isn't entirely on AWS's end or if you think we may be able to work around it somehow.

**Closed by euank** 2018-02-07 19:37 UTC
Labels: component/coreos-metadata, needs/more-information, platform/aws, team/tools
