### ISSUE TITLE
fleetctl reports incorrect status

### ISSUE THREAD

**Issue by mxpv** [coreos/bugs#389] opened 2015-06-16 12:17 UTC
I'm getting strange status from fleetctl
```
core@podsync ~ $ fleetctl status redis
● \x22redis.service\x22.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

I'm using clean CoreOS 681.0.0 (stable) from DigitalOcean

Here is some information from my environment:
```
core@host ~ $ fleetctl list-unit-files
UNIT            HASH    DSTATE          STATE           TARGET
redis.service   d1b59be launched        launched        4eeae511.../10.133.159.240

core@host  ~ $ fleetctl list-units
UNIT            MACHINE                         ACTIVE  SUB
redis.service   4eeae511.../10.133.159.240      active  running

core@host ~ $ systemctl status redis
● redis.service - Redis server
   Loaded: loaded (/run/fleet/units/redis.service; linked-runtime; vendor preset: disabled)
   Active: active (running) since Tue 2015-06-16 12:01:16 ; 10min ago
  Process: 1717 ExecStartPost=/usr/bin/etcdctl set /host/systemd/%H/%n running (code=exited, status=0/SUCCESS)
  Process: 1692 ExecStartPre=/usr/bin/docker pull redis (code=exited, status=0/SUCCESS)
  Process: 1686 ExecStartPre=/usr/bin/docker kill redis (code=exited, status=1/FAILURE)
 Main PID: 1716 (docker)
   Memory: 1.4M
   CGroup: /system.slice/redis.service
           └─1716 /usr/bin/docker run --rm --name redis -v /data/redis:/data redis redis-server --appendonly yes

Jun 16 12:01:16 podsync docker[1716]: 1:M 16 Jun 12:01:16.540 * The server is now ready to accept connections on port 6379
Jun 16 12:02:20 podsync docker[1716]: 1:M 16 Jun 12:02:20.627 * Background AOF rewrite finished successfully

```

**Comment by jonboulle** [comment] 2015-06-16 17:50
coreos/fleet#1252

**Comment by djmaze** [comment] 2015-06-17 16:57
I am wondering why this would make it into the stable version at all. A bug in an oft-used feature like this should have hit many people running fleet 0.10 in alpha and beta already, right?

**Comment by crawford** [comment] 2015-06-17 18:19
I'm actually having trouble reproducing this...

```sh
$ cat redis.service
[Service]
ExecStart=/usr/bin/sleep 1000000
```

```sh
$ fleetctl submit redis.service
```

```sh
$ fleetctl start redis
Unit redis.service launched on 47f62231.../45.55.83.102
```

```sh
$ fleetctl status redis
● redis.service
   Loaded: loaded (/run/fleet/units/redis.service; linked-runtime; vendor preset: disabled)
   Active: active (running) since Wed 2015-06-17 18:15:29 ; 7s ago
 Main PID: 715 (sleep)
   Memory: 120.0K
   CGroup: /system.slice/redis.service
           └─715 /usr/bin/sleep 1000000

Jun 17 18:15:29 crawford-test-2 systemd[1]: Started redis.service.
Jun 17 18:15:29 crawford-test-2 systemd[1]: Starting redis.service...
```

```sh
$ grep VERSION_ID /etc/os-release 
VERSION_ID=681.0.0
```

**Comment by crawford** [comment] 2015-06-17 20:52
This appears to be a duplicate of https://github.com/coreos/fleet/issues/1208.

**Closed by crawford** 2015-06-17 20:52 UTC
Labels: fleet
