### ISSUE TITLE
Blank [Match] value in networkd config file causes all interfaces to use the same config resulting in constant ARP requests

### ISSUE THREAD

**Issue by soggiest** [coreos/bugs#2015] opened 2017-06-21 22:57 UTC
## Bug ##
If the /etc/systemd/network/*.network file contains an empty match value all interfaces on the host will pick up the config and use it. For example:
A networkd config of:
[Match]
Name=
[Network]
DNS=10.10.10.10
Address=10.10.10.2
Gateway=10.10.10.1

Will result in all interfaces trying to use the IP address 10.10.10.2.  When this occurs will begin responding positively to all ARP requests in its subnet, causing IP conflict issues on that subnet. 

This appears consistent with proxy ARP, however we've found the Kernel is not configured for proxy ARP:
<img width="799" alt="screen shot 2017-06-21 at 2 22 44 pm" src="https://user-images.githubusercontent.com/6342806/27409817-43d7bfe8-5698-11e7-8c6e-e5fd773b7c82.png">

This is similar to:
https://github.com/coreos/bugs/issues/1005

### Container Linux Version ###
1353.8.0

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
VMWare

### Expected Behavior ###

When a network config has a single MATCH condition and that condition is blank the config file should be disregarded.

### Actual Behavior ###

A network config file has a single MATCH condition that is blank which is then applied to all interfaces.

### Reproduction Steps ###

1. On a Container Linux host create a networkd config file in `/etc/systemd/network/` based on the config above. This should be the only networkd config file present.
2. Restart networkd: `systemctl restart networkd`
3. Verify all interfaces on the machine are using the network configuration file/IP address: `networkctl list --no-legend | awk '{print $2}' | xargs networkctl status`

We observed the Container Linux host responding to all ARP requests by running a traffic sniffer (wireshark in this case) and configuring a separate host to use a distinct IP address. The wire sniffer found the mac address belonging to the Container Linux host responded that it contained the IP address the second host was attempting to use.

**Comment by lucab** [comment] 2017-06-22 10:10
Can you please check systemd-networkd logs to see if it mentions "Interface name is not valid or too long, ignoring"? In any case, it looks like this is probably a duplicate of https://github.com/systemd/systemd/issues/4454.

I'm inclined to close this here, as the wrong behavior should be either fixed or better documented in upstream systemd.

**Comment by lucab** [comment] 2017-06-23 08:59
Closing in favor of the upstream ticket.

**Closed by lucab** 2017-06-23 08:59 UTC
Labels: area/usability, component/systemd, kind/bug, team/tools
