### ISSUE TITLE
kernel command line option `rd.auto=1` should probably be default

### ISSUE THREAD

**Issue by dgonyeo** [coreos/bugs#2099] opened 2017-08-10 21:52 UTC
Right now the only way to have a raid array auto-assembled on boot is by appending the line `set linux_append="rd.auto"` to `/usr/share/oem/grub.cfg`, which users shouldn't have to touch.

This is the documentation on the setting, as per the `dracut.cmdline` man page:

> enable autoassembly of special devices like cryptoLUKS, dmraid, mdraid or lvm.

This option should probably be set by default in CL, otherwise raid arrays won't come online after a reboot (on first boot they're assembled by Ignition).

**Comment by bgilbert** [comment] 2017-08-16 01:31
`rd.auto` affects several types of virtual devices, is subject to races with device enumeration, and will not respect configuration such as an `/etc/mdadm.conf` in the rootfs for devices it assembles, so it's not an ideal choice.  CL has udev rules in `/usr` which assemble RAID arrays, thus the problem is really just assembling the root RAID(s).

We would like to have bootengine assemble only those arrays necessary for the root disk; this can be done in a race-free way from udev rules using appropriate filters.  The plausible filters are a well-defined MD UUID (not great) or a well-defined RAID name or name prefix or name suffix.  The current goal is to use a name-based filter.  A similar mechanism could later be used for LVM, LUKS, etc.

**Comment by ajeddeloh** [comment] 2017-08-23 22:28
Closed via https://github.com/coreos/bootengine/pull/130

**Closed by ajeddeloh** 2017-08-23 22:28 UTC
Labels: area/usability, component/distro, kind/enhancement, team/os
