### ISSUE TITLE
Feature: apply channel tags to AMIs for programatic updates

### ISSUE THREAD

**Issue by lattwood** [coreos/bugs#1511] opened 2016-08-10 14:39 UTC
# Issue Report
### Environment

AWS + Terraform
### Desired Feature

Tags on the AMIs containing channel information- stable/beta/alpha
### Other Information

This allows the use of an AWS describe-images call like this: `aws ec2 describe-images --owners 595879546273 --filters Name=virtualization-type,Values=hvm Name=tag-key,Values=channel Name=tag-value,Values=beta` and it allows the use of https://www.terraform.io/docs/providers/aws/d/ami.html to select the correct AMI in launch configurations.

**Comment by jimmycuadra** [comment] 2016-12-01 01:11
Terraform is a new use case, but otherwise this is a dupe of #111.

**Comment by crawford** [comment] 2016-12-18 23:17
Closing as a dup of https://github.com/coreos/bugs/issues/111 (thanks @jimmycuadra).

**Closed by crawford** 2016-12-18 23:17 UTC
Labels: area/distribution, component/distro, kind/enhancement, low hanging fruit, priority/Pmaybe, team/os
