### ISSUE TITLE
ignition source should support AWS S3 buckets

### ISSUE THREAD

**Issue by signull** [coreos/bugs#1818] opened 2017-02-20 20:09 UTC
## Feature Request ##

Currently setting a source looks something like this: `"source": "http://example.com/config.json",`
I would love to be able to use AWS Instance Roles to give new instances access to view an otherwise restricted s3 bucket and use a source like this: `"source": "s3://example-bucket/config.json",`

Since we are now able to use external data sources, it would be nice to secure those data sources so only in network machines could view the material. Using AWS's roles and s3 buckets we can take advantage of this. 

The current alternative is launching an internal webserver or enabling an s3 bucket for public web traffic, both of these options would be less than desirable. 

Unless there is a policy for an s3 bucket out there that allows public web traffic but restricted to instances only in vpc-123456789 which i havent seemed to find anywhere, enabling the source to support s3 buckets would be the best form of action. I am sure users of other cloud providers would want something similar for Microsoft Azure Blob ZRS, or Google Cloud Storage standard. 

### Other Information ###

Love your work!

**Comment by Sodki** [comment] 2017-02-21 15:31
Seems to be a duplicate of #1631.

**Closed** 2017-02-21 19:02 UTC
Labels: area/usability, component/ignition, kind/enhancement, team/os
