### ISSUE TITLE
Creating an overlay mount on /lib/modules fails in v1688.5.3

### ISSUE THREAD

**Issue by eranreshef** [coreos/bugs#2407] opened 2018-04-16 09:11 UTC
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.5.3
VERSION_ID=1688.5.3
BUILD_ID=2018-04-03-0547
PRETTY_NAME="Container Linux by CoreOS 1688.5.3 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

AWS EC2

### Expected Behavior ###

I'm following the tutorial for how to install custom kernel modules [https://coreos.com/os/docs/latest/kernel-modules.html](https://coreos.com/os/docs/latest/kernel-modules.html).
When I ran it on previous stable version (1632.3.0) everything worked great.
### Actual Behavior ###

In new stable version (1688.5.3) when I try to mount an overlay on /lib/modules the process fails and I see the following error in the journal:
```
systemd[1]: lib-modules.mount: Mount path /lib/modules is not canonical (contains a symlink).
systemd[1]: lib-modules.mount: Failed to run 'mount' task: Too many levels of symbolic links
systemd[1]: lib-modules.mount: Failed with result 'resources'.
systemd[1]: Failed to mount Custom Kernel Modules.
```
### Reproduction Steps ###

Simply follow the steps in https://coreos.com/os/docs/latest/kernel-modules.html

**Comment by lucab** [comment] 2018-04-16 09:38
Confirmed, this is a safety-improving behavioral change introduced in systemd-238 by this PR: https://github.com/systemd/systemd/pull/7940.

On a ContainerLinux node, `/lib/modules` is buried below several layers of symlinks due to usr-merge and the lib/lib64 unification. The underlying real path is `/usr/lib64/modules`.

@eranreshef in order to fix your failure it should be enough to change all occurrences of `/lib/modules ` in that page with `/usr/lib64/modules`. Can you please try that configuration on a fresh stable node and report back?

/cc @dm0- @bgilbert I guess we'll have to live with the new behavior and update the docs. I'm not super happy with the exposing the exact path though, any better ideas? Are hardlinks viable maybe? Assigning to @dm0- for the final word.

/cc @arithx I think this is something we can easily cover via tests to ensure we don't regress again in future.

**Comment by eranreshef** [comment] 2018-04-16 09:41
@lucab I already tried your suggestion and it works as expected. I too also don't like idea of using the exact path but I needed to workaround the issue ASAP so thats what I did.

**Comment by sourcejedi** [comment] 2018-04-16 12:14
Note `man systemd.mount` suggests you generally want to use fstab instead of explicit mount units.
fstab is still supposed to accept symlinks... at least the symlink chain must be available on rootfs+usr only, but I guess you're fine there. What do you need `ConditionPathExists=` for? (it's not available in fstab options, I think).  `nofail` might be an option if it's just a safety thing to avoid failing the boot and entering the dreaded emergency shell.

That would let systemd end up creating `usr-lib64-modules.mount` for you.

---

I think the most important thing to understand about the names, is that other units will try to refer to them e.g. `RequiresMountFor=`, including automatically to handle nested mounts.  All the dependencies need to be resolved as soon as PID 1 loads its config.

`RequiresMountFor=/this/path` might not have been used to start with, just `Requires=` and `After=` on `this-path.mount`.  Certainly it would have seemed easier to shoehorn the path into the unit name.  And we needed some convention for mount unit names anyway, for when we automatically generate them from fstab.  You'd need a fairly strong argument to overhaul the whole thing at this point, I think.

Though don't let me stop you arguing for revert of my commit generalizing the check, if it's too much of a breaking change.

**Comment by dm0-** [comment] 2018-04-16 22:42
@lucab I am okay with changing the mount unit to `/etc/fstab`.  The change is in coreos/docs#1224.

**Comment by bgilbert** [comment] 2018-04-16 23:50
Correction: systemd/systemd#7940 landed in systemd 237, which explains why it's affecting 1688.5.3.

**Comment by rmenn** [comment] 2018-04-17 13:04
there might be some correlation with the issue here - https://github.com/cloudnativelabs/kube-router/issues/370

**Comment by dm0-** [comment] 2018-04-18 16:42
I'm going to close this as an issue with our documentation, which has been updated to use systemd's preferred configuration method, and the coreos-user list has been notified of this change.  Please reopen if anyone feels this change in systemd is problematic enough to warrant further discussion.

**Closed by dm0-** 2018-04-18 16:42 UTC
Labels: area/distribution, component/systemd, kind/documentation, kind/regression, team/os

**Comment by seh** [comment] 2018-06-05 16:37
If you'd like to mount the prescribed overlay by way of Ignition configuration, I found the following stanzas to work well:
```json
{
  "ignition": {
    "version": "2.1.0"
  },
  "storage": {
    "directories": [
      {
        "filesystem": "root",
        "path": "/opt/modules",
        "mode": 493
      },
      {
        "filesystem": "root",
        "path": "/opt/modules.wd",
        "mode": 493
      }
    ],
    "files": [
      {
        "filesystem": "root",
        "path": "/etc/fstab",
        "contents": {
          "source": "data:,overlay%20/lib/modules%20overlay%20lowerdir=/lib/modules,upperdir=/opt/modules,workdir=/opt/modules.wd%200%200"
        }
      }
    ]
  }
}
```
