### ISSUE TITLE
SELinux + Kubernetes tmpfs issue

### ISSUE THREAD

**Issue by Calpicow** [coreos/bugs#2221] opened 2017-11-03 00:49 UTC
# Issue Report #
### Container Linux Version ###
```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.8.0
VERSION_ID=1520.8.0
BUILD_ID=2017-10-26-0342
PRETTY_NAME="Container Linux by CoreOS 1520.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?

AWS, Kubernetes v1.7.8

### Other Information ###
Python multiprocess library doesn't work in Kubernetes with SELinux enabled.

To reproduce, run a python3 container in Kubernetes:

```
root@python:/# python                                                                                                                                                                                    
Python 3.6.3 (default, Oct 10 2017, 02:29:16) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from multiprocessing import Pool
>>> p = Pool(processes=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 156, in __init__
    self._setup_queues()
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 249, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/usr/local/lib/python3.6/multiprocessing/context.py", line 112, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/usr/local/lib/python3.6/multiprocessing/queues.py", line 315, in __init__
    self._rlock = ctx.Lock()
  File "/usr/local/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/local/lib/python3.6/multiprocessing/synchronize.py", line 163, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/local/lib/python3.6/multiprocessing/synchronize.py", line 60, in __init__
    unlink_now)
FileNotFoundError: [Errno 2] No such file or directory
```

Which gives an error related to tmpfs:

```
AVC avc:  denied  { search } for  pid=14335 comm="python" name="/" dev="tmpfs" ino=3876791 scontext=system_u:system_r:svirt_lxc_net_t:s0:c12,c904 tcontext=system_u:object_r:svirt_lxc_file_t:s0:c669,c884 tclass=dir permissive=0
```

**Comment by euank** [comment] 2017-11-06 19:58
Thanks for reporting this issue.

I've managed to reproduce it without Kubernetes using the following:

```sh
$ docker run -itd --name pause fedora sleep inf
$ docker run --security-opt seccomp=unconfined -it --ipc container:pause python:3 python -c $'from multiprocessing import Pool\np = Pool(processes=2)'
```

Both `seccomp=unconfined` and using a different the ipc namespace is required to reproduce it for me.

I was unable to reproduce this using docker version `17.09.0-ce` on v1520 (after updating it via the mechanism discussed [here](https://coreos.com/blog/toward-docker-17-in-container-linux)).

My current shot-in-the-dark guess is that https://github.com/moby/moby/pull/2679 might fix this based on the fact that setting `seccomp=unconfined` triggers it.

**Comment by Calpicow** [comment] 2017-12-20 00:35
Any workarounds without having to update Docker? If not, I think we could close this. Thanks.

**Comment by dm0-** [comment] 2017-12-20 01:12
I don't know of any changes to the 1.12 branch that would have changed this.  Note that kubernetes 1.8 also supports Docker CE 17.03 which should include the fix linked above.  Docker 17.03 is used by default with Tectonic 1.8 (released in preprod today), and non-Tectonic systems can pick 17.03 by [using torcx directly](https://gist.github.com/dm0-/66f8375418a8f2369070a2f5902ec5f0).

**Closed by dm0-** 2017-12-20 01:12 UTC
Labels: area/usability, component/selinux, kind/bug, priority/P0, team/os, version/docker/1.12.6
