### ISSUE TITLE
Ignition Fails to Create Groups

### ISSUE THREAD

**Issue by dmeiser** [coreos/bugs#994] opened 2015-11-20 14:40 UTC
Ignition 0.2.2 (CoreOS 835.4.0) fails to create new groups.  I've tested with and without a hash (md5).

Below is a snippet from a test with a password hash:

```
[   15.175921] localhost ignition[574]: Ignition v0.2.2
[   15.176130] localhost ignition[574]: files: createGroups: op(1): [started]  adding group "mygroup"
[   15.176239] localhost ignition[574]: files: createGroups: op(1): executing: /usr/sbin/groupadd [--root /sysroot --gid 1001 --password ThisWasAValidHash domain_admins]
[   15.180445] localhost ignition[574]: files: createGroups: op(1): [failed]   adding group "mygroup": exit status 1: Stderr: ""
[   15.180551] localhost ignition[574]: files: failed to create users/groups: failed to create groups: failed to create group "mygroup": exit status 1: Stderr: ""
[   15.180774] localhost systemd[1]: ignition-files.service: Main process exited, code=exited, status=1/FAILURE
```

Running the command as it is presented above (/usr/sbin/groupadd --root /sysroot --gid 1001 --password ThisWasAValidHash mygroup) returns an error (1).  Running the command for no password (/usr/sbin/groupadd --root /sysroot --gid 1001 --password * domain_admins) returns the command usage helper.  Wrapping the * in quotes (/usr/sbin/groupadd --root /sysroot --gid 1001 --password "*" mygroup) returns an error (1).

According to the manual, 1 is not a valid return value.

Finally, "--password *" is the default behavior if no password hash is included.  It could be left out if the user does not include a hash.

**Comment by dmeiser** [comment] 2015-11-20 15:11
I confirmed this is also present in 0.2.3 (CoreOS 835.5.0)

**Comment by dmeiser** [comment] 2015-11-20 15:59
This also appears to be the same for user creation.

**Comment by crawford** [comment] 2015-11-20 18:52
I'm having trouble reproducing this failure. I used the config:

```json
{
  "ignitionVersion": 1,
  "passwd": {
    "groups": [
      {
        "name": "test"
      }
    ]
  }
}
```

... which ran properly.

```sh
$ cat /etc/group
wheel:x:10:root,core
sudo:x:150:
docker:x:233:core
rkt:x:251:core
test:x:1000:
```

Can you provide the config you are using?

**Comment by dmeiser** [comment] 2015-11-20 19:11
I created a gist, should I just send you an email?

Also, I should have said this:  I'm using specified uids/gids.  That might be the biggest difference.

**Comment by crawford** [comment] 2015-11-20 19:34
Sure, you can email my github address or just post a link to the gist (you can trim out everything except the passwd.groups section).

**Comment by dmeiser** [comment] 2015-11-20 19:53
Here you go: https://gist.githubusercontent.com/dmeiser/65bbcaa4915bef32f38c/raw/14a2402bf026a919a1e17fce33e6e7d46d2e048c/ignition.json

**Comment by crawford** [comment] 2015-11-20 20:36
```
$ cat /etc/group
wheel:x:10:root,core
sudo:x:150:
docker:x:233:core
rkt:x:251:core
domain_admins:x:110001:
domain_users:x:110007:
linux_admins:x:110295:
```

Can you provide the logs (`journalctl -t ignition --no-pager`)?

**Comment by dmeiser** [comment] 2015-11-21 20:20
Alex,

I'll get this to you Monday, I was busy taking the LPIC-3 yesterday
afternoon.

**Comment by dmeiser** [comment] 2015-11-23 16:29
rdsosreport:  https://gist.github.com/dmeiser/14fbb7f17325007cd4d8
journalctl:  https://gist.github.com/dmeiser/273c57f70f084e4b1f22

These are from the same boot, so hopefully it gets you some better information.

**Comment by crawford** [comment] 2015-11-23 22:10
I was able to reproduce the failure using your config and a disk-less PXE image.

**Comment by dmeiser** [comment] 2015-12-08 18:51
@crawford : Do you have any idea of a timeline on this bug?

**Comment by crawford** [comment] 2015-12-08 19:57
@dmeiser I'm going to spend some time on this one in the next few weeks. I'm shooting for having a fix for this in the next Stable release.

**Comment by dmeiser** [comment] 2015-12-08 19:59
Awesome, thanks.

**Comment by crawford** [comment] 2015-12-09 00:34
I looked into this and it is failing because the `--sysroot` flag doesn't really behave the way we want.

```
strace /usr/sbin/groupadd --root /sysroot --password '*' test
...
chroot("/sysroot")                      = 0
...
connect(5, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = -1 ENOENT (No such file or directory)
...
```

In the initramfs, `/dev/log` is symlinked to `/run/systemd/journal/dev-log`, but `/sysroot/dev` is obviously empty. `groupadd` fails because it is attempting to open `/sysroot/dev/log`, which doesn't exist.

**Comment by crawford** [comment] 2015-12-10 01:02
I take that all back. I looked at it a bit more and the key line in the strace is:

```
open("/etc/login.defs", O_RDONLY)       = -1 ENOENT (No such file or directory)
```

vs. in the working case:

```
open("/etc/login.defs", O_RDONLY)       = 5
```

**Comment by vcaputo** [comment] 2015-12-14 23:36
Ugh, why the shadow package doesn't have sane defaults builtin for use in lieu of a login.defs runtime file escapes me.  The code reflects your strace observations:
```
407 static void def_load (void)
408 {
409         int i;
410         FILE *fp;
411         char buf[1024], *name, *value, *s;
412 
413         /*
414          * Open the configuration definitions file.
415          */
416         fp = fopen (def_fname, "r");
417         if (NULL == fp) {
418                 int err = errno;
419                 SYSLOG ((LOG_CRIT, "cannot open login definitions %s [%s]",
420                          def_fname, strerror (err)));
421                 exit (EXIT_FAILURE);
422         }
```

**Comment by dmeiser** [comment] 2016-01-08 15:38
@crawford : Has there been any movement on this?

**Comment by crawford** [comment] 2016-01-11 16:50
No :(

I need to spend some time on Ignition this week, so I'll throw this on my queue.

**Comment by crawford** [comment] 2016-01-11 19:56
In between running the disks and files stage, we need to let tmpfilesd apply shadow.conf. This will create the necessary symlinks.

**Comment by crawford** [comment] 2016-01-11 22:15
Tada:

```
$ cat /etc/group  
wheel:x:10:root,core
sudo:x:150:
docker:x:233:core
rkt:x:251:core
test:x:1000:
```

**Closed** 2016-01-12 05:46 UTC
Labels: area/usability, component/ignition, kind/bug, priority/P1, team/os
