### ISSUE TITLE
developer container's perl is entirely broken

### ISSUE THREAD

**Issue by zx2c4** [coreos/bugs#2545] opened 2019-01-22 16:46 UTC
The developer container's perl is broken. I followed the directions in the [official docs](https://coreos.com/os/docs/latest/kernel-modules.html):

```
. /usr/share/coreos/release
. /usr/share/coreos/update.conf
url="http://${GROUP:-stable}.release.core-os.net/$COREOS_RELEASE_BOARD/$COREOS_RELEASE_VERSION/coreos_developer_container.bin.bz2"
gpg2 --recv-keys 04127D0BFABEC8871FFB2CCE50E0885593D2DCB4  # Fetch the buildbot key if neccesary.
curl -L "$url" |
    tee >(bzip2 -d > coreos_developer_container.bin) |
    gpg2 --verify <(curl -Ls "$url.sig") -
sudo systemd-nspawn \
    --bind=/lib/modules \
    --image=coreos_developer_container.bin
coreos_developer_container # emerge-gitclone
```

Then I tried the simplest of perl programs:

```
coreos_developer_container # echo 'use strict;' | perl
Attempt to free unreferenced scalar: SV 0x55f28babf338 at /usr/lib64/perl5/5.24.1/strict.pm line 38.
Segmentation fault (core dumped)
```

Recompiling perl fixed the issue:

```
coreos_developer_container # emerge perl
...
coreos_developer_container # echo 'use strict;' | perl
[no output]
```

So it would seem that the included perl in that container is badly broken.

**Comment by dm0-** [comment] 2019-01-22 16:59
Yes, this was reported as #2369, which seems to be the fault of the cross-compiling patches for Perl.  Rebuilding Perl natively so it doesn't use the cross-compiling patches should be a usable workaround.

**Comment by bgilbert** [comment] 2019-01-25 00:57
Closing as duplicate of https://github.com/coreos/bugs/issues/2369.

**Closed by bgilbert** 2019-01-25 00:57 UTC
Labels: area/developer tooling, component/distro, kind/regression
