### ISSUE TITLE
polkit.service fails to start on AWS due to time out.

### ISSUE THREAD

**Issue by mvanholsteijn** [coreos/bugs#1406] opened 2016-06-15 12:03 UTC
# Issue Report #
On my CoreOS machines on AWS it often occurs that  polkit.service fails to start. About 1/2 of the machines fail to start the polkit.service.

### CoreOS Version ###
CoreOS-stable-1010.5.0-hvm (ami-cfca25a0)

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1010.5.0
VERSION_ID=1010.5.0
BUILD_ID=2016-05-26-2225
PRETTY_NAME="CoreOS 1010.5.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run CoreOS?
AWS EC2

### Expected Behavior ###
polkit.service starts

### Actual Behavior ###
polkit.service sometimes starts, sometimes does not

### Reproduction Steps ###

  1. Download DC/OS AWS template https://s3-us-west-2.amazonaws.com/downloads.dcos.io/dcos/EarlyAccess/commit/14509fe1e7899f439527fb39867194c7a425c771/cloudformation/single-master.cloudformation.json
  2. Modified RegionToAmi for eu-central-1 to point to ami-cfca25a0
  3. Deploy the CFN stack
  4. After a while, login to the machines and check the polkit.service journal on the machines. 

```
-- Logs begin at Wed 2016-06-15 11:14:20 UTC, end at Wed 2016-06-15 11:57:51 UTC. --
Jun 15 11:14:35 localhost systemd[1]: Starting Authorization Manager...
Jun 15 11:14:36 localhost polkitd[808]: Started polkitd version 0.113
Jun 15 11:14:36 localhost polkitd[808]: Loading rules from directory /etc/polkit-1/rules.d
Jun 15 11:14:36 localhost polkitd[808]: Loading rules from directory /usr/share/polkit-1/rules.d
Jun 15 11:14:36 localhost polkitd[808]: Finished loading, compiling and executing 3 rules
Jun 15 11:14:36 localhost polkitd[808]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jun 15 11:16:56 ip-10-0-6-254.eu-central-1.compute.internal systemd[1]: polkit.service: Start operation timed out. Terminating.
Jun 15 11:16:56 ip-10-0-6-254.eu-central-1.compute.internal systemd[1]: Failed to start Authorization Manager.
Jun 15 11:16:56 ip-10-0-6-254.eu-central-1.compute.internal systemd[1]: polkit.service: Unit entered failed state.
Jun 15 11:16:56 ip-10-0-6-254.eu-central-1.compute.internal systemd[1]: polkit.service: Failed with result 'timeout'.
```

**Comment by crawford** [comment] 2016-06-15 16:28
Duplicate of https://github.com/coreos/bugs/issues/462. This was fixed in 1029.0.0.

**Closed by crawford** 2016-06-15 16:28 UTC
Labels: area/usability, component/systemd, kind/bug, team/os
