### ISSUE TITLE
Filesystem remounted read-only; "deleted inode referenced"

### ISSUE THREAD

**Issue by APILLSBURY** [coreos/bugs#1309] opened 2016-06-01 19:43 UTC
CoreOS Version: 1053.2.0

I have a coreos machine set up using Vagrant. I didn't make any changes to the machine, I encountered an error in docker ("read-only filesystem") that I tracked down to '/' being mounted read-only. Looking in dmesg I found:

```
[ 5128.549167] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[ 5128.786187] EXT4-fs error (device sda9): ext4_lookup:1602: inode #67005: comm docker: deleted inode referenced: 3186320
[ 5128.787186] Aborting journal on device sda9-8.
[ 5128.788318] EXT4-fs error (device sda9): ext4_journal_check_start:56: Detected aborted journal
[ 5128.789091] EXT4-fs (sda9): Remounting filesystem read-only
[ 5128.789548] EXT4-fs (sda9): Remounting filesystem read-only
[ 5128.790217] overlayfs: cleanup of 'work/#ffff88005c618000' failed (-30)
[ 5128.792053] EXT4-fs error (device sda9): ext4_lookup:1602: inode #67005: comm docker: deleted inode referenced: 3186320
```

**Comment by crawford** [comment] 2016-06-01 22:40
```
[ 5128.788318] EXT4-fs error (device sda9): ext4_journal_check_start:56: Detected aborted journal
```

It looks like there was trouble committing changes to the filesystem. This could have been caused by any number of things like a hardware failure or trouble suspending/resuming. You'll need to fsck the filesystem, potentially removing and re-adding the journal. It's been a while since I've had to do that so the details are fuzzy.

**Comment by vcaputo** [comment] 2016-07-11 23:14
@APILLSBURY are you still having problems with ext4 journal errors?

**Comment by APILLSBURY** [comment] 2016-07-12 17:53
@vcaputo yes, I'm still seeing this periodically. `vagrant destroy && vagrant up` fixes the problem.

**Comment by crawford** [comment] 2016-12-13 23:45
Closing due to inactivity.

**Comment by abulford** [comment] 2017-03-13 15:51
I know this is a bit late, but we've started seeing this since the update to CoreOS 1298.5.0:

```
Mar 08 10:44:06 crocnt02 kernel: EXT4-fs error (device sda9): ext4_lookup:1611: inode #10605376: comm dockerd: deleted inode referenced: 10605377
Mar 08 10:44:06 crocnt02 kernel: Aborting journal on device sda9-8.
Mar 08 10:44:06 crocnt02 kernel: EXT4-fs (sda9): Remounting filesystem read-only
Mar 08 10:44:06 crocnt02 kernel: EXT4-fs error (device sda9): ext4_lookup:1611: inode #10605376: comm dockerd: deleted inode referenced: 10605377
```

This has happened on two different physical machines running CoreOS.

On the first host to be affected it happened the day after the update to CoreOS 1298.5.0.  We fixed the filesystem and restarted and it was OK for a while, but we then saw the same error a couple of days later.  Since then we've kept it on the previous version, 1235.12.0 and haven't seen the issue since - that was 5 days ago.

The second host suffered from the same issue today, just over a week after it got the update.

Both machines are used for our build system so do a fair amount of disk I/O, they also use containers for builds and containers are periodically run for performing backups, so there's a lot of container churn.  The first host does more disk I/O and container churn than the second, so this might explain why it failed faster.

From `docker info`, the backing filesystem is `extfs` and the storage driver is `overlay`.

Does anyone have any idea what the issue could be?  The kernel 4.7.3 jumped from 4.9.9 in this release, so we're suspecting it's a kernel issue.

**Comment by crawford** [comment] 2017-03-13 17:01
@abulford we are tracking the issue over here https://github.com/coreos/bugs/issues/1811.

**Comment by abulford** [comment] 2017-03-13 17:08
Thanks @crawford, I'll keep an eye on that, though the reason for the remount seems to be different - we're consistently seeing the 'deleted inode' messages, e.g.: `inode #10605376: comm dockerd: deleted inode referenced: 10605377`.  Maybe there's some common cause which is behind both these issues, though.

**Comment by bgilbert** [comment] 2017-03-16 02:05
@abulford, I assume you're not seeing container OOMs on your system?  #1811 is known to occur with 4.7 kernels and only happens after a container OOM, so it appears to be a different issue.

**Comment by abulford** [comment] 2017-03-17 07:17
@bgilbert no, I don't think we were getting OOMs on either affected system.

Both hosts have remained downgraded to CoreOS 1235.12.0 (kernel 4.7.3) and we've not seen the issue again, so it does appear to be something related to the new kernel (or CoreOS version).

**Comment by bgilbert** [comment] 2017-07-04 20:46
@abulford Are you still seeing this on 1409.5.0?

**Comment by abulford** [comment] 2017-07-04 21:45
@bgilbert I'm afraid to say we're not running CoreOS any more, so I can't really check this for you.  Sorry :(.

**Comment by bgilbert** [comment] 2017-07-04 22:05
@abulford Okay, thanks for getting back to me.

I'm going to close this out for now.  We're now shipping 4.11, soon to start shipping 4.12 in alpha, and there have been a lot of upstream filesystem fixes since 4.9.9.  If anyone is still seeing this issue, please comment here.

**Comment by matti** [comment] 2017-09-27 11:40
Something like this just happened with latest stable:


>$ cat /etc/lsb-release
DISTRIB_ID="Container Linux by CoreOS"
DISTRIB_RELEASE=1465.8.0
DISTRIB_CODENAME="Ladybug"
DISTRIB_DESCRIPTION="Container Linux by CoreOS 1465.8.0 (Ladybug)"

>$ uname -a
Linux myhostname 4.12.14-coreos #1 SMP Wed Sep 20 22:20:05 UTC 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux


>Sep 26 17:11:51 myhostname kernel: EXT4-fs error (device sda9): ext4_lookup:1580: inode #10426189: comm dockerd: deleted inode referenced: 10426462

>failed to cleanup ipc mounts:\nfailed to umount /var/lib/docker/containers/67aa357aee662b60a4fbce00e44ff518586515da0de7187e2b791f4417b9b46f/shm: invalid argument

>Sep 26 17:11:51 myhostname docker[3229]: Docker::Error::ServerError: Cannot restart container 67aa357aee662b60a4fbce00e44ff518586515da0de7187e2b791f4417b9b46f: lstat /var/lib/docker/containers/67aa357aee662b60a4fbce00e44ff518586515da0de7187e2b791f4417b9b46f/hosts: structure needs cleaning

Running in Google Cloud Platform

**Comment by matti** [comment] 2017-09-27 11:41
Looks like the OOM happened after this, not before

**Comment by matti** [comment] 2017-09-27 12:04
ping @bgilbert

**Comment by bgilbert** [comment] 2017-09-27 20:33
@matti Could you post the relevant part of the kernel log?

**Comment by matti** [comment] 2017-09-28 04:44
@bgilbert what kernel log do you mean? dmesg didn’t contain the start of this anymore (we noticed this after 24h+)

**Comment by matti** [comment] 2017-09-28 04:45
(”fixed” this by fsck that fixed a bunch of errors)

**Comment by bgilbert** [comment] 2017-09-28 07:03
If it caused your root filesystem to be remounted read-only, there's no way to recover the logs after a reboot.  Have you seen this problem more than once?  If it happens again, and you can get kernel logs, please post them here.

**Comment by matti** [comment] 2017-09-28 07:04
Just once, but could I have seen the logs before the reboot? dmesg didnt have enough lines.

**Comment by bgilbert** [comment] 2017-09-28 20:18
@matti I'm confused.  The error and backtrace should easily fit within the dmesg buffer.  What messages were you seeing that filled up your kernel log?

**Comment by matti** [comment] 2017-09-28 21:22
@bgilbert dmesg contained a lot of: 

```
[404488.183816] overlayfs: upper fs is r/o, try multi-lower layers mount
[404489.555576] overlayfs: upper fs is r/o, try multi-lower layers mount
```

that’s why the original error was not visible. should push the dmesg logs away from the machines...

**Comment by joshk0** [comment] 2017-12-19 22:54
Hi, encountering this on 1576.4.0. Our workload involves a lot of ephemeral pods (lasting anywhere from 1 to 15 minutes) that use NFS PersistentVolumes -- if that says anything.

```
Dec 19 07:53:31 k8s-prod-svc-worker01 kernel: EXT4-fs error (device sda9): ext4_lookup:1580: inode #19349816: comm dockerd: deleted inode referenced: 19350910
Dec 19 07:53:31 k8s-prod-svc-worker01 kernel: Aborting journal on device sda9-8.
Dec 19 07:53:32 k8s-prod-svc-worker01 kernel: EXT4-fs (sda9): Remounting filesystem read-only
Dec 19 07:53:32 k8s-prod-svc-worker01 kernel: EXT4-fs error (device sda9): ext4_lookup:1580: inode #19349816: comm dockerd: deleted inode referenced: 19350910
Dec 19 07:53:32 k8s-prod-svc-worker01 kernel: EXT4-fs (sda9): ext4_writepages: jbd2_start: 9223372036854774795 pages, ino 19401; err -30
```

This is the last log in the journal. The kernel version is 4.13.16.

I found that dmesg was overloaded with errors from journalctl not being able to write any more data to its journal files. That's probably why @matti was not able to collect the logs that way. I was able to get them using `journalctl -t kernel`. Conveniently, it is the very last message in that stream.

**Comment by bgilbert** [comment] 2018-05-15 02:33
Closing due to inactivity.

**Comment by george-angel** [comment] 2018-07-24 09:09
We are seeing a similar issue:

Container Linux: 1745.7.0
Kernel: 4.14.48-coreos-r2
Cloud env: AWS

```
Jul 23 03:34:31 ip-10-66-21-90 kernel: oom_reaper: reaped process 29050 (mongod), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
Jul 23 04:46:57 ip-10-66-21-90 kernel: ftdc invoked oom-killer: gfp_mask=0x14000c0(GFP_KERNEL), nodemask=(null),  order=0, oom_score_adj=998
Jul 23 04:46:57 ip-10-66-21-90 kernel: ftdc cpuset=37650b2ef9950343912e773ef083107c7b81ffdf67e628164d14005ec21f72bc mems_allowed=0
Jul 23 04:46:57 ip-10-66-21-90 kernel: CPU: 4 PID: 28956 Comm: ftdc Not tainted 4.14.48-coreos-r2 #1
Jul 23 04:46:57 ip-10-66-21-90 kernel: Hardware name: Xen HVM domU, BIOS 4.2.amazon 08/24/2006
Jul 23 04:46:57 ip-10-66-21-90 kernel: Call Trace:
Jul 23 04:46:57 ip-10-66-21-90 kernel:  dump_stack+0x5c/0x85
Jul 23 04:46:57 ip-10-66-21-90 kernel:  dump_header+0x94/0x229
Jul 23 04:46:57 ip-10-66-21-90 kernel:  oom_kill_process+0x213/0x410
Jul 23 04:46:57 ip-10-66-21-90 kernel:  out_of_memory+0x2ab/0x4c0
Jul 23 04:46:57 ip-10-66-21-90 kernel:  mem_cgroup_out_of_memory+0x49/0x80
Jul 23 04:46:57 ip-10-66-21-90 kernel:  mem_cgroup_oom_synchronize+0x2ed/0x330
Jul 23 04:46:57 ip-10-66-21-90 kernel:  ? mem_cgroup_css_online+0x30/0x30
Jul 23 04:46:57 ip-10-66-21-90 kernel:  pagefault_out_of_memory+0x32/0x77
Jul 23 04:46:57 ip-10-66-21-90 kernel:  __do_page_fault+0x4b3/0x4c0
Jul 23 04:46:57 ip-10-66-21-90 kernel:  ? page_fault+0x2f/0x50
Jul 23 04:46:57 ip-10-66-21-90 kernel:  page_fault+0x45/0x50
Jul 23 04:46:57 ip-10-66-21-90 kernel: RIP: 9000:0x49be8
Jul 23 04:46:57 ip-10-66-21-90 kernel: RSP: 1937d000:00007f7040aae690 EFLAGS: 00010008
Jul 23 04:46:57 ip-10-66-21-90 kernel: Task in /kubepods/burstable/podaac08eb8-8901-11e8-854f-0688fd98c98a/37650b2ef9950343912e773ef083107c7b81ffdf67e628164d14005ec21f72bc killed as a result of limit of /kubepods/burstable/podaac08eb8-8901-11e8-854f-0688fd98c98a/37650b2ef9950343912e773ef083107c7b81ffdf67e628164d14005ec21f72bc
Jul 23 04:46:57 ip-10-66-21-90 kernel: memory: usage 1024000kB, limit 1024000kB, failcnt 0
Jul 23 04:46:57 ip-10-66-21-90 kernel: memory+swap: usage 1024000kB, limit 1024000kB, failcnt 24580
Jul 23 04:46:57 ip-10-66-21-90 kernel: kmem: usage 6860kB, limit 9007199254740988kB, failcnt 0
Jul 23 04:46:57 ip-10-66-21-90 kernel: Memory cgroup stats for /kubepods/burstable/podaac08eb8-8901-11e8-854f-0688fd98c98a/37650b2ef9950343912e773ef083107c7b81ffdf67e628164d14005ec21f72bc: cache:0KB rss:1017140KB rss_huge:120832KB shmem:0KB mapped_file:0KB dirty:0KB writeback:0KB swap:0KB inactive_anon:0KB active_anon:1017140KB inactive_file:0KB active_file:0KB
Jul 23 04:46:57 ip-10-66-21-90 kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
Jul 23 04:46:57 ip-10-66-21-90 kernel: [28863]     0 28863   632640   253284     623       5        0           998 mongod
Jul 23 04:46:57 ip-10-66-21-90 kernel: Memory cgroup out of memory: Kill process 28863 (mongod) score 1989 or sacrifice child
Jul 23 04:46:57 ip-10-66-21-90 kernel: Killed process 28863 (mongod) total-vm:2530560kB, anon-rss:979668kB, file-rss:33468kB, shmem-rss:0kB
Jul 23 04:46:57 ip-10-66-21-90 kernel: oom_reaper: reaped process 28863 (mongod), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
Jul 23 05:52:55 ip-10-66-21-90 kernel: replication-46 invoked oom-killer: gfp_mask=0x14000c0(GFP_KERNEL), nodemask=(null),  order=0, oom_score_adj=998
Jul 23 05:52:55 ip-10-66-21-90 kernel: replication-46 cpuset=0e36987ee58480b66c889b5aa51c86362615dcfba864fd1147284109658ec321 mems_allowed=0
Jul 23 05:52:55 ip-10-66-21-90 kernel: CPU: 3 PID: 19253 Comm: replication-46 Not tainted 4.14.48-coreos-r2 #1
Jul 23 05:52:55 ip-10-66-21-90 kernel: Hardware name: Xen HVM domU, BIOS 4.2.amazon 08/24/2006
Jul 23 05:52:55 ip-10-66-21-90 kernel: Call Trace:
Jul 23 05:52:55 ip-10-66-21-90 kernel:  dump_stack+0x5c/0x85
Jul 23 05:52:55 ip-10-66-21-90 kernel:  dump_header+0x94/0x229
Jul 23 05:52:55 ip-10-66-21-90 kernel:  oom_kill_process+0x213/0x410
Jul 23 05:52:55 ip-10-66-21-90 kernel:  out_of_memory+0x2ab/0x4c0
Jul 23 05:52:55 ip-10-66-21-90 kernel:  mem_cgroup_out_of_memory+0x49/0x80
Jul 23 05:52:55 ip-10-66-21-90 kernel:  mem_cgroup_oom_synchronize+0x2ed/0x330
Jul 23 05:52:55 ip-10-66-21-90 kernel:  ? mem_cgroup_css_online+0x30/0x30
Jul 23 05:52:55 ip-10-66-21-90 kernel:  pagefault_out_of_memory+0x32/0x77
Jul 23 05:52:55 ip-10-66-21-90 kernel:  __do_page_fault+0x4b3/0x4c0
Jul 23 05:52:55 ip-10-66-21-90 kernel:  ? page_fault+0x2f/0x50
Jul 23 05:52:55 ip-10-66-21-90 kernel:  page_fault+0x45/0x50
Jul 23 05:52:55 ip-10-66-21-90 kernel: RIP: 2f41e80:0x5624022029a0
Jul 23 05:52:55 ip-10-66-21-90 kernel: RSP: 3e1c1000:00007f1e6dd030a0 EFLAGS: 5624021fa4a0
Jul 23 05:52:55 ip-10-66-21-90 kernel: Task in /kubepods/burstable/podaac08eb8-8901-11e8-854f-0688fd98c98a/0e36987ee58480b66c889b5aa51c86362615dcfba864fd1147284109658ec321 killed as a result of limit of /kubepods/burstable/podaac08eb8-8901-11e8-854f-0688fd98c98a/0e36987ee58480b66c889b5aa51c86362615dcfba864fd1147284109658ec321
Jul 23 05:52:55 ip-10-66-21-90 kernel: memory: usage 1024000kB, limit 1024000kB, failcnt 0
Jul 23 05:52:55 ip-10-66-21-90 kernel: memory+swap: usage 1024000kB, limit 1024000kB, failcnt 24700
Jul 23 05:52:55 ip-10-66-21-90 kernel: kmem: usage 6748kB, limit 9007199254740988kB, failcnt 0
Jul 23 05:52:55 ip-10-66-21-90 kernel: Memory cgroup stats for /kubepods/burstable/podaac08eb8-8901-11e8-854f-0688fd98c98a/0e36987ee58480b66c889b5aa51c86362615dcfba864fd1147284109658ec321: cache:12KB rss:1017240KB rss_huge:247808KB shmem:0KB mapped_file:0KB dirty:0KB writeback:0KB swap:0KB inactive_anon:0KB active_anon:1017232KB inactive_file:12KB active_file:0K
Jul 23 05:52:55 ip-10-66-21-90 kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
Jul 23 05:52:55 ip-10-66-21-90 kernel: [21851]     0 21851   585197   235279     581       5        0           998 mongod
Jul 23 05:52:55 ip-10-66-21-90 kernel: Memory cgroup out of memory: Kill process 21851 (mongod) score 1919 or sacrifice child
Jul 23 05:52:56 ip-10-66-21-90 kernel: Killed process 21851 (mongod) total-vm:2340788kB, anon-rss:908012kB, file-rss:33104kB, shmem-rss:0kB
Jul 23 05:52:56 ip-10-66-21-90 kernel: oom_reaper: reaped process 21851 (mongod), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
Jul 23 06:04:08 ip-10-66-21-90 kernel: EXT4-fs error (device xvda9): ext4_lookup:1585: inode #4188273: comm du: deleted inode referenced: 4195542
Jul 23 06:04:08 ip-10-66-21-90 kernel: Aborting journal on device xvda9-8.
Jul 23 06:04:08 ip-10-66-21-90 kernel: EXT4-fs (xvda9): Remounting filesystem read-only
```

**Comment by bgilbert** [comment] 2019-01-11 20:34
Closing due to inactivity.

**For anyone who sees this problem in the future**: this is a recurring symptom of reference-counting bugs in the upstream kernel.  Container Linux developers probably won't be able to provide much assistance here, but [upstream](http://vger.kernel.org/vger-lists.html#linux-fsdevel) may be interested in hearing about problems.

**Closed by bgilbert** 2019-01-11 20:34 UTC
Labels: area/stability, component/kernel, kind/bug, team/os
