### ISSUE TITLE
Ignition fails to create btrfs root

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1521] opened 2016-08-16 03:32 UTC
# Issue Report #

### CoreOS Version ###

1141.0.0

### Environment ###

GCE and QEMU

### Actual Behavior ###

```
ignition[238]: disks: createFilesystems: op(4): [failed]   creating "btrfs" filesystem on "/dev/disk/by-label/ROOT": exit status 1: Stdout: "btrfs-progs v4.2.2\nSee http://btrfs.wiki.kernel.org for more information.\n\nPerforming full device TRIM (6.17GiB) ...\n" Stderr: "Superblock bytenr is larger than device size\nOpen ctree failed\n"
```

### Reproduction Steps ###

```json

{
  "ignition": { "version": "2.0.0" },
  "storage": {
    "filesystems": [{
      "mount": {
        "device": "/dev/disk/by-label/ROOT",
        "format": "btrfs",
        "create": {
          "force": true,
          "options": [ "--label=ROOT" ]
        }
      }
    }]
  }
}
```

**Comment by vcaputo** [comment] 2016-08-16 17:56
That's odd...

**Comment by mischief** [comment] 2016-08-17 21:19
this is fairly easily reproduced with `until mkfs.btrfs --force --label /dev/disk/by-label/ROOT; do sleep 1; done` at the pre-mount shell in dracut, which you can get to with `rd.break=pre-mount` on the kernel commandline; result:

```
pre-mount:/# [    2.353695] systemd-networkd[341]: eth0: Gained carrier
[    2.355466] systemd-networkd[341]: eth0: DHCPv4 address 10.0.2.15/24 via 10.0.2.2
[    2.356462] systemd-networkd[341]: eth0: Not connected to system bus, ignoring transient hostname.
[    3.326528] systemd-networkd[341]: eth0: Gained IPv6LL

pre-mount:/# [    4.801556] systemd-networkd[341]: eth0: Configured

pre-mount:/# 
pre-mount:/# 
<fs --force --label ROOT /dev/disk/by-label/ROOT; sleep 1; done              
sh: syntax error near unexpected token `done'
<fs --force --label ROOT /dev/disk/by-label/ROOT; do sleep 1; done             
btrfs-progs v4.4.1
See http://btrfs.wiki.kernel.org for more information.

Open ctree failed
[   49.328826] BTRFS: device label ROOT devid 1 transid 1 /dev/vda9
btrfs-progs v4.4.1
See http://btrfs.wiki.kernel.org for more information.

Open ctree failed
[   50.345853] BTRFS: device label ROOT devid 1 transid 1 /dev/vda9
btrfs-progs v4.4.1
See http://btrfs.wiki.kernel.org for more information.

Superblock bytenr is larger than device size
Open ctree failed
[   51.368405] BTRFS: device label ROOT devid 1 transid 1 /dev/vda9
btrfs-progs v4.4.1
See http://btrfs.wiki.kernel.org for more information.

Superblock bytenr is larger than device size
Open ctree failed
[   52.388596] BTRFS: device label ROOT devid 1 transid 1 /dev/vda9
btrfs-progs v4.4.1
See http://btrfs.wiki.kernel.org for more information.

Open ctree failed
[   53.407547] BTRFS: device label ROOT devid 1 transid 1 /dev/vda9
btrfs-progs v4.4.1
See http://btrfs.wiki.kernel.org for more information.

Superblock bytenr is larger than device size
Open ctree failed
[   54.433634] BTRFS: device label ROOT devid 1 transid 1 /dev/vda9
btrfs-progs v4.4.1
See http://btrfs.wiki.kernel.org for more information.

[   55.456168] BTRFS: device label ROOT devid 1 transid 1 /dev/vda9
Label:              ROOT
UUID:               138591f1-9bcb-47dd-9a16-3fb4f30faf08
Node size:          16384
Sector size:        4096
Filesystem size:    6.17GiB
Block group profiles:
  Data:             single            8.00MiB
  Metadata:         DUP             324.00MiB
  System:           DUP              12.00MiB
SSD detected:       no
Incompat features:  extref, skinny-metadata
Number of devices:  1
Devices:
   ID        SIZE  PATH
    1     6.17GiB  /dev/disk/by-label/ROOT

pre-mount:/# 
```

**Comment by mischief** [comment] 2016-08-17 21:20
it seems that we might want to invoke `wipefs` if `"force": true`. wipefs will need to be copied into the initrd.

**Comment by crawford** [comment] 2016-08-17 21:21
We didn't need to do it before. Why is it needed now?

**Comment by mischief** [comment] 2016-08-17 21:34
after some more investigation it looks like a race with udev. the fs label appears to change under mkfs feet and it gets confused. proper solution seems to be use /dev/disk/by-partlabel/ROOT and not /dev/disk/by-label/ROOT.

**Comment by vcaputo** [comment] 2016-08-26 22:12
Closed by https://github.com/coreos/ignition/issues/292

**Closed by vcaputo** 2016-08-26 22:12 UTC
Labels: area/usability, component/distro, component/ignition, kind/regression, priority/P1, team/os
