### ISSUE TITLE
Ignition boot gets stuck when using multiple disks

### ISSUE THREAD

**Issue by razvanm** [coreos/bugs#1571] opened 2016-09-13 19:45 UTC
# Issue Report #

## Bug ##

Using multiple disks make Ignition booting to stuck saying `A start job is running for Ignition (disks) ([...] / no limit)`. The issue doesn't happen when the list of disks is only one but it can happen even for a small number of disks (even two).

These is the exact setting I'm using for a SuperMicro server with 2 SSDs and 6 HDDs.

```
storage:
  disks:
    - device: "/dev/nvme0n1"
      wipe_table: true
      partitions:
        - label: "ssd0"
          number: 0
    - device: "/dev/nvme1n1"
      wipe_table: true
      partitions:
        - label: "ssd1"
          number: 0
    - device: "/dev/sda"
      wipe_table: true
      partitions:
        - label: "ata.1"
          number: 0
    - device: "/dev/sdb"
      wipe_table: true
      partitions:
        - label: "ata.2"
          number: 0
    - device: "/dev/sdc"
      wipe_table: true
      partitions:
        - label: "ata.3"
          number: 0
    - device: "/dev/sdd"
      wipe_table: true
      partitions:
        - label: "ata.4"
          number: 0
    - device: "/dev/sde"
      wipe_table: true
      partitions:
        - label: "ata.5"
          number: 0
    - device: "/dev/sdf"
      wipe_table: true
      partitions:
        - label: "ata.6"
          number: 0
```

### CoreOS Version ###

```
NAME=CoreOS
ID=coreos
VERSION=1122.2.0
VERSION_ID=1122.2.0
BUILD_ID=2016-09-06-1449
PRETTY_NAME="CoreOS 1122.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

Same thing happen also on the current CoreOS beta (1153.0.0) and CoreOS alpha (1164.1.0).

### Environment ###

Bare metal using a SuperMicro server.

### Expected Behavior ###

The boot should not get stuck.

### Actual Behavior ###

The boot gets stuck.

### Reproduction Steps ###

  1. Use an Ignition config with multiple disks.
  2. Attempt to boot the above config.

**Comment by crawford** [comment] 2016-09-14 18:15
I've also been able to reproduce this with QEMU and multiple disks. Internally, we use systemd to wait for the devices to appear, but it looks like systemd never recognizes that they've been attached.

**Comment by crawford** [comment] 2016-09-14 18:16
I should also mention that it doesn't always happen. Using the performance CPU governor on my laptop makes the problem appear less often.

**Comment by razvanm** [comment] 2016-09-14 18:36
The [waitOnDevices](https://github.com/coreos/ignition/blob/bd0a045eb35a4abd490fb8f2bccd44b3f65c2b40/internal/exec/stages/disks/disks.go#L87) calls [WaitOnDevices](https://github.com/coreos/ignition/blob/bd0a045eb35a4abd490fb8f2bccd44b3f65c2b40/internal/systemd/systemd.go#L25). Might that be the place where the wait gets stuck?

**Comment by crawford** [comment] 2016-09-14 20:06
I believe so. Ignition asks systemd to "start" those device units, which move to the started state once they are online. This is how Ignition waits for disks to show up. My guess is there is either a problem in this interface or with systemd itself.

**Comment by crawford** [comment] 2016-09-16 23:33
Fixed by https://github.com/coreos/ignition/pull/299.

**Closed by crawford** 2016-09-16 23:33 UTC
Labels: area/usability, component/ignition, kind/bug, priority/P1, team/os
