### ISSUE TITLE
any update fails on large disk + legacy boot

### ISSUE THREAD

**Issue by ailin-nemui** [coreos/bugs#1471] opened 2016-07-20 20:22 UTC
# Issue Report #

## Bug ##

any attempt to switch to the other USR partition fails with double self corruption of GPT by custom grub function, dropping the system into emergency initrd 

### Environment ###

Installed to bare metal in compatibility mode to > 2.1 TB hard disk

### Expected Behavior ###

at least a warning should be issued or installation refused in this case

### Actual Behavior ###

initial installation works and the system boots, giving the appearance of successful operation. but as soon as the first automatic update hits, the system is broken. a forced reboot (after walking into the server room) boots back into the original install and this continues forever.

### Other Information ###

https://github.com/coreos/grub/blob/master/grub-core/commands/gptprio.c#L77

this function tries to find the next boot entry but at the same time it does a whole load of other stuff: repair the gpts, change the priority and tries and write the changed gpt. Any kind of failure is handled with a simple `return ""`

That leads to the code in https://github.com/coreos/scripts/blob/master/build_library/grub.cfg#L111 to receive an empty partition uuid so the boot command line is attempted with PARTUUID=. Obviously there is no such empty partuuid so the mount unit in systemd fails and the user is dropped in an emergency shell.

Now the probable reason for the failure is that the legacy-booted grub cannot access the hard disk safely beyond the 2.1TB border, thus corrupting the secondary gpt which is located at the very end of the disk.

To add some fun: 
```
cgpt repair
Segmentation fault (core dumped)
```

**Comment by marineam** [comment] 2016-07-20 20:48
Thanks for the detailed report! I'll look into this asap.

**Comment by ailin-nemui** [comment] 2016-07-20 20:54
thanks. rewriting the gpt in grub seems scary to me, and not handling failure is a happy cause of disaster

**Comment by mjg59** [comment] 2016-07-20 22:00
grub should be able to access >2.1TB even on BIOS - the block field in the drive access packet is 64-bit. However, we're relying on the firmware handling >32 bit values in a reasonable way, which is not guaranteed. What platform is this?

**Comment by marineam** [comment] 2016-07-20 22:08
If the bios/grub is being kind enough to refuse to write to >32bit locations we can potentially fix this by merely being better at error handling which is needed anyway. If it is actually writing to the *wrong* location by truncating the 64 bit LBA value to 32bits then the whole thing cannot be trusted and we should never write the backup GPT in this situation.

If we skip writing the backup GPT in grub we can update it after boot instead, but that obviously requires fixing cgpt first. Looking into that now.

**Comment by ailin-nemui** [comment] 2016-07-21 09:01
Dell PowerEdge R430, smbios-2.8
Dell BIOS 1.2.6
LSI MegaRAID SAS-3 3108 / PERC H730P Mini 4.25
10TiB

**Comment by ailin-nemui** [comment] 2016-07-21 09:03
`error: attempt to write outside of (hd0)`

**Comment by marineam** [comment] 2016-07-21 17:48
Ok, so that's promising that the initial read worked. cgpt may be rejecting the secondary simply for being out of sync, but possible write is only partially working due to some off by one bug with the last sector. Are you still able to reproduce that cgpt segfault?

**Comment by ailin-nemui** [comment] 2016-07-21 18:25
It would segfault all of the time after grub corrupted the gpt

**Comment by marineam** [comment] 2016-07-27 20:03
I have been unable to break cgpt so far. If you have a chance capturing the core dump and/or the first and last 17408 bytes (34*512) of the disk prior to the cgpt crash would be helpful.

As for grub I did spot one potential bug that will be fixed in this week's alpha but I'm doubtful it is related to your bug since it shouldn't have left anything corrupted. At the very least the system will no longer attempt to boot with a blank uuid, stopping instead to keep any error messages visible.

**Comment by marineam** [comment] 2016-07-27 20:05
Likely we will just need to get the hardware ourselves, it's difficult to figure out what exactly the BIOS bug is and how to work around it remotely.

**Comment by marineam** [comment] 2016-10-04 21:18
Ok, I can confirm that the recent fix https://github.com/coreos/grub/pull/39 for another problem https://github.com/coreos/bugs/issues/1238#issuecomment-249030485 also fixes this part of this bug. Any system installed with CoreOS 1185 will be able to boot now.

Essentially the BIOS caps sizes at 2TiB (0xffffffff 512 byte sectors) despite the fact that the LBA BIOS interface has always used 64bit sectors. As such GRUB cannot update the backup GPT at the end of the volume. Now our code will skip the backup in this situation, depending on a later call to `cgpt repair` to fix the out-of-date backup GPT, issuing the following warning:

    warning: backup GPT located at 0x15d1fffff, beyond last disk sector at 0xfffffffe

cgpt is still segfaulting though so it isn't yet possible to repair after boot, currently working on that.

**Comment by marineam** [comment] 2016-10-04 21:44
Oh geez, this whole time the cgpt repair segfault was simply the result of not passing it a drive argument and it wasn't until today that I happened to make that same error.

**Comment by marineam** [comment] 2016-10-04 22:38
The next 1185 release adds the required cgpt repair command to coreos-setgoodroot so the backup GPT should always get fixed after boot. https://github.com/coreos/coreos-overlay/pull/2216

The cgpt segfault, being merely a usage error, will get fixed in the following alpha release.

**Closed by marineam** 2016-10-04 22:38 UTC
Labels: area/usability, component/grub, component/other, kind/bug, priority/P1, team/os
