### ISSUE TITLE
systemd-resolved[1826]: Failed to read DNS servers for interface eno1, ignoring: Argument list too long

### ISSUE THREAD

**Issue by rwky** [coreos/bugs#1456] opened 2016-07-12 20:33 UTC
# Issue Report #

Intermittently systemd-resolved reports `systemd-resolved[1826]: Failed to read DNS servers for interface eno1, ignoring: Argument list too long` and /etc/resolv.conf becomes empty.

### CoreOS Version ###

Beta 1068.3.0

###  Environment ###

Dedicated server

### Expected Behavior ###

No error and resolv.conf to remain as it was.

### Actual Behavior ###

resolv.conf is emptied

### Reproduction Steps ###

This sadly I've not figured out yet, I'm only seeing it on Beta since the update to 1068.3, however that could be a red herring, there are over 50 docker instances running on this server which is more than usual and could be a cause, I'm not sure if systemd-resolved is polling all instances and generating a list of dns servers from each. The system does have a static address config for the public interface which has two DNS lines 
```
DNS=8.8.4.4
DNS=8.8.8.8
```

**Comment by crawford** [comment] 2016-07-12 23:40
Can you attach the output of `cat "/run/systemd/netif/links/$(ip --oneline addr show dev eno1 | head --bytes 1)"`

**Comment by rwky** [comment] 2016-07-14 05:12
```
ADMIN_STATE=failed
OPER_STATE=routable
NETWORK_FILE=/etc/systemd/network/primary.network
DNS=8.8.4.4 8.8.8.8
NTP=
DOMAINS=
ROUTE_DOMAINS=
LLMNR=yes
MDNS=no
ADDRESSES=2001:41d0:1000:2ff:ec4:7aff:fe6b:f410/56 188.165.0.66/32 188.165.5.66/32 149.202.194.187/24
ROUTES=2001:41d0:1000:2ff:ff:ff:ff:ff/56/0/0/254/1539777205801380 ::/0/0/0/254/379161801380 0.0.0.0/0/0/0/253/18446744073709551615
```

Note currently /etc/resolv.conf is fine (but I haven't done anything on the machine since I fixed it).

**Comment by rwky** [comment] 2016-07-14 22:28
It did it again, the output from the command remains the same after it fails.

**Comment by TimothyKlim** [comment] 2016-07-27 15:06
Same error in `1109.1.0` version.

**Comment by vcaputo** [comment] 2016-08-02 01:02
This loop https://github.com/coreos/systemd/blob/v229-coreos/src/basic/fileio.c#L244 looks buggy to me in the case of short reads from `fread()`.  It always exponentially enlarges the buffer, assuming `fread()` filled what was available.

The way these files are written by systemd-networkd use a temporary file and atomic rename however, which should not produce a situation where things are being read while they're being written, so I'm not yet sure how short reads would be occurring to trigger this.

We may need to instrument the relevant code and supply you guys with a test binary for repro, since I haven't been able to reproduce it here myself.  Are the systems you're reproducing this on available for such an experiment?

**Comment by rwky** [comment] 2016-08-02 01:06
I've found this issue on two servers running CoreOS Beta (none running stable thankfully) both the beta servers run non-essential services so go ahead and provide test binaries and I'll happily help.

**Comment by vcaputo** [comment] 2016-08-02 19:15
Upon further investigation it appears more likely one of these is causing your error, these constants are both set at `32`:
https://github.com/coreos/systemd/blob/v229-coreos/src/resolve/resolved-dns-server.c#L57

If you could capture the output of this command:
`dbus-send --system --type=method_call --print-reply --dest=org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.DBus.Properties.GetAll string:org.freedesktop.resolve1.Manager` maybe we'll be able to see a large number of DNS servers approaching the constant of 32.

The aforementioned fread loop is buggy in the face of short reads, but those aren't likely occurring here, red herring.

**Comment by rwky** [comment] 2016-08-02 19:47
This is after the error has happened and resolv.conf is empty

```
s2 ~ # dbus-send --system --type=method_call --print-reply --dest=org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.DBus.Properties.GetAll string:org.freedesktop.resolve1.Manager
method return sender=:1.2428 -> dest=:1.4838 reply_serial=2
   array [
      dict entry(
         string "LLMNRHostname"
         variant             string "s2"
      )
      dict entry(
         string "DNS"
         variant             array [
            ]
      )
      dict entry(
         string "SearchDomains"
         variant             array [
            ]
      )
      dict entry(
         string "TransactionStatistics"
         variant             struct {
               uint64 0
               uint64 0
            }
      )
      dict entry(
         string "CacheStatistics"
         variant             struct {
               uint64 0
               uint64 0
               uint64 0
            }
      )
      dict entry(
         string "DNSSECStatistics"
         variant             struct {
               uint64 0
               uint64 0
               uint64 0
               uint64 0
            }
      )
      dict entry(
         string "DNSSECSupported"
         variant             boolean false
      )
   ]
```

This is after restarting systemd-resolved

```
s2 ~ # dbus-send --system --type=method_call --print-reply --dest=org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.DBus.Properties.GetAll string:org.freedesktop.resolv
e1.Manager
method return sender=:1.4841 -> dest=:1.4842 reply_serial=2
   array [
      dict entry(
         string "LLMNRHostname"
         variant             string "s2"
      )
      dict entry(
         string "DNS"
         variant             array [
               struct {
                  int32 2
                  int32 2
                  array of bytes [
                     08 08 04 04
                  ]
               }
               struct {
                  int32 2
                  int32 2
                  array of bytes [
                     08 08 08 08
                  ]
               }
            ]
      )
      dict entry(
         string "SearchDomains"
         variant             array [
            ]
      )
      dict entry(
         string "TransactionStatistics"
         variant             struct {
               uint64 0
               uint64 0
            }
      )
      dict entry(
         string "CacheStatistics"
         variant             struct {
               uint64 0
               uint64 0
               uint64 0
            }
      )
      dict entry(
         string "DNSSECStatistics"
         variant             struct {
               uint64 0
               uint64 0
               uint64 0
               uint64 0
            }
      )
      dict entry(
         string "DNSSECSupported"
         variant             boolean false
      )
   ]  
```

**Comment by vcaputo** [comment] 2016-08-02 19:52
well that's uninteresting

**Comment by ajeddeloh** [comment] 2016-08-02 20:03
It looks the n_dns_servers isn't be decremented here: https://github.com/coreos/systemd/blob/v229-coreos/src/resolve/resolved-dns-server.c#L156 . Looks like it's been fixed upstream by: https://github.com/systemd/systemd/commit/0e3e1aefebffdd97befd06586d055c5996697eed

**Comment by vcaputo** [comment] 2016-08-02 20:04
nice find @ajeddeloh

**Comment by rwky** [comment] 2016-08-02 20:12
:+1: if you want me to try a test build with the patch applied then yell.

**Comment by crawford** [comment] 2016-08-23 04:12
Fixed via https://github.com/coreos/systemd/pull/56.

**Closed by crawford** 2016-08-23 04:12 UTC
Labels: area/usability, component/systemd, kind/bug, priority/P2, team/os
