### ISSUE TITLE
Hostname Invalid Output

### ISSUE THREAD

**Issue by Blackglade** [coreos/bugs#1764] opened 2017-01-16 02:58 UTC
# Issue Report #

## Bug ##
`hostname -s` returns hostname: Unknown Error when on most Distro's I've tested, it usually returns the original hostname

### CoreOS Version ###
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.6.0
VERSION_ID=1235.6.0
BUILD_ID=2017-01-10-0545
PRETTY_NAME="Container Linux by CoreOS 1235.6.0 (Ladybug)"
```
### Environment ###

Digital Ocean 1GB Droplet

### Expected Behavior ###
hostname -s is expected to return the original hostname if no short version is found

### Actual Behavior ###
`hostname: Unknown host`

### Reproduction Steps ###

Type hostname -s

**Comment by crawford** [comment] 2017-02-24 15:52
I'm unable to reproduce the issue on the latest Alpha.

```
core@apollo ~ $ hostname -s
apollo
```

```
core@apollo ~ $ cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1325.1.0
VERSION_ID=1325.1.0
BUILD_ID=2017-02-23-0035
PRETTY_NAME="Container Linux by CoreOS 1325.1.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

Could you try again?

**Comment by Blackglade** [comment] 2017-03-07 17:07
Tested this again on the latest Alpha (1339.0.0) as well and got the same issue!
![test](https://cloud.githubusercontent.com/assets/6363077/23668294/9f2d76c0-032e-11e7-95ad-6e8be742aee2.png)

**Comment by euank** [comment] 2017-03-07 21:27
`hostname -s` on Gentoo, and subsequently Container Linux, ends up using the "gethostname" syscall which also ends up doing network-stuff by default.

There are a number of ways this can be fixed.

### nsswitch hostname config

Update /etc/nsswitch.conf's "hosts" line to be the following: `hosts:       files usrfiles dns myhostname`.
Note that it's a symlink to `/usr`/, so it'll have to be clobbered.

This will allow `hostname` and `hostname -s` (and actually `hostname -i`) to succeed without them resolving normally.

It's possible this should be the default on Container Linux and we just haven't bothered to make it so yet.

### /etc/hosts

Appending "$public_ip4    $my_hostname" to `/etc/hosts` should work as well.

Alternately, if `hostname -i` can be wrong, adding the hostname as the first entry after `127.0.0.1` will also have `hostname -s` work (order does matter! if it's not first you'll get 'localhost' for it).

### Actual valid dns

This one won't work on DO necessarily, but I solve this for myself by running a dns resolver for my VMs which contains a mapping of ip<->hostname and can resolve those locally.

-------

Hopefully one of those things helps.

@crawford adding `myhostname` to the default nsswitch config for `hosts` would probably be less confusing for most people; any reason we shouldn't?

**Comment by crawford** [comment] 2017-03-08 00:18
Nope, let's go ahead and add it.

**Comment by euank** [comment] 2017-03-14 19:01
The nsswitch.conf change I mentioned above should be set by default in the next Container Linux alpha release.

In the meanwhile, any of the options I mentioned should work on existing releases.

**Closed by euank** 2017-03-14 19:01 UTC
Labels: area/usability, component/other, team/os
