### ISSUE TITLE
CoreOS VMs on Azure drop network when overlay vxlan is under load

### ISSUE THREAD

**Issue by nordbergm** [coreos/bugs#1156] opened 2016-03-06 15:58 UTC
We've set up a 3 node CoreOS cluster on Azure with a Flannel vxlan overlay network. Everything works fine initially when trying to ping containers over flannel, however as soon as network traffic increases, the VMs lose network connectivity.

What we can see the VMs are still running, but you can no longer SSH into the VM and etcd logs fill up with connection errors to other cluster members.

Here's how we're able to reproduce the issue:

1. Start a 3 node CoreOS Stable (835.13.0) cluster in an Azure virtual network. In our case West US region with vnet subnet `172.16.0.0/16` and the following flannel config `{ "Network": "10.0.0.0/16", "SubnetLen": 25, "Backend": { "Type": "vxlan" } }`
1. Start a qperf container on two separate VMs `docker run -ti tobwiens/ubuntu-qperf`
1. In the first container, run `qperf`
1. In the second container, run `qperf -t 10 <first container ip> tcp_bw udp_lat`

The first container's qperf eventually prints `qperf failed to receive synchronization after test: timed out` and the second container VM becomes unresponsive.

The same steps run without a hitch on AWS, this only seems to be a problem for us on Azure. 
I wasn't sure if the problem was with Azure or Flannel, so I tried Flannel's default UDP backend, and that worked fine.

I then tried Weave's vxlan (fast datapath) and that caused the same problem as with Flannel vxlan, ruling out Flannel I would think.

Out of curiosity I started two CentOS 7.1 VMs in the same Azure vnet, installed Docker (1.10) and Weave (1.4.5) and ran the same qperf test that caused the previous network issues. This however worked without an issue and the qperf test completed successfully.

Since it seems to work on CentOS I assume that the issue is somewhere in CoreOS or its compatibility with Azure. Any thoughts?

**Comment by crawford** [comment] 2016-03-08 03:37
Thanks for the clear bug report and simple repro case. I was able to reproduce this with CoreOS 835.13.0 (current Stable) and 899.9.0 (current Beta), but not 976.0.0 (current Alpha).

@nordbergm would you mind using Alpha in the mean time while we promote the 4.4 kernel through Beta and Stable?

**Comment by crawford** [comment] 2016-03-08 03:38
Heh, go figure. As soon as I sent that, the 976.0.0 machine failed as well.

**Comment by crawford** [comment] 2016-03-08 03:39
I'll loop in the Azure folks and see if we can't figure out what's going on here.

**Comment by nordbergm** [comment] 2016-03-08 08:28
@crawford Thanks for looking into this so quickly. Let me know if there's anything I can do to help test and if you need more information.

**Comment by crawford** [comment] 2016-03-24 23:17
It looks like the relevant patches (https://github.com/coreos/linux/commit/757647e10e55c01fb7a9c4356529442e316a7c72, https://github.com/coreos/linux/commit/a060679c6b3da17dc9e95d0500f811de118ec901, and https://github.com/coreos/linux/commit/c85e4924452ae8225c8829f3fa8a2f7baa34bc5c) made it into Linux 4.5. I think we can pull that in next week.

**Comment by nordbergm** [comment] 2016-04-05 13:43
Thanks, that's great. Look forward to trying it out in the alpha channel.

**Comment by crawford** [comment] 2016-04-05 21:46
Should be fixed by https://github.com/coreos/coreos-overlay/pull/1867.

**Closed by crawford** 2016-04-05 21:46 UTC
Labels: area/usability, component/kernel, kind/bug, priority/P1, team/os
