### ISSUE TITLE
Upgrade to CoreOS Alpha 1339.0.0 breaks connectivity to node-exporter container after instance reboot

### ISSUE THREAD

**Issue by wilkko** [coreos/bugs#1844] opened 2017-03-06 07:35 UTC
# Issue Report #

After upgrading to CoreOS Alpha 1339.0.0 our Swarm instances were rebooted.
Our monitoring solution Prometheus reported that instances were down. Upon investigating everything seemed to be running fine and also node-exporter container was up and running. Seems that Prometheus cannot connect to the node-exporter endpoint after instance reboot unless node-exporter containers are restarted.

### Container Linux Version ###

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1339.0.0
VERSION_ID=1339.0.0
BUILD_ID=2017-03-01-2346
PRETTY_NAME="Container Linux by CoreOS 1339.0.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

AWS CoreOS-beta-1235.1.0-hvm (ami-abebb5d8) as a starting point.

### Expected Behavior ###

Node-exporter containers should stay connectable after instance reboot.

### Actual Behavior ###

Node-exporter containers cannot be connected.

### Reproduction Steps ###

  1. Run node exporter container

```
docker run -d -p 9100:9100 \
  -v "/proc:/host/proc" \
  -v "/sys:/host/sys" \
  -v "/:/rootfs" \
  --net="host" \
  --name node-exporter \
  --restart always \
  prom/node-exporter:0.12.0 \
    -collector.procfs /host/proc \
    -collector.sysfs /host/sys \
    -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($|/)"
```
  2. cUrl to http://_instanceIP_:9100/metrics --> SUCCESS
  3. Reboot instance (sudo reboot -h now)
  4. cUrl to http://_instanceIP_:9100/metrics --> FAILURE
  5. docker restart node-exporter
  6. cUrl to http://_instanceIP_:9100/metrics --> SUCCESS

**Comment by tazle** [comment] 2017-03-06 07:57
node-exporter itself responds (curl to http://instanceIP:9100/) but /metrics gets stuck trying to stat /proc/sys/fs/binfmt_misc of the host.

Indeed any operation on /proc/sys/fs/binfmt_misc seems to block forever. E.g. readlink on it gets stuck. The last five calls of the readilnk syscall within kernel were:
```
readlink-12324 [001] .... 7613110.327497: __d_lookup_rcu <-lookup_fast
readlink-12324 [001] .... 7613110.327497: complete_walk <-path_lookupat
readlink-12324 [001] .... 7613110.327498: unlazy_walk <-complete_walk
readlink-12324 [001] .... 7613110.327498: legitimize_mnt <-unlazy_walk
readlink-12324 [001] .... 7613110.327498: __legitimize_mnt <-legitimize_mnt
```

**Comment by lucab** [comment] 2017-03-06 08:47
This sounds suspiciously similar to https://github.com/coreos/bugs/issues/1630.

**Comment by tazle** [comment] 2017-03-06 17:13
Currently all the CoreOS nodes are able to stat /proc/sys/fs/binfmt_misc just fine. If/when this reoccurs, we can try to get a bit deeper on what `__legitimize_mnt` is doing.

**Comment by wilkko** [comment] 2017-03-06 17:17
It reoccurs immediately after instance reboot. As a temporary workaround I forced Ansible to restart the node-exporter containers and CoreOS update reboot policy was set to `off`.

**Comment by tazle** [comment] 2017-03-06 17:30
Let's take a look at it on one of the nodes tomorrow or the day after, to figure out why restarting the node-exporter container has this kind of effect on the host, and what happens if the container is not started in the first place.

**Comment by euank** [comment] 2017-03-06 19:38
Adding a `Requires=proc-sys-fs-binfmt_misc.automount` and `After=proc-sys-fs-binfmt_misc.automount` to the docker daemon unit might work around this if the problem is caused by racing with that mount somehow.

**Comment by wilkko** [comment] 2017-03-08 08:49
@euank Should the workaround work in the drop-in configuration like this?

```
core@coreos-3 ~ $ cat /etc/systemd/system/docker.service.d/docker.conf 
[Service]
Environment="DOCKER_OPTS=--log-opt max-size=10m --log-opt max-file=1 --host tcp://0.0.0.0:2375"

[Unit]
Requires=proc-sys-fs-binfmt_misc.automount
After=proc-sys-fs-binfmt_misc.automount
```
https://coreos.com/os/docs/latest/customizing-docker.html

I did not yet see an improvement with that configuration.

**Comment by wilkko** [comment] 2017-03-08 08:57
This seemed to do the trick.

```
core@coreos-3 ~ $ cat /etc/systemd/system/docker.service.d/docker.conf 
[Unit]
Wants=proc-sys-fs-binfmt_misc.mount
After=proc-sys-fs-binfmt_misc.mount
```

**Comment by crawford** [comment] 2017-03-20 22:21
I haven't been able to reproduce this issue. I'd suggest that the service for the prometheus exporter include:

```ini
[Unit]
After=proc-sys-fs-binfmt_misc.automount
```

This is how `systemd-binfmt.service` declares the dependency. Since it looks like this strategy worked for you, I'm going to go ahead and close this out.

**Closed by crawford** 2017-03-20 22:21 UTC
Labels: area/usability, component/docker, component/kernel, kind/friction, priority/P0, team/os
