### ISSUE TITLE
CoreOS 1153.4.0 seems to have no outgoing connections inside docker containers

### ISSUE THREAD

**Issue by DeviaVir** [coreos/bugs#1585] opened 2016-09-26 12:58 UTC
# Issue Report #
It looks like CoreOS 1153.X does not allow outgoing connections on dockers anymore (at all).

### CoreOS Version ###

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1153.4.0
VERSION_ID=1153.4.0
BUILD_ID=2016-09-10-0107
PRETTY_NAME="CoreOS 1153.4.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

### Environment ###

AWS t2.micro

### Expected Behavior ###
```
$ docker run -it --rm alpine /usr/bin/wget google.com
Connecting to google.com (216.58.216.142:80)
Connecting to www.google.com (74.125.28.105:80)
index.html           100% |***********************************************************************************************************************************************************************************************************************************************************************************************| 11074   0:00:00 ETA
```
### Actual Behavior ###
```
$ docker run -it --rm alpine /usr/bin/wget google.com
wget: bad address 'google.com'
```
### Reproduction Steps ###

  1. `$ docker run -it --rm alpine /usr/bin/wget google.com`
  2. observe output

### Other Information ###
- Can this have something to do with NAT? The host itself has internet connectivity (it can successfully download `alpine`) the dockers do not.
- This might be related to #1574.
- Definitely related to #1554, now as-is reproducible.

**Comment by crawford** [comment] 2016-09-26 16:45
I'm pretty sure this is a duplicate of https://github.com/coreos/bugs/issues/1554. Can you try stopping networkd (`systemctl stop systemd-networkd`) and then re-running your Docker command? If it succeeds it is a duplicate.

**Comment by DeviaVir** [comment] 2016-09-26 18:18
@crawford does not seem to have an impact:

```
$ sudo systemctl stop systemd-networkd
Warning: Stopping systemd-networkd.service, but it can still be activated by:
  systemd-networkd.socket
$ docker run -it --rm alpine /usr/bin/wget google.com
wget: bad address 'google.com'
```

**Comment by dm0-** [comment] 2016-09-26 18:39
The service should probably be masked to test this to avoid its socket activation (i.e. running a Docker command will start it again).  Try one of these two things.

    systemctl mask systemd-networkd
    systemctl stop systemd-networkd
    for ((i=0; i<10; i++)) ; do docker run --rm busybox wget http://google.com/ || break ; done
    [ $i -ge 10 ] || echo Failed at $i
    systemctl unmask systemd-networkd  # Undo

Or, this which will make networkd ignore the Docker interfaces.  (Double-check you don't have custom configuration files in `/etc/systemd/network` that this would clobber.)

    for x in /usr/lib/systemd/network/[5yz]*.network ; do ln -s /dev/null /etc/systemd/network/${x##*/} ; done
    systemctl restart systemd-networkd
    for ((i=0; i<10; i++)) ; do docker run --rm busybox wget http://google.com/ || break ; done
    [ $i -ge 10 ] || echo Failed at $i
    rm -f /etc/systemd/network/*.network  # Undo

I could still see this being #1554.  The race condition involved has been causing the failure in nearly 100% of the Docker commands in some of my testing.

**Comment by DeviaVir** [comment] 2016-09-27 08:57
@dm0- I could reproduce with your first steps, aye. Do you wish to keep this issue open for visibility (seeing #1554 closed without a "fix" available), or do you want me to close this?

**Comment by crawford** [comment] 2016-09-27 16:51
We can go ahead and close this. CoreOS Linux 1180.0.0 should be available shortly with the fix.

**Closed by crawford** 2016-09-27 16:51 UTC
Labels: area/usability, component/docker, team/os

**Comment by DeviaVir** [comment] 2016-09-27 17:24
@crawford cool, looking forward! Soon as it's out you might want to ping #1574 to give that version a try, I think it's related.
