### ISSUE TITLE
ignition file mode interpretation

### ISSUE THREAD

**Issue by Hackebein** [coreos/bugs#2389] opened 2018-03-26 21:19 UTC
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.3.0
VERSION_ID=1632.3.0
BUILD_ID=2018-02-14-0338
PRETTY_NAME="Container Linux by CoreOS 1632.3.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###

VMware ESXi 6.0

### Expected Behavior ###

File permissions 204

### Actual Behavior ###

File permissions 644

### Reproduction Steps ###

  1. Write Ignition file
```
{
	"ignition": {
		"version": "2.1.0"
	},
	"storage": {
		"files": [
			{
				"filesystem": "root",
				"path": "/test",
				"contents": {
					"source": "tftp://x.x.x.x/test"
				},
				"mode": 644
			}
		]
	}
}
```
  2. boot CoreOS with Ignition file via ipxe
```
kernel ${coreos-download-kernel} initrd=${coreos-initrd-filename} quiet coreos.first_boot=1 coreos.config.url=${coreos-config-url} coreos.autologin=tty1 vga=0x305
initrd ${coreos-download-initrd}
```
  3. check permissions
```
$ stat /test
  File: '/test'
  Size: 511             Blocks: 8          IO Block: 4096   regular file
Device: 24h/36d Inode: 10823       Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:tmpfs_t:s0
Access: 2018-03-26 19:52:46.220705241 +0000
Modify: 2018-03-26 19:52:46.220705241 +0000
Change: 2018-03-26 19:52:46.220705241 +0000
 Birth: -
```

### Other Information ###
On the first boot processes i doesn't recognize the note "Note that the mode must be properly specified as a decimal value (i.e. 0644 -> 420)". After systemd units no longer start processes i started to search.

The error is very rare. The reproduction steps are not safe to reproduce the error. I do not know how many times i have restarted the machine to reproduce this error.

#### My Original file (EOL [CR][LF]) ####
```
{
	"ignition": {
		"version": "2.1.0"
	},
	"storage": {
		"disks": [
			{
				"device": "/dev/sda",
				"wipeTable": true,
				"partitions": [
					{
						"label": "DOCKER",
						"number": 1
					}
				]
			}
		],
		"filesystems": [
			{
				"name": "dockerlib",
				"mount": {
					"device": "/dev/disk/by-partlabel/DOCKER",
					"format": "ext4",
					"wipeFilesystem": false
				}
			}
		],
		"files": [
			{
				"filesystem": "root",
				"path": "/etc/systemd/system/var-lib-docker.mount",
				"contents": {
					"source": "tftp://x.x.x.x/stable/sysroot/etc/systemd/system/var-lib-docker.mount"
				},
				"mode": 644
			}, {
				"filesystem": "root",
				"path": "/etc/systemd/system/open-vm-tools.service",
				"contents": {
					"source": "tftp://x.x.x.x/stable/sysroot/etc/systemd/system/open-vm-tools.service"
				},
				"mode": 644
			}, {
				"filesystem": "root",
				"path": "/etc/systemd/system/rancher-server-v1.service",
				"contents": {
					"source": "tftp://x.x.x.x/stable/sysroot/etc/systemd/system/rancher-server-v1.service"
				},
				"mode": 644
			}, {
				"filesystem": "root",
				"path": "/etc/systemd/system/rancher-server-v2.service",
				"contents": {
					"source": "tftp://x.x.x.x/stable/sysroot/etc/systemd/system/rancher-server-v2.service"
				},
				"mode": 644
			}, {
				"filesystem": "root",
				"path": "/etc/systemd/system/rancher-agent-v1.service",
				"contents": {
					"source": "tftp://x.x.x.x/stable/sysroot/etc/systemd/system/rancher-agent-v1.service"
				},
				"mode": 644
			}, {
				"filesystem": "root",
				"path": "/etc/systemd/system/rancher-agent-v2.service",
				"contents": {
					"source": "tftp://x.x.x.x/stable/sysroot/etc/systemd/system/rancher-agent-v2.service"
				},
				"mode": 644
			}, {
				"filesystem": "root",
				"path": "/etc/systemd/system/docker.service.d/10-var-lib-docker.mount.conf",
				"contents": {
					"source": "tftp://x.x.x.x/stable/sysroot/etc/systemd/system/docker.service.d/10-var-lib-docker.mount.conf"
				},
				"mode": 644
			}
		]
	},
	"passwd": {
		"users": [
			{
				"name": "core",
				"sshAuthorizedKeys": [
					"ssh-rsa AAAA..."
				]
			}
		]
	},
	"systemd": {
		"units": [
			{
				"name": "var-lib-docker.mount",
				"enabled": true
			}, {
				"name": "open-vm-tools.service",
				"enabled": true
			}, {
				"name": "rancher-server-v1.service",
				"enabled": false
			}, {
				"name": "rancher-server-v2.service",
				"enabled": true
			}, {
				"name": "rancher-agent-v1.service",
				"enabled": false
			}, {
				"name": "rancher-agent-v2.service",
				"enabled": false
			}
		]
	}
}
```

**Comment by lucab** [comment] 2018-03-27 07:42
I'm closing this as a duplicate of https://github.com/coreos/bugs/issues/1729.

As explained in https://github.com/coreos/bugs/issues/1729#issuecomment-376272766 JSON integers only support base-10 notation.

**Comment by lucab** [comment] 2018-03-27 08:06
As a sidenote, the original report is a bit confused as it shows an ignition config with `mode: 644` and a `stat` with `0644` (which is apparently fine, but it isn't the specified ignition behavior). Also, a few other details are off (expected/actual behavior and mode value).

I'm just assuming this concerns the octal/decimal discussion above, but feel free to correct me if wrong.

**Comment by Hackebein** [comment] 2018-03-27 09:38
It's not a duplicate of #1729.

The data confused me, too. `mode: 644` and `stat` with `0644` are real data, that's the Bug! I don't know how to trigger it. The Bug is very Rare.

I try to explain again what's going on. On the first try with Ignition i use the systemd unit section in the JSON for the content. I realize that the file content in JSON makes the config unreadable. I `stat` the files in `/etc/systemd/system/` and try to get the same result if i download the file from the tftp server. On the next boot i doesn't set the `mode` and by checking with `stat` and get `0000`. I check out the documentation and only read the first part of mode. On next boot i write `mode: 644` (see original report "My Original file (EOL [CR][LF])"), `stat` the files again and get `0644`. I used rancher-server and open-vm-tools, without touching any file from systemd. 2 boot processes later i woundering about that my systemd services doesn't start anymore. I start searching about the problem. I `stat` the downloaded systemd files again and get `0204`. First i think the Bug is that i get `0204`, but after reading the second part of `mode`, i realize that the bug was early that i get `0644`.

**Comment by lucab** [comment] 2018-03-27 10:03
As you are writing and activating systemd service, there are likely other processes (e.g. systemd or rancher) which may try to repair permissions if they are clearly off.

Is the barebone `/test` configuration actually enough to reproduce it or did you manually synthesize it? Are you always running in this diskless PXE environment?

**Comment by Hackebein** [comment] 2018-03-27 10:49
The barebone `/test` configuration is synthesize. I still running in PXE enviroment. 5 of 7 loaded files starts only a docker container. The other 2 files mount /dev/disk/by-partlabel/DOCKER to /var/lib/docker and add a wait-for-mount. All other is default CoreOS. I'm not deep enough in systemd to know if systemd fixes file permissions. A quick google search and checking out the Issue section of systemd on github results into no one is writing about systemd fixes file permissions. Only `systemd-nspawn` seems to have some bugs like systemd/systemd#3547. Do CoreOS use `systemd-nspawn`?

**Comment by ajeddeloh** [comment] 2018-03-27 19:30
Container Linux doesn't do anything with nspawn by default. I exists and can be used, but it doesn't launch anything in it automatically. Do you have logs from a failed system?

**Comment by Hackebein** [comment] 2018-03-27 19:46
Unfortunately not, because I have not noticed the bug until after I have the virtual machine back to Snapshoot law back

**Comment by lucab** [comment] 2018-04-06 13:14
@Hackebein can you please try to reproduce this with your actual minimal example from original "Reproduction Steps" section? If you still get unexpected mode, please attach [logs from igntion](https://coreos.com/ignition/docs/latest/getting-started.html#gathering-logs).

**Comment by Hackebein** [comment] 2018-04-06 14:08
i'll try it after the weekend

**Comment by Hackebein** [comment] 2018-04-09 16:28
I can't reproduce it.
I'm not sure, because i run near the the available ram limit of the ESXi host at the issue report day. I think it was just a local issue.
What I do not understand is why it worked several times. That's a very big coincidence.

**Comment by lucab** [comment] 2018-04-11 09:47
Lacking any further reproducer, I'm going to close this ticket for the moment.
If anybody is hitting this, please open a new bug and attach a minimal ignition configuration together with logs from the node being provisioned.

**Closed by lucab** 2018-04-11 09:47 UTC
Labels: component/ignition, kind/bug, needs/repro, team/tools
