### ISSUE TITLE
broken yum-based images

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#615] opened 2015-09-23 19:58 UTC
<a href="https://github.com/ibukanov"><img src="https://avatars.githubusercontent.com/u/2381216?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ibukanov](https://github.com/ibukanov)**
_Friday Mar 20, 2015 at 06:54 GMT_
_Originally opened as https://github.com/coreos/coreos-overlay/issues/1153_

---

Switch to overlayfs broke containers using the yum to install packages, see docker/docker#10180. To reproduce on all CoreOS channels, run:

```
docker run -ti --rm fedora yum install -y firefox
```

That eventually gives:

```
Rpmdb checksum is invalid: dCDPT(pkg checksums): libXxf86vm.x86_64 0:1.1.3-4.fc21 - u
```

As it is not clear if this is a docker issues or one of the hard to fix problems with overlaysfs that could take a while to fix, see https://lwn.net/Articles/636943/ , a workaround should be provided.

Currently the only way to proceed with yum is to replace the original yum command with a sequence like:

```
rpm --rebuilddb && yum install -y xorg-x11-xkb-utils  && rpm --rebuilddb && yum install -y firefox
```

where that chain can be rather long (for my container I had to split the yum install into 7 pieces) and it is not clear if newer image updates would require more splits.

**Comment by crawford** [comment] 2015-09-23 19:58
<a href="https://github.com/AntonioMeireles"><img src="https://avatars.githubusercontent.com/u/743527?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AntonioMeireles](https://github.com/AntonioMeireles)**
_Friday Mar 20, 2015 at 11:34 GMT_

----

fwiw - looks like upstream docker is working on it - docker/docker#11422. eventually worth a backport, perhaps... (assuming it fixes this for real ...)

**Comment by crawford** [comment] 2015-09-23 19:58
<a href="https://github.com/AntonioMeireles"><img src="https://avatars.githubusercontent.com/u/743527?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AntonioMeireles](https://github.com/AntonioMeireles)**
_Monday Mar 30, 2015 at 18:29 GMT_

----

@marineam @crawford any chance of backporting the alleged fix (docker/docker#11422) until CoreOS ships docker 1.6 ?

**Comment by crawford** [comment] 2015-09-23 19:58
<a href="https://github.com/hany"><img src="https://avatars.githubusercontent.com/u/26979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hany](https://github.com/hany)**
_Monday Mar 30, 2015 at 18:34 GMT_

----

+1 on this as well.

**Comment by crawford** [comment] 2015-09-23 19:58
<a href="https://github.com/marineam"><img src="https://avatars.githubusercontent.com/u/153640?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marineam](https://github.com/marineam)**
_Monday Mar 30, 2015 at 19:07 GMT_

----

@mischief Could you look into this and see what docker/docker#11422 issues this may fix or cause?

We need to write up a doc on all the things that tend to break with overlay (unix sockets being another one) and how to work around them and how to use docker with a local btrfs loopback file.

**Comment by crawford** [comment] 2015-09-23 19:58
<a href="https://github.com/mischief"><img src="https://avatars.githubusercontent.com/u/1487996?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mischief](https://github.com/mischief)**
_Monday Mar 30, 2015 at 19:15 GMT_

----

@marineam i have applied the patch locally, and i will test it out.

**Comment by crawford** [comment] 2015-09-23 19:58
<a href="https://github.com/mischief"><img src="https://avatars.githubusercontent.com/u/1487996?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mischief](https://github.com/mischief)**
_Monday Mar 30, 2015 at 22:00 GMT_

----

@AntonioMeireles i tested the commit here, https://github.com/docker/docker/pull/11422. unfortunately i still get a very similar error to what @ibukanov originally posted, "Rpmdb checksum is invalid: dCDPT(pkg checksums): nss-softokn-freebl.x86_64 0:3.18.0-1.fc21 - u". seems like this needs more work/investigating.

**Comment by crawford** [comment] 2015-09-23 19:58
<a href="https://github.com/AntonioMeireles"><img src="https://avatars.githubusercontent.com/u/743527?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AntonioMeireles](https://github.com/AntonioMeireles)**
_Monday Mar 30, 2015 at 22:13 GMT_

----

@mischief at sight, it seems that for this to vanish one *may*  also need the underlying kernel to have multi read-only layers support in overlayfs too... (and so far that is only available in 4.0 :disappointed: ...)

**Comment by crawford** [comment] 2015-09-23 19:58
<a href="https://github.com/marineam"><img src="https://avatars.githubusercontent.com/u/153640?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [marineam](https://github.com/marineam)**
_Tuesday Mar 31, 2015 at 01:55 GMT_

----

Oh, they are switching to using the layering? Awesome. That itself will ease some issues. We'll need to review this more...

**Comment by crawford** [comment] 2015-09-23 19:58
<a href="https://github.com/ibukanov"><img src="https://avatars.githubusercontent.com/u/2381216?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ibukanov](https://github.com/ibukanov)**
_Tuesday May 05, 2015 at 06:43 GMT_

----

This is still broken with CoreOS 668.2.0 with kernel 4.0 and docker 1.6.0

**Comment by crawford** [comment] 2015-09-23 19:58
<a href="https://github.com/charliedrage"><img src="https://avatars.githubusercontent.com/u/6422176?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [charliedrage](https://github.com/charliedrage)**
_Tuesday May 26, 2015 at 16:55 GMT_

----

Cross-referencing this from Docker,

But seems that there is an overlayfs kernel patch that fixes these issues. https://github.com/docker/docker/issues/10180

direct link: https://github.com/portworx/overlayfs

**Comment by crawford** [comment] 2015-10-19 21:20
Is this still an ongoing issue?

**Comment by kbrwn** [comment] 2015-10-19 23:51
This was encountered today by a user on 766.4.0 with this [Dockerfile](https://gist.github.com/kbrwn/ea7c0e8963e323558d02). Reproduced on 835.1.0 as well.

**Comment by mischief** [comment] 2015-10-20 00:00
@crawford @kbrwn it is a *known* issue in docker/overlayfs and there is not a solution. see https://github.com/docker/docker/issues/10180

**Comment by euank** [comment] 2017-07-20 00:17
This issue hasn't seen activity in a while.

I'm going to optimistically close this since I think all the yum based distros now include the `ovl` plugin which works around this suitably well.

We also have https://github.com/coreos/bugs/issues/285 which I think tracks the overlay2 bugs well enough.

**Closed by euank** 2017-07-20 00:17 UTC
Labels: component/distro, component/docker, kind/bug, priority/P1, team/os
