### ISSUE TITLE
Kubernetes broken on stable channel (Flanneld)

### ISSUE THREAD

**Issue by eskaaren** [coreos/bugs#1938] opened 2017-04-27 15:08 UTC
# Issue Report #

### Container Linux Version ###

```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.7.0
VERSION_ID=1353.7.0
BUILD_ID=2017-04-26-2154
PRETTY_NAME="Container Linux by CoreOS 1353.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###

What hardware/cloud provider/hypervisor is being used to run Container Linux?
vsphere 6

### Expected Behavior ###
Working kubernetes cluster.

### Actual Behavior ###
Flanneld was unable to start after the Container Linux automatic upgrade.

### Reproduction Steps ###

  1. Have Kubernetes working on CoreOs version prior to april 26.
  2. Do the CoreOS upgrade, now you have a broken kubernetes cluster.

"Fix" by doing this on all nodes:
```# cat /usr/lib/systemd/system/flanneld.service > /etc/systemd/system/flanneld.service```
```# cat /usr/lib/systemd/system/flannel-docker-opts.service > /etc/systemd/system/flannel-docker-opts.service```

In those files downgrade Flannel to 0.6.2:
```Environment="FLANNEL_IMAGE_TAG=v0.6.2"```

Reboot

### Other Information ###
Upgraded hypercube images from 1.5.3 to 1.5.4.
Tried with 1.6.1 but that did not work.

**Comment by eskaaren** [comment] 2017-04-27 15:12
I have read somewhere in another bug report that Flannel 0.7.0 possibly needs docker 1.13 for Kubernetes.

**Comment by euank** [comment] 2017-04-27 15:54
My 1353.7.0 / flannel=0.7.0 cluster works. Flannel 0.7.0 doesn't need docker 1.13.

I'm using the kubelet with `--network-plugin=cni` and `KUBELET_VERSION=v1.5.6_coreos.0`.

Otherwise it's all pretty normal.

Can you provide a little more information, specifically what your kubelet configuration is (network plugin especially) and what flannel's logs and `systemctl status` look like?

Thanks!

**Comment by eskaaren** [comment] 2017-04-27 16:22
The cluster was set up by following the guide on https://coreos.com/kubernetes/docs/latest/getting-started.html.

I don't have printouts from earlier this morning byt the first symptoms were a lot of container not found and file path too long and the rkt gc could not delete the garbage. (The system was not working at this point.)

This was when I saw that an update had happened and I also saw that the flannel 0.7.0 image had been pulled.

Kubelet config:
```# cat /etc/systemd/system/kubelet.service
[Service]
Environment=KUBELET_IMAGE_TAG=v1.5.4_coreos.0
Environment=KUBELET_IMAGE_URL=quay.io/coreos/hyperkube
Environment="RKT_RUN_ARGS=--uuid-file-save=/var/run/kubelet-pod.uuid \
  --volume dns,kind=host,source=/etc/resolv.conf
  --mount volume=dns,target=/etc/resolv.conf \
  --volume rkt,kind=host,source=/opt/bin/host-rkt \
  --mount volume=rkt,target=/usr/bin/rkt \
  --volume var-lib-rkt,kind=host,source=/var/lib/rkt \
  --mount volume=var-lib-rkt,target=/var/lib/rkt \
  --volume stage,kind=host,source=/tmp \
  --mount volume=stage,target=/tmp \
  --volume var-log,kind=host,source=/var/log \
  --mount volume=var-log,target=/var/log"
ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
ExecStartPre=/usr/bin/mkdir -p /opt/cni/bin
ExecStartPre=/usr/bin/mkdir -p /var/log/containers
ExecStartPre=-/usr/bin/rkt rm --uuid-file=/var/run/kubelet-pod.uuid
ExecStart=/usr/lib/coreos/kubelet-wrapper \
  --api-servers=http://127.0.0.1:8080 \
  --register-schedulable=false \
  --cni-conf-dir=/etc/kubernetes/cni/net.d \
  --network-plugin=cni \
  --container-runtime=docker \
  --rkt-path=/usr/bin/rkt \
  --rkt-stage1-image=coreos.com/rkt/stage1-coreos \
  --allow-privileged=true \
  --pod-manifest-path=/etc/kubernetes/manifests \
  --hostname-override=172.25.100.214 \
  --cluster_dns=172.201.0.10 \
  --cluster_domain=cluster.local
ExecStop=-/usr/bin/rkt stop --uuid-file=/var/run/kubelet-pod.uuid
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target```

Obviously everything is working now after the flannel downgrade, and this is an internal production system so I can't take it offline again.

I could try upgrading the kubelet to 1.5.6_coreos.0 on one of the cluster managers though.

**Comment by eskaaren** [comment] 2017-04-27 16:43
OK so here is what happened:

I updated the config files with flannel 0.7.0 and kubelet 1.5.6_coreos.0 and rebooted the server.
After it had downloaded the new image i tried docker ps, but that just timed out (i did ctrl+c).
I then rebooted once more.
Docker ps still hangs, and the api container does not work:
```curl http://127.0.0.1:8080/version
curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused```

Systemctl status docker says "failed with result 'dependency'".

Systemctl status flanneld;

```● flanneld.service - flannel - Network fabric for containers (System Application Container)
   Loaded: loaded (/etc/systemd/system/flanneld.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/flanneld.service.d
           └─40-ExecStartPre-symlink.conf.conf
   Active: activating (start) since Thu 2017-04-27 16:40:41 UTC; 10s ago
     Docs: https://github.com/coreos/flannel
  Process: 1484 ExecStartPre=/usr/bin/ln -sf /etc/flannel/options.env /run/flannel/options.env (code=exited, status=0/SUCCESS)
  Process: 1460 ExecStartPre=/usr/bin/rkt rm --uuid-file=/var/lib/coreos/flannel-wrapper.uuid (code=exited, status=254)
  Process: 1456 ExecStartPre=/usr/bin/mkdir --parents /var/lib/coreos /run/flannel (code=exited, status=0/SUCCESS)
  Process: 1446 ExecStartPre=/sbin/modprobe ip_tables (code=exited, status=0/SUCCESS)
 Main PID: 1488 (flanneld)
    Tasks: 7 (limit: 32768)
   Memory: 24.6M
      CPU: 1.099s
   CGroup: /system.slice/flanneld.service
           └─1488 /opt/bin/flanneld --ip-masq=true

Apr 27 16:40:41 k8s-master3 systemd[1]: Starting flannel - Network fabric for containers (System Application Container)...
Apr 27 16:40:42 k8s-master3 rkt[1460]: rm: unable to remove pod "c7908d61-4c64-4103-9f7b-0addc4c29b7f": remove /var/lib/rkt/pods/exited-garbage/c7908d61-4c64-4103-9f7b-0addc4c29b7f/stage1/rootfs: device or resource busy
Apr 27 16:40:42 k8s-master3 rkt[1460]: rm: failed to remove one or more pods
Apr 27 16:40:42 k8s-master3 flannel-wrapper[1488]: + exec /usr/bin/rkt run --uuid-file-save=/var/lib/coreos/flannel-wrapper.uuid --trust-keys-from-https --mount volume=notify,target=/run/systemd/notify --volume notify,kind=host,source=/run/systemd/notify --set-env=NOTIFY_SOCKET=/run/systemd/notify --net=host --volume run-flannel,kind=host,source=/run/flannel,readOnly=false --volume etc-ssl-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume usr-share-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume etc-hosts,kind=host,source=/etc/hosts,readOnly=true --volume etc-resolv,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=run-flannel,target=/run/flannel --mount volume=etc-ssl-certs,target=/etc/ssl/certs --mount volume=usr-share-certs,target=/usr/share/ca-certificates --mount volume=etc-hosts,target=/etc/hosts --mount volume=etc-resolv,target=/etc/resolv.conf --inherit-env --stage1-from-dir=stage1-fly.aci quay.io/coreos/flannel:v0.7.0 -- --ip-masq=true
Apr 27 16:40:43 k8s-master3 flannel-wrapper[1488]: I0427 16:40:43.240494    1488 main.go:132] Installing signal handlers
Apr 27 16:40:43 k8s-master3 flannel-wrapper[1488]: I0427 16:40:43.240617    1488 manager.go:124] Searching for interface using 172.25.100.216
Apr 27 16:40:43 k8s-master3 flannel-wrapper[1488]: I0427 16:40:43.242126    1488 manager.go:149] Using interface with name ens192 and address 172.25.100.216
Apr 27 16:40:43 k8s-master3 flannel-wrapper[1488]: I0427 16:40:43.242454    1488 manager.go:166] Defaulting external address to interface address (172.25.100.216)```

Some output from journalctl:

```Apr 27 16:42:12 k8s-master3 systemd[1]: flanneld.service: Start operation timed out. Terminating.
Apr 27 16:42:12 k8s-master3 flannel-wrapper[1488]: I0427 16:42:12.153914    1488 main.go:172] Exiting...
Apr 27 16:42:12 k8s-master3 systemd[1]: Failed to start flannel - Network fabric for containers (System Application Container).
-- Subject: Unit flanneld.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit flanneld.service has failed.
--
-- The result is failed.
Apr 27 16:42:12 k8s-master3 systemd[1]: Dependency failed for flannel docker export service - Network fabric for containers (System Application Container)
-- Subject: Unit flannel-docker-opts.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit flannel-docker-opts.service has failed.
--
-- The result is dependency.
Apr 27 16:42:12 k8s-master3 systemd[1]: flannel-docker-opts.service: Job flannel-docker-opts.service/start failed with result 'dependency'.
Apr 27 16:42:12 k8s-master3 systemd[1]: Dependency failed for Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is dependency.
Apr 27 16:42:12 k8s-master3 systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Apr 27 16:42:12 k8s-master3 systemd[1]: flanneld.service: Unit entered failed state.
Apr 27 16:42:12 k8s-master3 systemd[1]: flanneld.service: Failed with result 'timeout'.```

**Comment by eskaaren** [comment] 2017-04-27 16:54
rkt list fills up with garbage:

```
UUID		APP		IMAGE NAME					STATE		CREATED		STARTED		NETWORKS
1da7547c	flannel		quay.io/coreos/flannel:v0.6.2			exited garbage	2 hours ago	2 hours ago
4cae7498	hyperkube	quay.io/coreos/hyperkube:v1.5.6_coreos.0	exited garbage	20 minutes ago	20 minutes ago
ad7969f7	flannel		quay.io/coreos/flannel:v0.7.0			running		40 seconds ago	40 seconds ago
c5a26146	hyperkube	quay.io/coreos/hyperkube:v1.6.1_coreos.0	exited garbage	2 hours ago	2 hours ago
d019be01	hyperkube	quay.io/coreos/hyperkube:v1.6.1_coreos.0	exited garbage	6 hours ago	6 hours ago
ec6f21b9	hyperkube	quay.io/coreos/hyperkube:v1.5.6_coreos.0	running		18 minutes ago	18 minutes ago
fccf6468	hyperkube	quay.io/coreos/hyperkube:v1.5.4_coreos.0	exited garbage	2 hours ago	2 hours ago
list: 354 error(s) encountered when listing pods:
list: ----------------------------------------
list: Unable to read pod 006abdd6-f573-4d35-9177-e091ba446ab7 manifest:
  error reading pod manifest
list: ----------------------------------------
list: Unable to read pod 008aea7e-e5f2-467b-99f5-2a2df00aec53 manifest:
  error reading pod manifest
list: ----------------------------------------
list: Unable to read pod 0105764c-ac82-4ced-b545-09101d115920 manifest:
  error reading pod manifest
list: ----------------------------------------
list: Unable to read pod 02ef96d6-85fb-4c05-81fc-85a75d67ba62 manifest:
  error reading pod manifest
list: ----------------------------------------
list: Unable to read pod 0318dc56-8b27-477f-9f0d-b4d9fc7428b8 manifest:
  error reading pod manifest
list: ----------------------------------------
list: Unable to read pod 04b66840-2209-47b7-9ea0-ddb637af8a3d manifest:
...
```

**Comment by euank** [comment] 2017-04-27 18:02
Maybe this is a dupe of https://github.com/coreos/bugs/issues/1833 ?

Can you try removing the [timeout](https://github.com/coreos/coreos-overlay/blob/32cbfd6b66db6acef79aaf8edc0da009a49e0fce/app-admin/flannel-wrapper/files/flannel-docker-opts.service#L11) via dropins like:

```ini
# /etc/systemd/system/flannel-docker-opts.service.d/10-timeout.conf
[Service]
TimeoutStartSec=infinity

# /etc/systemd/system/flannel.service.d/10-timeout.conf
[Service]
TimeoutStartSec=infinity
```

From 0.6 to 0.7, the flanneld binary jumped from about 20MB to about 60MB, so it's possible that's making it hit timeouts.

Using `systemctl list-dependencies flanneld` to make sure it's clear which dependency failed could also be helpful!

**Comment by eskaaren** [comment] 2017-04-28 07:34
I set the timeout to 320 since it just hung when set to infinity.

journalctl -eu flanneld:

```
Apr 28 06:33:43 k8s-master3 systemd[1]: Stopped flannel - Network fabric for containers (System Application Container).
Apr 28 06:33:43 k8s-master3 systemd[1]: Starting flannel - Network fabric for containers (System Application Container)...
Apr 28 06:33:44 k8s-master3 rkt[1650]: rm: unable to remove pod "a9f8bca5-021a-43d5-bde3-a0d44d07dcb3": remove /var/lib/rkt/pods/exited-garbage/a9f8bca5-021a-43d5-bde3-a0d44d07dcb3/stage1/rootfs: device or resource busy
Apr 28 06:33:44 k8s-master3 rkt[1650]: rm: failed to remove one or more pods
Apr 28 06:33:44 k8s-master3 flannel-wrapper[1676]: + exec /usr/bin/rkt run --uuid-file-save=/var/lib/coreos/flannel-wrapper.uuid --trust-keys-from-https --mount volume=notify,target=/run/systemd/notify --volume notify,kind=host,source=/run/systemd/notify --set-env=NOTIFY_SOCKET=/run/systemd/notify --net=host --volume run-flannel,kind=host,source=/run/flannel,readOnly=false --volume etc-ssl-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume usr-share-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume etc-hosts,kind=host,source=/etc/hosts,readOnly=true --volume etc-resolv,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=run-flannel,target=/run/flannel --mount volume=etc-ssl-certs,target=/etc/ssl/certs --mount volume=usr-share-certs,target=/usr/share/ca-certificates --mount volume=etc-hosts,target=/etc/hosts --mount volume=etc-resolv,target=/etc/resolv.conf --inherit-env --stage1-from-dir=stage1-fly.aci quay.io/coreos/flannel:v0.7.0 -- --ip-masq=true
Apr 28 06:33:45 k8s-master3 flannel-wrapper[1676]: I0428 06:33:45.309176    1676 main.go:132] Installing signal handlers
Apr 28 06:33:45 k8s-master3 flannel-wrapper[1676]: I0428 06:33:45.309347    1676 manager.go:124] Searching for interface using 172.25.100.216
Apr 28 06:33:45 k8s-master3 flannel-wrapper[1676]: I0428 06:33:45.309679    1676 manager.go:149] Using interface with name ens192 and address 172.25.100.216
Apr 28 06:33:45 k8s-master3 flannel-wrapper[1676]: I0428 06:33:45.309704    1676 manager.go:166] Defaulting external address to interface address (172.25.100.216)
Apr 28 06:33:55 k8s-master3 flannel-wrapper[1676]: I0428 06:33:55.405862    1676 main.go:172] Exiting...
Apr 28 06:33:55 k8s-master3 systemd[1]: Stopped flannel - Network fabric for containers (System Application Container).
Apr 28 06:33:55 k8s-master3 systemd[1]: Starting flannel - Network fabric for containers (System Application Container)...
Apr 28 06:33:55 k8s-master3 rkt[1748]: rm: unable to remove pod "bfed1099-8da7-4703-b012-e4bf0ee15772": remove /var/lib/rkt/pods/exited-garbage/bfed1099-8da7-4703-b012-e4bf0ee15772/stage1/rootfs: device or resource busy
Apr 28 06:33:55 k8s-master3 rkt[1748]: rm: failed to remove one or more pods
Apr 28 06:33:55 k8s-master3 flannel-wrapper[1778]: + exec /usr/bin/rkt run --uuid-file-save=/var/lib/coreos/flannel-wrapper.uuid --trust-keys-from-https --mount volume=notify,target=/run/systemd/notify --volume notify,kind=host,source=/run/systemd/notify --set-env=NOTIFY_SOCKET=/run/systemd/notify --net=host --volume run-flannel,kind=host,source=/run/flannel,readOnly=false --volume etc-ssl-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume usr-share-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume etc-hosts,kind=host,source=/etc/hosts,readOnly=true --volume etc-resolv,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=run-flannel,target=/run/flannel --mount volume=etc-ssl-certs,target=/etc/ssl/certs --mount volume=usr-share-certs,target=/usr/share/ca-certificates --mount volume=etc-hosts,target=/etc/hosts --mount volume=etc-resolv,target=/etc/resolv.conf --inherit-env --stage1-from-dir=stage1-fly.aci quay.io/coreos/flannel:v0.7.0 -- --ip-masq=true
Apr 28 06:33:57 k8s-master3 flannel-wrapper[1778]: I0428 06:33:57.015805    1778 main.go:132] Installing signal handlers
Apr 28 06:33:57 k8s-master3 flannel-wrapper[1778]: I0428 06:33:57.015906    1778 manager.go:124] Searching for interface using 172.25.100.216
Apr 28 06:33:57 k8s-master3 flannel-wrapper[1778]: I0428 06:33:57.016165    1778 manager.go:149] Using interface with name ens192 and address 172.25.100.216
Apr 28 06:33:57 k8s-master3 flannel-wrapper[1778]: I0428 06:33:57.016181    1778 manager.go:166] Defaulting external address to interface address (172.25.100.216)
Apr 28 06:36:56 k8s-master3 flannel-wrapper[1778]: E0428 06:36:56.726209    1778 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
Apr 28 06:39:15 k8s-master3 systemd[1]: flanneld.service: Start operation timed out. Terminating.
Apr 28 06:39:15 k8s-master3 flannel-wrapper[1778]: I0428 06:39:15.784608    1778 main.go:172] Exiting...
Apr 28 06:39:15 k8s-master3 systemd[1]: Failed to start flannel - Network fabric for containers (System Application Container).
Apr 28 06:39:15 k8s-master3 systemd[1]: flanneld.service: Unit entered failed state.
Apr 28 06:39:15 k8s-master3 systemd[1]: flanneld.service: Failed with result 'timeout'.
Apr 28 06:39:26 k8s-master3 systemd[1]: flanneld.service: Service hold-off time over, scheduling restart.
Apr 28 06:39:26 k8s-master3 systemd[1]: Stopped flannel - Network fabric for containers (System Application Container).
Apr 28 06:39:26 k8s-master3 systemd[1]: Starting flannel - Network fabric for containers (System Application Container)...
Apr 28 06:39:26 k8s-master3 rkt[1860]: rm: unable to remove pod "0ca857ad-eacf-4ef5-bce2-4efab693346b": remove /var/lib/rkt/pods/exited-garbage/0ca857ad-eacf-4ef5-bce2-4efab693346b/stage1/rootfs: device or resource busy
Apr 28 06:39:26 k8s-master3 rkt[1860]: rm: failed to remove one or more pods
Apr 28 06:39:26 k8s-master3 flannel-wrapper[1887]: + exec /usr/bin/rkt run --uuid-file-save=/var/lib/coreos/flannel-wrapper.uuid --trust-keys-from-https --mount volume=notify,target=/run/systemd/notify --volume notify,kind=host,source=/run/systemd/notify --set-env=NOTIFY_SOCKET=/run/systemd/notify --net=host --volume run-flannel,kind=host,source=/run/flannel,readOnly=false --volume etc-ssl-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume usr-share-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume etc-hosts,kind=host,source=/etc/hosts,readOnly=true --volume etc-resolv,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=run-flannel,target=/run/flannel --mount volume=etc-ssl-certs,target=/etc/ssl/certs --mount volume=usr-share-certs,target=/usr/share/ca-certificates --mount volume=etc-hosts,target=/etc/hosts --mount volume=etc-resolv,target=/etc/resolv.conf --inherit-env --stage1-from-dir=stage1-fly.aci quay.io/coreos/flannel:v0.7.0 -- --ip-masq=true
Apr 28 06:39:27 k8s-master3 flannel-wrapper[1887]: I0428 06:39:27.840069    1887 main.go:132] Installing signal handlers
Apr 28 06:39:27 k8s-master3 flannel-wrapper[1887]: I0428 06:39:27.840184    1887 manager.go:124] Searching for interface using 172.25.100.216
Apr 28 06:39:27 k8s-master3 flannel-wrapper[1887]: I0428 06:39:27.840409    1887 manager.go:149] Using interface with name ens192 and address 172.25.100.216
Apr 28 06:39:27 k8s-master3 flannel-wrapper[1887]: I0428 06:39:27.840424    1887 manager.go:166] Defaulting external address to interface address (172.25.100.216)
```

journalctl -eu flannel-docker-opts:
```
Apr 28 06:30:10 k8s-master3 systemd[1]: Dependency failed for flannel docker export service - Network fabric for containers (System Application Container).
Apr 28 06:30:10 k8s-master3 systemd[1]: flannel-docker-opts.service: Job flannel-docker-opts.service/start failed with result 'dependency'.
Apr 28 06:31:51 k8s-master3 systemd[1]: Dependency failed for flannel docker export service - Network fabric for containers (System Application Container).
Apr 28 06:31:51 k8s-master3 systemd[1]: flannel-docker-opts.service: Job flannel-docker-opts.service/start failed with result 'dependency'.
Apr 28 06:33:33 k8s-master3 systemd[1]: Dependency failed for flannel docker export service - Network fabric for containers (System Application Container).
Apr 28 06:33:33 k8s-master3 systemd[1]: flannel-docker-opts.service: Job flannel-docker-opts.service/start failed with result 'dependency'.
Apr 28 06:39:15 k8s-master3 systemd[1]: Dependency failed for flannel docker export service - Network fabric for containers (System Application Container).
Apr 28 06:39:15 k8s-master3 systemd[1]: flannel-docker-opts.service: Job flannel-docker-opts.service/start failed with result 'dependency'.
```

journalctl -eu docker:
```
Apr 28 06:30:10 k8s-master3 systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Apr 28 06:31:51 k8s-master3 systemd[1]: Dependency failed for Docker Application Container Engine.
Apr 28 06:31:51 k8s-master3 systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Apr 28 06:33:33 k8s-master3 systemd[1]: Dependency failed for Docker Application Container Engine.
Apr 28 06:33:33 k8s-master3 systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Apr 28 06:39:15 k8s-master3 systemd[1]: Dependency failed for Docker Application Container Engine.
Apr 28 06:39:15 k8s-master3 systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Apr 28 06:44:46 k8s-master3 systemd[1]: Dependency failed for Docker Application Container Engine.
Apr 28 06:44:46 k8s-master3 systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Apr 28 06:50:17 k8s-master3 systemd[1]: Dependency failed for Docker Application Container Engine.
```

systemctl list-dependencies flanneld (flannel-docker-opts not running):
```
flanneld.service
● ├─flannel-docker-opts.service
● ├─system.slice
● └─sysinit.target
●   ├─clean-ca-certificates.service
●   ├─coreos-tmpfiles.service
●   ├─dev-hugepages.mount
●   ├─dev-mqueue.mount
●   ├─kmod-static-nodes.service
●   ├─ldconfig.service
●   ├─proc-sys-fs-binfmt_misc.automount
●   ├─sys-fs-fuse-connections.mount
●   ├─sys-kernel-config.mount
●   ├─sys-kernel-debug.mount
●   ├─systemd-ask-password-console.path
●   ├─systemd-binfmt.service
●   ├─systemd-hwdb-update.service
●   ├─systemd-journal-catalog-update.service
●   ├─systemd-journal-flush.service
●   ├─systemd-journald.service
●   ├─systemd-machine-id-commit.service
●   ├─systemd-modules-load.service
●   ├─systemd-random-seed.service
●   ├─systemd-sysctl.service
●   ├─systemd-sysusers.service
●   ├─systemd-timesyncd.service
●   ├─systemd-tmpfiles-setup-dev.service
●   ├─systemd-tmpfiles-setup.service
●   ├─systemd-udev-trigger.service
●   ├─systemd-udevd.service
●   ├─systemd-update-done.service
●   ├─systemd-update-utmp.service
●   ├─update-ca-certificates.service
●   ├─xenserver-pv-version.service
●   ├─cryptsetup.target
●   ├─local-fs.target
●   │ ├─boot.automount
●   │ ├─media.mount
●   │ ├─proc-xen.mount
●   │ ├─remount-root.service
●   │ ├─systemd-remount-fs.service
●   │ ├─tmp.mount
●   │ ├─usr-share-oem.mount
●   │ └─var-lib-machines.mount
●   └─swap.target
```


systemctl list-dependencies flannel-docker-opts (flanneld loaded but not active):
```
flannel-docker-opts.service
● ├─flanneld.service
● ├─system.slice
● └─sysinit.target
●   ├─clean-ca-certificates.service
●   ├─coreos-tmpfiles.service
●   ├─dev-hugepages.mount
●   ├─dev-mqueue.mount
●   ├─kmod-static-nodes.service
●   ├─ldconfig.service
●   ├─proc-sys-fs-binfmt_misc.automount
●   ├─sys-fs-fuse-connections.mount
●   ├─sys-kernel-config.mount
●   ├─sys-kernel-debug.mount
●   ├─systemd-ask-password-console.path
●   ├─systemd-binfmt.service
●   ├─systemd-hwdb-update.service
●   ├─systemd-journal-catalog-update.service
●   ├─systemd-journal-flush.service
●   ├─systemd-journald.service
●   ├─systemd-machine-id-commit.service
●   ├─systemd-modules-load.service
●   ├─systemd-random-seed.service
●   ├─systemd-sysctl.service
●   ├─systemd-sysusers.service
●   ├─systemd-timesyncd.service
●   ├─systemd-tmpfiles-setup-dev.service
●   ├─systemd-tmpfiles-setup.service
●   ├─systemd-udev-trigger.service
●   ├─systemd-udevd.service
●   ├─systemd-update-done.service
●   ├─systemd-update-utmp.service
●   ├─update-ca-certificates.service
●   ├─xenserver-pv-version.service
●   ├─cryptsetup.target
●   ├─local-fs.target
●   │ ├─boot.automount
●   │ ├─media.mount
●   │ ├─proc-xen.mount
●   │ ├─remount-root.service
●   │ ├─systemd-remount-fs.service
●   │ ├─tmp.mount
●   │ ├─usr-share-oem.mount
●   │ └─var-lib-machines.mount
●   └─swap.target
```

systemctl list-dependencies docker:
```
docker.service
● ├─containerd.service
● ├─docker.socket
● ├─flanneld.service
● ├─system.slice
● └─sysinit.target
●   ├─clean-ca-certificates.service
●   ├─coreos-tmpfiles.service
●   ├─dev-hugepages.mount
●   ├─dev-mqueue.mount
●   ├─kmod-static-nodes.service
●   ├─ldconfig.service
●   ├─proc-sys-fs-binfmt_misc.automount
●   ├─sys-fs-fuse-connections.mount
●   ├─sys-kernel-config.mount
●   ├─sys-kernel-debug.mount
●   ├─systemd-ask-password-console.path
●   ├─systemd-binfmt.service
●   ├─systemd-hwdb-update.service
●   ├─systemd-journal-catalog-update.service
●   ├─systemd-journal-flush.service
●   ├─systemd-journald.service
●   ├─systemd-machine-id-commit.service
●   ├─systemd-modules-load.service
●   ├─systemd-random-seed.service
●   ├─systemd-sysctl.service
●   ├─systemd-sysusers.service
●   ├─systemd-timesyncd.service
●   ├─systemd-tmpfiles-setup-dev.service
●   ├─systemd-tmpfiles-setup.service
●   ├─systemd-udev-trigger.service
●   ├─systemd-udevd.service
●   ├─systemd-update-done.service
●   ├─systemd-update-utmp.service
●   ├─update-ca-certificates.service
●   ├─xenserver-pv-version.service
●   ├─cryptsetup.target
●   ├─local-fs.target
●   │ ├─boot.automount
●   │ ├─media.mount
●   │ ├─proc-xen.mount
●   │ ├─remount-root.service
●   │ ├─systemd-remount-fs.service
●   │ ├─tmp.mount
●   │ ├─usr-share-oem.mount
●   │ └─var-lib-machines.mount
●   └─swap.target
```

**Comment by euank** [comment] 2017-04-28 18:15
Based on those logs, it's never sending notify ready (the exiting-after-10s ones all are just it being a notify service).

That does make it sound like flannel's having trouble talking to etcd potentially.

@tomdee, any ideas?

**Comment by tomdee** [comment] 2017-05-01 16:18
@euank I did revendor the version of github.com/coreos/go-systemd in flanneld 0.7.1 - which meant that this line changed between [0.7.0]( https://github.com/coreos/flannel/blob/v0.7.0/network/manager.go#L256  ) and [0.7.1]( https://github.com/coreos/flannel/blob/v0.7.1/network/manager.go#L256  )-Could that be the issue?

**Comment by euank** [comment] 2017-05-02 00:11
@tomdee If that were it I'd expect it to repro either 100% or 0%. I'm unable to reproduce this issue.

@eskaaren Want to double check your flannel config? Specifically FLANNELD_IFACE and FLANNELD_ETCD_ENDPOINTS? Even if `etcdctl` works, depending on how ETCD_ENDPOINTS are configured there could still be something wrong there.

I attempted to reproduce this issue by running the following script as root on a fresh container-linux stable instance: https://gist.github.com/euank/485e5ed5984185a5a21db28e6bcd7d1c

That script, for me, runs successfully on EC2 and results in a running flanneld, so it gets further than whatever problem you're running into.

If you can find a simpler repro, that would help immensely!

Thanks,
Euan

**Comment by lucab** [comment] 2017-05-02 08:13
Some (perhaps relevant) datapoints:
 * go-systemd recently got a slightly different `SdNotify` API: https://github.com/coreos/go-systemd/pull/185
 * systemd v233 got a different semantic regarding notify-type services: https://github.com/systemd/systemd/blob/master/NEWS#L88-L90

**Comment by dev-e** [comment] 2017-05-31 10:34
Flannel v0.7.0 is working on CoreOS with etcd cluster v 3.0+.

**Comment by euank** [comment] 2017-08-30 21:41
For lack of us being able to reproduce this problem, I'm closing this.

If this still impacts you and you're able to provide a reproduction, that woudl be immensely helpful!

**Closed by euank** 2017-08-30 21:41 UTC
Labels: area/distribution, component/flannel, needs/more-information, team/os
