### ISSUE TITLE
CoreOS fails to boot on 10% of AWS instances m5.large

### ISSUE THREAD

**Issue by mildred** [coreos/bugs#2326] opened 2018-01-24 17:19 UTC
# Issue Report #

### Container Linux Version ###

CoreOS Container Linux stable 1576.5.0 (HVM)
CoreOS-stable-1576.5.0-hvm

AMI: ami-32d1474b

### Environment ###

AWS m5.large

### Expected and Actual Behavior ###

When starting m5.large instances on CoreOS (it also happens with m5.xlarge) 10% of the instances end up unreachable. SSH access is impossible and the AWS console shows: **1/2 checks passed** (after sometimes 10 minutes)
![image](https://user-images.githubusercontent.com/33804/35346602-fa4a17e0-0132-11e8-9b4f-d8fd802fa140.png)

Instead, all instances should start up and be available.

Possibly, this is a problem with all the m5.* machines of AWS.

### Reproduction Steps ###

  1. download the attached terraform files and use [terraform](https://www.terraform.io) to provision the machines
  2. `terraform init`
  3. `terraform apply`
  4. Wait up until 10 minutes to see the errors

### Other Information ###

The machines show the following log (accessible from the AWS console): https://gist.github.com/mildred/6dcac14bff12da6445395153581bb81b

terraform files: [proto-coreos-aws-m5.large.tar.gz](https://github.com/coreos/bugs/files/1669185/proto-coreos-aws-m5.large.tar.gz) (the ssh key contained is generated specially for this bug report. it is not a leaked credential)

**Comment by bgilbert** [comment] 2018-01-26 02:59
Interestingly, there are 30-second gaps between several of the log messages.

**Comment by stmarier** [comment] 2018-03-30 18:37
Wanted to note that this is occurring for us as well, AWS, us-east-1, using m5.large instances as well as `ami-3f061b45`.

Slightly different behavior though: we had no issue with the m5.large instances until randomly we had an issue with every m5.large instance.

**Comment by bgilbert** [comment] 2018-03-31 16:16
For the record, @stmarier's image is 1632.3.0, us-east-1.

**Comment by mildred** [comment] 2018-04-03 20:57
For the information, we stopped having the problem since I reported the issue. We were on eu-west-1 and AWS seemed to have issues with m5 machines at that time.

**Comment by euank** [comment] 2018-04-03 21:40
Thanks for letting us know it seems to have fixed itself.

Since it sounds like it may have been an issue on AWSs side, I'm closing this issue. If it starts reproducing again and seems to impact Container Linux more than other distros, please do let us know!

@stmarier can you check if yours also is Container Linux specific or has since been fixed? If it still happens for you, please open an issue with details about how to reproduce it.

**Closed by euank** 2018-04-03 21:40 UTC
Labels: area/stability, component/kernel, kind/bug, platform/aws, team/os
