### ISSUE TITLE
Lots of I/O causes program hangs and allocation failure

### ISSUE THREAD

**Issue by polarina** [coreos/bugs#930] opened 2015-10-16 22:37 UTC
I have on a bare-metal machine eight (8) two terabyte hard disk drives. When performing lots of I/O operations on those disk, after a short while, programs may start to enter uninterruptible sleep for a very long time, others will fail to allocate memory.

    for i in {a,b,c,d,e,f,g,h}; do dd bs=65536 if=/dev/zero of=/dev/sd$i; done

After a few minutes, commands such as `sync` will enter uninterruptible sleep and can not even be killed with `kill -9` until the `dd` processes are stopped or complete.

Other programs may fail to allocate memory, such as `docker`:

    Error response from daemon: open /var/lib/docker/overlay/19aa97d74de6bd3af67179473c596c24292004f13b321ae262a57852b79e927e-init/merged/etc/resolv.conf: cannot allocate memory

**Comment by mischief** [comment] 2015-10-16 23:32
duplicate of #489.

**Closed by mischief** 2015-10-16 23:32 UTC
