### ISSUE TITLE
DNS from Cloud Config not being used

### ISSUE THREAD

**Issue by rikatz** [coreos/bugs#1875] opened 2017-03-21 16:27 UTC
# Issue Report #

## Bug ##

Container Linux Version: 1353.1.0

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1353.1.0
VERSION_ID=1353.1.0
BUILD_ID=2017-03-17-0813
PRETTY_NAME="Container Linux by CoreOS 1353.1.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

### Environment ###

Using VMWare with Ignition or Cloud Config, the behaviour is the same

### Expected Behavior ###

Configuring the Network from Ignition or from Cloud Config, the resolv.conf from the server should contain the DNS Server.

### Actual Behavior ###

resolv.conf is empty, containing only the original comments from file

### Reproduction Steps ###

  1. Deploy a CoreOS with cloud-config configuring the Network Interface, as the following

```yaml
coreos:
  units:
  - name: 00-en.network
    runtime: true
    content: |
      [Match]
      Name=ens192
      [Network]
      DNS=10.31.31.50
      Address=10.200.80.10/24
      Gateway=10.200.80.1
[...]
```
  2. Use this cloud config (coreos-cloudinit) 

 3. Check that the systemd unit have changed, containing the right DNS:

```
[Match]
Name=ens1*

[Network]
DNS=10.31.31.50
Address=10.200.80.10/24
Gateway=10.200.80.1
```

4. After restarting the systemd-networkd, the /etc/resolv.conf file still doesn't have any DNS configured.

### Other Information ###

It seems that this is some change of behaviour in systemd. If I configure this directive in ``/etc/systemd/resolved.conf`` and restart the daemon ``systemd-resolved`` it seems to work.

I don't know if this is some kind of docs bugs, or if maybe systemd got updated in new CoreOS releases. This same cloud-init used to work on some older CoreOS versions. 

So, I'm starting to use this resolved.conf file, but it would be nice to have some feedback about this, so I can open a PR to correct the docs, or correct something here :)

Thanks!

**Comment by dm0-** [comment] 2017-03-21 18:26
I can't reproduce this, with Ignition at least.  Using your exact file name and contents (with appropriately updated `Match=`), everything works as expected.  What does `networkctl status ens192` (or whatever your interface name is) say for the `Network File` line?

**Comment by rikatz** [comment] 2017-03-21 19:58
```
networkctl status ens192
● 2: ens192
       Link File: /usr/lib64/systemd/network/99-default.link
    Network File: /run/systemd/network/00-.network
            Type: ether
           State: routable (configuring)
            Path: pci-0000:0b:00.0
          Driver: vmxnet3
          Vendor: VMware
           Model: VMXNET3 Ethernet Controller
      HW Address: 00:50:56:83:d7:36 (VMware, Inc.)
         Address: 10.200.83.14
                  fe80::250:56ff:fe83:d736
         Gateway: 10.200.80.1 (Extreme Networks)
```

Maybe this is related to https://github.com/coreos/bugs/issues/1802 as I'm using the very same OVA / model deployment.

**Comment by that1guy15** [comment] 2017-04-30 17:16
I have this exact issue currently with version 1353.7.0.

**Comment by pgburt** [comment] 2017-04-30 22:38
@dgonyeo the above user reported a similar issue [on reddit][reddit]. They've shared their ignition config here:

https://github.com/that1guy15/blog-dc-trends/blob/master/CoreOS/ignition.json

[reddit]: https://www.reddit.com/r/coreos/comments/68hrax/dns_issues_on_coreos_install/

**Comment by bgilbert** [comment] 2017-05-05 01:25
@rikatz Yep, the root cause is the same as #1802, and this should be fixed by https://github.com/coreos/scripts/pull/680.  Thanks for the report!

**Closed by bgilbert** 2017-05-05 01:25 UTC
Labels: area/usability, component/networkd, kind/regression, priority/P0, team/os
