### ISSUE TITLE
Incorrect storage driver selected when /var/lib/docker is btrfs

### ISSUE THREAD

**Issue by bradfordcp** [coreos/bugs#413] opened 2015-07-15 17:28 UTC
Recently I encountered the issue listed in docker/docker#10180. Following the advice of [this comment](https://github.com/docker/docker/issues/10180#issuecomment-120193807) I stopped the docker service, emptied out /var/lib/docker and followed the [CoreOS documentation](https://coreos.com/docs/cluster-management/setup/mounting-storage/#creating-and-mounting-a-btrfs-volume-file) steps for setting up btrfs.

Once the formatting was done I started docker.service. Running `docker images` threw an error about a missing directory under /var/lib/docker. `sudo docker info` listed the storage driver as ext4 + overlay instead of btrfs.

To fix this I copied the docker.service file into /etc/systemd/system and added the `-s btrfs` flag. Now `sudo docker info` lists the appropriate storage drive and I no longer have the issue from docker/docker#10180.

It was mentioned in [this issue](https://github.com/coreos/bugs/issues/319#issuecomment-121426664) that the storage driver should automatically be detected, but that did not happen here.

**Comment by bradfordcp** [comment] 2015-07-15 17:28
I am wondering if this is because `/var/lib/docker` was modified after the system was already running instead of in the cloud config.

**Comment by crawford** [comment] 2015-07-17 23:12
The default docker service on CoreOS actually runs /usr/lib/coreos/dockerd instead of /usr/bin/docker. This helper script is responsible for figuring out the correct filesystem and passing that to docker. My guess is that when you ran docker directly it didn't realize that the filesystem had changed.

**Comment by bradfordcp** [comment] 2015-07-17 23:13
I started the docker service with systemctl, not by hand.

On Friday, July 17, 2015, Alex Crawford <notifications@github.com> wrote:

> The default docker service on CoreOS actually runs /usr/lib/coreos/dockerd
> instead of /usr/bin/docker. This helper script is responsible for figuring
> out the correct filesystem and passing that to docker. My guess is that
> when you ran docker directly it didn't realize that the filesystem had
> changed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coreos/bugs/issues/413#issuecomment-122441539>.
>


-- 

Christopher Bradford

**Comment by marineam** [comment] 2015-07-17 23:33
Strange, it is entirely possible something else about your system is fooling my script. Will look into it.

**Comment by crawford** [comment] 2015-09-17 00:39
@marineam any update?

**Comment by marineam** [comment] 2015-09-17 00:45
No, forgot about this. Basically this command would have to behave wrong for the script to fail:
```
findmnt --noheadings --output FSTYPE --target /var/lib/docker
```

**Comment by crawford** [comment] 2015-11-09 14:26
@bradfordcp can you attach the output of `findmnt --noheadings --output FSTYPE --target /var/lib/docker`?

**Comment by bradfordcp** [comment] 2015-11-09 15:44
The host where this issue occurred has been recycled. 

I was able to follow the procedure on a *new* host, without issue, but it is worth noting that this bug was reported on a host which was previously running docker containers and not brand new.

**Comment by crawford** [comment] 2015-11-09 18:47
I'm going to close this since we haven't reproduced this failure. If you run into this again, go ahead and reopen it.

**Closed by crawford** 2015-11-09 18:47 UTC
Labels: component/docker, component/other, priority/P0, team/os
