### ISSUE TITLE
Encrypted HVM AMI from 1800.6.0 not booting

### ISSUE THREAD

**Issue by joshw123** [coreos/bugs#2489] opened 2018-08-08 10:58 UTC
# Issue Report #

### Container Linux Version ###
1800.6.0
```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
...
BUG_REPORT_URL="https://issues.coreos.com"
```

### Environment ###
Encrypted HVM Instance on AWS in eu-west-1 

What hardware/cloud provider/hypervisor is being used to run Container Linux?

### Expected Behavior ###
Boot
### Actual Behavior ###
Instance is Unreachable 
### Reproduction Steps ###

  1. Create an Encrypted Copy of official CoreOS 1800.6.0 from eu-west-1
  2. Boot HVM Instance

### Other Information ###

```
Starting Reload Configuration from the Real Root...
systemd[1]: Mounted /sysroot.

[    4.840386] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.840887] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.840901] Buffer I/O error on dev dm-0, logical block 256, async page read
[    4.884723] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.885211] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.885224] Buffer I/O error on dev dm-0, logical block 256, async page read
[    4.898095] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.898549] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.898561] Buffer I/O error on dev dm-0, logical block 256, async page read
[    4.914019] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.914539] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.914551] Buffer I/O error on dev dm-0, logical block 256, async page read
[    4.930044] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.930457] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.930467] Buffer I/O error on dev dm-0, logical block 256, async page read
[    4.940903] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.941338] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.941348] Buffer I/O error on dev dm-0, logical block 256, async page read
[    4.957930] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.958356] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.958369] Buffer I/O error on dev dm-0, logical block 256, async page read
[    4.976896] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.977321] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.977334] Buffer I/O error on dev dm-0, logical block 256, async page read
[    4.988797] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.989230] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.989240] Buffer I/O error on dev dm-0, logical block 256, async page read
[    5.001474] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.001903] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.011955] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.012387] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.026928] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.027339] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.038473] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.038873] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.050086] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.050502] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.062411] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.062802] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.074370] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.074766] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.085588] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.085982] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.094755] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.095144] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.106747] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.107193] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.120637] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.121071] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.141727] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.142127] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.152414] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.152831] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.161533] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.161955] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.170554] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.170980] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.179714] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.180127] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.188777] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.189183] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.197906] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.198325] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.206851] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.207269] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.215970] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.216404] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.225315] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.225728] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.234422] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.234843] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.244079] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.244501] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.253114] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.253534] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.261893] random: crng init done
[    5.262216] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.262626] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.271315] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.271751] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.280018] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.280435] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.288917] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.289360] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.297660] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.298074] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.306499] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.306895] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.315482] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.315904] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.324340] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.324754] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.333362] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.333789] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.342392] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.342801] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.351017] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.351505] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.360046] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.360449] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.369034] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.369486] device-mapper: verity: 202:3: data block 256 is corrupted
[    4.846457] systemd[  OK  ] Stopped Network Service.
[  OK  ] Started Setup Virtual Console.
[1]: verity-setup.service: Main process exited, code=exited, status=1/FAILURE
[    5.398571] systemd[1]: verity-setup.service: Failed with result 'exit-code'.
[    5.403255] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.406704] device-mapper: verity: 202:3: data block 256 is corrupted
[    5.405873] systemd[1]: Failed to start Verity Setup for /dev/mapper/usr.
[    5.417250] systemd[1]: [  OK  ] Started Reload Configuration from the Real Root.
Dependency failed for dev-mapper-usr.device.
[    5.425381] systemd         [    5.426974] device-mapper: verity: 202:3: data block 256 is corrupted
[1]: Dependency failed for File System Check on /dev/mapper/usr.Starting Verity Setup for /dev/mapper/usr...
         Starting Emergency Shell...
[    5.438121] device-mapper: verity: 202:3: data block 256 is corrupted

[    5.443916] systemd[FAILED] Failed to start Verity Setup for /dev/mapper/usr.
See 'systemctl status verity-setup.service' for details.
```

**Comment by joshw123** [comment] 2018-08-08 11:00
FYI, Instances boot running version 1800.5.0

**Comment by kabbedijk** [comment] 2018-08-08 12:45
We have this exact same issue using the same version.

**Comment by ajeddeloh** [comment] 2018-08-08 22:07
I suspect this is an AWS bug. The only change from 1800.5.0 to 1800.6.0 was a kernel patch and our release process hasn't changed. I'll look into this.

**Comment by swestcott** [comment] 2018-08-14 13:38
@ajeddeloh [I work with Josh] I can raise a support ticket with AWS if you think that might help. Do you have any further details that I could pass onto them?

**Comment by lucab** [comment] 2018-08-14 14:28
This is pretty much the same issue we initially hit in https://github.com/coreos/bugs/issues/1692#issuecomment-323898175. It may be worthy reporting to AWS so that they aware that something on their side changed and the behavior regressed on our dm-verity.

I also highlighted this to @davdunc in person, as we would be happy if AWS could expose an option to opt-out the default sparse-copying logic.

**Comment by swestcott** [comment] 2018-08-15 08:15
Ok, I've pinged AWS support on this.

Just an observation, the length AMI IDs has increased between CL 1800.5.0 & 1800.6.0, `ami-1d3cd8f0` and `ami-012afb51d9c2d918f` respectively.

**Comment by lucab** [comment] 2018-08-15 09:31
@swestcott that's due to https://aws.amazon.com/about-aws/whats-new/2018/02/longer-format-resource-ids-are-now-available-in-amazon-ec2/ and shouldn't have externally observable side-effects that are relevant in this context.

**Comment by CliffHoogervorst** [comment] 2018-08-22 14:13
Is there any update on this? Should we open a support case with AWS to fix it?

**Comment by ibrokethecloud** [comment] 2018-09-04 00:02
Might sound strange and unrelated but I have run into the same issue with custom RHEL images i bake locally and import into AWS.

The unencrypted ami works just fine however after encryption turned on i run into similar issues with partition recovery failing.

**Comment by Cryptophobia** [comment] 2018-09-04 18:42
We have opened a support case with AWS as well. They said that they are still working on a fix. They mentioned that CoreOS may be working on a fix as well. @ajeddeloh are they liars?

**Comment by ibrokethecloud** [comment] 2018-09-12 05:04
AWS have confirmed that the fix is now available in us-east-1. Import the image again and encrypt it and it should work.

The encrypted image can then be copied for all other regions.

Fix should soon be rolling out to other regions.

I can confirm that my custom rhel imports are working fine.

**Comment by kabbedijk** [comment] 2018-09-12 09:14
I can confirm it works for us as well (eu-west-1).

**Comment by ajeddeloh** [comment] 2018-09-12 16:19
Closing this since it's been fixed by AWS.

**Closed by ajeddeloh** 2018-09-12 16:19 UTC
Labels: area/distribution, dependency/external, kind/regression, platform/aws, team/os
