### ISSUE TITLE
coreos alpha 976 doesn't setup ssh correctly on GCE

### ISSUE THREAD

**Issue by sjpotter** [coreos/bugs#1164] opened 2016-03-10 19:26 UTC
Upgraded my rktnetes testing from 960 to 976 and could no longer ssh into the GCE boxes, downgraded back to 960 and ssh worked just fine.

**Comment by mischief** [comment] 2016-03-10 19:27
can you get any logs from the read-only console?

**Comment by sjpotter** [comment] 2016-03-10 19:46
and now that I've gone to try and reproduce this with logs, it works all the time.  <sigh>

**Comment by sjpotter** [comment] 2016-03-10 19:50
ignore previous comment, here are the logs.  reproducible, wasn't ssh'ing into right box.


[960.txt](https://github.com/coreos/bugs/files/167880/960.txt)
[976.txt](https://github.com/coreos/bugs/files/167881/976.txt)

**Comment by yifan-gu** [comment] 2016-03-10 20:06
What's the docker version on 976？

**Comment by sjpotter** [comment] 2016-03-10 21:13
any recommendations for a cmd line to test with?  this is via gcloud so they take care of everything behind the scenes.

**Comment by crawford** [comment] 2016-03-10 22:37
Something like `gcutil ssh --ssh_arg "-i ~/.ssh/id_rsa" ...`. Didn't test this.

**Comment by euank** [comment] 2016-05-04 21:27
I can't recall for sure, but I think the root cause here was an issue I've also observed: my `$HOME/.ssh/authorized_keys` file being owned by root. ssh-ing in as `core@` still worked in these situations. `gcloud ssh` uses your own username.

I only see messaging for updating the `core` user's authorized_keys in journalctl.

@sjpotter want to confirm whether or not the above matches the symptoms you saw?

**Comment by marineam** [comment] 2016-05-04 21:33
Likely related to https://github.com/coreos/coreos-overlay/pull/1919

**Comment by bprashanth** [comment] 2016-05-16 23:00
I think this is borked in beta as well, or at least fresh coreos-beta + gcloud ssh doesn't work. It should right? core@ ssh works, and authorize_keys is owned by core.

**Comment by crawford** [comment] 2016-05-18 04:31
`gcloud ssh` does some absolutely insane stuff under the hood and creates a new user on the box. The Google Daemon which is responsible for creating these users was malfunctioning due to our builds not including the proper patches. That's why plain old ssh works. This will be fixed in this week's Alpha and Beta.

**Closed by crawford** 2016-05-18 04:31 UTC
Labels: component/other, kind/regression, reviewed/needs more information, team/os
