### ISSUE TITLE
Systemd breaks when restarting timer unit 1068.8.0

### ISSUE THREAD

**Issue by AlexRudd** [coreos/bugs#1493] opened 2016-08-01 13:08 UTC
## Bug ##
Restarting Timer unit file completely breaks systemd

### CoreOS Version ###
Version 1068.8.0 from ami-cbb5d5b8

### Environment ###
Running on AWS t2.mediums

### Expected Behavior ###
Trying to create a timer for a service unit which will login to AWS ECR at regular intervals. Have already been using the exact same unit files and commands on CoreOS 1010.5.0 without issue.

### Actual Behavior ###
Trying out the same process on 1068.8.0 cause systemd to stop responding. 

### Reproduction Steps ###

Create service unit file `/etc/systemd/system/ecr_login.service`
```
[Unit]
Description=ECR get-login
After=docker.service
Requires=docker.service
[Service]
Type=oneshot
ExecStartPre=/usr/bin/docker pull anigeo/awscli
ExecStart=/bin/bash -c '`docker run --rm anigeo/awscli --region us-east-1 ecr get-login`'
```

Create timer unit file `/etc/systemd/system/ecr_login.timer`
```
[Unit]
Description=ECR get-login timer
[Install]
WantedBy=timers.target
[Timer]
OnBootSec=0
OnCalendar=*-*-* 01,09,17:00:00
```

Run commands:
```bash
sudo systemctl daemon-reload
sudo systemctl enable ecr_login.timer
# Created symlink from /etc/systemd/system/timers.target.wants/ecr_login.timer to /etc/systemd/system/ecr_login.timer.
sudo systemctl restart ecr_login.timer
# ...command hangs...
^c
systemctl
# Failed to list units: Connection timed out
sudo shutdown -r now
# Failed to start reboot.target: Connection timed out
# See system logs and 'systemctl status reboot.target' for details.
# Failed to talk to init daemon.
systemctl status reboot.target
# Failed to get properties: Connection timed out
```

Journalctl:
```
systemd[1]: Stopped ECR get-login timer.
systemd[1]: Assertion '*v' failed at ../systemd-229/src/core/timer.c:337, function add_random(). Aborting.
```

Let me know if there are any more details you need

**Comment by crawford** [comment] 2016-08-01 23:16
@dm0- can you try reproducing this with systemd 231? I was able to completely hose my 229 system.

**Comment by dm0-** [comment] 2016-08-01 23:36
It doesn't seem to have a problem on v231.

    0 localhost system # systemctl restart ecr_login.timer
    0 localhost system # [   74.379374] bridge: automatic filtering via arp/ip/ip6tables has been deprecated. Update your scripts to load br_netfilter if you need this.
    [   74.384353] Bridge firewalling registered
    [   74.391973] nf_conntrack version 0.5.0 (16384 buckets, 65536 max)            
    [   74.599227] IPv6: ADDRCONF(NETDEV_UP): docker0: link is not ready            
    0 localhost system # systemctl status ecr_login.timer
    * ecr_login.timer - ECR get-login timer
       Loaded: loaded (/etc/systemd/system/ecr_login.timer; enabled; vendor preset:
       Active: active (waiting) since Mon 2016-08-01 23:33:38 UTC; 14s ago
    
     Aug 01 23:33:38 localhost systemd[1]: Started ECR get-login timer.

**Comment by dm0-** [comment] 2016-08-02 20:02
I'm closing this since coreos/coreos-overlay#2106 has been merged, upgrading to systemd v231.

**Closed by dm0-** 2016-08-02 20:02 UTC
Labels: area/usability, component/systemd, kind/regression, priority/P0, team/os
