### ISSUE TITLE
`docker: Stale file handle` after updating Container Linux to alpha

### ISSUE THREAD

**Issue by jrave9000** [coreos/bugs#2152] opened 2017-09-13 11:02 UTC
## Bug ##

After an update from latest stable to latest alpha I encounter 'Stale file handle' errors while trying to use apt (dpkg) in Ubuntu-based docker containers (tested on 16.04 and 14.04). In Debian-based containers everything is ok.
Totally reproducible.

Everything is fine with fresh alpha setup, but maybe there's an update issue. And I'll be grateful for ANY advice, because it's way more boring to move all the stuff to another instance.

### Container Linux Version ###
```
cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.1.0
VERSION_ID=1520.1.0
BUILD_ID=2017-09-05-2146
PRETTY_NAME="Container Linux by CoreOS 1520.1.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

### Environment ###
Google Cloud Engine

### Reproduction Steps ###

  1. Create an instance with latest stable Container Linux.
  2. Update it to alpha.
  3. Run the following command in ubuntu docker container:
`$ apt update && apt install software-properties-common`

### Error: ###

`dpkg: error: error removing old backup file '/var/lib/dpkg/status-old': Stale file handle`

**Comment by nathankleyn** [comment] 2017-09-15 13:48
We are also seeing this issue on the alpha release, pretty much identical scenario as described above - however happy to provide more info if needed!

**Comment by bgilbert** [comment] 2017-09-16 00:19
One other step is needed to reproduce: between steps 1 and 2, run a container.

Container Linux stable currently has docker 1.12, which defaults to the `overlay` storage driver.  docker 17.06 defaults to `overlay2` unless it finds existing data from the `overlay` driver, in which case it uses `overlay`.  The `Stale file handle` problem apparently only occurs with `overlay`.

As a workaround, you can stop `docker.service` and delete `/var/lib/docker`.  **This will, of course, delete all your Docker data.**  Afterward, you should be using the `overlay2` storage driver; you can verify this in `docker info`.

I don't see any recent `Stale file handle` reports in [moby/moby](https://github.com/moby/moby/issues); they may be interested in knowing about the issue as well.

**Comment by bgilbert** [comment] 2017-09-16 08:44
- Reproduced on CL alpha 1535.1.0 on AWS.
- Reproduced on CL beta 1520.3.0, which has kernel 4.13.2 and docker 1.12.6.
- Not reproduced on CL stable 1465.7.0, which has kernel 4.12.10 and docker 1.12.6.

So it looks as though this is a problem with the `overlay` driver + kernel 4.13, and not specifically with docker 17.06.  On 17.06, `overlay2` is at least available to switch to, but no such luck on 1.12.

`apt-get update && apt-get install pv` is sufficient to provoke the problem, but only once per container.  `dpkg -i <package>` does not provoke the problem.  I've captured a [partial strace](https://github.com/coreos/bugs/files/1308179/strace-1.txt) by copying in a `/usr/bin/strace` and attaching to dpkg processes as they show up.  The obvious unusual sequence of events is the create/unlink/link/rename of `/var/lib/dpkg/status{,-old,-new}`, but replicating that did not immediately reproduce the problem.

There are three overlayfs commits that add ESTALE returns in 4.13.  Two of them only affect mount time, and the third is torvalds/linux@b9ac5c274b8c9d642567022c0e319bca4db31956.  Other 4.13 overlayfs changes may have introduced new calls to existing functions returning ESTALE, but I haven't checked.

**Comment by euank** [comment] 2017-09-18 21:30
The upstream patch https://patchwork.kernel.org/patch/9955803/ fixes this issue for me.
After applying it locally, `apt-get update && apt-get install pv` on `17.06` configured with `-s overlay` no longer reproduces the issue.

**Comment by weikinhuang** [comment] 2017-09-19 20:53
Happens to me too on the `beta` channel since 4 days ago.

```bash
cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.3.0
VERSION_ID=1520.3.0
BUILD_ID=2017-09-15-2017
PRETTY_NAME="Container Linux by CoreOS 1520.3.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

```bash
docker run -it --rm centos:7 bash
Unable to find image 'centos:7' locally
7: Pulling from library/centos
d9aaf4d82f24: Pull complete
Digest: sha256:eba772bac22c86d7d6e72421b4700c3f894ab6e35475a34014ff8de74c10872e
Status: Downloaded newer image for centos:7
[root@cc3077c5252a /]# yum install -y -q openssh-clients
warning: /var/cache/yum/x86_64/7/base/packages/fipscheck-lib-1.4.1-6.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for fipscheck-lib-1.4.1-6.el7.x86_64.rpm is not installed
Public key for openssh-7.4p1-12.el7_4.x86_64.rpm is not installed
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-4.1708.el7.centos.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Traceback (most recent call last):
  File "/usr/bin/yum", line 29, in <module>
    yummain.user_main(sys.argv[1:], exit_code=True)
  File "/usr/share/yum-cli/yummain.py", line 370, in user_main
    errcode = main(args)
  File "/usr/share/yum-cli/yummain.py", line 276, in main
    return_code = base.doTransaction()
  File "/usr/share/yum-cli/cli.py", line 783, in doTransaction
    resultobject = self.runTransaction(cb=cb)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1943, in runTransaction
    self.verifyTransaction(resultobject, vTcb)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 2006, in verifyTransaction
    po.yumdb_info.releasever = self.conf.yumvar['releasever']
  File "/usr/lib/python2.7/site-packages/yum/rpmsack.py", line 1930, in __setattr__
    self._write(attr, value)
  File "/usr/lib/python2.7/site-packages/yum/rpmsack.py", line 1854, in _write
    misc.unlink_f(fn + '.tmp')
  File "/usr/lib/python2.7/site-packages/yum/misc.py", line 955, in unlink_f
    os.unlink(filename)
OSError: [Errno 116] Stale file handle: '/var/lib/yum/yumdb/f/cb7e013b0931dc495c9295d40ffbd0f49e31484b-fipscheck-lib-1.4.1-6.el7-x86_64/releasever.tmp'
```

**Comment by bgilbert** [comment] 2017-09-20 22:56
This should be fixed in alpha 1535.2.0 and beta 1520.4.0, due shortly.  Thanks for reporting.

**Closed by bgilbert** 2017-09-20 22:56 UTC
Labels: area/stability, blocks/linux/4.13, component/docker, kind/bug, team/os

**Comment by nathankleyn** [comment] 2017-09-21 05:45
Many thanks @bgilbert and @euank for the amazingly quick fix - you guys make OSS look easy! 👍

**Comment by ccureau** [comment] 2017-10-12 17:40
👍 We ran into this exact issue today, and updating the kernel to 4.13.6 from kernel-ml solved the issue.  Thanks!!!

**Comment by hordemark** [comment] 2017-11-22 05:31
Awesome! resolve it by upgrading kernel to 4.14.1-1.el7.elrepo
