### ISSUE TITLE
iptables FORWARD-chain glitch

### ISSUE THREAD

**Issue by porjo** [coreos/bugs#344] opened 2015-05-01 04:24 UTC
I have a CoreOS server that constantly gets its iptables messed up. The result is a `FORWARD` chain that prevents my containers initiating connections to the Internet. This is the FORWARD chain just after the issue has occured:

```
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
    pkts      bytes target     prot opt in     out     source               destination         
    4767   286784 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
   11194   710122 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            reject-with icmp-host-prohibited
```

For comparison, the same output on a 'normal' server is as follows:
```
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
    pkts      bytes target     prot opt in     out     source               destination         
 3737122 1552996992 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
 3044702 1391494658 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
       0        0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           
  141404  8456867 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
       0        0 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            reject-with icmp-host-prohibited
```

The fix is simply to restart Docker. The issue has been happening once every 2-3 days recently.

The following is a dump from `journalctl` showing log entries just before, during and just after the issue has occurred: http://pastebin.com/NsRDPDLp

CoreOS 647.0.0

**Comment by porjo** [comment] 2015-05-21 09:12
I suspect what is happening here is that the systemd reload:
```
May 01 01:58:26 sf01 fleetd[598]: INFO manager.go:184: Instructing systemd to reload units
May 01 01:58:26 sf01 systemd[1]: Reloading.
```
is triggering `iptables-restore.service` to reload 
```
May 01 01:58:26 sf01 systemd[1]: Starting Restore iptables firewall rules...
```
and that is simply overwriting Docker's custom rules.

Is there a way to tell systemd to only stop/start a particular service at boot time, and ignore it otherwise?

**Comment by porjo** [comment] 2015-06-02 21:11
I've tried putting `docker.service` in the `Before=` line of my `iptables-restore.service` unfortunately that hasn't helped.

@crawford any suggestions?

**Comment by porjo** [comment] 2015-06-08 21:53
I've wrapped iptables-restore in a shell script which checks uptime and skips the operation if the host has been up for awhile. Seems to be working...

**Comment by crawford** [comment] 2015-10-19 22:31
@porjo Are you still seeing this issue with the later versions of Docker?

**Comment by crawford** [comment] 2015-11-18 00:02
@porjo Bump. Have you seen these failures in the Alpha or Beta channels? We are shipping a newer version of Docker there (soon to make its way to Stable).

**Comment by porjo** [comment] 2015-11-18 01:41
> Have you seen these failures in the Alpha or Beta channels?

Unfortunately I'm no longer using CoreOS, so I'm not able to comment on that.

**Comment by crawford** [comment] 2015-11-20 23:11
OK, I think this has the same root cause as https://github.com/coreos/bugs/issues/469. I'm going to close this issue.

**Closed by crawford** 2015-11-20 23:11 UTC
Labels: component/docker, kind/bug, priority/P0, team/os
