### ISSUE TITLE
Container Linux Config Transpiler 0.6.1 doesn't report the version properly

### ISSUE THREAD

**Issue by vinyldarkscratch** [coreos/bugs#2333] opened 2018-01-27 23:55 UTC
# Issue Report #

## Bug ##

Under macOS (using the Homebrew package manager), running `ct -version` reports `ct 0.6.1`, but the output is `ct ` (including the trailing whitespace).  This fails a test that was originally in https://github.com/Homebrew/homebrew-core/pull/23354 but was removed since it doesn't really test the program's functionality.

**Comment by dgonyeo** [comment] 2018-01-29 18:51
The version is set at compile time via the [`LD_FLAGS` variable in the makefile](https://github.com/coreos/container-linux-config-transpiler/blob/b76ab0b2d66ff1ac6902f4fe118a02c1bed6e5ce/Makefile#L14). The version is correctly set on Linux, so I'm guessing that the flags required to set it are different for MacOS.

**Comment by dgonyeo** [comment] 2018-01-29 19:09
I just had a coworker run `make release` on MacOS, and the version field was set properly.

```
$ bin/ct-v0.6.1-x86_64-apple-darwin --version
ct v0.6.1
```

This feels like a bug in something related to cross-compilation in golang. I'll go complain upstream.

**Comment by euank** [comment] 2018-02-07 22:35
@dgonyeo I believe this is caused by make defaulting to `git` to determine the version, but since `brew` uses the archive url associated with the release, there's no `.git` folder to work with. Presumably it's actually falling back to homebrew's git output there.

@vinyldarkscratch I think this is a bug in the homebrew recipe. `ct`'s makefile allows overriding the version with e.g. `make VERSION=v0.6.1`, so if it's being built from the downloaded `.tar.gz` source archive github provides, that'll be needed.

It's possible brew lets you do a git checkout instead (maybe like [this](https://github.com/Homebrew/homebrew-core/blob/0b2a9b8090d52250dcd3d00512c423966144e13f/Formula/docker.rb#L4-L6)), but I'm not familiar enough with brew to sure.

Thank you very much for creating that ct package, by the way. It's appreciated!

**Comment by lucab** [comment] 2018-02-14 12:41
I just checked and this doesn't affect the binaries we publish at https://github.com/coreos/container-linux-config-transpiler/releases/tag/v0.6.1, so this only affects homebrew. And @euank explanation seems reasonable too.

@vinyldarkscratch can we move this to a homebrew ticket/PR?

**Comment by euank** [comment] 2018-03-09 00:54
I went ahead and opened a PR against the homebrew formula since I think it's best fixed there. I'm optimistically closing this with the hope it'll get merged/fixed over there.

**Closed by euank** 2018-03-09 00:54 UTC
