### ISSUE TITLE
problem with etcd proxies after update Beta 991.2.0 -> 1010.1.0

### ISSUE THREAD

**Issue by arjanschaaf** [coreos/bugs#1251] opened 2016-04-28 13:22 UTC
I had a 3 node etcd cluster running CoreOS beta 991.2.0. In the same deployment I had a couple of other servers running the CoreOS beta version with an etcd proxy service. Everything worked as expected.
After the release of beta 1010.1.0 the 3 servers running my etcd cluster were updated first. After the successful update of those 3 servers the etcd cluster updated from 2.2.5 to 2.3.1 (the etcd version shipped with 1010.1.0).
At that time the etcd proxies on my other servers stopped working. Those servers still ran the old etcd version (2.2.5). It took me a while before I realised the CoreOS update and the associated update to etcd 2.3.1 was behind my problems.

When I ran `etcdctl cluster-health` on the failing etcd proxies, etcdctl reported that the cluster was healthy:
```
etcdctl cluster-health
member xxx is healthy: got healthy result from http://10.139.16.16:2379
member yyy is healthy: got healthy result from http://10.139.32.16:2379
member zzz is healthy: got healthy result from http://10.139.48.16:2379
```
When I ran `etcdctl member list` on the failing etcd proxies, etcdctl reported a unavailable cluster:
```
etcdctl member list
client: etcd cluster is unavailable or misconfigured
```
Especially the healthy result from `etcdctl cluster-health` made it hard to determine that the etcd proxy actually wasn't healthy at all.
Upgrading the servers that run the etcd proxies to CoreOS 1010.1.0 fixed the etcd proxies again.

**Comment by xiang90** [comment] 2016-04-28 17:35
> At that time the etcd proxies on my other servers stopped working. Those servers still ran the old etcd version (2.2.5). 

Do you have logging information from these proxies?

> When I ran etcdctl cluster-health on the failing etcd proxies, etcdctl reported that the cluster was healthy:

What do you mean by running etcdctl on the proxies? Running etcdctl through the proxy? Or running etcdctl on the proxy machine?

**Comment by f0** [comment] 2016-04-28 17:45
@arjanschaaf  i have done exactly the same only my proxy versions are 2.2.2, i do not see such problems

**Comment by xiang90** [comment] 2016-04-28 18:00
@arjanschaaf I tried to set up a 2.2.5 proxy with 2.3.1 etcd cluster, it works fine. I suspect there is something bad happened during the upgrade. It would be a great help if you can provide more log or other information.

**Comment by arjanschaaf** [comment] 2016-04-28 18:12
@f0 @xiang90 I didn't save the complete logs files and I forcefully updated all the systems running 2.2.5 which fixed the situation for me.

> What do you mean by running etcdctl on the proxies? Running etcdctl through the proxy? Or running etcdctl on the proxy machine?

I meant running `etcdctl cluster-health` on the machine running etcd in proxy, thus connecting to the ectd proxy on 127.0.0.1:2379

Before I updated the systems I did check the status of one of the etcd proxies with systemctl:

```
core@ip-10-139-16-32 ~ $ sudo systemctl status etcd2
● etcd2.service - etcd2
   Loaded: loaded (/usr/lib64/systemd/system/etcd2.service; disabled; vendor preset: disabled)
  Drop-In: /run/systemd/system/etcd2.service.d
           └─10-oem.conf, 20-cloudinit.conf
   Active: active (running) since Mon 2016-04-25 10:33:58 UTC; 2 days ago
 Main PID: 859 (etcd2)
   Memory: 23.7M
      CPU: 5min 23.161s
   CGroup: /system.slice/etcd2.service
           └─859 /usr/bin/etcd2

Apr 28 09:37:04 ip-10-139-16-32.eu-west-1.compute.internal etcd2[859]: proxy: zero endpoints currently available
Apr 28 09:37:04 ip-10-139-16-32.eu-west-1.compute.internal etcd2[859]: proxy: zero endpoints currently available
Apr 28 09:37:04 ip-10-139-16-32.eu-west-1.compute.internal etcd2[859]: proxy: zero endpoints currently available
Apr 28 09:37:04 ip-10-139-16-32.eu-west-1.compute.internal etcd2[859]: proxy: zero endpoints currently available
Apr 28 09:37:04 ip-10-139-16-32.eu-west-1.compute.internal etcd2[859]: proxy: zero endpoints currently available
```

So I don't have any relevant logs of the servers running the etcd proxies. But the actual etcd servers on which the update caused to problems for the proxies are untouched. Let me know how to look for relevant logs on those machines.

**Comment by xiang90** [comment] 2016-04-28 19:20
@arjanschaaf From the logging, it seems like the etcd server was down for upgrading and proxy cannot reach them. The proxy masked these endpoints correctly. Proxy should be able to unmask these endpoints after sometime out. So I do not think this is a version issue. Maybe proxy was suffering from the unavailability and is not able to unmask the endpoints. 

So I would suggest you to move this issue to etcd repo. Hopefully you can reproduce this by taking down etcd servers and restart them to see if proxy can recover from the server failure.

**Comment by xiang90** [comment] 2016-05-12 21:27
I am closing this due to low activity. Reopen if you still have issue. Thanks.

**Closed by xiang90** 2016-05-12 21:27 UTC
Labels: component/etcd
