### ISSUE TITLE
Locksmithd fails and journal not working correctly

### ISSUE THREAD

**Issue by nballotta** [coreos/bugs#929] opened 2015-10-16 10:28 UTC
Hi,

I recently upgraded from CoreOS stable (723.3.0) to CoreOS stable (766.4.0). Because my reboot strategy is set to off, I manually rebooted every node of my cluster composed by 3 statically bootstrapped  etcd nodes and 2 proxies. The upgrade seemed fine, but today logging in I found this:

```
CoreOS stable (766.3.0)
Update Strategy: No Reboots
Failed Units: 1
  locksmithd.service
```
A systemctl status locksmithd give me this:

```
● locksmithd.service
   Loaded: masked (/dev/null)
   Active: failed (Result: exit-code) since Wed 2015-10-14 09:42:52 UTC; 2 days ago
 Main PID: 706 (code=exited, status=2)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```

So I tried to debug with journalctl, but without success:

```
0002 ~ $ journalctl -t locksmithd --no-pager
-- Logs begin at Wed 2015-10-14 21:46:31 UTC, end at Fri 2015-10-16 09:54:49 UTC. --
Failed to get journal fields: Cannot assign requested address
``` 

My journal log directory is about 50M:

```
0002 /var/log/journal ~ $ du -h
51M	./847da1b3002749d49a9135408205b12b
51M	.
```

This is after enabling DEBUG on journald:

```
0002 ~ $ dmesg | grep systemd-journald
[    2.320584] audit: type=1130 audit(1444815762.856:2): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-journald comm="systemd" exe="/usr/lib64/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    4.928811] systemd-journald[130]: Received SIGTERM from PID 1 (n/a).
[    7.669123] systemd-journald[503]: Creating journal file /var/log/journal/847da1b3002749d49a9135408205b12b/system.journal on a btrfs file system, and copy-on-write is enabled. This is likely to slow down journal access substantially, please consider turning off the copy-on-write file attribute on the journal directory, using chattr +C.
[    8.029979] audit: type=1130 audit(1444815768.571:63): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-journald comm="systemd" exe="/usr/lib64/systemd/systemd" hostname=? addr=? terminal=? res=success'
[    8.132380] systemd-journald[503]: Received request to flush runtime journal from PID 1
[177101.203004] systemd-journald[503]: Received SIGTERM from PID 1 (systemd).
[177101.337623] systemd-journald[14434]: Cannot restore stream file 8:1080889
[177101.337633] systemd-journald[14434]: Cannot restore stream file 8:236861
[177101.337638] systemd-journald[14434]: Cannot restore stream file 8:13908
[177101.337643] systemd-journald[14434]: Cannot restore stream file 8:13905
[177101.337647] systemd-journald[14434]: Cannot restore stream file 8:13773
[177101.337652] systemd-journald[14434]: Cannot restore stream file 8:13192
[177101.337657] systemd-journald[14434]: Cannot restore stream file 8:13179
[177101.337661] systemd-journald[14434]: Cannot restore stream file 8:13176
[177101.337665] systemd-journald[14434]: Cannot restore stream file 8:13167
[177101.337670] systemd-journald[14434]: Cannot restore stream file 8:10780
[177101.337750] systemd-journald[14434]: Fixed max_use=50.0M max_size=6.2M min_size=4.0M keep_free=4.0G
[177101.417984] systemd-journald[14434]: Vacuuming...
[177101.418055] systemd-journald[14434]: Vacuuming done, freed 0B of archived journals on disk.
[177101.418058] systemd-journald[14434]: Flushing /dev/kmsg...
[177101.418513] systemd-journald[14434]: systemd-journald running as pid 14434
```

This is my btrfs version:

```
0002 ~ $ sudo btrfs fi show
Label: 'ROOT'  uuid: 198bd5dc-205b-4b34-8bc1-f28a2fbfd5e5
	Total devices 1 FS bytes used 5.52GiB
	devid    1 size 463.45GiB used 9.46GiB path /dev/sda9

Btrfs v3.17.3
```
If you need any other detail, just ask. I can't figure out what's happening. If needed I can also activate debugging (no reboot was done atm).

**Comment by kayrus** [comment] 2015-10-16 11:37
looks like locksmithd was enabled to run on boot. of course it fails. then coreos-cloudinit comes and unmasks this service. but failed status was already recorded by systemd.

have just reproduced that issue. create symlink, then reboot with "reboot-strategy: off" inside cloud-config:

```sh
ls -la /etc/systemd/system/multi-user.target.wants/
total 20
drwxr-xr-x 2 root root 4096 Oct 16 11:28 .
drwxr-xr-x 5 root root 4096 Oct 16 11:28 ..
lrwxrwxrwx 1 root root   44 Oct 16 11:28 locksmithd.service -> /usr/lib64/systemd/system/locksmithd.service
```

After reboot we have this:
```
CoreOS alpha (815.0.0)
Update Strategy: No Reboots
Failed Units: 1
  locksmithd.service
```

**Comment by kayrus** [comment] 2015-10-16 11:55
Workaround: `sudo systemctl mask locksmithd.service`

**Comment by kayrus** [comment] 2015-10-16 12:40
Here are additional logs from irc:

* http://pastebin.com/tV051i5M
* http://pastebin.com/KpGBkhuA

Looks like race condition, especially this:

```
Oct 16 11:46:01 node-0002 coreos-cloudinit[656]: 2015/10/16 11:46:01 Ensuring runtime unit file "locksmithd.service" is unmasked
Oct 16 11:46:01 node-0002 coreos-cloudinit[656]: 2015/10/16 11:46:01 Masking unit file "locksmithd.service"
Oct 16 11:46:01 node-0002 systemd[1]: Reloading.
Oct 16 11:46:01 node-0002 systemd[1]: systemd-timesyncd.service: Cannot add dependency job, ignoring: Unit systemd-timesyncd.service is masked.
Oct 16 11:46:01 node-0002 systemd[1]: systemd-timesyncd.service: Cannot add dependency job, ignoring: Unit systemd-timesyncd.service is masked.
Oct 16 11:46:01 node-0002 coreos-cloudinit[656]: 2015/10/16 11:46:01 Restarting systemd-networkd
Oct 16 11:46:01 node-0002 systemd[1]: Starting Garbage Collection for rkt...
Oct 16 11:46:01 node-0002 systemd[1]: Failed to start locksmithd.service.
```

Probably could be fixed by:
https://gist.github.com/kayrus/faf3d683c9009a4768c8

**Comment by kayrus** [comment] 2015-10-16 14:01
My CoreOS VM prints this info:

``yaml
journalctl -b | grep -C5 locksmithd
Oct 16 13:04:39 coreos1 coreos-cloudinit[534]: 2015/10/16 13:04:39 Writing drop-in unit "20-cloudinit.conf" to filesystem
Oct 16 13:04:39 coreos1 coreos-cloudinit[534]: 2015/10/16 13:04:39 Writing file to "/run/systemd/system/fleet.service.d/20-cloudinit.conf"
Oct 16 13:04:39 coreos1 coreos-cloudinit[534]: 2015/10/16 13:04:39 Wrote file to "/run/systemd/system/fleet.service.d/20-cloudinit.conf"
Oct 16 13:04:39 coreos1 coreos-cloudinit[534]: 2015/10/16 13:04:39 Wrote drop-in unit "20-cloudinit.conf"
Oct 16 13:04:39 coreos1 coreos-cloudinit[534]: 2015/10/16 13:04:39 Ensuring runtime unit file "fleet.service" is unmasked
Oct 16 13:04:39 coreos1 coreos-cloudinit[534]: 2015/10/16 13:04:39 Ensuring runtime unit file "locksmithd.service" is unmasked
Oct 16 13:04:39 coreos1 coreos-cloudinit[534]: 2015/10/16 13:04:39 Masking unit file "locksmithd.service"
Oct 16 13:04:39 coreos1 systemd[1]: Reloading.
Oct 16 13:04:39 coreos1 locksmithd[573]: Reboot strategy is "off" - shutting down.
Oct 16 13:04:39 coreos1 systemd[1]: Started Generate /run/coreos/motd.
Oct 16 13:04:39 coreos1 coreos-cloudinit[534]: 2015/10/16 13:04:39 Calling unit command "start" on "etcd2.service"'
Oct 16 13:04:39 coreos1 systemd[1]: Starting Garbage Collection for rkt...
Oct 16 13:04:39 coreos1 systemd[1]: Reached target Multi-User System.
Oct 16 13:04:39 coreos1 systemd[1]: Started Garbage Collection for rkt.
```

coreos-cloudinit unmasks locksmithd, reloads systemd daemon, but systemd *still tries* to run locksmithd. So this is first problem.

Second problem is why locksmithd dies with non-zero result for @nballotta

@nballotta: can you add this debug info?

```
cat /etc/systemd/system/locksmithd.service.d/10-debug.conf 
[Service]
ExecStart=
ExecStart=/usr/bin/bash -c 'env >> /var/log/locksmithd.log && /usr/lib/locksmith/locksmithd >> /var/log/locksmithd.log 2>&1'
```

Reboot your node and let me know if you have something inside: /var/log/locksmithd.log ?

And provide the list of your service files:

```
find /etc/systemd/system -ls
```

**Comment by nballotta** [comment] 2015-10-16 17:13
hi @kayrus 

here the list of service files: http://pastebin.com/GXeYsadk

I've tried also to add the debug, but without success (the file /var/log/locksmithd.log was not created after reboot)

**Comment by kayrus** [comment] 2015-10-16 19:44
@nballotta can you remove `/etc/systemd/system/locksmithd.service` symlink and try again?

**Comment by nballotta** [comment] 2015-10-17 17:21
@kayrus same result, no /var/log/locksmithd.log was created

**Comment by kayrus** [comment] 2015-10-17 18:19
Does system log contain data about locksmith?

**Comment by nballotta** [comment] 2015-10-18 04:32
```
Oct 18 04:30:31 node-0002 coreos-cloudinit[626]: 2015/10/18 04:30:31 Ensuring runtime unit file "locksmithd.service" is unmasked
Oct 18 04:30:31 node-0002 coreos-cloudinit[626]: 2015/10/18 04:30:31 Masking unit file "locksmithd.service"
Oct 18 04:30:31 node-0002 systemd[1]: Failed to start locksmithd.service.
Oct 18 04:30:31 node-0002 coreos-cloudinit[626]: 2015/10/18 04:30:31 Calling unit command "stop" on "locksmithd.service"'
Oct 18 04:30:31 node-0002 systemd[1]: Stopped locksmithd.service.
Oct 18 04:30:31 node-0002 coreos-cloudinit[626]: 2015/10/18 04:30:31 Result of "stop" on "locksmithd.service": done
```

**Comment by kayrus** [comment] 2015-10-18 07:24
Please post results of this command `sudo systemctl cat locksmithd`

Then try to enable back `systemd-timesyncd.service` and disable `ntpd.service` if it is possible:

```
sudo rm /etc/systemd/system/systemd-timesyncd.service /etc/systemd/system/multi-user.target.wants/ntpd.service
```

Reboot your node and let me know if locksmithd has wrote logs into `/var/log/locksmithd.log` file.

In addition please post `find /etc/systemd/system -ls` once again.

**Comment by nballotta** [comment] 2015-10-18 08:07
```

**Comment by nballotta** [comment] 2015-10-18 08:21
```
0002 ~ $ sudo systemctl cat locksmithd
Warning: locksmithd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
# /dev/null
```

Also this time no /var/log/locksmithd.log was created.

```
0002 ~ $ find /etc/systemd/system -ls
  4676    0 drwxr-xr-x   1 root     root          340 Oct 18 08:08 /etc/systemd/system
 15415    0 drwxr-xr-x   1 root     root            0 Jul 29 16:20 /etc/systemd/system/fleet.socket.d
 27672    0 drwxr-xr-x   1 root     root           50 Oct 18 08:08 /etc/systemd/system/docker.service.d
 49211    4 -rw-r--r--   1 root     root           75 Oct 18 08:08 /etc/systemd/system/docker.service.d/50-insecure-registry.conf
 30359    0 drwxr-xr-x   1 root     root           34 Aug 25 10:51 /etc/systemd/system/sockets.target.wants
 30360    0 lrwxrwxrwx   1 root     root           37 Aug 25 10:51 /etc/systemd/system/sockets.target.wants/docker-tcp.socket -> /etc/systemd/system/docker-tcp.socket
 48651    0 drwxr-xr-x   1 root     root            0 Oct 18 08:07 /etc/systemd/system/multi-user.target.wants
 48994    0 drwxr-xr-x   1 root     root           26 Oct 16 10:57 /etc/systemd/system/systemd-journald.service.d
 48998    4 -rw-r--r--   1 root     root           46 Oct 16 10:57 /etc/systemd/system/systemd-journald.service.d/10-debug.conf
 49039    0 drwxr-xr-x   1 root     root           26 Oct 16 16:27 /etc/systemd/system/locksmithd.service.d
 49074    4 -rw-r--r--   1 root     root          146 Oct 16 16:27 /etc/systemd/system/locksmithd.service.d/10-debug.conf
 49043    4 -rw-r--r--   1 root     root          102 Oct 16 12:20 /etc/systemd/system/10-require_config.conf
 49213    4 -rw-r--r--   1 root     root           76 Oct 18 08:08 /etc/systemd/system/fleet.socket
 49214    4 -rw-r--r--   1 root     root          148 Oct 18 08:08 /etc/systemd/system/docker-tcp.socket
```

**Comment by kayrus** [comment] 2015-10-18 09:02
Can you print also these: `find /run/systemd/system -ls`, `mount`, `df -h`

Then remove `/run/systemd/system/locksmithd.service` symlink (it should be symlink), run `systemctl daemon-reload` (and print its result if appear), and then `systemctl cat locksmithd`.

**Comment by kayrus** [comment] 2015-10-18 09:36
Last (for now) possible solution to debug systemd is to enable debug mode. Make sure you have mounted OEM partition, then create `/usr/share/oem/grub.cfg` file there with contents below:

```
set linux_append="systemd.log_level=debug"
```

This will enable systemd debug on next boot (boot will be slower than usual). Please provide system log for that boot. When debug is done please remove this file and reboot (or disable debug using `kill` [signal](http://www.freedesktop.org/software/systemd/man/systemd.html#SIGRTMIN+22))

**Comment by dongsupark** [comment] 2015-10-19 13:39
```
Creating journal file /var/log/journal/847da1b3002749d49a9135408205b12b/system.journal on a btrfs file system, and copy-on-write is enabled. This is likely to slow down journal access substantially, please consider turning off the copy-on-write file attribute on the journal directory, using chattr +C.
```

FWIW the above warning looks a little suspicious. Since systemd v222, the default version on CoreOS 766.4.0, `chattr +C` should be already done under `/var/log/journal` and all other journals. See `/usr/lib/tmpfiles.d/journal-nocow.conf` too. If that's not the case, something must have gone missing during upgrading CoreOS to 766.4.0.

In general, I would try cleaning up all journals after upgrading systemd v222, especially when Btrfs with CoW was activated for the journals. It would be also worth running `sudo btrfs fi df`, as that could differ from what the normal `df` showed.

**Comment by mischief** [comment] 2015-12-07 21:38
@nballotta any updates here? can you post the information kayrus asked for?

**Comment by vcaputo** [comment] 2016-08-02 22:40
Closing due to inactivity, please reopen if this is still a problem for you in current CoreOS releases.

**Closed by vcaputo** 2016-08-02 22:40 UTC
Labels: component/locksmith, kind/bug, priority/P0, team/os
