### ISSUE TITLE
What is the usecase of Ignition

### ISSUE THREAD

**Issue by alpana17** [coreos/bugs#2621] opened 2019-10-18 08:48 UTC
# Issue Report #
What is the scenario where Ignition should be used?

As I have seen, all the actions like creating service files, updating conf used by these services, updating file permissions, etc can be done by normal shell script.

Then, why should one use Ignition script?

Also,
Can we alter files and directories of /usr with ignition scripts?

**Comment by ajeddeloh** [comment] 2019-10-18 22:03
>  Can we alter files and directories of /usr with ignition scripts?

No, `/usr` is read only and enforced with verity. Even if you somehow made a change it would fail to boot. Also, Ignition configs are not scripts.

> What is the scenario where Ignition should be used?

First boot setup, especially with immutable OS's. Ignition configs are declarative, not imperative like scripts. They describe the state the machine should be in, not how to get there. This is useful in two ways:
1) In the general case configs are easier. You don't need to worry about _how_ do download a file or where systemd units go, you just specify they should exist.
2) It allows config chaining and introspection of a config. Since the configs are declarative, you can merge configs together without worrying about ordering. This is a bit broken with the spec v1 and v2.x config specifications, but fixed in v3 (not supported in CL since fixing that was a compat break). 

Ignition has some other nice properties that _could_ be also done with scripts but would be tricky to get right:
 - It either gives you the machine your config describes or no machine at all. It never gives you a partially configured machine.
 - It runs from the initramfs before "normal boot" starts. This enables it to do things like partitioning that scripts running from the normal root can't. It also means it can configure the "normal boot" without racing with it.

Of course there's things Ignition _can't_ do, but you can always use Ignition to write out a systemd unit with a script to handle those edge cases. This also give you more control because you're in control of when that script is run.

Finally, there's things you should not use Ignition for: configuration management. Ignition is not meant to replace things like Chef or Puppet. It was designed with immutable opertating systems where the idea is you don't change your configuration. If you do you just reprovision. That being said Ignition would be a good fit for configuring something like Chef or Puppet, if that was needed.

**Comment by alpana17** [comment] 2019-10-19 03:31
ok
What if I change file permission of  /usr/share/oem/grub.cfg from 0644 to 0600, just to make it more restrictive?

**Comment by ajeddeloh** [comment] 2019-10-21 16:42
> What if I change file permission of /usr/share/oem/grub.cfg from 0644 to 0600, just to make it more restrictive?

I don't follow? Yes, you can do that, it will be more restrictive then.

**Comment by alpana17** [comment] 2019-10-22 12:47
But that file is in /usr
What all things can be edited in /usr?

**Comment by ajeddeloh** [comment] 2019-10-22 15:45
`/usr/share/oem/grub.cfg` is in the OEM partition which is mounted at `/usr/share/oem`. It should be rw. Sorry, I forgot about that one exception. You might find https://coreos.com/os/docs/latest/sdk-disk-partitions.html useful. I'm going to close this ticket since the original issue is resolved.

**Closed by ajeddeloh** 2019-10-22 15:45 UTC
